package br.com.eventmenu.go
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import br.com.eventmenu.go.data.*
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
data class HubState(val links:List<HubLink> = emptyList(),val selectedLinkId:Int?=null,val terminals:List<HubTerminal> = emptyList(),val selectedTerminalId:Int?=null,val loading:Boolean=false,val error:String?=null,val message:String?=null,val lastCommand:HubCommand?=null,val pairingVersion:Int=0,val monitoring:Boolean=false,val consecutiveFailures:Int=0){val selected:HubLink? get()=links.firstOrNull{it.id==selectedLinkId}?:links.firstOrNull();val selectedTerminal:HubTerminal? get()=terminals.firstOrNull{it.id==selectedTerminalId}?:terminals.firstOrNull()}
class HubViewModel(private val repository:HubRepository):ViewModel(){private val _state=MutableStateFlow(HubState());val state:StateFlow<HubState> = _state.asStateFlow();private var monitorJob:Job?=null
 fun refresh()=viewModelScope.launch{refreshInternal(true)}
 private suspend fun refreshInternal(show:Boolean){if(show)_state.update{it.copy(loading=true,error=null)};runCatching{repository.links()}.onSuccess{links->val selected=_state.value.selectedLinkId?.takeIf{id->links.any{it.id==id}}?:links.firstOrNull{it.online}?.id?:links.firstOrNull()?.id;_state.update{it.copy(links=links,selectedLinkId=selected,loading=false,consecutiveFailures=0)}}.onFailure{e->_state.update{it.copy(loading=false,consecutiveFailures=it.consecutiveFailures+1,error=if(show)e.message?:"Falha ao carregar o Hub." else it.error)}}}
 fun startMonitoring(){if(monitorJob?.isActive==true)return;monitorJob=viewModelScope.launch{_state.update{it.copy(monitoring=true)};while(isActive){refreshInternal(false);val f=_state.value.consecutiveFailures;delay(when{f<=0->10_000;f==1->15_000;f==2->30_000;else->60_000})}}}
 fun stopMonitoring(){monitorJob?.cancel();monitorJob=null;_state.update{it.copy(monitoring=false)}}
 fun select(id:Int){_state.update{it.copy(selectedLinkId=id,terminals=emptyList(),selectedTerminalId=null)}}
 fun loadTerminals()=viewModelScope.launch{val unit=_state.value.selected?.unitId?:return@launch;runCatching{repository.terminals(unit)}.onSuccess{list->_state.update{it.copy(terminals=list,selectedTerminalId=it.selectedTerminalId?.takeIf{id->list.any{x->x.id==id}}?:list.firstOrNull()?.id)}}.onFailure{e->_state.update{it.copy(error=e.message?:"Não foi possível carregar os PINPads.")}}}
 fun selectTerminal(id:Int){_state.update{it.copy(selectedTerminalId=id)}}
 fun claimPairing(qr:String,label:String)=viewModelScope.launch{val code=qr.trim();if(code.isBlank()){_state.update{it.copy(error="Informe ou leia o código exibido no computador.")};return@launch};_state.update{it.copy(loading=true,error=null,message=null)};runCatching{repository.claimPairing(code,label)}.onSuccess{link->_state.update{it.copy(loading=false,selectedLinkId=link.id,pairingVersion=it.pairingVersion+1,message="Computador vinculado ao celular.")};refreshInternal(false);startMonitoring()}.onFailure{e->_state.update{it.copy(loading=false,error=e.message?:"Não foi possível vincular o computador.")}}}
 fun printOrder(id:Int)=withSelected{repository.printOrder(it,id)};fun printReceipt(id:Int)=withSelected{repository.printReceipt(it,id)};fun openDrawer(reason:String)=withSelected{repository.openDrawer(it,reason)};fun showCustomerDisplay(id:Int)=withSelected{repository.showCustomerDisplay(it,id)};fun playAlert(message:String)=withSelected{repository.playAlert(it,message)};fun readScale()=withSelected(requirePeripheral={it.hardware.scale.isNotBlank()},unavailable="Nenhuma balança está configurada neste computador."){repository.readScale(it)}
 fun chargeTef(orderId:Int,amount:Int,type:String,installments:Int){val terminal=_state.value.selectedTerminal;if(terminal==null){_state.update{it.copy(error="Nenhum PINPad está disponível nesta unidade.")};return};withSelected{repository.chargeTef(it,orderId,terminal.id,amount,type,installments)}}
 fun revokeSelected()=viewModelScope.launch{val link=_state.value.selected?:return@launch;_state.update{it.copy(loading=true,error=null)};runCatching{repository.revokeLink(link.id)}.onSuccess{_state.update{it.copy(loading=false,message="Vínculo removido.",selectedLinkId=null,terminals=emptyList(),selectedTerminalId=null)};refreshInternal(false)}.onFailure{e->_state.update{it.copy(loading=false,error=e.message?:"Não foi possível remover o vínculo.")}}}
 private fun withSelected(requirePeripheral:(HubLink)->Boolean={true},unavailable:String="",block:suspend(HubLink)->HubCommand)=viewModelScope.launch{val link=_state.value.selected;if(link==null){_state.update{it.copy(error="Vincule este celular a um computador EventMenu.")};return@launch};if(!link.online){_state.update{it.copy(error="O computador EventMenu está offline. Você pode continuar usando as demais funções normalmente.")};return@launch};if(!requirePeripheral(link)){_state.update{it.copy(error=unavailable.ifBlank{"Este equipamento não está disponível no computador selecionado."})};return@launch};_state.update{it.copy(loading=true,error=null,message=null,lastCommand=null)};runCatching{block(link)}.onSuccess{cmd->_state.update{it.copy(loading=false,lastCommand=cmd,message="Solicitação enviada ao ${link.desktopLabel}.")};watchCommand(cmd.id)}.onFailure{e->_state.update{it.copy(loading=false,error=e.message?:"Falha ao enviar comando ao computador.")}}}
 private fun watchCommand(id:Int)=viewModelScope.launch{var wait=750L;val deadline=System.currentTimeMillis()+120_000;var failures=0;while(isActive&&System.currentTimeMillis()<deadline){delay(wait);val result=runCatching{repository.commandStatus(id)}.getOrElse{failures++;wait=(wait*2).coerceAtMost(8_000);if(failures>=5){_state.update{it.copy(error="A conexão com o computador está instável. As demais funções continuam disponíveis.")};return@launch};continue};failures=0;wait=(wait+500).coerceAtMost(3_000);_state.update{it.copy(lastCommand=result)};when(result.status){"completed"->{when{result.commandType=="scale_read"&&result.weightGrams!=null->_state.update{it.copy(message="Peso: ${formatWeight(result.weightGrams)}${if(result.weightStable==false)" · leitura ainda não estabilizada" else ""}")};result.commandType=="tef_charge"&&result.approvedLocal==false->_state.update{it.copy(error=result.resultMessage.ifBlank{"A cobrança não foi aprovada no PINPad."})};result.commandType=="tef_charge"&&result.verified==true->_state.update{it.copy(message="Pagamento confirmado pelo servidor/provedor.")};result.commandType=="tef_charge"&&result.approvedLocal==true->_state.update{it.copy(message="PINPad aprovou. Aguardando confirmação do provedor; o pedido ainda não foi marcado como pago.")};else->_state.update{it.copy(message="Comando concluído no computador.")}};return@launch};"failed"->{_state.update{it.copy(error=result.error.ifBlank{"O computador não conseguiu concluir a operação."})};return@launch};"expired","cancelled"->{_state.update{it.copy(error="A solicitação expirou ou foi cancelada. Tente novamente.")};return@launch}}};_state.update{it.copy(error="O computador não respondeu dentro de 2 minutos. A operação foi encerrada sem bloquear o EventMenu GO.")}}
 private fun formatWeight(g:Int)=if(g>=1000)"%.3f kg".format(g/1000.0).replace('.',',') else "$g g"
 fun clearFeedback(){_state.update{it.copy(error=null,message=null)}};override fun onCleared(){stopMonitoring();super.onCleared()};class Factory(private val repository:HubRepository):ViewModelProvider.Factory{@Suppress("UNCHECKED_CAST")override fun<T:ViewModel>create(modelClass:Class<T>):T=HubViewModel(repository) as T}}
