<?php

declare(strict_types=1);

namespace EventMenu\Services;

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use PDO;
use RuntimeException;

final class BackupService
{
    private const MAGIC="EMBAK92\n";
    public function create(string $password):array
    {
        $this->requireSuperAdmin();if(strlen($password)<12)throw new RuntimeException('Use uma senha de backup com pelo menos 12 caracteres.');$pdo=Database::connection();$tables=$this->tables($pdo);$data=[];foreach($tables as$t)$data[$t]=$pdo->query('SELECT * FROM `'.$t.'`')->fetchAll(PDO::FETCH_ASSOC);
        $payload=['format'=>'EventMenu-EMBAK','format_version'=>2,'app_version'=>'9.2-new','created_at'=>gmdate('c'),'tables'=>$tables,'data'=>$data];$plain=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE|JSON_THROW_ON_ERROR);$salt=random_bytes(16);$iv=random_bytes(12);$iterations=310000;$key=hash_pbkdf2('sha256',$password,$salt,$iterations,32,true);$tag='';$aad='EventMenu-v9.2-new-embak-v2';$cipher=openssl_encrypt($plain,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag,$aad);if($cipher===false)throw new RuntimeException('Falha ao cifrar backup.');$outer=['format'=>'EventMenu-EMBAK','v'=>2,'kdf'=>'PBKDF2-HMAC-SHA256','iterations'=>$iterations,'cipher'=>'AES-256-GCM','salt'=>base64_encode($salt),'iv'=>base64_encode($iv),'tag'=>base64_encode($tag),'aad'=>$aad,'plain_sha256'=>hash('sha256',$plain),'cipher_sha256'=>hash('sha256',$cipher),'ciphertext'=>base64_encode($cipher)];$blob=self::MAGIC.json_encode($outer,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";$filename='EventMenu-'.gmdate('Ymd-His').'.embak';$checksum=hash('sha256',$blob);$this->history('backup',$filename,$checksum,strlen($blob),'succeeded','Backup completo criptografado AES-256-GCM');Auth::audit('backup.created','backup',null,['checksum'=>$checksum,'tables'=>count($tables)]);return compact('blob','filename','checksum')+['size'=>strlen($blob),'tables'=>count($tables)];
    }
    public function restore(string $blob,string $password):array
    {
        $this->requireSuperAdmin();if(strlen($password)<12||strlen($blob)>67108864||!str_starts_with($blob,self::MAGIC))throw new RuntimeException('Arquivo ou senha de backup inválidos.');$outer=json_decode(trim(substr($blob,strlen(self::MAGIC))),true,64,JSON_THROW_ON_ERROR);if(!is_array($outer)||($outer['format']??'')!=='EventMenu-EMBAK'||(int)($outer['v']??0)!==2)throw new RuntimeException('Versão de backup não suportada.');foreach(['salt','iv','tag','ciphertext']as$k)if(empty($outer[$k]))throw new RuntimeException('Backup incompleto.');$salt=base64_decode((string)$outer['salt'],true);$iv=base64_decode((string)$outer['iv'],true);$tag=base64_decode((string)$outer['tag'],true);$cipher=base64_decode((string)$outer['ciphertext'],true);if($salt===false||$iv===false||$tag===false||$cipher===false||!hash_equals((string)($outer['cipher_sha256']??''),hash('sha256',$cipher)))throw new RuntimeException('Backup corrompido ou adulterado.');$iterations=(int)($outer['iterations']??0);if($iterations<200000||$iterations>1000000)throw new RuntimeException('Parâmetros de criptografia inválidos.');$key=hash_pbkdf2('sha256',$password,$salt,$iterations,32,true);$plain=openssl_decrypt($cipher,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag,(string)$outer['aad']);if($plain===false||!hash_equals((string)$outer['plain_sha256'],hash('sha256',$plain)))throw new RuntimeException('Senha incorreta ou backup adulterado.');$payload=json_decode($plain,true,128,JSON_THROW_ON_ERROR);$pdo=Database::connection();$current=$this->tables($pdo);$incoming=$payload['tables']??[];sort($incoming,SORT_STRING);if($current!==$incoming)throw new RuntimeException('Restauração bloqueada: a estrutura do banco não corresponde exatamente ao backup.');
        try{$pdo->exec('SET FOREIGN_KEY_CHECKS=0');$pdo->beginTransaction();foreach(array_reverse($incoming)as$t)$pdo->exec('DELETE FROM `'.$t.'`');foreach($incoming as$t){foreach(($payload['data'][$t]??[])as$row){if(!$row)continue;$cols=array_keys($row);foreach($cols as$c)if(!preg_match('/^[A-Za-z0-9_]+$/',(string)$c))throw new RuntimeException('Coluna inválida no backup.');$sql='INSERT INTO `'.$t.'` (`'.implode('`,`',$cols).'`) VALUES ('.implode(',',array_fill(0,count($cols),'?')).')';$pdo->prepare($sql)->execute(array_values($row));}}$pdo->exec('UPDATE payment_gateways SET active=0');$pdo->exec('UPDATE nfc_devices SET status="revoked",revoked_at=UTC_TIMESTAMP(),revocation_reason="backup_restore" WHERE status<>"revoked"');$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}finally{try{$pdo->exec('SET FOREIGN_KEY_CHECKS=1');}catch(\Throwable){}}
        $checksum=hash('sha256',$blob);$this->history('restore','uploaded.embak',$checksum,strlen($blob),'succeeded','Restauração concluída; gateways desativados e NFC revogado');Auth::audit('backup.restored','backup',null,['checksum'=>$checksum]);return['ok'=>true,'checksum'=>$checksum,'tables'=>count($incoming)];
    }
    private function tables(PDO $pdo):array{$q=$pdo->query("SELECT table_name name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_type='BASE TABLE' ORDER BY table_name");$tables=array_column($q->fetchAll(),'name');$tables=array_values(array_filter(array_map('strval',$tables),fn($t)=>preg_match('/^[A-Za-z0-9_]+$/',$t)));sort($tables,SORT_STRING);return$tables;}
    private function history(string $operation,?string $filename,?string $checksum,?int $size,string $status,string $details):void{try{Database::connection()->prepare('INSERT INTO backup_history (tenant_id,created_by,operation,filename,checksum,size_bytes,status,details) VALUES (?,?,?,?,?,?,?,?)')->execute([Auth::tenantId(),Auth::id(),$operation,$filename,$checksum,$size,$status,mb_substr($details,0,4000)]);}catch(\Throwable){}}
    private function requireSuperAdmin():void{if(Auth::role()!=='super_admin')throw new RuntimeException('Backup completo é restrito ao Super Administrador.');}
}
