<?php

declare(strict_types=1);

namespace EventMenu\Services;

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use EventMenu\Services\Payments\PaymentProviderRegistry;
use EventMenu\Services\Payments\SumUpProvider;
use PDO;
use RuntimeException;

final class CardPresentService
{
    public function createIntent(int $orderId,string $deviceIdentifier,?int $amountCents=null,string $method='credit',int $installments=1,?string $provider=null): array
    {
        Auth::requirePermission('nfc.collect');$tenantId=Auth::tenantId();$userId=Auth::id();$deviceIdentifier=trim($deviceIdentifier);if(!$tenantId||!$userId||strlen($deviceIdentifier)<8)throw new RuntimeException('Operador, empresa ou aparelho inválidos.');
        $method=strtolower(trim($method));if(!in_array($method,['credit','debit'],true))throw new RuntimeException('Escolha crédito ou débito.');$installments=$method==='debit'?1:max(1,min(12,$installments));$registry=new PaymentProviderRegistry();$provider=$provider?:$registry->preference($tenantId,'card_present');if(!$provider)throw new RuntimeException('Nenhum provedor de pagamento por aproximação está ativo.');if(!$registry->supports($provider,'card_present'))throw new RuntimeException('O provedor escolhido não aceita pagamento por aproximação.');
        $pdo=Database::connection();$hash=hash('sha256',$deviceIdentifier);$d=$pdo->prepare('SELECT * FROM nfc_devices WHERE tenant_id=? AND device_identifier_hash=? AND status="active" LIMIT 1');$d->execute([$tenantId,$hash]);$device=$d->fetch();if(!$device)throw new RuntimeException('Este aparelho ainda não está autorizado para NFC.');if($device['user_id']!==null&&(int)$device['user_id']!==$userId)throw new RuntimeException('O aparelho NFC está vinculado a outro usuário.');
        $o=$pdo->prepare('SELECT * FROM orders WHERE id=? AND tenant_id=? LIMIT 1');$o->execute([$orderId,$tenantId]);$order=$o->fetch();if(!$order)throw new RuntimeException('Pedido não encontrado.');if(in_array((string)$order['status'],['cancelled','completed'],true)||(string)$order['payment_status']==='paid')throw new RuntimeException('Este pedido não aceita nova cobrança.');$this->assertOperatorCanCharge($order,$userId);
        $balance=(new PaymentService())->remaining($orderId,$tenantId);$remaining=(int)$balance['remaining_cents'];$amount=$amountCents??$remaining;if($amount<100||$amount>$remaining)throw new RuntimeException('Valor inválido para pagamento por aproximação. Saldo: R$ '.number_format($remaining/100,2,',','.').'.');
        $open=$pdo->prepare('SELECT id FROM payments WHERE tenant_id=? AND order_id=? AND status IN ("created","pending","authorized") LIMIT 1');$open->execute([$tenantId,$orderId]);if($open->fetchColumn())throw new RuntimeException('Já existe outra cobrança em andamento para este pedido.');$open=$pdo->prepare('SELECT id FROM nfc_payment_intents WHERE tenant_id=? AND order_id=? AND status="created" AND expires_at>CURRENT_TIMESTAMP LIMIT 1');$open->execute([$tenantId,$orderId]);if($open->fetchColumn())throw new RuntimeException('Já existe uma aproximação em andamento para este pedido.');
        $raw=bin2hex(random_bytes(32));$clientId='eventmenu-'.$tenantId.'-'.$orderId.'-'.bin2hex(random_bytes(12));$expires=date('Y-m-d H:i:s',time()+600);$pdo->prepare('INSERT INTO nfc_payment_intents (tenant_id,order_id,user_id,nfc_device_id,intent_token_hash,amount_cents,provider,payment_method,installments_count,client_transaction_id,status,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,"created",?)')->execute([$tenantId,$orderId,$userId,$device['id'],hash('sha256',$raw),$amount,$provider,$method,$installments,$clientId,$expires]);$intentId=(int)$pdo->lastInsertId();
        $providerSession=match($provider){'sumup'=>(new SumUpProvider())->sdkSession($tenantId),'pagbank'=>$this->legacyPagBankSession($tenantId),default=>throw new RuntimeException('O adaptador de cartão '.$provider.' ainda não está habilitado no app.')};
        Auth::audit('card_present.intent_created','order',(string)$orderId,['intent_id'=>$intentId,'provider'=>$provider,'method'=>$method,'installments'=>$installments,'amount_cents'=>$amount,'device_id'=>(int)$device['id']]);return['intent_token'=>$raw,'intent_id'=>$intentId,'order_id'=>$orderId,'amount_cents'=>$amount,'remaining_before_cents'=>$remaining,'provider'=>$provider,'payment_method'=>$method,'installments_count'=>$installments,'client_transaction_id'=>$clientId,'expires_at'=>$expires,'provider_session'=>$providerSession];
    }

    public function verifyIntent(string $intentToken,array $providerResult,string $deviceIdentifier): array
    {
        Auth::requirePermission('nfc.collect');$tenantId=Auth::tenantId();$userId=Auth::id();$intentToken=trim($intentToken);if(!$tenantId||!$userId||strlen($intentToken)<32||strlen(trim($deviceIdentifier))<8)throw new RuntimeException('Dados da cobrança por aproximação inválidos.');$pdo=Database::connection();$q=$pdo->prepare('SELECT i.*,d.device_identifier_hash,d.status device_status,d.user_id device_user_id,o.status order_status,o.payment_status order_payment_status,o.assigned_delivery_user_id FROM nfc_payment_intents i JOIN nfc_devices d ON d.id=i.nfc_device_id JOIN orders o ON o.id=i.order_id AND o.tenant_id=i.tenant_id WHERE i.tenant_id=? AND i.intent_token_hash=? LIMIT 1');$q->execute([$tenantId,hash('sha256',$intentToken)]);$intent=$q->fetch();if(!$intent||(int)$intent['user_id']!==$userId)throw new RuntimeException('Intenção de pagamento inválida.');if((string)$intent['device_status']!=='active'||!hash_equals((string)$intent['device_identifier_hash'],hash('sha256',trim($deviceIdentifier))))throw new RuntimeException('Aparelho NFC não autorizado.');if($intent['device_user_id']!==null&&(int)$intent['device_user_id']!==$userId)throw new RuntimeException('Aparelho NFC pertence a outro usuário.');
        if((string)$intent['status']==='verified')return['ok'=>true,'already_verified'=>true,'order_id'=>(int)$intent['order_id'],'payment_id'=>$intent['payment_id']?(int)$intent['payment_id']:null];if((string)$intent['status']!=='created'||strtotime((string)$intent['expires_at'])<time()){$pdo->prepare('UPDATE nfc_payment_intents SET status="expired" WHERE id=? AND status="created"')->execute([$intent['id']]);throw new RuntimeException('A cobrança por aproximação expirou.');}if(in_array((string)$intent['order_status'],['cancelled','completed'],true)||(string)$intent['order_payment_status']==='paid')throw new RuntimeException('O pedido não aceita mais esta cobrança.');$this->assertOperatorCanCharge($intent,$userId);
        $verified=match((string)$intent['provider']){'sumup'=>(new SumUpProvider())->verifyCardPresent($tenantId,$intent,$providerResult),'pagbank'=>$this->verifyLegacyPagBank($intent,$providerResult),default=>throw new RuntimeException('Adaptador de validação do provedor indisponível.')};
        $paymentId=Database::transaction(function(PDO$tx)use($tenantId,$intent,$verified,$providerResult):int{
            $lock=$tx->prepare(Database::portableSql($tx,'SELECT * FROM nfc_payment_intents WHERE id=? AND tenant_id=? FOR UPDATE'));$lock->execute([$intent['id'],$tenantId]);$fresh=$lock->fetch();if(!$fresh)throw new RuntimeException('Intenção não encontrada.');if($fresh['status']==='verified')return(int)$fresh['payment_id'];if($fresh['status']!=='created')throw new RuntimeException('Intenção não está disponível para confirmação.');
            $providerId=(string)$verified['provider_payment_id'];$dupe=$tx->prepare('SELECT id FROM nfc_payment_intents WHERE tenant_id=? AND provider=? AND provider_transaction_id=? AND id<>? LIMIT 1');$dupe->execute([$tenantId,$fresh['provider'],$providerId,$fresh['id']]);if($dupe->fetchColumn())throw new RuntimeException('Transação do provedor já utilizada em outro pedido.');$balance=(new PaymentService())->remaining((int)$fresh['order_id'],$tenantId);if((int)$fresh['amount_cents']>(int)$balance['remaining_cents'])throw new RuntimeException('O saldo do pedido mudou. Não é seguro confirmar esta cobrança.');
            $key='card-present:'.$fresh['provider'].':'.$fresh['id'];$existing=$tx->prepare('SELECT id FROM payments WHERE tenant_id=? AND idempotency_key=? LIMIT 1');$existing->execute([$tenantId,$key]);$paymentId=(int)$existing->fetchColumn();if($paymentId<1){$tx->prepare('INSERT INTO payments (tenant_id,order_id,provider,idempotency_key,amount_cents,currency,status) VALUES (?,?,?,?,?,"BRL","created")')->execute([$tenantId,$fresh['order_id'],$fresh['provider'],$key,$fresh['amount_cents']]);$paymentId=(int)$tx->lastInsertId();}
            $tx->prepare('UPDATE nfc_payment_intents SET provider_transaction_code=?,provider_transaction_id=?,provider_merchant_reference=?,provider_result_json=?,payment_id=? WHERE id=?')->execute([(string)($verified['transaction_code']??$providerId),$providerId,(string)$verified['account_reference'],json_encode($providerResult,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$paymentId,$fresh['id']]);return$paymentId;
        });
        try{(new PaymentCollectionService())->register($paymentId,'card','eventmenu_go_'.(string)$intent['provider'].'_tap_to_pay');}catch(\Throwable){}
        $verified['payment_id']=$paymentId;(new PaymentService())->confirmVerified($verified);$pdo->prepare('UPDATE nfc_payment_intents SET status="verified",verified_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?')->execute([$intent['id'],$tenantId]);Auth::audit('card_present.payment_verified','order',(string)$intent['order_id'],['intent_id'=>(int)$intent['id'],'payment_id'=>$paymentId,'provider'=>$intent['provider'],'method'=>$intent['payment_method'],'amount_cents'=>(int)$intent['amount_cents']]);return['ok'=>true,'provider'=>$intent['provider'],'order_id'=>(int)$intent['order_id'],'payment_id'=>$paymentId,'balance'=>(new PaymentService())->remaining((int)$intent['order_id'],$tenantId)];
    }

    public function failIntent(string $intentToken,string $reason,string $deviceIdentifier): void
    {
        $tenantId=Auth::tenantId();$userId=Auth::id();if(!$tenantId||!$userId)return;$reason=mb_substr(trim($reason),0,500);$pdo=Database::connection();$q=$pdo->prepare('SELECT i.id,i.user_id,d.device_identifier_hash FROM nfc_payment_intents i JOIN nfc_devices d ON d.id=i.nfc_device_id WHERE i.tenant_id=? AND i.intent_token_hash=? AND i.status="created" LIMIT 1');$q->execute([$tenantId,hash('sha256',trim($intentToken))]);$row=$q->fetch();if(!$row||(int)$row['user_id']!==$userId||!hash_equals((string)$row['device_identifier_hash'],hash('sha256',trim($deviceIdentifier))))return;$pdo->prepare('UPDATE nfc_payment_intents SET status="failed",provider_result_json=? WHERE id=? AND status="created"')->execute([json_encode(['failure_reason'=>$reason],JSON_UNESCAPED_UNICODE),$row['id']]);
    }

    private function assertOperatorCanCharge(array $order,int $userId): void
    {
        $shift=(new WorkShiftService())->current();if($shift&&$shift['mode']==='delivery'){if(!Auth::can('orders.delivery')||(int)($order['assigned_delivery_user_id']??0)!==$userId)throw new RuntimeException('Esta entrega não está atribuída a você.');(new DeliveryProgressService())->assertArrived((int)$order['order_id']?: (int)$order['id']);return;}if(!Auth::can('payments.manage')&&!Auth::can('nfc.collect'))throw new RuntimeException('Sua função não pode iniciar cobranças por aproximação.');
    }

    private function legacyPagBankSession(int $tenantId): array
    {
        $gateway=(new PaymentProviderRegistry())->gateway($tenantId,'pagbank');$config=$gateway['config'];$appKey=trim((string)($config['tap_on_app_key']??''));if($appKey==='')throw new RuntimeException('Tap On PagBank não configurado.');return['provider'=>'pagbank','app_key'=>$appKey,'app_name'=>(string)($config['tap_on_app_name']??'EventMenu'),'app_version'=>(string)($config['tap_on_app_version']??'1.0.0')];
    }

    private function verifyLegacyPagBank(array $intent,array $result): array
    {
        $code=trim((string)($result['transaction_code']??''));if($code==='')throw new RuntimeException('Código PagBank ausente.');$legacy=new NfcService();$ref=new \ReflectionClass($legacy);$method=$ref->getMethod('queryTapOnTransaction');$method->setAccessible(true);$provider=$method->invoke($legacy,(int)$intent['tenant_id'],$code);if(empty($provider['paid'])||(int)$provider['amount_cents']!==(int)$intent['amount_cents'])throw new RuntimeException('PagBank não confirmou esta transação.');return['paid'=>true,'tenant_id'=>(int)$intent['tenant_id'],'order_id'=>(int)$intent['order_id'],'provider'=>'pagbank','provider_payment_id'=>$code,'amount_cents'=>(int)$provider['amount_cents'],'currency'=>'BRL','account_reference'=>(string)$provider['account_reference'],'raw_status'=>(string)$provider['raw_status'],'source'=>'pagbank_tap_on','transaction_code'=>$code];
    }
}
