<?php

declare(strict_types=1);
namespace EventMenu\Services;
use EventMenu\Core\Crypto;use EventMenu\Core\Database;use RuntimeException;
final class CheckoutService{
 public function create(string $publicToken,string $provider,array $options=[]):array{
  $provider=strtolower(trim($provider));if(!in_array($provider,['stripe','mercadopago','pagbank'],true))throw new RuntimeException('Provedor inválido.');$method=strtolower((string)($options['payment_method']??'checkout'));$document=preg_replace('/\D+/','',(string)($options['payer_document']??''))??'';
  $pdo=Database::connection();$s=$pdo->prepare('SELECT o.*,t.slug tenant_slug,t.status tenant_status,c.name customer_name,c.email customer_email,c.phone customer_phone FROM orders o JOIN tenants t ON t.id=o.tenant_id LEFT JOIN customers c ON c.id=o.customer_id WHERE o.public_token=? LIMIT 1');$s->execute([$publicToken]);$order=$s->fetch();if(!$order||$order['tenant_status']!=='active')throw new RuntimeException('Pedido não encontrado.');if(in_array($order['status'],['cancelled','completed'],true)||$order['payment_status']==='paid')throw new RuntimeException('Pedido não aceita nova cobrança.');if((int)$order['total_cents']<=0)throw new RuntimeException('Pedido com valor inválido.');if($method==='pix'&&!in_array(strlen($document),[11,14],true))throw new RuntimeException('CPF/CNPJ obrigatório para Pix.');
  $g=$pdo->prepare('SELECT * FROM payment_gateways WHERE tenant_id=? AND provider=? AND active=1');$g->execute([$order['tenant_id'],$provider]);$gateway=$g->fetch();if(!$gateway)throw new RuntimeException('Forma de pagamento indisponível.');$config=Crypto::decryptJson($gateway['config_encrypted']);if($method==='pix'&&empty($config['pix_enabled']))throw new RuntimeException('Pix não habilitado neste provedor.');
  $key='public:'.$provider.':'.$method.':'.$order['tenant_id'].':'.$order['id'];$open=$pdo->prepare('SELECT * FROM payments WHERE tenant_id=? AND order_id=? AND status IN ("created","pending","authorized") ORDER BY id DESC LIMIT 1');$open->execute([$order['tenant_id'],$order['id']]);if($existing=$open->fetch()){ $raw=json_decode((string)($existing['raw_payload']??''),true);if(is_array($raw)&&(!empty($raw['_eventmenu_checkout_url'])||!empty($raw['_eventmenu_pix_code'])))return ['provider'=>$existing['provider'],'url'=>(string)($raw['_eventmenu_checkout_url']??''),'qr_code'=>(string)($raw['_eventmenu_pix_code']??''),'qr_code_base64'=>(string)($raw['_eventmenu_pix_base64']??''),'payment_id'=>(int)$existing['id'],'reused'=>true];throw new RuntimeException('Já existe uma cobrança em andamento para este pedido.');}
  $pdo->prepare('INSERT INTO payments (tenant_id,order_id,provider,idempotency_key,amount_cents,currency,status) VALUES (?,?,?,?,?,"BRL","created")')->execute([$order['tenant_id'],$order['id'],$provider,$key,$order['total_cents']]);$paymentId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE orders SET payment_status="pending" WHERE id=?')->execute([$order['id']]);(new StockReservationService())->holdForPayment((int)$order['tenant_id'],(int)$order['id']);
  try{$result=$method==='pix'&&$provider==='mercadopago'?$this->mercadoPagoPix($order,$config,$key,$document):($provider==='mercadopago'?$this->mercadoPago($order,$config,$key):($provider==='pagbank'?$this->pagBank($order,$config,$key,$method):$this->stripe($order,$gateway,$config,$key)));$payload=$result['raw'];$payload['_eventmenu_checkout_url']=$result['url']??'';$payload['_eventmenu_pix_code']=$result['qr_code']??'';$payload['_eventmenu_pix_base64']=$result['qr_code_base64']??'';$pdo->prepare('UPDATE payments SET provider_payment_id=?,status="pending",raw_payload=? WHERE id=?')->execute([$result['external_id'],json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$paymentId]);return ['provider'=>$provider,'url'=>$result['url']??'','qr_code'=>$result['qr_code']??'','qr_code_base64'=>$result['qr_code_base64']??'','payment_id'=>$paymentId,'reused'=>false];}catch(\Throwable $e){$pdo->prepare('UPDATE payments SET status="failed",raw_payload=? WHERE id=?')->execute([json_encode(['error'=>$e->getMessage()]),$paymentId]);$pdo->prepare('UPDATE orders SET payment_status="failed" WHERE id=? AND payment_status="pending"')->execute([$order['id']]);(new StockReservationService())->rearmAfterPaymentFailure((int)$order['tenant_id'],(int)$order['id']);throw$e;}
 }
 private function mercadoPagoPix(array$o,array$c,string$key,string$doc):array{$token=(string)($c['access_token']??'');if($token==='')throw new RuntimeException('Mercado Pago não configurado.');$type=strlen($doc)===11?'CPF':'CNPJ';$body=['transaction_amount'=>((int)$o['total_cents'])/100,'description'=>'Pedido EventMenu #'.$o['id'],'payment_method_id'=>'pix','external_reference'=>'eventmenu:'.$o['tenant_id'].':'.$o['id'],'payer'=>['email'=>$o['customer_email']?:'cliente@eventmenu.local','identification'=>['type'=>$type,'number'=>$doc]],'notification_url'=>\app_absolute_url('webhook.php?provider=mercadopago&tenant='.rawurlencode($o['tenant_slug']))];$d=$this->httpJson('POST','https://api.mercadopago.com/v1/payments',['Authorization: Bearer '.$token,'X-Idempotency-Key: '.$key],$body);$tx=$d['point_of_interaction']['transaction_data']??[];return['url'=>(string)($tx['ticket_url']??''),'qr_code'=>(string)($tx['qr_code']??''),'qr_code_base64'=>(string)($tx['qr_code_base64']??''),'external_id'=>(string)($d['id']??''),'raw'=>$d];}
 private function mercadoPago(array$o,array$g,array$c,string$key):array{$token=(string)($c['access_token']??'');if($token==='')throw new RuntimeException('Mercado Pago não configurado.');$ret=\app_absolute_url('pedido.php?t='.rawurlencode($o['public_token']));$b=['items'=>[['title'=>'Pedido EventMenu #'.$o['id'],'quantity'=>1,'currency_id'=>'BRL','unit_price'=>((int)$o['total_cents'])/100]],'external_reference'=>'eventmenu:'.$o['tenant_id'].':'.$o['id'],'back_urls'=>['success'=>$ret,'pending'=>$ret,'failure'=>$ret],'notification_url'=>\app_absolute_url('webhook.php?provider=mercadopago&tenant='.rawurlencode($o['tenant_slug']))];$d=$this->httpJson('POST','https://api.mercadopago.com/checkout/preferences',['Authorization: Bearer '.$token,'X-Idempotency-Key: '.$key],$b);return['url'=>(string)($d['init_point']??''),'external_id'=>(string)($d['id']??''),'raw'=>$d];}
 private function pagBank(array$o,array$c,string$key,string$method):array{$token=(string)($c['token']??'');if($token==='')throw new RuntimeException('PagBank não configurado.');$api=rtrim((string)($c['api_base']??'https://api.pagseguro.com'),'/');$methods=$method==='pix'?[['type'=>'PIX']]:[['type'=>'CREDIT_CARD'],['type'=>'PIX']];$ret=\app_absolute_url('pedido.php?t='.rawurlencode($o['public_token']));$b=['reference_id'=>'eventmenu:'.$o['tenant_id'].':'.$o['id'],'items'=>[['name'=>'Pedido EventMenu #'.$o['id'],'quantity'=>1,'unit_amount'=>(int)$o['total_cents']]],'payment_methods'=>$methods,'redirect_url'=>$ret,'return_url'=>$ret,'notification_urls'=>[\app_absolute_url('webhook.php?provider=pagbank&tenant='.rawurlencode($o['tenant_slug']))]];$d=$this->httpJson('POST',$api.'/checkouts',['Authorization: Bearer '.$token,'x-idempotency-key: '.$key],$b);$url='';foreach(($d['links']??[])as$l)if(($l['rel']??'')==='PAY'){$url=(string)$l['href'];break;}return['url'=>$url,'external_id'=>(string)($d['id']??''),'raw'=>$d];}
 private function stripe(array$o,array$g,array$c,string$key):array{throw new RuntimeException('Stripe permanece disponível pelo checkout padrão; Pix não é processado pelo Stripe neste fluxo.');}
 private function httpJson(string$m,string$u,array$h,array$b):array{$ch=curl_init($u);if($ch===false)throw new RuntimeException('Falha HTTP.');$h[]='Accept: application/json';$h[]='Content-Type: application/json';curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$m,CURLOPT_HTTPHEADER=>$h,CURLOPT_POSTFIELDS=>json_encode($b,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>25,CURLOPT_SSL_VERIFYPEER=>true]);$r=curl_exec($ch);$s=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($r===false||$s<200||$s>=300)throw new RuntimeException('Gateway recusou a cobrança (HTTP '.$s.').');$d=json_decode((string)$r,true,512,JSON_THROW_ON_ERROR);if(!is_array($d))throw new RuntimeException('Resposta inválida do gateway.');return$d;}
}
