<?php

declare(strict_types=1);

namespace EventMenu\Services;

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use PDO;
use RuntimeException;

final class InventoryService
{
    public function move(int $productId,string $type,float $quantity,string $reason,?int $unitCostCents=null):array
    {
        Auth::requirePermission('inventory.manage');$tenantId=Auth::tenantId();$userId=Auth::id();if(!$tenantId||!$userId)throw new RuntimeException('Operador ou empresa inválidos.');
        $unit=(new OperatingUnitService())->requireCurrent();$unitId=(int)$unit['id'];$type=strtolower(trim($type));if(!in_array($type,['in','out'],true))throw new RuntimeException('Escolha entrada ou saída.');if(!is_finite($quantity)||$quantity<=0)throw new RuntimeException('Informe uma quantidade maior que zero.');$reason=mb_substr(trim($reason),0,500);if($reason==='')throw new RuntimeException('Informe o motivo da movimentação.');if($unitCostCents!==null&&$unitCostCents<0)throw new RuntimeException('Informe um custo válido.');
        $dedupe=$this->shortActionKey('move',$tenantId,$userId,$unitId,$productId,$type,$quantity,$reason,$unitCostCents);
        return Database::transaction(function(PDO$pdo)use($tenantId,$userId,$unitId,$unit,$productId,$type,$quantity,$reason,$unitCostCents,$dedupe):array{
            $product=$this->lockedProduct($pdo,$tenantId,$productId);if(!(int)$product['track_stock'])throw new RuntimeException('Este produto não está com controle de estoque ativo.');$this->ensureUnitRow($pdo,$tenantId,$unitId,$product);
            $s=$pdo->prepare(Database::portableSql($pdo,'SELECT * FROM unit_inventory WHERE tenant_id=? AND unit_id=? AND product_id=? FOR UPDATE'));$s->execute([$tenantId,$unitId,$productId]);$inventory=$s->fetch();if(!$inventory)throw new RuntimeException('Não foi possível carregar o saldo desta unidade.');
            $dup=$pdo->prepare('SELECT id FROM stock_movements WHERE tenant_id=? AND unit_id=? AND product_id=? AND idempotency_key=? LIMIT 1');$dup->execute([$tenantId,$unitId,$productId,$dedupe]);if($dup->fetchColumn())return['product_id'=>$productId,'unit_id'=>$unitId,'before'=>(float)$inventory['stock_qty'],'after'=>(float)$inventory['stock_qty'],'type'=>$type,'quantity'=>0.0,'average_cost_cents'=>(int)$inventory['average_cost_cents'],'duplicate_ignored'=>true];
            $current=(float)$inventory['stock_qty'];$next=$type==='in'?$current+$quantity:$current-$quantity;if($next<-.0005)throw new RuntimeException('A quantidade de saída é maior que o estoque disponível.');$average=(int)$inventory['average_cost_cents'];
            if($type==='in'&&$unitCostCents!==null){$r=$pdo->prepare('SELECT COALESCE(SUM(quantity),0) FROM stock_reservations WHERE tenant_id=? AND unit_id=? AND product_id=? AND status="reserved"');$r->execute([$tenantId,$unitId,$productId]);$reserved=(float)$r->fetchColumn();$physical=max(0.0,$current+$reserved);$den=$physical+$quantity;$average=$den>0?(int)round((($physical*(int)$inventory['average_cost_cents'])+($quantity*$unitCostCents))/$den):$unitCostCents;}
            $pdo->prepare('UPDATE unit_inventory SET stock_qty=?,average_cost_cents=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND unit_id=? AND product_id=?')->execute([$next,$average,$tenantId,$unitId,$productId]);$movementCost=$type==='in'?($unitCostCents??$average):$average;$pdo->prepare('INSERT INTO stock_movements (tenant_id,unit_id,product_id,order_id,type,quantity,idempotency_key,unit_cost_cents,total_cost_cents,reason,performed_by) VALUES (?,?,?,NULL,?,?,?,?,?,?,?)')->execute([$tenantId,$unitId,$productId,$type,$quantity,$dedupe,$movementCost,(int)round($movementCost*$quantity),$reason,$userId]);$this->syncLegacyProduct($pdo,$tenantId,$productId);Auth::audit('inventory.'.$type,'product',(string)$productId,['unit_id'=>$unitId,'unit_name'=>$unit['name'],'quantity'=>$quantity,'before'=>$current,'after'=>$next,'reason'=>$reason,'unit_cost_cents'=>$movementCost,'average_cost_cents'=>$average]);return['product_id'=>$productId,'unit_id'=>$unitId,'before'=>$current,'after'=>$next,'type'=>$type,'quantity'=>$quantity,'average_cost_cents'=>$average,'duplicate_ignored'=>false];
        });
    }

    public function setStock(int$productId,float$newQuantity,string$reason):array
    {
        Auth::requirePermission('inventory.manage');$tenantId=Auth::tenantId();$userId=Auth::id();if(!$tenantId||!$userId)throw new RuntimeException('Operador ou empresa inválidos.');$unit=(new OperatingUnitService())->requireCurrent();$unitId=(int)$unit['id'];if(!is_finite($newQuantity)||$newQuantity<0)throw new RuntimeException('Informe um saldo válido.');$reason=mb_substr(trim($reason),0,500);if($reason==='')throw new RuntimeException('Informe o motivo do ajuste.');
        return Database::transaction(function(PDO$pdo)use($tenantId,$userId,$unitId,$unit,$productId,$newQuantity,$reason):array{$product=$this->lockedProduct($pdo,$tenantId,$productId);if(!(int)$product['track_stock'])throw new RuntimeException('Este produto não está com controle de estoque ativo.');$this->ensureUnitRow($pdo,$tenantId,$unitId,$product);$s=$pdo->prepare(Database::portableSql($pdo,'SELECT * FROM unit_inventory WHERE tenant_id=? AND unit_id=? AND product_id=? FOR UPDATE'));$s->execute([$tenantId,$unitId,$productId]);$inventory=$s->fetch();$current=(float)$inventory['stock_qty'];if(abs($current-$newQuantity)<.000001)return['product_id'=>$productId,'unit_id'=>$unitId,'before'=>$current,'after'=>$newQuantity,'type'=>'adjustment','quantity'=>0.0];$delta=$newQuantity-$current;$pdo->prepare('UPDATE unit_inventory SET stock_qty=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND unit_id=? AND product_id=?')->execute([$newQuantity,$tenantId,$unitId,$productId]);$average=(int)$inventory['average_cost_cents'];$key='inventory-adjust:'.$tenantId.':'.$unitId.':'.$productId.':'.bin2hex(random_bytes(12));$pdo->prepare('INSERT INTO stock_movements (tenant_id,unit_id,product_id,order_id,type,quantity,idempotency_key,unit_cost_cents,total_cost_cents,reason,performed_by) VALUES (?,?,?,NULL,"adjustment",?,?,?,?,?,?)')->execute([$tenantId,$unitId,$productId,$delta,$key,$average,(int)round($average*$delta),$reason,$userId]);$this->syncLegacyProduct($pdo,$tenantId,$productId);Auth::audit('inventory.adjustment','product',(string)$productId,['unit_id'=>$unitId,'unit_name'=>$unit['name'],'delta'=>$delta,'before'=>$current,'after'=>$newQuantity,'reason'=>$reason]);return['product_id'=>$productId,'unit_id'=>$unitId,'before'=>$current,'after'=>$newQuantity,'type'=>'adjustment','quantity'=>$delta];});
    }

    public function waste(int$productId,float$quantity,string$reasonType,string$reason=''):int
    {
        Auth::requirePermission('inventory.manage');$allowed=['expired','breakage','production_error','internal_use','courtesy','waste','other'];if(!in_array($reasonType,$allowed,true))throw new RuntimeException('Escolha o motivo da perda.');$tenantId=Auth::tenantId();$userId=Auth::id();if(!$tenantId||!$userId)throw new RuntimeException('Sessão inválida.');if($quantity<=0)throw new RuntimeException('Informe uma quantidade maior que zero.');$unit=(new OperatingUnitService())->requireCurrent();$unitId=(int)$unit['id'];$reason=mb_substr(trim($reason),0,500);$dedupe=$this->shortActionKey('waste',$tenantId,$userId,$unitId,$productId,$reasonType,$quantity,$reason,null);
        return Database::transaction(function(PDO$pdo)use($tenantId,$userId,$unitId,$productId,$quantity,$reasonType,$reason,$dedupe):int{$product=$this->lockedProduct($pdo,$tenantId,$productId);$this->ensureUnitRow($pdo,$tenantId,$unitId,$product);$s=$pdo->prepare(Database::portableSql($pdo,'SELECT * FROM unit_inventory WHERE tenant_id=? AND unit_id=? AND product_id=? FOR UPDATE'));$s->execute([$tenantId,$unitId,$productId]);$inventory=$s->fetch();$dup=$pdo->prepare('SELECT id FROM stock_movements WHERE tenant_id=? AND unit_id=? AND product_id=? AND idempotency_key=? LIMIT 1');$dup->execute([$tenantId,$unitId,$productId,$dedupe]);if($dup->fetchColumn())return 0;$current=(float)$inventory['stock_qty'];if($quantity-$current>.0005)throw new RuntimeException('A perda informada é maior que o saldo disponível.');$cost=(int)$inventory['average_cost_cents'];$pdo->prepare('UPDATE unit_inventory SET stock_qty=stock_qty-?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND unit_id=? AND product_id=?')->execute([$quantity,$tenantId,$unitId,$productId]);$pdo->prepare('INSERT INTO inventory_waste (tenant_id,unit_id,product_id,quantity,reason_type,reason,cost_cents,user_id) VALUES (?,?,?,?,?,?,?,?)')->execute([$tenantId,$unitId,$productId,$quantity,$reasonType,$reason?:null,(int)round($cost*$quantity),$userId]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO stock_movements (tenant_id,unit_id,product_id,order_id,type,quantity,idempotency_key,unit_cost_cents,total_cost_cents,reason,performed_by) VALUES (?,?,?,NULL,"out",?,?,?,?,?,?)')->execute([$tenantId,$unitId,$productId,$quantity,$dedupe,$cost,(int)round($cost*$quantity),$reasonType.($reason?': '.$reason:''),$userId]);$this->syncLegacyProduct($pdo,$tenantId,$productId);Auth::audit('inventory.waste','product',(string)$productId,['unit_id'=>$unitId,'quantity'=>$quantity,'reason_type'=>$reasonType,'reason'=>$reason]);return$id;});
    }

    private function shortActionKey(string$operation,int$tenantId,int$userId,int$unitId,int$productId,string$type,float$quantity,string$reason,?int$cost):string
    {
        // Janela curta: protege clique duplo/reenvio imediato sem impedir uma nova operação legítima depois.
        $bucket=(int)floor(time()/8);$fingerprint=implode('|',[$operation,$tenantId,$userId,$unitId,$productId,$type,number_format($quantity,6,'.',''),mb_strtolower(trim($reason)),$cost??'',(string)$bucket]);return 'inventory-action:'.hash('sha256',$fingerprint);
    }

    private function lockedProduct(PDO$pdo,int$tenantId,int$productId):array{$s=$pdo->prepare(Database::portableSql($pdo,'SELECT id,name,stock_qty,track_stock,average_cost_cents,min_stock_qty FROM products WHERE id=? AND tenant_id=? FOR UPDATE'));$s->execute([$productId,$tenantId]);$product=$s->fetch();if(!$product)throw new RuntimeException('Produto não encontrado.');return$product;}
    private function ensureUnitRow(PDO$pdo,int$tenantId,int$unitId,array$product):void{$sql=Database::portableSql($pdo,'INSERT IGNORE INTO unit_inventory (tenant_id,unit_id,product_id,stock_qty,average_cost_cents,min_stock_qty) VALUES (?,?,?,?,?,?)');$pdo->prepare($sql)->execute([$tenantId,$unitId,$product['id'],0,$product['average_cost_cents']??0,$product['min_stock_qty']??0]);}
    private function syncLegacyProduct(PDO$pdo,int$tenantId,int$productId):void{$s=$pdo->prepare('SELECT COALESCE(SUM(stock_qty),0) qty,CASE WHEN COALESCE(SUM(stock_qty),0)>0 THEN CAST(ROUND(SUM(stock_qty*average_cost_cents)/SUM(stock_qty)) AS INTEGER) ELSE MAX(average_cost_cents) END avg_cost FROM unit_inventory WHERE tenant_id=? AND product_id=?');$s->execute([$tenantId,$productId]);$row=$s->fetch()?:['qty'=>0,'avg_cost'=>0];$pdo->prepare('UPDATE products SET stock_qty=?,average_cost_cents=? WHERE id=? AND tenant_id=?')->execute([(float)$row['qty'],(int)($row['avg_cost']??0),$productId,$tenantId]);}
}
