<?php

declare(strict_types=1);

namespace EventMenu\Services;

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use EventMenu\Services\Payments\MercadoPagoPixProvider;
use EventMenu\Services\Payments\PagBankPixProvider;
use EventMenu\Services\Payments\PagarMePixProvider;
use EventMenu\Services\Payments\PaymentProviderRegistry;
use EventMenu\Services\Payments\PixProviderInterface;
use PDO;
use RuntimeException;

final class NativePixService
{
    public function create(int $orderId,string $taxId,?int $amountCents=null,?string $provider=null):array
    {
        $tenantId=Auth::tenantId();$userId=Auth::id();if(!$tenantId||!$userId)throw new RuntimeException('Sessão inválida.');$taxId=$this->validTaxId($taxId);$pdo=Database::connection();
        $o=$pdo->prepare('SELECT o.*,c.name customer_name,c.email customer_email,c.phone customer_phone,t.slug tenant_slug FROM orders o LEFT JOIN customers c ON c.id=o.customer_id JOIN tenants t ON t.id=o.tenant_id WHERE o.id=? AND o.tenant_id=? LIMIT 1');$o->execute([$orderId,$tenantId]);$order=$o->fetch();if(!$order)throw new RuntimeException('Pedido não encontrado.');if(in_array((string)$order['status'],['cancelled','completed'],true)||(string)$order['payment_status']==='paid')throw new RuntimeException('Pedido não aceita cobrança PIX.');
        $shift=(new WorkShiftService())->current();if($shift&&$shift['mode']==='delivery'){if(!Auth::can('orders.delivery')||(int)($order['assigned_delivery_user_id']??0)!==$userId)throw new RuntimeException('Este pedido não está atribuído a você.');(new DeliveryProgressService())->assertArrived($orderId);}elseif(!Auth::can('payments.manage'))throw new RuntimeException('Você não possui permissão para cobrar PIX.');
        $balance=(new PaymentService())->remaining($orderId,$tenantId);$remaining=(int)$balance['remaining_cents'];$paidBefore=(int)$balance['paid_cents'];$amount=$amountCents??$remaining;if($amount<=0||$amount>$remaining)throw new RuntimeException('Valor PIX inválido. Saldo restante: R$ '.number_format($remaining/100,2,',','.').'.');
        $registry=new PaymentProviderRegistry();$provider=$provider?:$registry->preference($tenantId,'pix');if(!$provider)throw new RuntimeException('Nenhum provedor PIX está ativo nesta empresa.');if(!$registry->supports($provider,'pix'))throw new RuntimeException('O provedor escolhido não oferece PIX no EventMenu.');$gateway=$registry->gateway($tenantId,$provider);$adapter=$this->adapter($provider);
        $key='go-pix:'.$provider.':'.$tenantId.':'.$orderId.':'.$paidBefore.':'.$amount;$existing=$pdo->prepare('SELECT * FROM payments WHERE tenant_id=? AND order_id=? AND provider=? AND idempotency_key=? LIMIT 1');$existing->execute([$tenantId,$orderId,$provider,$key]);$payment=$existing->fetch();if($payment){try{(new PaymentCollectionService())->register((int)$payment['id'],'pix','eventmenu_go_pix_'.$provider);}catch(\Throwable){}$raw=json_decode((string)($payment['raw_payload']??''),true);if(is_array($raw)&&!empty($raw['_eventmenu_pix_text'])&&in_array($payment['status'],['created','pending','authorized'],true))return$this->responseFromPayload($payment,$raw,true,$provider);}
        $active=$pdo->prepare('SELECT id FROM payments WHERE tenant_id=? AND order_id=? AND status IN ("created","pending","authorized") AND id<>? LIMIT 1');$active->execute([$tenantId,$orderId,$payment['id']??0]);if($active->fetchColumn())throw new RuntimeException('Já existe outra cobrança em andamento para este pedido.');$activeTap=$pdo->prepare('SELECT id FROM nfc_payment_intents WHERE tenant_id=? AND order_id=? AND status="created" AND expires_at>CURRENT_TIMESTAMP LIMIT 1');$activeTap->execute([$tenantId,$orderId]);if($activeTap->fetchColumn())throw new RuntimeException('Existe uma cobrança por aproximação em andamento para este pedido.');
        if(!$payment){Database::transaction(function(PDO$tx)use(&$payment,$tenantId,$orderId,$provider,$key,$amount):void{$lock=$tx->prepare(Database::portableSql($tx,'SELECT * FROM orders WHERE id=? AND tenant_id=? FOR UPDATE'));$lock->execute([$orderId,$tenantId]);$fresh=$lock->fetch();if(!$fresh||in_array((string)$fresh['status'],['cancelled','completed'],true)||(string)$fresh['payment_status']==='paid')throw new RuntimeException('Pedido não aceita cobrança.');$check=(new PaymentService())->remaining($orderId,$tenantId);if($amount>(int)$check['remaining_cents'])throw new RuntimeException('Saldo do pedido mudou. Atualize o pagamento.');$tx->prepare('INSERT INTO payments (tenant_id,order_id,provider,idempotency_key,amount_cents,currency,status) VALUES (?,?,?,?,?,"BRL","created")')->execute([$tenantId,$orderId,$provider,$key,$amount]);$id=(int)$tx->lastInsertId();$tx->prepare('UPDATE orders SET payment_status="pending" WHERE id=?')->execute([$orderId]);$q=$tx->prepare('SELECT * FROM payments WHERE id=?');$q->execute([$id]);$payment=$q->fetch();});}
        try{(new PaymentCollectionService())->register((int)$payment['id'],'pix','eventmenu_go_pix_'.$provider);}catch(\Throwable){}(new StockReservationService())->holdForPayment($tenantId,$orderId);
        $customerName=mb_substr(trim((string)($order['customer_name']?:'Cliente EventMenu')),0,120);$pagbankCustomer=['name'=>$customerName,'tax_id'=>$taxId];$email=trim((string)($order['customer_email']??''));if(filter_var($email,FILTER_VALIDATE_EMAIL))$pagbankCustomer['email']=$email;$phone=preg_replace('/\D+/','',(string)($order['customer_phone']??''))??'';if(strlen($phone)>=10){$local=substr($phone,-11);$pagbankCustomer['phones']=[['country'=>'55','area'=>substr($local,0,2),'number'=>substr($local,2),'type'=>'MOBILE']];}
        $context=['tenant_id'=>$tenantId,'order_id'=>$orderId,'payment_id'=>(int)$payment['id'],'amount_cents'=>$amount,'tax_id'=>$taxId,'customer_name'=>$customerName,'customer_email'=>$email,'customer_phone'=>$phone,'pagbank_customer'=>$pagbankCustomer,'reference'=>'eventmenu:'.$tenantId.':'.$orderId.':payment:'.$payment['id'],'idempotency_key'=>$key,'webhook_url'=>\app_absolute_url('webhook.php?provider='.rawurlencode($provider).'&tenant='.rawurlencode((string)$order['tenant_slug']))];
        try{$created=$adapter->createCharge($context,$gateway);if(trim((string)$created['external_id'])==='')throw new RuntimeException('Provedor não retornou identificador da cobrança PIX.');$raw=$created['raw'];$raw['_eventmenu_pix_text']=$created['copy_paste'];$raw['_eventmenu_pix_image_url']=$created['image_url'];$raw['_eventmenu_pix_image_base64']=$created['image_base64'];$raw['_eventmenu_pix_expires_at']=$created['expires_at'];$raw['_eventmenu_payment_id']=(int)$payment['id'];$raw['_eventmenu_provider']=$provider;$pdo->prepare('UPDATE payments SET provider_payment_id=?,status="pending",raw_payload=? WHERE id=? AND tenant_id=?')->execute([(string)$created['external_id'],json_encode($raw,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$payment['id'],$tenantId]);Auth::audit('payment.pix_created','payment',(string)$payment['id'],['order_id'=>$orderId,'provider'=>$provider,'amount_cents'=>$amount,'source'=>'eventmenu_go']);$payment['status']='pending';$payment['provider_payment_id']=(string)$created['external_id'];return$this->responseFromPayload($payment,$raw,false,$provider);}catch(\Throwable$e){$pdo->prepare('UPDATE payments SET status="failed",raw_payload=? WHERE id=? AND tenant_id=?')->execute([json_encode(['provider'=>$provider,'error'=>$e->getMessage(),'remote_result_unknown'=>str_contains(strtolower($e->getMessage()),'timeout')],JSON_UNESCAPED_UNICODE),$payment['id'],$tenantId]);$sum=$pdo->prepare('SELECT COALESCE(SUM(amount_cents),0) FROM payments WHERE tenant_id=? AND order_id=? AND status="paid"');$sum->execute([$tenantId,$orderId]);$pdo->prepare('UPDATE orders SET payment_status=? WHERE id=? AND tenant_id=? AND payment_status<>"paid"')->execute([(int)$sum->fetchColumn()>0?'pending':'failed',$orderId,$tenantId]);(new StockReservationService())->rearmAfterPaymentFailure($tenantId,$orderId,30);throw$e;}
    }

    private function adapter(string$provider):PixProviderInterface{return match($provider){'pagbank'=>new PagBankPixProvider(),'mercadopago'=>new MercadoPagoPixProvider(),'pagarme'=>new PagarMePixProvider(),default=>throw new RuntimeException('Adaptador PIX '.$provider.' ainda não está implementado.')};}
    private function responseFromPayload(array$payment,array$raw,bool$reused,string$provider):array{return['provider'=>$provider,'payment_id'=>(int)$payment['id'],'order_id'=>(int)$payment['order_id'],'amount_cents'=>(int)$payment['amount_cents'],'copy_paste'=>(string)$raw['_eventmenu_pix_text'],'image_url'=>(string)($raw['_eventmenu_pix_image_url']??''),'image_base64'=>(string)($raw['_eventmenu_pix_image_base64']??''),'expires_at'=>(string)($raw['_eventmenu_pix_expires_at']??''),'reused'=>$reused];}
    private function validTaxId(string$value):string{$v=preg_replace('/\D+/','',$value)??'';if(!in_array(strlen($v),[11,14],true)||preg_match('/^(\d)\1+$/',$v))throw new RuntimeException('CPF/CNPJ inválido.');if(strlen($v)===11){for($t=9;$t<11;$t++){$sum=0;for($i=0;$i<$t;$i++)$sum+=(int)$v[$i]*(($t+1)-$i);$d=(10*($sum%11))%11;if($d===10)$d=0;if((int)$v[$t]!==$d)throw new RuntimeException('CPF inválido.');}return$v;}$calc=function(string$base,array$weights):int{$sum=0;foreach($weights as$i=>$w)$sum+=(int)$base[$i]*$w;$r=$sum%11;return$r<2?0:11-$r;};$d1=$calc(substr($v,0,12),[5,4,3,2,9,8,7,6,5,4,3,2]);$d2=$calc(substr($v,0,12).$d1,[6,5,4,3,2,9,8,7,6,5,4,3,2]);if((int)$v[12]!==$d1||(int)$v[13]!==$d2)throw new RuntimeException('CNPJ inválido.');return$v;}
}
