<?php

declare(strict_types=1);
namespace EventMenu\Services;
use EventMenu\Core\Crypto;use EventMenu\Core\Database;use RuntimeException;
final class PixPaymentService{
 public function configuration(int $tenantId):array{$pdo=Database::connection();$s=$pdo->prepare('SELECT provider,config_encrypted FROM payment_gateways WHERE tenant_id=? AND active=1');$s->execute([$tenantId]);$providers=[];$default='';$has=false;foreach($s->fetchAll()as$row){$cfg=Crypto::decryptJson($row['config_encrypted']);if(!empty($cfg['pix_enabled']))$providers[]=(string)$row['provider'];if(!empty($cfg['pix_enabled'])&&!empty($cfg['pix_default']))$default=(string)$row['provider'];$doc=$this->digits((string)($cfg['pix_default_document']??''));if(!empty($cfg['pix_enabled'])&&in_array(strlen($doc),[11,14],true))$has=true;}if($default===''&&$providers)$default=$providers[0];return['enabled'=>(bool)$providers,'default_provider'=>$default,'providers'=>array_values(array_unique($providers)),'requires_document'=>!$has,'has_default_document'=>$has];}
 public function create(int $tenantId,int $orderId,string $document='',string $provider=''):array{$pdo=Database::connection();$o=$pdo->prepare('SELECT public_token,total_cents FROM orders WHERE id=? AND tenant_id=?');$o->execute([$orderId,$tenantId]);$order=$o->fetch();if(!$order)throw new RuntimeException('Pedido não encontrado.');$cfg=$this->configuration($tenantId);$provider=strtolower(trim($provider));if($provider==='')$provider=(string)$cfg['default_provider'];if($provider===''||!in_array($provider,$cfg['providers'],true))throw new RuntimeException('Pix não configurado para esta empresa.');$g=$pdo->prepare('SELECT config_encrypted FROM payment_gateways WHERE tenant_id=? AND provider=? AND active=1 LIMIT 1');$g->execute([$tenantId,$provider]);$encrypted=$g->fetchColumn();if($encrypted===false)throw new RuntimeException('Provedor Pix indisponível.');$pc=Crypto::decryptJson((string)$encrypted);$provided=$this->digits($document);$fallback=$this->digits((string)($pc['pix_default_document']??''));$effective=$provided!==''?$provided:$fallback;if(!in_array(strlen($effective),[11,14],true))throw new RuntimeException('Informe CPF/CNPJ ou configure um documento padrão para o Pix.');$r=(new CheckoutService())->create((string)$order['public_token'],$provider,['payment_method'=>'pix','payer_document'=>$effective]);$copy=(string)($r['qr_code']??'');$image=(string)($r['qr_code_base64']??'');return $r+['order_id'=>$orderId,'amount_cents'=>(int)$order['total_cents'],'copy_paste'=>$copy,'image_url'=>$image!==''?'data:image/png;base64,'.$image:'','expires_at'=>'','document_masked'=>$this->mask($effective),'document_source'=>$provided!==''?'customer':'configured_default','payment_method'=>'pix'];}
 private function digits(string$v):string{return preg_replace('/\D+/','',$v)??'';}private function mask(string$v):string{return strlen($v)===11?'***.***.***-'.substr($v,-2):'**.***.***/****-'.substr($v,-2);}
}
