<?php

declare(strict_types=1);
namespace EventMenu\Services;
use EventMenu\Core\Auth;use EventMenu\Core\Crypto;use EventMenu\Core\Database;use RuntimeException;
final class PixService{
 private const SUPPORTED=['mercadopago','pagbank','efi','inter'];
 public function create(int $orderId,string $taxId='',?int $amountCents=null,?string $requestedProvider=null):array{$provider=$this->resolveProvider($requestedProvider);$taxId=$this->resolveTaxId($orderId,$taxId);$result=match($provider){'mercadopago'=>(new MercadoPagoPixService())->create($orderId,$taxId,$amountCents),'pagbank'=>(new PagBankPixService())->create($orderId,$taxId,$amountCents),'efi','inter'=>(new OperationalBankPixService())->create($orderId,$taxId,$amountCents,$provider),default=>throw new RuntimeException('Provedor PIX não suportado.')};return ['provider'=>$provider]+$result;}
 public function available():array{$tenantId=Auth::tenantId();if(!$tenantId)return [];$s=Database::connection()->prepare('SELECT provider,config_encrypted FROM payment_gateways WHERE tenant_id=? AND active=1 AND provider IN ("mercadopago","pagbank","efi","inter")');$s->execute([$tenantId]);$out=[];foreach($s->fetchAll()as$row){$config=Crypto::decryptJson((string)$row['config_encrypted']);if(array_key_exists('pix_enabled',$config)&&!filter_var($config['pix_enabled'],FILTER_VALIDATE_BOOL))continue;$out[]=(string)$row['provider'];}return$out;}
 private function resolveProvider(?string $requested):string{$available=$this->available();if(!$available)throw new RuntimeException('Nenhum provedor PIX está ativo para esta empresa.');$requested=strtolower(trim((string)$requested));if($requested!==''){if(!in_array($requested,self::SUPPORTED,true)||!in_array($requested,$available,true))throw new RuntimeException('Provedor PIX indisponível para esta empresa.');return$requested;}$tenantId=Auth::tenantId();$pdo=Database::connection();$s=$pdo->prepare('SELECT id,provider,config_encrypted FROM payment_gateways WHERE tenant_id=? AND active=1 AND provider IN ("mercadopago","pagbank","efi","inter")');$s->execute([$tenantId]);$best=null;$priority=PHP_INT_MAX;$defaults=[];foreach($s->fetchAll()as$row){$provider=(string)$row['provider'];if(!in_array($provider,$available,true))continue;$config=Crypto::decryptJson((string)$row['config_encrypted']);$p=max(1,(int)($config['pix_priority']??100));if(!empty($config['pix_default']))$defaults[]=['provider'=>$provider,'priority'=>$p];if($p<$priority){$priority=$p;$best=$provider;}}if($defaults){usort($defaults,static fn(array$a,array$b):int=>($a['priority']<=>$b['priority'])?:strcmp($a['provider'],$b['provider']));$chosen=(string)$defaults[0]['provider'];if(count($defaults)>1)$this->normalizeDefaults($pdo,(int)$tenantId,$chosen);return$chosen;}return$best??$available[0];}
 private function normalizeDefaults(\PDO$pdo,int$tenantId,string$chosen):void{$q=$pdo->prepare('SELECT id,provider,config_encrypted FROM payment_gateways WHERE tenant_id=? AND provider IN ("mercadopago","pagbank","efi","inter")');$q->execute([$tenantId]);foreach($q->fetchAll()as$row){$config=Crypto::decryptJson((string)$row['config_encrypted']);$should=(string)$row['provider']===$chosen;if((bool)($config['pix_default']??false)===$should)continue;$config['pix_default']=$should;$pdo->prepare('UPDATE payment_gateways SET config_encrypted=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?')->execute([Crypto::encryptJson($config),(int)$row['id'],$tenantId]);}}
 private function resolveTaxId(int$orderId,string$provided):string{$digits=preg_replace('/\D+/','',$provided)??'';if($digits!=='')return$digits;$tenantId=Auth::tenantId();if(!$tenantId)return'';$s=Database::connection()->prepare('SELECT c.document FROM orders o LEFT JOIN customers c ON c.id=o.customer_id AND c.tenant_id=o.tenant_id WHERE o.id=? AND o.tenant_id=? LIMIT 1');$s->execute([$orderId,$tenantId]);return preg_replace('/\D+/','',(string)($s->fetchColumn()?:''))??'';}
}
