<?php

declare(strict_types=1);

namespace EventMenu\Services;

use EventMenu\Core\Database;
use EventMenu\Core\TenantFeatures;
use PDO;
use RuntimeException;

final class PublicMenuService
{
    public function create(int$tenantId,array$cart,string$customerName,string$phone,string$address,?string$tableToken=null,string$fulfillment='delivery',?int$eventId=null):array
    {
        $customerName=mb_substr(trim($customerName),0,160);$phone=mb_substr(trim($phone),0,30);$address=mb_substr(trim($address),0,1000);$tableToken=trim((string)$tableToken);$fulfillment=strtolower(trim($fulfillment));$eventId=$eventId&&$eventId>0?$eventId:null;if($customerName==='')throw new RuntimeException('Nome é obrigatório.');$rows=[];foreach($cart as$row){if(!is_array($row))continue;$id=(int)($row['product_id']??0);$qty=(float)($row['qty']??$row['quantity']??0);if($id<1||!is_finite($qty)||$qty<=0)continue;$row['product_id']=$id;$row['qty']=$qty;$rows[]=$row;}if(!$rows)throw new RuntimeException('Carrinho vazio.');
        return Database::transaction(function(PDO$tx)use($tenantId,$rows,$customerName,$phone,$address,$tableToken,$fulfillment,$eventId):array{
            $tenantStmt=$tx->prepare(Database::portableSql($tx,'SELECT * FROM tenants WHERE id=? AND status="active" FOR UPDATE'));$tenantStmt->execute([$tenantId]);$tenant=$tenantStmt->fetch();if(!$tenant||!TenantFeatures::menu($tenantId))throw new RuntimeException('Cardápio indisponível.');$settings=json_decode((string)($tenant['settings']??'{}'),true)?:[];$tableId=null;$tabId=null;$unitId=null;$channel='delivery';$orderEventId=null;$publicUnits=new PublicUnitService();
            if($tableToken!==''&&$eventId)throw new RuntimeException('Pedido de evento não pode ser vinculado a uma mesa.');
            if($tableToken!==''){$lock=$tx->prepare(Database::portableSql($tx,'SELECT * FROM restaurant_tables WHERE tenant_id=? AND qr_token=? AND status<>"inactive" FOR UPDATE'));$lock->execute([$tenantId,$tableToken]);$table=$lock->fetch();if(!$table)throw new RuntimeException('Mesa não está disponível.');$tableId=(int)$table['id'];$unitId=isset($table['unit_id'])&&$table['unit_id']!==null?(int)$table['unit_id']:null;if(!$unitId)throw new RuntimeException('Esta mesa ainda não está vinculada a uma unidade operacional.');$unit=$tx->prepare('SELECT id FROM operating_units WHERE id=? AND tenant_id=? AND active=1 LIMIT 1');$unit->execute([$unitId,$tenantId]);if(!$unit->fetchColumn())throw new RuntimeException('A unidade desta mesa está inativa. Fale com a equipe.');$publicUnits->selectById($tenantId,$unitId);$channel='table';$tab=$tx->prepare(Database::portableSql($tx,'SELECT id FROM tabs WHERE tenant_id=? AND table_id=? AND status="open" ORDER BY id DESC LIMIT 1 FOR UPDATE'));$tab->execute([$tenantId,$tableId]);$tabId=$tab->fetchColumn();if($tabId===false){$tx->prepare('INSERT INTO tabs (tenant_id,table_id,label,status) VALUES (?, ?, ?, "open")')->execute([$tenantId,$tableId,'QR '.$table['name']]);$tabId=(int)$tx->lastInsertId();}}
            elseif($eventId){$eventStmt=$tx->prepare(Database::portableSql($tx,'SELECT id,name,status,bar_enabled,bar_unit_id FROM events WHERE id=? AND tenant_id=? FOR UPDATE'));$eventStmt->execute([$eventId,$tenantId]);$event=$eventStmt->fetch();if(!$event||(string)$event['status']!=='published')throw new RuntimeException('Este evento não está disponível para pedidos.');if(!(int)$event['bar_enabled'])throw new RuntimeException('O cardápio do bar está desativado para este evento.');$barUnitId=(int)($event['bar_unit_id']??0);if($barUnitId<1)throw new RuntimeException('O bar deste evento ainda não possui uma unidade de atendimento configurada.');$selectedUnit=$publicUnits->selectById($tenantId,$barUnitId);$unitId=(int)$selectedUnit['id'];$channel='event_bar';$orderEventId=$eventId;if($phone==='')throw new RuntimeException('Telefone é obrigatório para acompanhar o pedido do evento.');}
            else{if(!in_array($fulfillment,['pickup','delivery'],true))throw new RuntimeException('Escolha Retirada no local ou Delivery.');$selectedUnit=$publicUnits->requireCurrent($tenantId);$unitId=(int)$selectedUnit['id'];$channel=$fulfillment;if($phone==='')throw new RuntimeException('Telefone é obrigatório para acompanhar o pedido.');if($channel==='delivery'&&$address==='')throw new RuntimeException('Endereço é obrigatório para delivery.');}
            $configured=new ConfiguredOrderService();$items=[];$subtotal=0;foreach($rows as$row){$resolved=$configured->resolveLine($tx,$tenantId,$row,true);$subtotal+=(int)$resolved['total_cents'];$items[]=$resolved;}$deliveryFee=$channel==='delivery'?max(0,(int)($settings['delivery_fee_cents']??0)):0;$minimum=max(0,(int)($settings['min_delivery_order_cents']??0));if($channel==='delivery'&&$subtotal<$minimum)throw new RuntimeException('Pedido mínimo para delivery: R$ '.number_format($minimum/100,2,',','.').'.');$total=$subtotal+$deliveryFee;if($total<=0)throw new RuntimeException('Pedido sem valor válido.');
            $customerId=null;if($phone!==''){$c=$tx->prepare('SELECT id FROM customers WHERE tenant_id=? AND phone=? ORDER BY id DESC LIMIT 1');$c->execute([$tenantId,$phone]);$customerId=$c->fetchColumn()?:null;}if($customerId){$tx->prepare('UPDATE customers SET name=? WHERE id=? AND tenant_id=?')->execute([$customerName,$customerId,$tenantId]);}else{$c=$tx->prepare('INSERT INTO customers (tenant_id,name,phone) VALUES (?,?,?)');$c->execute([$tenantId,$customerName,$phone?:null]);$customerId=(int)$tx->lastInsertId();}
            $publicToken=bin2hex(random_bytes(20));$s=$tx->prepare('INSERT INTO orders (public_token,tenant_id,unit_id,event_id,customer_id,table_id,tab_id,channel,status,payment_status,subtotal_cents,delivery_fee_cents,total_cents,delivery_address) VALUES (?,?,?,?,?,?,?,?,"pending","unpaid",?,?,?,?)');$s->execute([$publicToken,$tenantId,$unitId,$orderEventId,$customerId,$tableId,$tabId,$channel,$subtotal,$deliveryFee,$total,$channel==='delivery'?$address:null]);$orderId=(int)$tx->lastInsertId();$ins=$tx->prepare('INSERT INTO order_items (order_id,product_id,name_snapshot,unit_price_cents,quantity,total_cents) VALUES (?,?,?,?,?,?)');foreach($items as$item){$ins->execute([$orderId,$item['product_id'],$item['name'],$item['unit_price_cents'],$item['quantity'],$item['total_cents']]);$configured->persistModifiers($tx,$tenantId,$orderId,(int)$tx->lastInsertId(),$item);}if($tableId)$tx->prepare('UPDATE restaurant_tables SET status=CASE WHEN status="available" THEN "occupied" ELSE status END WHERE id=? AND tenant_id=? AND unit_id=?')->execute([$tableId,$tenantId,$unitId]);$expires=(new\DateTimeImmutable('+30 minutes'))->format('Y-m-d H:i:s');(new StockReservationService())->reserve($tx,$tenantId,$orderId,$items,$expires);$isEventBar=$channel==='event_bar';$history=$isEventBar?'Pedido criado pelo cardápio do evento.':($channel==='pickup'?'Pedido de retirada criado pelo cardápio digital.':'Pedido criado pelo cardápio digital.');(new OrderHistoryService())->record($tx,$tenantId,$orderId,null,'pending',$isEventBar?'event_public':'public',$history,null);return['id'=>$orderId,'public_token'=>$publicToken,'subtotal_cents'=>$subtotal,'delivery_fee_cents'=>$deliveryFee,'total_cents'=>$total,'channel'=>$channel,'unit_id'=>$unitId,'event_id'=>$orderEventId,'table_id'=>$tableId,'tab_id'=>$tabId,'stock_reserved_until'=>$expires];
        });
    }
}
