using System.Globalization;
using System.Media;
using System.Text;
using System.Text.Json;
using EventMenu.Desktop.Models;
namespace EventMenu.Desktop.Services;
public sealed class HubCommandProcessor{
 private readonly DesktopIntegrationApiClient _hubApi;private readonly EventMenuApiClient _api;private readonly LocalHardwareProfileStore _hardwareStore;private readonly RawPrinterService _rawPrinter;private readonly CustomerDisplayStateStore _customerDisplay;private readonly PaymentTerminalCoordinator? _terminalCoordinator;private readonly ScaleReaderService _scaleReader=new();private static readonly CultureInfo PtBr=new("pt-BR");
 public HubCommandProcessor(DesktopIntegrationApiClient hubApi,EventMenuApiClient api,LocalHardwareProfileStore hardwareStore,RawPrinterService rawPrinter,CustomerDisplayStateStore customerDisplay,PaymentTerminalCoordinator? terminalCoordinator=null){_hubApi=hubApi;_api=api;_hardwareStore=hardwareStore;_rawPrinter=rawPrinter;_customerDisplay=customerDisplay;_terminalCoordinator=terminalCoordinator;}
 public async Task ProcessAsync(HubCommand command,CancellationToken ct=default){if(command.Id<1)return;var claimed=await _hubApi.ClaimHubCommandAsync(command.Id,ct);var current=claimed.Command??command;if(current.Status is "completed" or "failed" or "cancelled" or "expired")return;try{var result=await ExecuteAsync(current,ct);await _hubApi.CompleteHubCommandAsync(current.Id,true,result,"",ct);}catch(OperationCanceledException){throw;}catch(Exception ex){await _hubApi.CompleteHubCommandAsync(current.Id,false,new{},Friendly(ex.Message),ct);}}
 private async Task<object> ExecuteAsync(HubCommand command,CancellationToken ct)=>command.CommandType switch{"print_order"=>await PrintOrderAsync(command,ct),"print_receipt"=>await PrintOfficialReceiptAsync(command,ct),"open_drawer"=>OpenDrawer(),"tef_charge"=>await ChargeTefAsync(command,ct),"customer_display"=>await CustomerDisplayAsync(command,ct),"scale_read"=>await ReadScaleAsync(ct),"kitchen_alert"=>PlayAlert(command),"play_alert"=>PlayAlert(command),"print_label"=>PrintLabel(command),_=>throw new InvalidOperationException("Este comando não é suportado por esta versão do EventMenu Desktop.")};
 private async Task<object> PrintOrderAsync(HubCommand command,CancellationToken ct){var orderId=Int(command.Payload,"order_id");if(orderId<1)throw new InvalidOperationException("Pedido inválido.");var details=await _api.OrderDetailsAsync(orderId,ct);var order=details.Order??throw new InvalidOperationException("Pedido não encontrado.");var profile=_hardwareStore.Load();var printer=profile.DefaultPrinter;if(string.IsNullOrWhiteSpace(printer))throw new InvalidOperationException("Configure a impressora padrão no EventMenu Desktop.");_rawPrinter.PrintText(printer,BuildOrderText(order,details.Items),$"EventMenu - Pedido {orderId}");return new{printed=true,order_id=orderId,document="order"};}
 private async Task<object> PrintOfficialReceiptAsync(HubCommand command,CancellationToken ct){var orderId=Int(command.Payload,"order_id");if(orderId<1)throw new InvalidOperationException("Pedido inválido.");var profile=_hardwareStore.Load();var printer=profile.DefaultPrinter;if(string.IsNullOrWhiteSpace(printer))throw new InvalidOperationException("Configure a impressora padrão no EventMenu Desktop.");var official=await _api.OfficialReceiptAsync(orderId,ct);if(!SiteReceiptPrinter.PrintTo(printer,official.Receipt,official.Presentation))throw new InvalidOperationException("Não foi possível imprimir o comprovante.");return new{printed=true,order_id=orderId,document="receipt"};}
 private object OpenDrawer(){var profile=_hardwareStore.Load();var printer=!string.IsNullOrWhiteSpace(profile.CashDrawer)?profile.CashDrawer:profile.DefaultPrinter;if(string.IsNullOrWhiteSpace(printer))throw new InvalidOperationException("Configure a impressora/gaveta neste computador.");_rawPrinter.OpenCashDrawer(printer);return new{opened=true};}
 private async Task<object> ChargeTefAsync(HubCommand command,CancellationToken ct){if(_terminalCoordinator is null)throw new InvalidOperationException("A maquininha ainda não está disponível neste computador.");var orderId=Int(command.Payload,"order_id");var terminalId=Int(command.Payload,"terminal_config_id");var amount=Int(command.Payload,"amount_cents");var installments=Math.Max(1,Int(command.Payload,"installments",1));var paymentType=Text(command.Payload,"payment_type");if(orderId<1||terminalId<1||amount<=0)throw new InvalidOperationException("Dados da cobrança incompletos.");var terminals=await _hubApi.TerminalListAsync(command.UnitId,ct);var terminal=terminals.Terminals.FirstOrDefault(t=>t.Id==terminalId)??throw new InvalidOperationException("A maquininha não está disponível nesta unidade.");var request=new TerminalPaymentRequest(orderId,amount,paymentType,installments,$"hub-tef:{command.Id}:{orderId}");var flow=await _terminalCoordinator.ChargeAsync(request,terminal,ct);return new{approved_local=flow.ApprovedLocally,verified=flow.VerifiedByServer,status=flow.ServerStatus,message=flow.Message,transaction_code=flow.TransactionCode,authorization_code=flow.AuthorizationCode};}
 private async Task<object> CustomerDisplayAsync(HubCommand command,CancellationToken ct){var orderId=Int(command.Payload,"order_id");if(orderId<1)throw new InvalidOperationException("Pedido inválido.");var details=await _api.OrderDetailsAsync(orderId,ct);var order=details.Order??throw new InvalidOperationException("Pedido não encontrado.");_customerDisplay.ShowOrder(order.Id,order.CustomerName??"",order.TotalCents,order.Status);return new{shown=true,order_id=order.Id};}
 private async Task<object> ReadScaleAsync(CancellationToken ct){var profile=_hardwareStore.Load();if(string.IsNullOrWhiteSpace(profile.Scale))throw new InvalidOperationException("Nenhuma balança está configurada neste computador.");var reading=await _scaleReader.ReadAsync(profile.Scale,ct);return new{weight_grams=reading.WeightGrams,stable=reading.Stable,scale=reading.Device,message=reading.Stable?$"Peso: {reading.WeightGrams/1000m:0.###} kg":$"Peso: {reading.WeightGrams/1000m:0.###} kg (aguarde estabilizar)"};}
 private object PlayAlert(HubCommand command){SystemSounds.Exclamation.Play();var message=Text(command.Payload,"message");if(!string.IsNullOrWhiteSpace(message))_customerDisplay.ShowMessage(message);return new{played=true};}
 private object PrintLabel(HubCommand command){var profile=_hardwareStore.Load();var printer=profile.DefaultPrinter;if(string.IsNullOrWhiteSpace(printer))throw new InvalidOperationException("Configure a impressora de etiquetas.");var text=Text(command.Payload,"text");if(string.IsNullOrWhiteSpace(text))throw new InvalidOperationException("Etiqueta sem conteúdo.");_rawPrinter.PrintText(printer,text,"EventMenu - Etiqueta");return new{printed=true};}
 private static string BuildOrderText(Order order,IReadOnlyCollection<OrderItem> items){var b=new StringBuilder();b.AppendLine("EVENTMENU");b.AppendLine($"PEDIDO #{order.Id}");b.AppendLine(new string('-',32));if(!string.IsNullOrWhiteSpace(order.CustomerName))b.AppendLine($"Cliente: {order.CustomerName}");b.AppendLine($"Canal: {Channel(order.Channel)}");b.AppendLine($"Situação: {OrderStatus(order.Status)}");b.AppendLine(new string('-',32));foreach(var item in items)b.AppendLine($"{item.Quantity:0.##}x {item.Name}\n   {Money(item.TotalCents)}");b.AppendLine(new string('-',32));b.AppendLine($"TOTAL: {Money(order.TotalCents)}");b.AppendLine();b.AppendLine("EventMenu");return b.ToString();}
 private static string Channel(string value)=>value switch{"counter"=>"Balcão","pickup"=>"Retirada","delivery"=>"Entrega","table"=>"Mesa / comanda","bar" or "event_bar"=>"Evento / Bar",_=>"Atendimento"};
 private static string OrderStatus(string value)=>value switch{"draft"=>"Rascunho","pending"=>"Aguardando confirmação","confirmed"=>"Confirmado","preparing"=>"Em preparo","ready"=>"Pronto","served"=>"Servido","out_for_delivery"=>"Saiu para entrega","arrived"=>"Entregador chegou","completed"=>"Concluído","delivered"=>"Entregue","cancelled"=>"Cancelado",_=>"Em andamento"};
 private static string Money(int cents)=>(cents/100m).ToString("C2",PtBr);private static int Int(Dictionary<string,JsonElement> payload,string key,int fallback=0)=>payload.TryGetValue(key,out var v)&&v.ValueKind==JsonValueKind.Number&&v.TryGetInt32(out var n)?n:payload.TryGetValue(key,out v)&&int.TryParse(v.ToString(),out n)?n:fallback;private static string Text(Dictionary<string,JsonElement> payload,string key)=>payload.TryGetValue(key,out var v)?v.ToString():"";private static string Friendly(string message){var lower=message.ToLowerInvariant();return lower.Contains("sqlstate")||lower.Contains("stack trace")||lower.Contains("exception")||lower.Contains("tenant")||lower.Contains("provider")||lower.Contains("webhook")||lower.Contains("payload")?"Não foi possível concluir a operação no computador.":message;}
}
