using System.Windows;using System.Windows.Controls;using System.Windows.Documents;using System.Windows.Media;using EventMenu.Desktop.Models;
namespace EventMenu.Desktop.Services;
public static class SiteReceiptPrinter{
 public static bool Print(OrderReceipt r,ReceiptPresentation p){var dialog=new PrintDialog();if(dialog.ShowDialog()!=true)return false;var paper=p.PaperWidth=="58"?58d:80d;var d=Build(r,Math.Min(dialog.PrintableAreaWidth,Mm(paper)),p);d.PageHeight=dialog.PrintableAreaHeight;dialog.PrintDocument(((IDocumentPaginatorSource)d).DocumentPaginator,$"EventMenu - Cupom {r.OrderId}");return true;}
 private static FlowDocument Build(OrderReceipt r,double width,ReceiptPresentation p){var d=new FlowDocument{PageWidth=width,PagePadding=new Thickness(Mm(2.5)),ColumnGap=0,FontFamily=new FontFamily("Arial"),FontSize=10.5,Foreground=Brushes.Black};var s=p.Sections;
 if(s.Business){var trade=Has(r.Identity.TradeName)?r.Identity.TradeName:r.TenantName;Center(d,Has(trade)?trade:"EventMenu",14,FontWeights.Bold);if(Has(r.Identity.LegalName)&&!string.Equals(r.Identity.LegalName,trade,StringComparison.OrdinalIgnoreCase))Center(d,r.Identity.LegalName,10);if(Has(r.Identity.Document))Center(d,$"CPF/CNPJ: {r.Identity.Document}",10);if(Has(r.Identity.Address))Center(d,r.Identity.Address,9.5);if(Has(r.Identity.Phone))Center(d,$"Tel/WhatsApp: {r.Identity.Phone}",9.5);if(Has(r.Identity.Email))Center(d,r.Identity.Email,9.5);}
 Divider(d);Center(d,p.Title,10.5,FontWeights.Bold);Center(d,$"{p.Subtitle} · {r.ReceiptNumber}",8.5);Divider(d);Pair(d,"Pedido",$"#{r.OrderId}",true);Pair(d,"Data/hora",r.CreatedDisplay);Pair(d,"Canal",Channel(r.Channel));if(s.Customer&&Has(r.CustomerName))Pair(d,"Cliente",r.CustomerName);if(s.Customer&&s.CustomerPhone&&Has(r.CustomerPhone))Pair(d,"Telefone",r.CustomerPhone);if(Has(r.TableName))Pair(d,"Mesa",r.TableName);if(Has(r.TabLabel))Pair(d,"Comanda",r.TabLabel);if(s.Operator&&Has(r.CreatedByName))Pair(d,"Operador",r.CreatedByName);
 if(s.Items){Divider(d);Line(d,"ITENS",FontWeights.Bold);foreach(var i in r.Items){Pair(d,$"{i.Quantity}x {i.Name}",i.TotalDisplay,true);Line(d,$"{i.UnitPriceDisplay} un.",null,8.5);if(Has(i.Notes))Line(d,$"Obs.: {i.Notes}",null,8.5);}Divider(d);Pair(d,"Subtotal",r.SubtotalDisplay);if(r.DiscountCents>0)Pair(d,"Desconto",$"- {r.DiscountDisplay}");if(r.DeliveryFeeCents>0)Pair(d,"Entrega",r.DeliveryFeeDisplay);Pair(d,"TOTAL",r.TotalDisplay,true,13.5);}
 if(s.Payments){Divider(d);Line(d,"PAGAMENTO",FontWeights.Bold);if(r.Payments.Count==0)Line(d,$"Pagamento: {r.PaymentStatus}");else foreach(var pay in r.Payments)Pair(d,$"{pay.MethodDisplay} · {pay.StatusDisplay}",pay.AmountDisplay);}
 if(p.Qr.Enabled&&Has(p.Qr.Payload)){Divider(d);Center(d,p.Qr.Label,10.5,FontWeights.Bold);var img=new Image{Source=QrCodeRenderer.Create(p.Qr.Payload!,p.PaperWidth=="58"?5:6),Width=Mm(34),Height=Mm(34),Stretch=Stretch.Uniform};d.Blocks.Add(new BlockUIContainer(img){TextAlignment=TextAlignment.Center,Margin=new Thickness(0,Mm(2),0,Mm(1))});if(Has(p.Qr.Help))Center(d,p.Qr.Help,8.5);}
 if(p.Advertisement.Enabled&&(Has(p.Advertisement.Headline)||Has(p.Advertisement.Body)||Has(p.Advertisement.TargetUrl))){Divider(d);Center(d,p.Advertisement.Label,7.5,FontWeights.Bold);if(Has(p.Advertisement.Headline))Center(d,p.Advertisement.Headline,10.5,FontWeights.Bold);if(Has(p.Advertisement.Body))Center(d,p.Advertisement.Body,9);if(Has(p.Advertisement.TargetUrl)){var adQr=new Image{Source=QrCodeRenderer.Create(p.Advertisement.TargetUrl,4),Width=Mm(24),Height=Mm(24),Stretch=Stretch.Uniform};d.Blocks.Add(new BlockUIContainer(adQr){TextAlignment=TextAlignment.Center,Margin=new Thickness(0,Mm(1),0,0)});}}
 d.Blocks.Add(new Paragraph(new Run(Has(p.Footer)?p.Footer:"Obrigado pela preferência!")){TextAlignment=TextAlignment.Center,FontSize=9,Margin=new Thickness(0,10,0,3)});Center(d,"Este comprovante não substitui NFC-e, NF-e ou documento fiscal legal quando exigido.",7.5);Center(d,$"Impresso em {DateTime.Now:dd/MM/yyyy HH:mm:ss} · EventMenu",7.5);return d;}
 private static void Divider(FlowDocument d)=>d.Blocks.Add(new Paragraph(new Run(new string('-',42))){Margin=new Thickness(0,5,0,5),FontSize=8});private static void Line(FlowDocument d,string t,FontWeight? w=null,double z=10.5){var p=new Paragraph(new Run(t)){Margin=new Thickness(0,1,0,1),FontSize=z};if(w.HasValue)p.FontWeight=w.Value;d.Blocks.Add(p);}private static void Center(FlowDocument d,string t,double z,FontWeight? w=null){var p=new Paragraph(new Run(t)){Margin=new Thickness(0,1,0,1),FontSize=z,TextAlignment=TextAlignment.Center};if(w.HasValue)p.FontWeight=w.Value;d.Blocks.Add(p);}private static void Pair(FlowDocument d,string l,string r,bool b=false,double z=10.5){var t=new Table{CellSpacing=0,Margin=new Thickness(0,1,0,1),FontSize=z};t.Columns.Add(new TableColumn{Width=new GridLength(1,GridUnitType.Star)});t.Columns.Add(new TableColumn{Width=GridLength.Auto});var row=new TableRow();var lp=new Paragraph(new Run(l)){Margin=new Thickness(0)};var rp=new Paragraph(new Run(r)){Margin=new Thickness(6,0,0,0),TextAlignment=TextAlignment.Right};if(b){lp.FontWeight=FontWeights.Bold;rp.FontWeight=FontWeights.Bold;}row.Cells.Add(new TableCell(lp));row.Cells.Add(new TableCell(rp));var g=new TableRowGroup();g.Rows.Add(row);t.RowGroups.Add(g);d.Blocks.Add(t);}private static string Channel(string v)=>v switch{"counter"=>"Balcão / PDV","pickup"=>"Retirada","delivery"=>"Delivery","table"=>"Mesa / comanda","event"=>"Evento / Ingresso","bar" or "event_bar"=>"Evento / Bar",_=>v};private static double Mm(double v)=>v*96d/25.4d;private static bool Has(string? v)=>!string.IsNullOrWhiteSpace(v);
}
