package br.com.eventmenu.go.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import br.com.eventmenu.go.EventMenuGoApplication
import br.com.eventmenu.go.OrderOperationsViewModel
import br.com.eventmenu.go.data.*

@Composable fun DispatchScreen(orders:List<Order>,deliveryUsers:List<DeliveryUser>,canAssignDelivery:Boolean,focusOrderId:Int?,unassignedUnitOrders:List<UnassignedUnitDelivery> = emptyList(),units:List<OperatingUnit> = emptyList(),canRouteUnit:Boolean=false,onRefresh:()->Unit,onDispatch:(Order)->Unit,onAssignDelivery:(Int,Int)->Unit,onScanDelivery:(Int)->Unit,onAssignUnit:(Int,Int)->Unit={_,_->}){
 val app=LocalContext.current.applicationContext as EventMenuGoApplication;val vm:OrderOperationsViewModel=viewModel(factory=OrderOperationsViewModel.Factory(app.orderOperationsRepository));val state by vm.state.collectAsState()
 val pending=orders.filter{it.status=="pending"&&it.channel in setOf("counter","pickup","table","delivery")}.sortedBy{it.id};val ready=orders.filter{it.status=="ready"&&it.channel in setOf("counter","pickup","table","delivery")}.sortedWith(compareByDescending<Order>{focusOrderId!=null&&it.id==focusOrderId}.thenBy{it.id})
 var assigning by remember{mutableStateOf<Order?>(null)};var routing by remember{mutableStateOf<UnassignedUnitDelivery?>(null)}
 LaunchedEffect(state.changedVersion){if(state.changedVersion>0)onRefresh()}
 LazyColumn(Modifier.fillMaxSize().padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
  item{Text("Saída de pedidos",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);Text("Veja rapidamente o que está liberado e o que ainda exige ação.",color=MaterialTheme.colorScheme.onSurfaceVariant);state.error?.let{PersistentNotice("Não foi possível concluir a ação",friendlyDispatchError(it),true){vm.clearFeedback()}};state.message?.let{PersistentNotice("Ação concluída",it,false){vm.clearFeedback()}}}
  if(canRouteUnit&&unassignedUnitOrders.isNotEmpty()){item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Pedidos aguardando unidade",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text("${unassignedUnitOrders.size} pedido(s) precisam ser encaminhados.")}}};items(unassignedUnitOrders,key={"unit-${it.id}"}){o->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){OrderHead(o.id,o.totalCents);useful(o.customerName)?.let{Text(it,fontWeight=FontWeight.SemiBold)};useful(o.deliveryAddress)?.let{Text(it)};DispatchPaymentPill(o.paymentStatus);Button({routing=o},enabled=units.isNotEmpty(),modifier=Modifier.fillMaxWidth()){Text(if(units.isEmpty())"Nenhuma unidade disponível" else "Escolher unidade")}}}}}
  if(pending.isNotEmpty()){item{Text("Novos pedidos",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black)};items(pending,key={"pending-${it.id}"}){o->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){OrderHead(o.id,o.totalCents);Text(dispatchChannel(o),color=MaterialTheme.colorScheme.onSurfaceVariant);DispatchStatePill("AGUARDANDO ACEITE",false);DispatchPaymentPill(o.paymentStatus);OutlinedButton({vm.open(o.id)},Modifier.fillMaxWidth()){Text("Ver pedido")};Button({vm.accept(o.id)},enabled=!state.loading,modifier=Modifier.fillMaxWidth()){Text("Aceitar pedido")}}}}}
  if(ready.isNotEmpty())item{Text("Prontos para sair",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black)}
  items(ready,key={it.id}){o->val focused=focusOrderId==o.id;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){if(focused)Text("Pedido localizado pelo QR",color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Bold);OrderHead(o.id,o.totalCents);Text(dispatchChannel(o),color=MaterialTheme.colorScheme.onSurfaceVariant);useful(o.customerName)?.takeIf{!it.equals("Consumidor",true)}?.let{Text(it,fontWeight=FontWeight.SemiBold)};val blocked=o.channel in setOf("counter","pickup")&&o.paymentStatus!="paid";DispatchStatePill(if(blocked)"AGUARDANDO PAGAMENTO" else if(o.channel=="delivery"&&useful(o.deliveryName)==null)"AGUARDANDO ENTREGADOR" else "LIBERADO PARA SAÍDA",!blocked);DispatchPaymentPill(o.paymentStatus);OutlinedButton({vm.open(o.id)},Modifier.fillMaxWidth()){Text("Ver pedido")};when(o.channel){"table"->Button({onDispatch(o)},Modifier.fillMaxWidth()){Text("Marcar como servido")};"counter","pickup"->{Button({onDispatch(o)},enabled=!blocked,modifier=Modifier.fillMaxWidth()){Text(if(blocked)"Aguardando pagamento" else "Entregar ao cliente")};if(blocked)Text("Receba o pedido antes de liberar a retirada.",color=MaterialTheme.colorScheme.error,fontWeight=FontWeight.SemiBold)};"delivery"->{if(useful(o.deliveryName)!=null){Text("Entregador: ${useful(o.deliveryName)}",fontWeight=FontWeight.Bold);if(canAssignDelivery)OutlinedButton({assigning=o},Modifier.fillMaxWidth()){Text("Trocar entregador")}}else if(canAssignDelivery)Button({assigning=o},Modifier.fillMaxWidth()){Text("Escolher entregador")}else Text("Aguardando atribuição de entregador.",color=MaterialTheme.colorScheme.error,fontWeight=FontWeight.SemiBold)}}}}}
  if(ready.isEmpty()&&pending.isEmpty()&&unassignedUnitOrders.isEmpty())item{Text("Nenhum pedido aguardando ação.")};item{OutlinedButton(onRefresh,Modifier.fillMaxWidth()){Text("Atualizar")}}
 }
 state.detail?.let{OrderDetailDialog(it,it.status=="pending",vm::accept,vm::close)}
 routing?.let{o->AlertDialog(onDismissRequest={routing=null},title={Text("Escolher unidade · Pedido #${o.id}")},text={Column{units.forEach{u->OutlinedButton({routing=null;onAssignUnit(o.id,u.id)},Modifier.fillMaxWidth()){Text(u.name)}}}},confirmButton={},dismissButton={TextButton({routing=null}){Text("Fechar")}})}
 assigning?.let{o->val available=deliveryUsers.filter{it.onShift};AlertDialog(onDismissRequest={assigning=null},title={Text("Entregador · Pedido #${o.id}")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Button({assigning=null;onScanDelivery(o.id)},Modifier.fillMaxWidth()){Text("Ler QR do entregador")};available.forEach{u->OutlinedButton({assigning=null;onAssignDelivery(o.id,u.id)},Modifier.fillMaxWidth()){Text(u.name)}};if(available.isEmpty())Text("Nenhum entregador disponível agora.")}},confirmButton={},dismissButton={TextButton({assigning=null}){Text("Fechar")}})}
}
@Composable private fun PersistentNotice(title:String,text:String,error:Boolean,onDismiss:()->Unit){Card(colors=CardDefaults.cardColors(containerColor=if(error)MaterialTheme.colorScheme.errorContainer else MaterialTheme.colorScheme.primaryContainer),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(if(error)"⚠ $title" else "✓ $title",fontWeight=FontWeight.Black);Text(text);TextButton(onDismiss){Text("Entendi")}}}}
@Composable private fun OrderHead(id:Int,total:Int){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text("Pedido #$id",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(dispatchMoney(total),fontWeight=FontWeight.Black)}}
@Composable private fun DispatchStatePill(label:String,ok:Boolean){Surface(color=if(ok)MaterialTheme.colorScheme.tertiaryContainer else MaterialTheme.colorScheme.errorContainer,shape=MaterialTheme.shapes.small){Text(label,Modifier.padding(horizontal=10.dp,vertical=7.dp),fontWeight=FontWeight.Black,color=if(ok)MaterialTheme.colorScheme.onTertiaryContainer else MaterialTheme.colorScheme.onErrorContainer)}}
@Composable private fun DispatchPaymentPill(status:String){val paid=status=="paid";Surface(color=if(paid)MaterialTheme.colorScheme.secondaryContainer else MaterialTheme.colorScheme.surfaceVariant,shape=MaterialTheme.shapes.small){Text(if(paid)"Pago" else if(status=="pending")"Pagamento em processamento" else "A receber",Modifier.padding(horizontal=10.dp,vertical=6.dp),fontWeight=FontWeight.SemiBold)}}
private fun friendlyDispatchError(v:String):String{val s=v.trim();return when{ s.contains("Ainda há itens não entregues",true)->s.replace("Ainda há itens não entregues. Use Retirada / QR:","Este pedido ainda não pode ser entregue. Falta retirar:",true)+". Faça a retirada/QR e tente novamente.";s.isBlank()->"Tente novamente. Se continuar, atualize os pedidos.";else->s}}
private fun dispatchChannel(o:Order)=when(o.channel){"counter"->"Balcão";"pickup"->"Retirada";"table"->"Mesa";"delivery"->"Delivery";else->"Pedido"}
private fun useful(v:String?):String?=v?.trim()?.takeIf{it.isNotBlank()&&!it.equals("null",true)&&!it.equals("undefined",true)}
private fun dispatchMoney(c:Int)="R$ %.2f".format(c/100.0).replace('.',',')
