package br.com.eventmenu.go.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import br.com.eventmenu.go.EventBarState
import kotlinx.coroutines.delay

@Composable
fun EventBarScreen(state:EventBarState,cashOpen:Boolean,canCash:Boolean,canPix:Boolean,canNfc:Boolean,onAdd:(Int)->Unit,onRemove:(Int)->Unit,onClearCart:()->Unit,onCreate:(String)->Unit,onCash:(Int)->Unit,onPix:(Int,String)->Unit,onNfc:(Int)->Unit,onRefreshPayment:()->Unit,onPollPix:()->Unit,onDismissPix:()->Unit,onReceipt:(Int)->Unit,onPrint:(Int)->Unit,onFinish:()->Unit,onExit:()->Unit){
 val order=state.order
 if(order!=null){EventBarPayment(state,cashOpen,canCash,canPix,canNfc,onCash,onPix,onNfc,onRefreshPayment,onReceipt,onPrint,onFinish);state.pixCharge?.let{EventBarPixDialog(it.copyPaste,it.amountCents,it.expiresAt,onPollPix,onDismissPix)};return}
 var category by remember{mutableStateOf("Todos")};var notes by remember{mutableStateOf("")};var search by remember{mutableStateOf("")}
 val categories=listOf("Todos")+state.products.map{it.categoryName}.filter{it.isNotBlank()}.distinct()
 val visible=state.products.filter{(category=="Todos"||it.categoryName==category)&&(search.isBlank()||it.name.contains(search,true)||it.description.contains(search,true))}
 val lines=state.cart.mapNotNull{(id,qty)->state.products.firstOrNull{it.id==id}?.let{it to qty}};val total=lines.sumOf{(p,q)->p.priceCents*q};val count=lines.sumOf{it.second}
 LazyColumn(Modifier.fillMaxSize().padding(14.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Text("Bar · ${state.eventName}",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);Text("PDV rápido do evento",color=MaterialTheme.colorScheme.onSurfaceVariant);OutlinedButton(onExit,Modifier.fillMaxWidth().padding(top=8.dp)){Text("Voltar ao evento")}}
  state.error?.let{item{Surface(color=MaterialTheme.colorScheme.errorContainer,shape=MaterialTheme.shapes.medium){Text(it,Modifier.padding(12.dp),color=MaterialTheme.colorScheme.onErrorContainer)}}}
  state.message?.let{item{Surface(color=MaterialTheme.colorScheme.secondaryContainer,shape=MaterialTheme.shapes.medium){Text(it,Modifier.padding(12.dp),color=MaterialTheme.colorScheme.onSecondaryContainer)}}}
  item{OutlinedTextField(search,{search=it},label={Text("Buscar produto")},placeholder={Text("Ex.: cerveja, água, lanche")},singleLine=true,modifier=Modifier.fillMaxWidth())}
  item{LazyRow(horizontalArrangement=Arrangement.spacedBy(7.dp)){items(categories){name->FilterChip(category==name,{category=name},{Text(name)})}}}
  if(visible.isEmpty())item{Text("Nenhum produto encontrado.",color=MaterialTheme.colorScheme.onSurfaceVariant)}
  items(visible,key={it.id}){p->val q=state.cart[p.id]?:0;Card(Modifier.fillMaxWidth()){Column(Modifier.padding(15.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(p.name,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);if(p.categoryName.isNotBlank())Text(p.categoryName,color=MaterialTheme.colorScheme.onSurfaceVariant);if(p.description.isNotBlank())Text(p.description,maxLines=2);Text(barMoney(p.priceCents),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);if(p.trackStock)Text("Estoque: ${p.stockQty}",color=MaterialTheme.colorScheme.onSurfaceVariant)};Button({onAdd(p.id)},enabled=!p.trackStock||p.stockQty>q){Text(if(q==0)"Adicionar" else "+")}};if(q>0){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("No carrinho: $q",fontWeight=FontWeight.SemiBold);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedButton({onRemove(p.id)}){Text("−")};Button({onAdd(p.id)},enabled=!p.trackStock||p.stockQty>q){Text("+")}}}}}}}
  item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("Carrinho",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text("$count item(ns)",color=MaterialTheme.colorScheme.onSurfaceVariant)};if(lines.isNotEmpty())TextButton(onClearCart){Text("Limpar")}};if(lines.isEmpty())Text("Toque em Adicionar nos produtos acima.",color=MaterialTheme.colorScheme.onSurfaceVariant);lines.forEach{(p,q)->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text("$q× ${p.name}",fontWeight=FontWeight.SemiBold);Text(barMoney(p.priceCents*q),color=MaterialTheme.colorScheme.onSurfaceVariant)};Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){OutlinedButton({onRemove(p.id)}){Text("−")};OutlinedButton({onAdd(p.id)},enabled=!p.trackStock||p.stockQty>q){Text("+")}}}};HorizontalDivider();Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("TOTAL",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(barMoney(total),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)};OutlinedTextField(notes,{notes=it},label={Text("Observação do pedido")},modifier=Modifier.fillMaxWidth());Button({onCreate(notes)},enabled=lines.isNotEmpty()&&!state.loading,modifier=Modifier.fillMaxWidth()){Text(if(state.loading)"Criando venda..." else "RECEBER · ${barMoney(total)}")}}}}
 }
}

@Composable private fun EventBarPayment(state:EventBarState,cashOpen:Boolean,canCash:Boolean,canPix:Boolean,canNfc:Boolean,onCash:(Int)->Unit,onPix:(Int,String)->Unit,onNfc:(Int)->Unit,onRefresh:()->Unit,onReceipt:(Int)->Unit,onPrint:(Int)->Unit,onFinish:()->Unit){
 val order=state.order?:return;val balance=state.balance;val remaining=balance?.remainingCents?:order.totalCents;var amountText by remember(remaining){mutableStateOf("%.2f".format(remaining/100.0).replace('.',','))};val amount=((amountText.replace(',','.').toDoubleOrNull()?:0.0)*100).toInt();var pixDialog by remember{mutableStateOf(false)}
 LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Text("Bar · ${state.eventName}",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);Text("Venda #${order.id}",color=MaterialTheme.colorScheme.onSurfaceVariant);Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Total ${barMoney(balance?.totalCents?:order.totalCents)}",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);if((balance?.paidCents?:0)>0)Text("Recebido ${barMoney(balance?.paidCents?:0)}");Text("Falta ${barMoney(remaining)}",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)}}}
  if(balance?.payments?.isNotEmpty()==true){item{Text("Recebimentos",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};items(balance.payments,key={it.id}){part->Card(Modifier.fillMaxWidth()){Row(Modifier.fillMaxWidth().padding(13.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(barPaymentLabel(part.provider),fontWeight=FontWeight.SemiBold);Text(barPaymentStatus(part.status),color=MaterialTheme.colorScheme.onSurfaceVariant)};Text(barMoney(part.amountCents),fontWeight=FontWeight.Black)}}}}
  if(remaining>0)item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Text("Receber pagamento",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text("Pode receber o total ou dividir em formas diferentes.",color=MaterialTheme.colorScheme.onSurfaceVariant);OutlinedTextField(amountText,{amountText=it},label={Text("Valor (R$)")},singleLine=true,modifier=Modifier.fillMaxWidth());if(canCash){Button({onCash(amount)},enabled=cashOpen&&amount in 1..remaining,modifier=Modifier.fillMaxWidth()){Text("DINHEIRO · ${barMoney(amount)}")};if(!cashOpen)Text("Abra o caixa para receber em dinheiro.",color=MaterialTheme.colorScheme.onSurfaceVariant)};if(canPix)Button({pixDialog=true},enabled=amount in 1..remaining,modifier=Modifier.fillMaxWidth()){Text("PIX · ${barMoney(amount)}")};if(canNfc)Button({onNfc(amount)},enabled=amount in 100..remaining,modifier=Modifier.fillMaxWidth()){Text("CARTÃO / APROXIMAÇÃO · ${barMoney(amount)}")};if(!canCash&&!canPix&&!canNfc)Text("Este acesso não está autorizado a receber pagamentos.")}}}
  else item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Surface(color=MaterialTheme.colorScheme.secondaryContainer,shape=MaterialTheme.shapes.small){Text("✓ PAGAMENTO CONFIRMADO",Modifier.padding(10.dp),color=MaterialTheme.colorScheme.onSecondaryContainer,fontWeight=FontWeight.Bold)};Button({onPrint(order.id)},Modifier.fillMaxWidth()){Text("IMPRIMIR COMANDA / RECIBO")};OutlinedButton({onReceipt(order.id)},Modifier.fillMaxWidth()){Text("Enviar recibo")};Button(onFinish,Modifier.fillMaxWidth()){Text("CONCLUIR E NOVA VENDA")}}}}
  item{OutlinedButton(onRefresh,Modifier.fillMaxWidth()){Text("Atualizar pagamento")}}
 }
 if(pixDialog){var taxId by remember{mutableStateOf("")};AlertDialog(onDismissRequest={pixDialog=false},title={Text("PIX · ${barMoney(amount)}")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Informe CPF ou CNPJ para gerar o PIX.");OutlinedTextField(taxId,{taxId=it.filter(Char::isDigit).take(14)},label={Text("CPF ou CNPJ")},singleLine=true)}},confirmButton={Button({pixDialog=false;onPix(amount,taxId)},enabled=taxId.length in setOf(11,14)){Text("Gerar PIX")}},dismissButton={TextButton({pixDialog=false}){Text("Cancelar")}})}
}

@Composable private fun EventBarPixDialog(copyPaste:String,amountCents:Int,expiresAt:String,onPoll:()->Unit,onDismiss:()->Unit){val context=LocalContext.current;val qr=remember(copyPaste){qrBitmap(copyPaste)};LaunchedEffect(copyPaste){while(true){delay(2500);onPoll()}};AlertDialog(onDismissRequest=onDismiss,title={Text("PIX · ${barMoney(amountCents)}")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){qr?.let{Image(it.asImageBitmap(),"QR PIX",Modifier.fillMaxWidth())};Text("Aguardando pagamento",fontWeight=FontWeight.SemiBold);eventBarUseful(expiresAt)?.let{Text("Válido até ${eventBarFriendlyDateTime(it)}")};OutlinedButton({copyPix(context,copyPaste)},Modifier.fillMaxWidth()){Text("Copiar código PIX")}}},confirmButton={TextButton(onDismiss){Text("Fechar")}})}
private fun copyPix(context:Context,text:String){(context.getSystemService(Context.CLIPBOARD_SERVICE)as ClipboardManager).setPrimaryClip(ClipData.newPlainText("PIX pedido",text))}
private fun barPaymentLabel(provider:String)=when(provider.lowercase()){"manual"->"Dinheiro";"pagbank","stripe","mercadopago"->"Pagamento eletrônico";else->"Pagamento"}
private fun barPaymentStatus(status:String)=when(status.lowercase()){"paid","approved","confirmed"->"Confirmado";"pending","processing"->"Processando";"refunded"->"Estornado";"failed","cancelled"->"Não concluído";else->"Em andamento"}
private fun eventBarUseful(value:String?):String?{val clean=value?.trim().orEmpty();return clean.takeIf{it.isNotBlank()&&!it.equals("null",true)&&!it.equals("undefined",true)}}
private fun eventBarFriendlyDateTime(value:String):String{val clean=value.trim().replace('T',' ');val date=clean.substringBefore(' ');val time=clean.substringAfter(' ',"").take(5);val p=date.split('-');val d=if(p.size==3)"${p[2]}/${p[1]}" else date;return if(time.isNotBlank())"$d às $time" else d}
private fun barMoney(cents:Int)="R$ %.2f".format(cents/100.0).replace('.',',')
