package br.com.eventmenu.go.ui.screens
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import br.com.eventmenu.go.HubState
import br.com.eventmenu.go.data.HubLink
@Composable fun HubDialog(state:HubState,canTerminalRequest:Boolean,canOpenDrawer:Boolean,onDismiss:()->Unit,onRefresh:()->Unit,onSelectLink:(Int)->Unit,onSelectTerminal:(Int)->Unit,onLoadTerminals:()->Unit,onPairCode:(String,String)->Unit,onScanPairing:()->Unit,onPrintOrder:(Int)->Unit,onPrintReceipt:(Int)->Unit,onOpenDrawer:(String)->Unit,onShowCustomer:(Int)->Unit,onChargeTef:(Int,Int,String,Int)->Unit,onAlert:(String)->Unit,onReadScale:()->Unit,onRevoke:()->Unit){var pairing by remember{mutableStateOf("")};var order by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};var type by remember{mutableStateOf("debit")};var installments by remember{mutableStateOf("1")};var alert by remember{mutableStateOf("")};LaunchedEffect(Unit){onRefresh()};LaunchedEffect(state.selectedLinkId,canTerminalRequest){if(canTerminalRequest&&state.selected!=null)onLoadTerminals()}
 Dialog(onDismissRequest=onDismiss,properties=DialogProperties(usePlatformDefaultWidth=false)){Surface(Modifier.fillMaxSize().padding(12.dp),shape=MaterialTheme.shapes.extraLarge,tonalElevation=3.dp){Column(Modifier.fillMaxSize().padding(18.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text("Conectar ao computador",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.SemiBold);Text("Use equipamentos do EventMenu Desktop pela internet, sem depender do mesmo Wi-Fi.",color=MaterialTheme.colorScheme.onSurfaceVariant)};TextButton(onClick=onDismiss){Text("Fechar")}};Spacer(Modifier.height(12.dp));LazyColumn(Modifier.fillMaxHeight(),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Title("Computadores vinculados");if(state.links.isEmpty()&&!state.loading)Text("Nenhum computador vinculado.",color=MaterialTheme.colorScheme.onSurfaceVariant)};items(state.links,key={it.id}){link->Computer(link,state.selected?.id==link.id){onSelectLink(link.id)}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick=onRefresh,enabled=!state.loading){Text("Atualizar")};Button(onClick=onScanPairing,enabled=!state.loading){Text("Ler QR do computador")}}};item{OutlinedTextField(pairing,{pairing=it},Modifier.fillMaxWidth(),label={Text("Código de pareamento")},supportingText={Text("O código expira e só funciona para a empresa/unidade autorizada.")},singleLine=true);Button(onClick={onPairCode(pairing,"Celular EventMenu GO")},enabled=pairing.isNotBlank()&&!state.loading){Text("Vincular")}}
 if(state.selected!=null){item{HorizontalDivider();Title("Recursos do computador")};item{OutlinedTextField(order,{order=it.filter(Char::isDigit)},Modifier.fillMaxWidth(),label={Text("Número do pedido")},singleLine=true)};item{val id=order.toIntOrNull()?:0;Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({onPrintOrder(id)},enabled=id>0&&state.selected?.online==true&&state.selected?.hardware?.defaultPrinter?.isNotBlank()==true){Text("Imprimir pedido")};OutlinedButton({onPrintReceipt(id)},enabled=id>0&&state.selected?.online==true&&state.selected?.hardware?.defaultPrinter?.isNotBlank()==true){Text("Imprimir recibo")}};OutlinedButton({onShowCustomer(id)},enabled=id>0&&state.selected?.online==true&&state.selected?.hardware?.customerDisplay?.isNotBlank()==true){Text("Mostrar no display do cliente")};if(state.selected?.hardware?.scale?.isNotBlank()==true)OutlinedButton(onClick=onReadScale,enabled=state.selected?.online==true&&!state.loading){Text("Ler peso da balança")}}}
 if(canTerminalRequest){item{Title("Cobrar no PINPad")};if(state.terminals.isEmpty())item{Text("Nenhum PINPad ativo nesta unidade.",color=MaterialTheme.colorScheme.onSurfaceVariant)}else items(state.terminals,key={"t-${it.id}"}){t->FilterChip(state.selectedTerminal?.id==t.id,{onSelectTerminal(t.id)},{Text(if(t.pinpad.isBlank())t.label else "${t.label} • ${t.pinpad}")})};item{OutlinedTextField(amount,{amount=it.take(12)},Modifier.fillMaxWidth(),label={Text("Valor")},prefix={Text("R$ ")},singleLine=true);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(type=="debit",{type="debit"},{Text("Débito")});FilterChip(type=="credit",{type="credit"},{Text("Crédito")});FilterChip(type=="pix",{type="pix"},{Text("Pix")})};if(type=="credit")OutlinedTextField(installments,{installments=it.filter(Char::isDigit).take(2)},label={Text("Parcelas")},singleLine=true);val id=order.toIntOrNull()?:0;val cents=money(amount);Button({onChargeTef(id,cents,type,installments.toIntOrNull()?.coerceIn(1,24)?:1)},enabled=id>0&&cents>0&&state.selectedTerminal!=null&&state.selected?.online==true&&!state.loading){Text("Enviar cobrança ao PINPad")};Text("A confirmação do pagamento continua sendo feita pelo servidor/provedor.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
 if(canOpenDrawer)item{OutlinedButton({onOpenDrawer("Abertura solicitada pelo celular")},enabled=state.selected?.online==true&&state.selected?.hardware?.cashDrawer?.isNotBlank()==true&&!state.loading){Text("Abrir gaveta")}};item{Title("Aviso no computador");OutlinedTextField(alert,{alert=it.take(300)},Modifier.fillMaxWidth(),label={Text("Mensagem")});OutlinedButton({onAlert(alert)},enabled=alert.isNotBlank()&&state.selected?.online==true){Text("Enviar alerta")}};item{TextButton(onClick=onRevoke,enabled=!state.loading){Text("Desvincular este celular")}}}
 state.message?.let{m->item{Text(m,color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Medium)}};state.error?.let{e->item{Text(e,color=MaterialTheme.colorScheme.error,fontWeight=FontWeight.Medium)}};if(state.loading)item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.Center){CircularProgressIndicator()}};item{Spacer(Modifier.height(24.dp))}}}}}}
@Composable private fun Computer(link:HubLink,selected:Boolean,onSelect:()->Unit){Card(onClick=onSelect,modifier=Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=if(selected)MaterialTheme.colorScheme.secondaryContainer else MaterialTheme.colorScheme.surfaceVariant)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(link.desktopLabel,fontWeight=FontWeight.SemiBold);Text(if(link.online)"● Online" else "○ Offline",color=if(link.online)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant)};if(link.unitName.isNotBlank())Text(link.unitName,color=MaterialTheme.colorScheme.onSurfaceVariant);val p=buildList{if(link.hardware.defaultPrinter.isNotBlank())add("Impressora");if(link.hardware.cashDrawer.isNotBlank())add("Gaveta");if(link.hardware.pinpad.isNotBlank()||link.hardware.tefProvider.isNotBlank())add("PINPad");if(link.hardware.scale.isNotBlank())add("Balança");if(link.hardware.barcodeScanner.isNotBlank())add("Leitor");if(link.hardware.customerDisplay.isNotBlank())add("Display")};Text(if(p.isEmpty())"Equipamentos ainda não configurados" else p.joinToString(" • "),style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun Title(s:String){Text(s,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold,modifier=Modifier.padding(top=4.dp,bottom=4.dp))}
private fun money(raw:String):Int{val c=raw.trim().replace("R$","").replace(" ","");if(c.isBlank())return 0;val n=if(c.contains(','))c.replace(".","").replace(',','.')else c;return runCatching{n.toBigDecimal().multiply(100.toBigDecimal()).toInt()}.getOrDefault(0).coerceAtLeast(0)}
