package br.com.eventmenu.go.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import br.com.eventmenu.go.AppScreen
import br.com.eventmenu.go.EventMenuGoApplication
import br.com.eventmenu.go.GoState
import br.com.eventmenu.go.data.CustomerIdentity
import br.com.eventmenu.go.data.DiscountRequest
import br.com.eventmenu.go.data.LoyaltyOrderSummary
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@Composable
fun PosScreen(state:GoState,discountRequest:DiscountRequest?,canRequestDiscount:Boolean,onRequestDiscount:(Int,Int,String)->Unit,onRefreshDiscount:(Int)->Unit,onAdd:(Int)->Unit,onRemove:(Int)->Unit,onClear:()->Unit,onCreate:(String,String,String,String,String)->Unit,onCash:(Int)->Unit,onPix:(Int,String)->Unit,onNfc:(Int)->Unit,onReceipt:(Int)->Unit,onPrintReceipt:(Int)->Unit,onRefreshPayment:()->Unit,onFinishFlow:()->Unit,onClearTable:()->Unit){
 val order=state.posOrder;if(order!=null){PosPaymentScreen(state,discountRequest,canRequestDiscount,onRequestDiscount,onRefreshDiscount,onCash,onPix,onNfc,onReceipt,onPrintReceipt,onRefreshPayment,onFinishFlow);return}
 val table=state.selectedTable;var category by remember{mutableStateOf("Todos")};var channel by remember(table?.id){mutableStateOf(if(table!=null)"table" else "counter")};var customer by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var address by remember{mutableStateOf("")};var notes by remember{mutableStateOf("")};var identity by remember{mutableStateOf<CustomerIdentity?>(null)};var lookupBusy by remember{mutableStateOf(false)};var customerMessage by remember{mutableStateOf<String?>(null)};var lookupJob by remember{mutableStateOf<Job?>(null)};val context=LocalContext.current;val app=context.applicationContext as EventMenuGoApplication;val scope=rememberCoroutineScope();val categories=listOf("Todos")+state.products.map{it.categoryName}.distinct();val visible=state.products.filter{category=="Todos"||it.categoryName==category};val cartLines=state.cart.mapNotNull{(id,qty)->state.products.firstOrNull{it.id==id}?.let{it to qty}};val previewTotal=cartLines.sumOf{(p,q)->p.priceCents*q}
 fun lookupPhone(raw:String){phone=raw;identity=null;customerMessage=null;lookupJob?.cancel();val digits=raw.filter(Char::isDigit);if(digits.length<8){lookupBusy=false;return};lookupJob=scope.launch{delay(450);lookupBusy=true;try{val found=app.customerIdentityRepository.lookup(digits);identity=found;if(found!=null){customer=found.name;if(found.phone.isNotBlank())phone=found.phone;if(found.address.isNotBlank())address=found.address;customerMessage="Cliente reconhecido${if(found.points>0)" · ${found.points} pontos" else ""}."}else customerMessage="Cliente novo. Será cadastrado ao finalizar."}catch(e:Exception){customerMessage=e.message?.takeIf{it.isNotBlank()}?:"Não foi possível consultar o cadastro agora."}finally{lookupBusy=false}}}
 fun finish(){scope.launch{val digits=phone.filter(Char::isDigit);if(digits.length>=8&&customer.isNotBlank()){try{identity=app.customerIdentityRepository.save(identity?.id,customer,digits,address)}catch(e:Exception){customerMessage="Pedido será criado, mas o cadastro do cliente não pôde ser atualizado."}};onCreate(channel,customer,phone,address,notes)}}
 LazyColumn(Modifier.fillMaxSize().padding(14.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Text(if(table!=null)"Venda · ${table.name}" else "Nova venda",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);if(table!=null){table.tabLabel.takeIf{it.isNotBlank()}?.let{Text(it,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text("Os itens serão adicionados à conta da mesa.",color=MaterialTheme.colorScheme.onSurfaceVariant);OutlinedButton(onClick=onClearTable,modifier=Modifier.fillMaxWidth().padding(top=8.dp)){Text("Voltar às mesas")}}else Text("Escolha os produtos e finalize o pedido.",color=MaterialTheme.colorScheme.onSurfaceVariant)}
  item{LazyRow(horizontalArrangement=Arrangement.spacedBy(7.dp)){items(categories){name->FilterChip(selected=category==name,onClick={category=name},label={Text(name)})}}}
  items(visible,key={it.id}){product->Card(Modifier.fillMaxWidth()){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(product.name,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text(product.categoryName,color=MaterialTheme.colorScheme.onSurfaceVariant);if(product.description.isNotBlank())Text(product.description,maxLines=2);Text(posMoney(product.priceCents),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);if(product.trackStock)Text("Disponível: ${product.stockQty}",color=MaterialTheme.colorScheme.onSurfaceVariant)};Button(onClick={onAdd(product.id)},enabled=!product.trackStock||product.stockQty>0){Text("+")}}}}
  item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Carrinho",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);if(cartLines.isNotEmpty())TextButton(onClick=onClear){Text("Limpar")}};if(cartLines.isEmpty())Text("Nenhum item.",color=MaterialTheme.colorScheme.onSurfaceVariant);cartLines.forEach{(p,q)->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("${q}× ${p.name}");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Text(posMoney(p.priceCents*q),fontWeight=FontWeight.Bold);OutlinedButton(onClick={onRemove(p.id)}){Text("−")};OutlinedButton(onClick={onAdd(p.id)}){Text("+")}}}};HorizontalDivider();Text("Total ${posMoney(previewTotal)}",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)}}}
  item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){if(table==null){Text("Tipo do pedido",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(channel=="counter",{channel="counter"},{Text("Balcão")});FilterChip(channel=="pickup",{channel="pickup"},{Text("Retirada")});FilterChip(channel=="delivery",{channel="delivery"},{Text("Delivery")})}}else Text("Pedido para ${table.name}",fontWeight=FontWeight.Bold);Text("Cliente",fontWeight=FontWeight.Bold);OutlinedTextField(phone,{lookupPhone(it)},label={Text(if(channel=="delivery")"Telefone" else "Telefone (opcional)")},singleLine=true,modifier=Modifier.fillMaxWidth(),trailingIcon={if(lookupBusy)CircularProgressIndicator(Modifier.size(20.dp),strokeWidth=2.dp)});customerMessage?.let{Text(it,color=if(identity!=null)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant)};OutlinedTextField(customer,{customer=it},label={Text(if(channel=="delivery")"Nome" else "Nome (opcional)")},modifier=Modifier.fillMaxWidth());if(channel=="delivery")OutlinedTextField(address,{address=it},label={Text("Endereço")},modifier=Modifier.fillMaxWidth());OutlinedTextField(notes,{notes=it},label={Text("Observações")},modifier=Modifier.fillMaxWidth());Button(onClick={finish()},enabled=cartLines.isNotEmpty()&&!lookupBusy&&(channel!="delivery"||(customer.isNotBlank()&&phone.filter(Char::isDigit).length>=8&&address.isNotBlank())),modifier=Modifier.fillMaxWidth()){Text(if(table!=null)"Adicionar à mesa" else "Finalizar pedido")}}}}
 }
}

@Composable
private fun PosPaymentScreen(state:GoState,discountRequest:DiscountRequest?,canRequestDiscount:Boolean,onRequestDiscount:(Int,Int,String)->Unit,onRefreshDiscount:(Int)->Unit,onCash:(Int)->Unit,onPix:(Int,String)->Unit,onNfc:(Int)->Unit,onReceipt:(Int)->Unit,onPrintReceipt:(Int)->Unit,onRefresh:()->Unit,onFinishFlow:()->Unit){
 val order=state.posOrder?:return;val balance=state.paymentBalance;val remaining=balance?.remainingCents?:order.totalCents;var amountText by remember(remaining){mutableStateOf("%.2f".format(remaining/100.0).replace('.',','))};val amount=((amountText.replace(',','.').toDoubleOrNull()?:0.0)*100).toInt();var pixTaxDialog by remember{mutableStateOf(false)};var pixConfigError by remember{mutableStateOf<String?>(null)};var discountDialog by remember{mutableStateOf(false)};val context=LocalContext.current;val app=context.applicationContext as EventMenuGoApplication;val scope=rememberCoroutineScope();val canRedeemLoyalty="loyalty_redeem" in state.session?.permissions.orEmpty();var loyalty by remember(order.id){mutableStateOf<LoyaltyOrderSummary?>(null)};var loyaltyLoaded by remember(order.id){mutableStateOf(false)};var loyaltyError by remember(order.id){mutableStateOf<String?>(null)}
 LaunchedEffect(order.id,canRedeemLoyalty){if(canRedeemLoyalty)try{loyalty=app.orderOperationsRepository.detail(order.id).loyalty;loyaltyLoaded=true}catch(e:Exception){loyaltyError=e.message?:"Não foi possível consultar os pontos.";loyaltyLoaded=true}}
 LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{Text("Receber · Pedido #${order.id}",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Black);if(state.posReturnScreen==AppScreen.TABLE_ACCOUNT)Text("Pagamento da conta da mesa.",color=MaterialTheme.colorScheme.onSurfaceVariant);Text("Total: ${posMoney(balance?.totalCents?:order.totalCents)}");if((balance?.paidCents?:0)>0)Text("Recebido: ${posMoney(balance?.paidCents?:0)}");Text("Falta receber: ${posMoney(remaining)}",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)}
  if(canRedeemLoyalty&&loyaltyLoaded&&loyalty!=null&&remaining>0)item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Pontos do cliente",fontWeight=FontWeight.Black);Text("${loyalty!!.available} pontos disponíveis");loyaltyError?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}}
  if(canRequestDiscount&&(balance?.paidCents?:0)==0&&remaining>0)item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("Desconto",fontWeight=FontWeight.Bold);when(discountRequest?.status){"pending"->Text("Aguardando aprovação · ${posMoney(discountRequest.requestedCents)}");"approved"->Text("Desconto aprovado · ${posMoney(discountRequest.requestedCents)}");"rejected"->Text("A última solicitação não foi aprovada.");else->Text("Você pode solicitar um desconto.")};if(discountRequest?.status!="pending")OutlinedButton(onClick={discountDialog=true},modifier=Modifier.fillMaxWidth()){Text("Solicitar desconto")}}}}
  if(balance?.payments?.isNotEmpty()==true){item{Text("Recebimentos",fontWeight=FontWeight.Bold)};items(balance.payments,key={it.id}){part->Card(Modifier.fillMaxWidth()){Row(Modifier.fillMaxWidth().padding(14.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(paymentLabel(part.provider),fontWeight=FontWeight.Bold);Text(paymentStatusLabel(part.status))};Text(posMoney(part.amountCents),fontWeight=FontWeight.Black)}}}}
  if(remaining>0)item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Text("Receber",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text("Você pode receber o valor inteiro ou apenas uma parte.");OutlinedTextField(amountText,{amountText=it},label={Text("Valor (R$)")},singleLine=true,modifier=Modifier.fillMaxWidth());Button(onClick={onCash(amount)},enabled=state.cashOpen&&amount in 1..remaining&&discountRequest?.status!="pending",modifier=Modifier.fillMaxWidth()){Text("Dinheiro")};Button(onClick={scope.launch{pixConfigError=null;try{val cfg=app.repository.pixConfiguration();if(!cfg.enabled)pixConfigError="PIX não está habilitado para esta empresa." else if(cfg.requiresDocument)pixTaxDialog=true else onPix(amount,"")}catch(e:Exception){pixConfigError=e.message?:"Não foi possível consultar o PIX."}}},enabled=amount in 1..remaining&&discountRequest?.status!="pending",modifier=Modifier.fillMaxWidth()){Text("PIX")};pixConfigError?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button(onClick={onNfc(amount)},enabled=amount in 100..remaining&&discountRequest?.status!="pending",modifier=Modifier.fillMaxWidth()){Text("Cartão por aproximação")}}}} else item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){Text("Pagamento concluído",fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick={onReceipt(order.id)},modifier=Modifier.weight(1f)){Text("Enviar recibo")};OutlinedButton(onClick={onPrintReceipt(order.id)},modifier=Modifier.weight(1f)){Text("Imprimir")}};Button(onClick=onFinishFlow,modifier=Modifier.fillMaxWidth()){Text(if(state.posReturnScreen==AppScreen.TABLE_ACCOUNT)"Voltar à conta" else "Novo pedido")}}}}
  item{OutlinedButton(onClick={onRefresh();onRefreshDiscount(order.id)},modifier=Modifier.fillMaxWidth()){Text("Atualizar")}}
 }
 if(discountDialog){var value by remember{mutableStateOf("")};var reason by remember{mutableStateOf("")};val cents=((value.replace(',','.').toDoubleOrNull()?:0.0)*100).toInt();AlertDialog(onDismissRequest={discountDialog=false},title={Text("Solicitar desconto")},text={Column{OutlinedTextField(value,{value=it},label={Text("Valor (R$)")});OutlinedTextField(reason,{reason=it.take(500)},label={Text("Motivo")})}},confirmButton={Button(onClick={discountDialog=false;onRequestDiscount(order.id,cents,reason)},enabled=cents>0&&reason.isNotBlank()){Text("Enviar")}},dismissButton={TextButton(onClick={discountDialog=false}){Text("Cancelar")}})}
 if(pixTaxDialog){var taxId by remember{mutableStateOf("")};AlertDialog(onDismissRequest={pixTaxDialog=false},title={Text("PIX · ${posMoney(amount)}")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Este provedor precisa do CPF ou CNPJ do pagador.");OutlinedTextField(taxId,{taxId=it.filter(Char::isDigit).take(14)},label={Text("CPF ou CNPJ")},singleLine=true)}},confirmButton={Button(onClick={pixTaxDialog=false;onPix(amount,taxId)},enabled=taxId.length in setOf(11,14)){Text("Gerar PIX")}},dismissButton={TextButton(onClick={pixTaxDialog=false}){Text("Cancelar")}})}
}
private fun paymentLabel(provider:String)=when(provider.lowercase()){ "manual"->"Dinheiro";"pagbank"->"PagBank";"mercadopago"->"Mercado Pago";"stripe"->"Stripe";else->"Pagamento" }
private fun paymentStatusLabel(status:String)=when(status.lowercase()){ "paid","approved","confirmed"->"Confirmado";"pending","processing"->"Processando";"refunded"->"Estornado";"failed","cancelled"->"Não concluído";else->"Em andamento" }
private fun posMoney(cents:Int)="R$ %.2f".format(cents/100.0).replace('.',',')
