<?php

declare(strict_types=1);

require __DIR__.'/../app/bootstrap.php';

use EventMenu\Services\DeliveryCustomerConsentService;

$version=(new DeliveryCustomerConsentService())->termsVersion();
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: public, max-age=300');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Termos de Uso · EventMenu Delivery</title><style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#fff8f1;color:#211b18;margin:0}.wrap{max-width:760px;margin:auto;padding:28px 20px 64px}h1{color:#b51f28}h2{margin-top:28px}p,li{line-height:1.6}.meta{color:#6d625d}.box{background:#fff;border:1px solid #eadfd8;border-radius:16px;padding:18px}</style></head><body><main class="wrap"><h1>Termos de Uso · EventMenu Delivery</h1><p class="meta">Versão <?=htmlspecialchars($version,ENT_QUOTES,'UTF-8')?> · vigência a partir de 19/09/2026</p><div class="box"><p>Ao criar uma conta e utilizar o EventMenu Delivery, você concorda com estes termos para pesquisar estabelecimentos participantes, montar pedidos, realizar pagamentos disponíveis e acompanhar entregas.</p></div><h2>1. Conta do cliente</h2><p>Você deve informar dados verdadeiros e manter seu e-mail e telefone atualizados. O primeiro acesso depende da confirmação do e-mail cadastrado. A senha é pessoal e não deve ser compartilhada.</p><h2>2. Pedidos</h2><p>Produtos, preços, disponibilidade, pedido mínimo, taxa, horários e área de entrega são definidos pelo estabelecimento participante e confirmados pelo servidor no momento do pedido. O estabelecimento pode pausar temporariamente novos pedidos.</p><h2>3. Pagamentos</h2><p>As formas disponíveis podem incluir Pix, cartão e dinheiro na entrega. Pagamentos eletrônicos são processados por provedores integrados. O EventMenu somente considera um pagamento confirmado após validação segura do provedor.</p><h2>4. Entrega e localização</h2><p>Quando o pedido estiver em rota, o aplicativo pode mostrar a posição do entregador vinculada exclusivamente à entrega em andamento. O rastreamento termina quando a entrega é concluída ou o link deixa de ser válido.</p><h2>5. Cancelamentos e indisponibilidade</h2><p>Pedidos, cobranças e cancelamentos seguem o estado real registrado no sistema e as regras operacionais do estabelecimento. Falhas temporárias de internet ou de provedores podem atrasar atualizações, sem autorizar confirmação manual de pagamento sem validação.</p><h2>6. Uso adequado</h2><p>Não é permitido tentar fraudar pagamentos, interferir no funcionamento do serviço, usar contas de terceiros sem autorização ou explorar o sistema para finalidade ilegal.</p><h2>7. Atualizações destes termos</h2><p>Quando houver mudança material, uma nova versão poderá exigir novo aceite antes da continuidade de determinados recursos.</p><p class="meta">Este documento integra a Política de Privacidade do EventMenu Delivery.</p></main></body></html>
