<?php

declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';

use EventMenu\Core\Database;
use EventMenu\Core\Security;
use EventMenu\Services\ApiRateLimitService;
use EventMenu\Services\MarketplaceCommissionService;

$pdo=Database::connection();
$rate=new ApiRateLimitService();if(PHP_SAPI!=='cli')$rate->assertAllowed('public.marketplace.browse',$rate->requestSubject('eventmenu-delivery'),120,60,'Muitas atualizações em pouco tempo. Aguarde alguns segundos.');

$openTenant=max(0,(int)($_GET['open']??0));$openUnit=max(0,(int)($_GET['unit']??0));$campaign=mb_substr(trim((string)($_GET['campanha']??'')),0,80);
if($openTenant>0&&$openUnit>0){
    $s=$pdo->prepare('SELECT t.id,t.slug,u.id unit_id,u.code unit_code FROM tenants t JOIN marketplace_tenant_settings ms ON ms.tenant_id=t.id JOIN operating_units u ON u.tenant_id=t.id WHERE t.id=? AND u.id=? AND t.status="active" AND ms.participates=1 AND ms.status="active" AND u.active=1 LIMIT 1');$s->execute([$openTenant,$openUnit]);$store=$s->fetch();
    if(!$store){http_response_code(404);exit('Estabelecimento não disponível no EventMenu Delivery.');}
    $_SESSION['_eventmenu_delivery_entry'][$openTenant]=['unit_id'=>$openUnit,'campaign_code'=>$campaign?:null,'entered_at'=>time(),'expires_at'=>time()+7200];
    header('Location: '.app_url('menu.php?empresa='.rawurlencode((string)$store['slug']).'&unidade='.rawurlencode((string)$store['unit_code'])),true,302);exit;
}

$q=mb_substr(trim((string)($_GET['q']??'')),0,120);$city=mb_substr(trim((string)($_GET['cidade']??'')),0,120);$state=mb_substr(mb_strtoupper(trim((string)($_GET['uf']??''))),0,2);
$where=['t.status="active"','ms.participates=1','ms.status="active"','u.active=1'];$args=[];
if($q!==''){$where[]='(t.name LIKE ? OR u.name LIKE ? OR ms.city LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}if($city!==''){$where[]='LOWER(ms.city)=LOWER(?)';$args[]=$city;}if($state!==''){$where[]='UPPER(ms.state)=UPPER(?)';$args[]=$state;}
$sql='SELECT t.id tenant_id,t.name tenant_name,t.slug,t.settings,u.id unit_id,u.code unit_code,u.name unit_name,u.address,ms.city,ms.state FROM tenants t JOIN marketplace_tenant_settings ms ON ms.tenant_id=t.id JOIN operating_units u ON u.tenant_id=t.id WHERE '.implode(' AND ',$where).' ORDER BY t.name,u.name LIMIT 300';$s=$pdo->prepare($sql);$s->execute($args);$rows=$s->fetchAll();
$cities=$pdo->query('SELECT DISTINCT city FROM marketplace_tenant_settings WHERE participates=1 AND status="active" AND city IS NOT NULL AND city<>"" ORDER BY city')->fetchAll(PDO::FETCH_COLUMN);$states=$pdo->query('SELECT DISTINCT state FROM marketplace_tenant_settings WHERE participates=1 AND status="active" AND state IS NOT NULL AND state<>"" ORDER BY state')->fetchAll(PDO::FETCH_COLUMN);
$stores=[];foreach($rows as$row){$settings=json_decode((string)($row['settings']??'{}'),true)?:[];$row['logo_url']=trim((string)($settings['menu_logo_url']??''));$row['cover_url']=trim((string)($settings['menu_cover_url']??''));$row['description']=trim((string)($settings['menu_subtitle']??''));$row['delivery_fee_cents']=max(0,(int)($settings['delivery_fee_cents']??0));$row['min_delivery_order_cents']=max(0,(int)($settings['min_delivery_order_cents']??0));$stores[]=$row;}
function delivery_money(int$cents):string{return$cents<=0?'Grátis':'R$ '.number_format($cents/100,2,',','.');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#5b34d6"><meta name="description" content="Peça nos estabelecimentos participantes do EventMenu Delivery."><title>EventMenu Delivery</title><link rel="stylesheet" href="<?=Security::e(app_url('assets/delivery-marketplace.css'))?>"></head><body>
<div class="market-shell"><header class="market-top"><div class="top-inner"><div class="brand"><span class="brand-mark">E</span><span>EventMenu Delivery</span></div><form class="search" method="get"><input name="q" value="<?=Security::e($q)?>" placeholder="Buscar restaurante ou comida" aria-label="Buscar"><input type="hidden" name="cidade" value="<?=Security::e($city)?>"><input type="hidden" name="uf" value="<?=Security::e($state)?>"></form></div></header>
<section class="hero"><div class="hero-copy"><small>EVENTMENU DELIVERY</small><h1>Seu próximo pedido começa aqui.</h1><p>Encontre estabelecimentos participantes e acompanhe seu pedido usando a mesma operação integrada do EventMenu.</p></div></section>
<div class="filter-row"><a class="chip <?=$city===''&&$state===''?'active':''?>" href="<?=Security::e(app_url('delivery.php'.($q!==''?'?q='.rawurlencode($q):'')))?>">Todos</a><?php foreach($cities as$c):?><a class="chip <?=$city===$c?'active':''?>" href="<?=Security::e(app_url('delivery.php?cidade='.rawurlencode((string)$c).($q!==''?'&q='.rawurlencode($q):'')))?>"><?=Security::e((string)$c)?></a><?php endforeach;?><?php foreach($states as$uf):?><a class="chip <?=$state===$uf?'active':''?>" href="<?=Security::e(app_url('delivery.php?uf='.rawurlencode((string)$uf).($q!==''?'&q='.rawurlencode($q):'')))?>"><?=Security::e((string)$uf)?></a><?php endforeach;?></div>
<div class="section-head"><div><h2>Estabelecimentos</h2><p><?=count($stores)?> opção<?=count($stores)===1?'':'ões'?> disponível<?=count($stores)===1?'':'is'?> agora.</p></div></div>
<?php if(!$stores):?><div class="empty"><strong>Nenhum estabelecimento encontrado</strong><p>Tente outra busca ou remova os filtros.</p></div><?php else:?><section class="store-grid"><?php foreach($stores as$store):$name=(string)$store['tenant_name'];$openUrl=app_url('delivery.php?open='.(int)$store['tenant_id'].'&unit='.(int)$store['unit_id'].($campaign!==''?'&campanha='.rawurlencode($campaign):''));?><article class="store-card"><div class="store-cover"><?php if($store['cover_url']!==''):?><img src="<?=Security::e($store['cover_url'])?>" alt="" loading="lazy" decoding="async"><?php endif;?><?php if($store['logo_url']!==''):?><img class="store-logo" src="<?=Security::e($store['logo_url'])?>" alt="Logo <?=Security::e($name)?>" loading="lazy" decoding="async"><?php else:?><div class="store-logo store-monogram" aria-hidden="true"><?=Security::e(mb_strtoupper(mb_substr($name,0,1)))?></div><?php endif;?></div><div class="store-body"><h3><?=Security::e($name)?></h3><span class="store-unit"><?=Security::e((string)$store['unit_name'])?></span><div class="store-meta"><span class="meta open">Disponível</span><span class="meta">Entrega <?=Security::e(delivery_money((int)$store['delivery_fee_cents']))?></span><?php if((int)$store['min_delivery_order_cents']>0):?><span class="meta">Mín. <?=Security::e(delivery_money((int)$store['min_delivery_order_cents']))?></span><?php endif;?></div><?php if($store['description']!==''):?><p class="store-address"><?=Security::e($store['description'])?></p><?php elseif($store['address']):?><p class="store-address"><?=Security::e((string)$store['address'])?></p><?php else:?><p class="store-address"><?=Security::e(trim((string)($store['city']??'').' '.(string)($store['state']??'')))?></p><?php endif;?><a class="store-button" href="<?=Security::e($openUrl)?>">Ver cardápio</a></div></article><?php endforeach;?></section><?php endif;?><footer class="market-foot">EventMenu Delivery · pedidos integrados diretamente ao estabelecimento</footer></div>
</body></html>
