<?php

declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
use EventMenu\Core\Auth;use EventMenu\Core\Database;use EventMenu\Core\Security;use EventMenu\Core\TenantFeatures;use EventMenu\Services\OnboardingService;use EventMenu\Services\PlanLimitService;
$route=(string)($_GET['route']??'dashboard');try{$pdo=Database::connection();}catch(Throwable $e){http_response_code(503);$install=Security::e(app_url('install.php'));exit('<h1>EventMenu Premium</h1><p>Banco ainda não configurado. Configure o ambiente e acesse <a href="'.$install.'">instalação</a>.</p>');}
if($route==='pickup'&&!Auth::check()){$pickupToken=strtolower(trim((string)($_GET['token']??'')));if(preg_match('/^[a-f0-9]{40}$/',$pickupToken))$_SESSION['_after_login_pickup']=$pickupToken;app_redirect('?route=login');}
if($route==='login'){
 if(Auth::check())app_redirect(Auth::isSuperAdmin()&&!Auth::tenantId()?'?route=super':'');$error=!empty($_GET['blocked'])?'Sua sessão foi encerrada porque o usuário ou a empresa foi bloqueado.':null;
 if($_SERVER['REQUEST_METHOD']==='POST'){if(!Security::validateCsrf($_POST['_csrf']??null))$error='Sua sessão expirou. Atualize a página e tente novamente.';elseif(Auth::attempt((string)($_POST['email']??''),(string)($_POST['password']??''))){$pickupToken=strtolower(trim((string)($_SESSION['_after_login_pickup']??'')));unset($_SESSION['_after_login_pickup']);if(!Auth::isSuperAdmin()&&preg_match('/^[a-f0-9]{40}$/',$pickupToken))app_redirect('?route=pickup&token='.rawurlencode($pickupToken));if(Auth::isSuperAdmin()&&!Auth::tenantId())app_redirect('?route=super');$tenant=Auth::tenantId();if($tenant&&Auth::can('settings.manage'))try{if((new OnboardingService())->shouldPrompt($tenant))app_redirect('?route=onboarding');}catch(Throwable){}app_redirect('');}else$error='E-mail ou senha inválidos, ou acesso temporariamente bloqueado por excesso de tentativas.';}
 $authCss=Security::e(app_url('assets/auth-v2.css'));?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Entrar — EventMenu</title><link rel="stylesheet" href="<?=$authCss?>"></head><body class="auth-v2"><main class="auth-main"><section class="auth-panel"><h2>EventMenu</h2><?php if($error):?><div class="auth-alert error"><?=Security::e($error)?></div><?php endif;?><form method="post" class="auth-form"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrfToken())?>"><label class="auth-field"><span>E-mail</span><input type="email" name="email" required autofocus autocomplete="username"></label><label class="auth-field"><span>Senha</span><input type="password" name="password" required autocomplete="current-password"></label><button class="auth-submit">Entrar</button></form></section></main></body></html><?php exit;
}
if($route==='logout'){Auth::logout();app_redirect('?route=login');}if(!Auth::check())app_redirect('?route=login');require __DIR__.'/../app/admin_helpers.php';if(Auth::isSuperAdmin()&&!Auth::tenantId()&&$route==='dashboard')em_go('super');if($route==='dashboard'&&Auth::tenantId()&&Auth::can('settings.manage'))try{if((new OnboardingService())->shouldPrompt((int)Auth::tenantId()))em_go('onboarding');}catch(Throwable){}
$routes=['super'=>'super.php','receipt-ads'=>'receipt-ads.php','system-health'=>'system-health.php','dashboard'=>'dashboard.php','unit-context'=>'unit-context.php','pos'=>'pos.php','pickup'=>'pickup.php','cash'=>'cash.php','kitchen'=>'kitchen.php','kds-stream'=>'kds-stream.php','production'=>'production.php','product-config'=>'product-config.php','delivery'=>'delivery.php','products'=>'products.php','inventory'=>'inventory.php','purchases'=>'purchases.php','orders'=>'orders.php','receipt'=>'receipt.php','receipt-settings'=>'receipt-settings.php','restaurant'=>'restaurant.php','customers'=>'customers.php','coupons'=>'coupons.php','events'=>'events.php','event-admin'=>'event-admin.php','tickets'=>'tickets.php','guests'=>'guests.php','promoters'=>'promoters.php','payments'=>'payments.php','gateways'=>'gateways.php','users'=>'users.php','units'=>'units.php','reports'=>'reports.php','audit'=>'audit.php','settings'=>'settings-hub.php','settings-general'=>'settings.php','media-settings'=>'media-settings.php','email-settings'=>'email-settings.php','onboarding'=>'onboarding.php'];$file=$routes[$route]??null;if(!$file){http_response_code(404);em_header('Página não encontrada','');echo '<section class="card"><h2>404</h2></section>';em_footer();exit;}
if(!in_array($route,['super','receipt-ads','system-health','email-settings'],true)&&Auth::tenantId()&&!TenantFeatures::routeEnabled($route,Auth::tenantId())){http_response_code(403);em_header('Módulo não habilitado','');echo '<section class="card"><h2>Módulo fora do tipo de operação</h2></section>';em_footer();exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&Auth::tenantId())try{$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);$limits=new PlanLimitService();if($route==='users'&&$action==='save'&&$id<1)$limits->assertCanCreate('users');if($route==='products'&&$action==='product-save'&&$id<1)$limits->assertCanCreate('products');}catch(Throwable $e){em_flash('error',$e->getMessage());em_go($route);}require __DIR__.'/../app/routes/'.$file;
