<?php

declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
use EventMenu\Core\Database;
use EventMenu\Core\Security;

$token=trim((string)($_GET['t']??''));$pdo=Database::connection();$s=$pdo->prepare('SELECT t.*,e.name event_name,e.starts_at,e.venue,e.address,b.name batch_name,c.name customer_name,tn.name tenant_name FROM tickets t JOIN events e ON e.id=t.event_id JOIN ticket_batches b ON b.id=t.batch_id JOIN tenants tn ON tn.id=t.tenant_id LEFT JOIN customers c ON c.id=t.customer_id WHERE t.qr_token=? LIMIT 1');$s->execute([$token]);$ticket=$s->fetch();if(!$ticket){http_response_code(404);exit('Ingresso não encontrado.');}
$qrSvg=null;if(in_array($ticket['status'],['paid','checked_in'],true)&&class_exists('Endroid\\QrCode\\QrCode')){try{$url=rtrim((string)env('APP_URL',''),'/').'/ingresso.php?t='.rawurlencode($token);$qr=new \Endroid\QrCode\QrCode(data:$url,size:320,margin:12);$writer=new \Endroid\QrCode\Writer\SvgWriter();$qrSvg=$writer->write($qr)->getString();}catch(Throwable){$qrSvg=null;}}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ingresso <?= Security::e($ticket['event_name']) ?></title><link rel="stylesheet" href="/assets/app.css"><style>.ticket-shell{max-width:520px;margin:32px auto;padding:18px}.ticket-card{text-align:center;padding:28px;border-radius:28px;background:var(--card);border:1px solid var(--line)}.qr svg{max-width:100%;height:auto;background:#fff;border-radius:18px;padding:12px}.code{font-family:monospace;letter-spacing:1px;word-break:break-all}</style></head><body><main class="ticket-shell"><article class="ticket-card"><div class="brand">EventMenu <span>Premium</span></div><p class="muted"><?= Security::e($ticket['tenant_name']) ?></p><h1><?= Security::e($ticket['event_name']) ?></h1><p><?= Security::e(date('d/m/Y H:i',strtotime($ticket['starts_at']))) ?><br><?= Security::e($ticket['venue']) ?><br><span class="muted"><?= Security::e($ticket['address']) ?></span></p><p><span class="badge"><?= Security::e($ticket['batch_name']) ?></span> <span class="badge"><?= Security::e($ticket['status']) ?></span></p><h3><?= Security::e($ticket['customer_name']??'Ingresso') ?></h3><?php if(in_array($ticket['status'],['paid','checked_in'],true)):?><?php if($qrSvg):?><div class="qr"><?= $qrSvg ?></div><?php else:?><div class="alert error">Instale as dependências com <code>composer install</code> para exibir o QR.</div><?php endif;?><p class="code"><?= Security::e($ticket['code']) ?></p><p class="muted">Apresente este QR na entrada. O código só pode ser utilizado uma vez.</p><?php elseif($ticket['status']==='reserved'):?><div class="alert">Reserva aguardando pagamento até <?= Security::e($ticket['reserved_until']??'') ?>.</div><?php else:?><div class="alert error">Este ingresso não está válido para entrada.</div><?php endif;?></article></main></body></html>
