<?php

declare(strict_types=1);

require __DIR__.'/../app/bootstrap.php';

use EventMenu\Core\Database;
use EventMenu\Core\Security;
use EventMenu\Core\TenantFeatures;
use EventMenu\Services\PublicUnitService;

$pdo=Database::connection();$slug=trim((string)($_GET['empresa']??''));$s=$pdo->prepare('SELECT id,name,slug,settings FROM tenants WHERE slug=? AND status="active" LIMIT 1');$s->execute([$slug]);$tenant=$s->fetch();if(!$tenant||!TenantFeatures::menu((int)($tenant['id']??0))){http_response_code(404);exit('Empresa não encontrada.');}$tenantId=(int)$tenant['id'];$service=new PublicUnitService();$units=$service->units($tenantId);if(!$units){http_response_code(503);exit('Nenhuma unidade disponível para pedidos.');}
$requested=trim((string)($_GET['unidade']??''));if($requested!==''){try{$unit=$service->selectByCode($tenantId,$requested);header('Location: '.$service->menuUrl((string)$tenant['slug'],$unit),true,303);exit;}catch(Throwable){http_response_code(404);exit('Unidade não encontrada.');}}
if(count($units)===1){$unit=$service->selectById($tenantId,(int)$units[0]['id']);header('Location: '.$service->menuUrl((string)$tenant['slug'],$unit),true,303);exit;}
$settings=json_decode((string)($tenant['settings']??'{}'),true)?:[];$color=static function(mixed$v,string$f):string{$v=strtolower(trim((string)$v));return preg_match('/^#[0-9a-f]{6}$/',$v)?$v:$f;};$primary=$color($settings['menu_primary_color']??'','#6236df');$background=$color($settings['menu_background_color']??'','#f7f7fb');$surface=$color($settings['menu_surface_color']??'','#ffffff');$text=$color($settings['menu_text_color']??'','#242136');$title=trim((string)($settings['menu_public_title']??''))?:$tenant['name'];$logo=trim((string)($settings['menu_logo_url']??''));
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="<?= Security::e($primary) ?>"><title>Escolha a unidade — <?= Security::e($title) ?></title><style>:root{--bg:<?= Security::e($background) ?>;--surface:<?= Security::e($surface) ?>;--text:<?= Security::e($text) ?>;--primary:<?= Security::e($primary) ?>;--muted:#77748b;--line:#e7e4ee}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,color-mix(in srgb,var(--primary) 10%,var(--bg)),var(--bg) 42%);color:var(--text);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.shell{width:min(760px,100%);margin:auto;padding:30px 18px 70px}.brand{display:flex;align-items:center;gap:12px;margin-bottom:46px}.logo{width:54px;height:54px;border-radius:16px;object-fit:cover;background:var(--primary);display:grid;place-items:center;color:#fff;font-weight:950;font-size:21px}.brand strong,.brand small{display:block}.brand small{color:var(--muted);margin-top:3px}.eyebrow{font-size:10px;letter-spacing:.16em;color:var(--primary);font-weight:900}h1{font-size:clamp(34px,7vw,58px);letter-spacing:-1.8px;line-height:1;margin:8px 0 12px}p{color:var(--muted);line-height:1.55}.units{display:grid;gap:12px;margin-top:28px}.unit{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:20px;background:var(--surface);border:1px solid var(--line);border-radius:20px;text-decoration:none;color:inherit;box-shadow:0 12px 36px rgba(45,35,80,.06);transition:.15s transform,.15s border-color}.unit:hover{transform:translateY(-2px);border-color:color-mix(in srgb,var(--primary) 45%,var(--line))}.unit strong{display:block;font-size:18px}.unit span{display:block;color:var(--muted);font-size:13px;margin-top:4px}.go{flex:0 0 auto;border-radius:999px;background:var(--primary);color:#fff;padding:10px 14px;font-weight:900;font-size:12px}@media(max-width:520px){.brand{margin-bottom:34px}.unit{align-items:flex-start}.go{margin-top:2px}}</style></head><body><main class="shell"><div class="brand"><?php if($logo!==''):?><img class="logo" src="<?= Security::e($logo) ?>" alt=""><?php else:?><div class="logo"><?= Security::e(mb_strtoupper(mb_substr((string)$title,0,1))) ?></div><?php endif;?><div><strong><?= Security::e($title) ?></strong><small>Cardápio digital</small></div></div><span class="eyebrow">ONDE VOCÊ QUER PEDIR?</span><h1>Escolha a unidade</h1><p>O estoque, a produção, a retirada e o delivery serão atendidos pela unidade escolhida.</p><div class="units"><?php foreach($units as$unit):?><a class="unit" href="<?= Security::e(app_url('loja.php?empresa='.rawurlencode((string)$tenant['slug']).'&unidade='.rawurlencode((string)$unit['code']))) ?>"><div><strong><?= Security::e($unit['name']) ?></strong><span><?= Security::e($unit['address']?:'Ver cardápio desta unidade') ?></span></div><b class="go">Escolher</b></a><?php endforeach;?></div></main></body></html>
