<?php

declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
use EventMenu\Core\Database;
use EventMenu\Core\Security;
use EventMenu\Services\CheckoutService;

$pdo=Database::connection();$token=trim((string)($_GET['t']??''));$error=null;
function p_money(int $c):string{return 'R$ '.number_format($c/100,2,',','.');}
function allowed_checkout_url(string $provider,string $url):bool{$p=parse_url($url);if(($p['scheme']??'')!=='https'||empty($p['host']))return false;$h=strtolower($p['host']);$allowed=['stripe'=>['stripe.com'],'mercadopago'=>['mercadopago.com','mercadopago.com.br'],'pagbank'=>['pagseguro.uol.com.br','pagbank.com.br']];foreach($allowed[$provider]??[] as $suffix){if($h===$suffix||str_ends_with($h,'.'.$suffix))return true;}return false;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!Security::validateCsrf($_POST['_csrf']??null))$error='Sessão expirada.';else{try{$provider=(string)($_POST['provider']??'');$checkout=(new CheckoutService())->create($token,$provider);if(!allowed_checkout_url($checkout['provider'],$checkout['url']))throw new RuntimeException('URL de checkout rejeitada por segurança.');header('Location: '.$checkout['url'],true,303);exit;}catch(Throwable $e){$error=$e->getMessage();}}
}
$s=$pdo->prepare('SELECT o.*,t.name tenant_name,t.slug tenant_slug,c.name customer_name FROM orders o JOIN tenants t ON t.id=o.tenant_id LEFT JOIN customers c ON c.id=o.customer_id WHERE o.public_token=? AND t.status="active" LIMIT 1');$s->execute([$token]);$order=$s->fetch();if(!$order){http_response_code(404);exit('Pedido não encontrado.');}
$items=$pdo->prepare('SELECT * FROM order_items WHERE order_id=?');$items->execute([$order['id']]);$items=$items->fetchAll();$g=$pdo->prepare('SELECT provider FROM payment_gateways WHERE tenant_id=? AND active=1 ORDER BY provider');$g->execute([$order['tenant_id']]);$gateways=$g->fetchAll(PDO::FETCH_COLUMN);$tickets=$pdo->prepare('SELECT t.*,e.name event_name,b.name batch_name FROM tickets t JOIN events e ON e.id=t.event_id JOIN ticket_batches b ON b.id=t.batch_id WHERE t.order_id=? ORDER BY t.id');$tickets->execute([$order['id']]);$tickets=$tickets->fetchAll();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pedido #<?= (int)$order['id'] ?> — EventMenu</title><link rel="stylesheet" href="/assets/app.css"><style>.public-shell{max-width:760px;margin:30px auto;padding:18px}.pay-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.ticket-link{display:block;margin:8px 0}</style></head><body><main class="public-shell"><div class="brand">EventMenu <span>Premium</span></div><p class="muted"><?= Security::e($order['tenant_name']) ?></p><section class="card"><div class="section-head"><div><h1>Pedido #<?= (int)$order['id'] ?></h1><p class="muted"><?= Security::e($order['customer_name']??'Cliente') ?></p></div><span class="badge"><?= Security::e($order['payment_status']) ?></span></div><?php if($error):?><div class="alert error"><?= Security::e($error) ?></div><?php endif;?><div class="table-wrap"><table class="table"><tbody><?php foreach($items as $i):?><tr><td><?= Security::e($i['name_snapshot']) ?> × <?= Security::e((string)$i['quantity']) ?></td><td><?= p_money($i['total_cents']) ?></td></tr><?php endforeach;?><tr><td>Desconto</td><td>- <?= p_money($order['discount_cents']) ?></td></tr><tr><td><strong>Total</strong></td><td><strong><?= p_money($order['total_cents']) ?></strong></td></tr></tbody></table></div><?php if($order['payment_status']==='paid'):?><div class="alert ok">Pagamento confirmado pelo servidor.</div><?php if($tickets):?><h2>Seus ingressos</h2><?php foreach($tickets as $t):?><a class="button secondary ticket-link" href="/ingresso.php?t=<?= urlencode($t['qr_token']) ?>">Abrir ingresso <?= Security::e($t['code']) ?> · <?= Security::e($t['status']) ?></a><?php endforeach;?><?php endif;?><?php elseif(!in_array($order['status'],['cancelled','completed'],true)):?><h2>Escolha como pagar</h2><?php if($gateways):?><div class="pay-grid"><?php foreach($gateways as $provider):?><form method="post"><input type="hidden" name="_csrf" value="<?= Security::e(Security::csrfToken()) ?>"><input type="hidden" name="provider" value="<?= Security::e($provider) ?>"><button class="primary" style="width:100%">Pagar com <?= Security::e(['stripe'=>'Stripe','mercadopago'=>'Mercado Pago','pagbank'=>'PagBank'][$provider]??$provider) ?></button></form><?php endforeach;?></div><p class="muted">A confirmação só ocorre após validação do webhook e consulta do pagamento no provedor.</p><?php else:?><div class="alert">Nenhum pagamento online foi habilitado por esta empresa.</div><?php endif;?><?php else:?><div class="alert error">Este pedido foi encerrado ou cancelado.</div><?php endif;?></section></main></body></html>
