CREATE TABLE IF NOT EXISTS refunds (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  payment_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  requested_by BIGINT UNSIGNED NULL,
  provider ENUM('stripe','pagbank','mercadopago','manual') NOT NULL,
  provider_refund_id VARCHAR(190) NULL,
  amount_cents INT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'BRL',
  status ENUM('requested','provider_pending','provider_succeeded','completed','failed') NOT NULL DEFAULT 'requested',
  reason VARCHAR(500) NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  provider_payload JSON NULL,
  error_message VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  provider_succeeded_at DATETIME NULL,
  completed_at DATETIME NULL,
  CONSTRAINT fk_refunds_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_user FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_refund_idempotency (tenant_id,idempotency_key),
  UNIQUE KEY uq_refund_payment_full (tenant_id,payment_id),
  INDEX idx_refunds_order (tenant_id,order_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
