CREATE TABLE refunds (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  payment_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  provider ENUM('stripe','pagbank','mercadopago','manual') NOT NULL,
  provider_refund_id VARCHAR(190) NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  amount_cents INT UNSIGNED NOT NULL,
  restore_stock TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('processing','succeeded','failed') NOT NULL DEFAULT 'processing',
  error_message VARCHAR(500) NULL,
  raw_response JSON NULL,
  requested_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_refunds_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_user FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_refund_idempotency (tenant_id,idempotency_key),
  UNIQUE KEY uq_provider_refund (provider,provider_refund_id),
  INDEX idx_refunds_payment (tenant_id,payment_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
