CREATE TABLE financial_recurring_templates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NULL,
  event_id BIGINT UNSIGNED NULL,
  account_id BIGINT UNSIGNED NULL,
  category_id BIGINT UNSIGNED NULL,
  direction VARCHAR(10) NOT NULL,
  description VARCHAR(255) NOT NULL,
  amount_cents BIGINT NOT NULL,
  frequency VARCHAR(20) NOT NULL,
  interval_count INT NOT NULL DEFAULT 1,
  anchor_day INT NULL,
  next_due_date DATE NOT NULL,
  end_date DATE NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  last_generated_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fin_recurring_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_fin_recurring_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE SET NULL,
  CONSTRAINT fk_fin_recurring_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL,
  CONSTRAINT fk_fin_recurring_account FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_fin_recurring_category FOREIGN KEY (category_id) REFERENCES financial_categories(id) ON DELETE SET NULL,
  CONSTRAINT fk_fin_recurring_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_fin_recurring_due (tenant_id,active,next_due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
