CREATE TABLE IF NOT EXISTS fiscal_profiles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  environment ENUM('homologation','production') NOT NULL DEFAULT 'homologation',
  default_document ENUM('nfce','nfe') NOT NULL DEFAULT 'nfce',
  legal_name VARCHAR(190) NULL,
  trade_name VARCHAR(190) NULL,
  cnpj VARCHAR(14) NOT NULL DEFAULT '',
  state_registration VARCHAR(32) NOT NULL DEFAULT '',
  state_code CHAR(2) NOT NULL DEFAULT '',
  city_code VARCHAR(16) NULL,
  tax_regime VARCHAR(16) NULL,
  nfce_series INT UNSIGNED NOT NULL DEFAULT 1,
  nfce_next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
  nfe_series INT UNSIGNED NOT NULL DEFAULT 1,
  nfe_next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
  csc_id VARCHAR(32) NULL,
  csc_token_encrypted LONGTEXT NULL,
  certificate_mode ENUM('server','desktop','hybrid','a3_local') NOT NULL DEFAULT 'server',
  contingency_enabled TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fiscal_profile_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_fiscal_profile_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE CASCADE,
  UNIQUE KEY uq_fiscal_profile_unit (tenant_id, unit_id),
  INDEX idx_fiscal_profile_enabled (tenant_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_certificates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  fiscal_profile_id BIGINT UNSIGNED NOT NULL,
  certificate_type ENUM('a1','a3') NOT NULL DEFAULT 'a1',
  storage_scope ENUM('server','hybrid','local_reference') NOT NULL DEFAULT 'server',
  pfx_encrypted LONGTEXT NULL,
  password_encrypted LONGTEXT NULL,
  subject_name VARCHAR(500) NULL,
  issuer_name VARCHAR(500) NULL,
  serial_number VARCHAR(190) NULL,
  thumbprint VARCHAR(190) NULL,
  valid_from DATETIME NULL,
  valid_until DATETIME NULL,
  status ENUM('active','expired','revoked','disabled') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fiscal_cert_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_fiscal_cert_profile FOREIGN KEY (fiscal_profile_id) REFERENCES fiscal_profiles(id) ON DELETE CASCADE,
  INDEX idx_fiscal_cert_profile (fiscal_profile_id, status, valid_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_documents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  fiscal_profile_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  model ENUM('55','65') NOT NULL,
  environment ENUM('homologation','production') NOT NULL,
  series INT UNSIGNED NOT NULL,
  document_number BIGINT UNSIGNED NOT NULL,
  status ENUM('queued','processing','authorized','rejected','cancelled','contingency','error') NOT NULL DEFAULT 'queued',
  access_key VARCHAR(64) NULL,
  protocol VARCHAR(120) NULL,
  rejection_code VARCHAR(32) NULL,
  rejection_message VARCHAR(1000) NULL,
  xml_encrypted LONGTEXT NULL,
  cancellation_xml_encrypted LONGTEXT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  issued_at DATETIME NULL,
  authorized_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fiscal_doc_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_fiscal_doc_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE RESTRICT,
  CONSTRAINT fk_fiscal_doc_profile FOREIGN KEY (fiscal_profile_id) REFERENCES fiscal_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_fiscal_doc_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  UNIQUE KEY uq_fiscal_doc_idempotency (tenant_id, idempotency_key),
  UNIQUE KEY uq_fiscal_doc_number (tenant_id, fiscal_profile_id, model, series, document_number),
  INDEX idx_fiscal_doc_order (tenant_id, order_id),
  INDEX idx_fiscal_doc_status (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_terminal_configs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  provider ENUM('pagbank_tef','stone_tef','sitef','generic_tef') NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  integration_mode ENUM('dll','local_service','tcp','serial') NOT NULL DEFAULT 'local_service',
  terminal_label VARCHAR(160) NULL,
  pinpad_identifier VARCHAR(190) NULL,
  config_encrypted LONGTEXT NULL,
  auto_capture TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_terminal_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_terminal_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE CASCADE,
  INDEX idx_terminal_unit (tenant_id, unit_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS desktop_hardware_bindings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  device_hash CHAR(64) NOT NULL,
  device_label VARCHAR(190) NULL,
  hardware_json LONGTEXT NULL,
  last_seen_at DATETIME NULL,
  revoked_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_hw_binding_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_hw_binding_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE CASCADE,
  UNIQUE KEY uq_hw_binding_device (tenant_id, device_hash),
  INDEX idx_hw_binding_unit (tenant_id, unit_id, revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
