CREATE TABLE IF NOT EXISTS terminal_payment_intents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  terminal_config_id BIGINT UNSIGNED NOT NULL,
  device_hash CHAR(64) NOT NULL,
  provider VARCHAR(64) NOT NULL,
  intent_token CHAR(64) NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  amount_cents INT UNSIGNED NOT NULL,
  payment_type ENUM('debit','credit','pix','voucher') NOT NULL,
  installments INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('created','processing','approved_local','verified','failed','cancelled','expired') NOT NULL DEFAULT 'created',
  provider_transaction_id VARCHAR(190) NULL,
  authorization_code VARCHAR(120) NULL,
  local_result_encrypted LONGTEXT NULL,
  verification_result_encrypted LONGTEXT NULL,
  expires_at DATETIME NOT NULL,
  verified_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_terminal_intent_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_terminal_intent_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE RESTRICT,
  CONSTRAINT fk_terminal_intent_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_terminal_intent_config FOREIGN KEY (terminal_config_id) REFERENCES payment_terminal_configs(id) ON DELETE RESTRICT,
  UNIQUE KEY uq_terminal_intent_token (intent_token),
  UNIQUE KEY uq_terminal_intent_idempotency (tenant_id, idempotency_key),
  INDEX idx_terminal_intent_order (tenant_id, order_id, status),
  INDEX idx_terminal_intent_expiry (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
