ALTER TABLE fiscal_documents
  ADD COLUMN contingency_mode VARCHAR(24) NULL AFTER response_encrypted,
  ADD COLUMN contingency_reason VARCHAR(500) NULL AFTER contingency_mode,
  ADD COLUMN contingency_started_at DATETIME NULL AFTER contingency_reason,
  ADD COLUMN contingency_synced_at DATETIME NULL AFTER contingency_started_at;

CREATE TABLE IF NOT EXISTS fiscal_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  fiscal_document_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  sequence_no INT UNSIGNED NOT NULL DEFAULT 1,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  reason VARCHAR(500) NOT NULL,
  protocol VARCHAR(120) NULL,
  rejection_code VARCHAR(32) NULL,
  rejection_message VARCHAR(1000) NULL,
  request_xml_encrypted LONGTEXT NULL,
  response_xml_encrypted LONGTEXT NULL,
  response_encrypted LONGTEXT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME NULL,
  authorized_at DATETIME NULL,
  last_attempt_at DATETIME NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fiscal_event_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_fiscal_event_document FOREIGN KEY (fiscal_document_id) REFERENCES fiscal_documents(id) ON DELETE CASCADE,
  UNIQUE KEY uq_fiscal_event_idempotency (tenant_id,idempotency_key),
  UNIQUE KEY uq_fiscal_event_sequence (tenant_id,fiscal_document_id,event_type,sequence_no),
  INDEX idx_fiscal_event_queue (tenant_id,status,event_type,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_inutilizations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NOT NULL,
  fiscal_profile_id BIGINT UNSIGNED NOT NULL,
  model VARCHAR(2) NOT NULL,
  environment VARCHAR(20) NOT NULL,
  fiscal_year SMALLINT UNSIGNED NOT NULL,
  series INT UNSIGNED NOT NULL,
  number_start BIGINT UNSIGNED NOT NULL,
  number_end BIGINT UNSIGNED NOT NULL,
  justification VARCHAR(255) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  protocol VARCHAR(120) NULL,
  rejection_code VARCHAR(32) NULL,
  rejection_message VARCHAR(1000) NULL,
  request_xml_encrypted LONGTEXT NULL,
  response_xml_encrypted LONGTEXT NULL,
  response_encrypted LONGTEXT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME NULL,
  authorized_at DATETIME NULL,
  last_attempt_at DATETIME NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_fiscal_inut_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_fiscal_inut_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE CASCADE,
  CONSTRAINT fk_fiscal_inut_profile FOREIGN KEY (fiscal_profile_id) REFERENCES fiscal_profiles(id) ON DELETE CASCADE,
  UNIQUE KEY uq_fiscal_inut_idempotency (tenant_id,idempotency_key),
  INDEX idx_fiscal_inut_queue (tenant_id,status,created_at),
  INDEX idx_fiscal_inut_range (tenant_id,model,series,fiscal_year,number_start,number_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
