CREATE TABLE IF NOT EXISTS delivery_location_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  delivery_user_id BIGINT UNSIGNED NOT NULL,
  shift_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  accuracy_m DECIMAL(9,2) NULL,
  speed_mps DECIMAL(9,3) NULL,
  heading_degrees DECIMAL(7,2) NULL,
  provider VARCHAR(30) NULL,
  device_id_hash CHAR(64) NOT NULL,
  recorded_at DATETIME NOT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_delivery_location_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_delivery_location_user FOREIGN KEY (delivery_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_delivery_location_shift FOREIGN KEY (shift_id) REFERENCES work_shifts(id) ON DELETE CASCADE,
  CONSTRAINT fk_delivery_location_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE SET NULL,
  CONSTRAINT fk_delivery_location_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  INDEX idx_delivery_location_route (tenant_id,order_id,recorded_at),
  INDEX idx_delivery_location_user (tenant_id,unit_id,delivery_user_id,recorded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS delivery_live_locations (
  tenant_id BIGINT UNSIGNED NOT NULL,
  delivery_user_id BIGINT UNSIGNED NOT NULL,
  shift_id BIGINT UNSIGNED NOT NULL,
  unit_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  accuracy_m DECIMAL(9,2) NULL,
  speed_mps DECIMAL(9,3) NULL,
  heading_degrees DECIMAL(7,2) NULL,
  recorded_at DATETIME NOT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  device_id_hash CHAR(64) NOT NULL,
  PRIMARY KEY (tenant_id,delivery_user_id),
  CONSTRAINT fk_delivery_live_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_delivery_live_user FOREIGN KEY (delivery_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_delivery_live_shift FOREIGN KEY (shift_id) REFERENCES work_shifts(id) ON DELETE CASCADE,
  CONSTRAINT fk_delivery_live_unit FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE SET NULL,
  CONSTRAINT fk_delivery_live_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  INDEX idx_delivery_live_unit (tenant_id,unit_id,received_at),
  INDEX idx_delivery_live_order (tenant_id,order_id,received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
