package br.com.eventmenu.delivery.ui

import android.content.Intent
import android.graphics.Bitmap
import android.net.Uri
import androidx.compose.foundation.Image
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import br.com.eventmenu.delivery.BuildConfig
import br.com.eventmenu.delivery.DeliveryViewModel
import br.com.eventmenu.delivery.Screen
import br.com.eventmenu.delivery.money
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter

private val V2Primary=Color(0xFF6D28D9)
private val V2Dark=Color(0xFF4C1D95)

@Composable
fun DeliveryAppRootV2(vm:DeliveryViewModel){MaterialTheme(colorScheme=lightColorScheme(primary=V2Primary,primaryContainer=Color(0xFFE9DDFF),background=Color(0xFFFAF8FF),surface=Color.White)){when(vm.screen){Screen.Register->CpfRegisterScreen(vm);Screen.Checkout->NativeCheckoutScreen(vm);Screen.Profile->CpfProfileScreen(vm);else->DeliveryAppRoot(vm)}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun CpfRegisterScreen(vm:DeliveryViewModel){val context=LocalContext.current;var name by remember{mutableStateOf("")};var cpf by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var visible by remember{mutableStateOf(false)};var accepted by remember{mutableStateOf(false)};val snack=remember{SnackbarHostState()};LaunchedEffect(vm.message){vm.message?.let{snack.showSnackbar(it);vm.clearMessage()}};fun open(path:String){runCatching{context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(BuildConfig.API_BASE_URL+path)))}};Scaffold(topBar={TopAppBar(title={Text("Criar conta",fontWeight=FontWeight.Bold)},navigationIcon={IconButton({vm.navigate(Screen.Login)}){Icon(Icons.Default.ArrowBack,null)}})},snackbarHost={SnackbarHost(snack)}){pad->Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Seus dados ficam salvos para agilizar pedidos e pagamentos.",color=MaterialTheme.colorScheme.onSurfaceVariant);OutlinedTextField(name,{name=it.take(160)},label={Text("Nome")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(cpf,{cpf=it.filter(Char::isDigit).take(11)},label={Text("CPF")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number),singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(phone,{phone=it.filter{c->c.isDigit()||c in "+()- "}},label={Text("Celular")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Phone),singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(email,{email=it},label={Text("E-mail")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Email),singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(password,{password=it},label={Text("Senha · mínimo 8 caracteres")},visualTransformation=if(visible)VisualTransformation.None else PasswordVisualTransformation(),trailingIcon={IconButton({visible=!visible}){Icon(if(visible)Icons.Default.VisibilityOff else Icons.Default.Visibility,null)}},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Password),singleLine=true,modifier=Modifier.fillMaxWidth());Card{Column(Modifier.padding(12.dp)){Row(verticalAlignment=Alignment.CenterVertically){Checkbox(accepted,{accepted=it});Text("Li e aceito os Termos de Uso e a Política de Privacidade.",Modifier.weight(1f),style=MaterialTheme.typography.bodySmall)};Row{TextButton({open("delivery-terms.php")}){Text("Termos")};TextButton({open("delivery-privacy.php")}){Text("Privacidade")}}}};Button({vm.registerWithCpf(name,cpf,email,phone,password,accepted)},Modifier.fillMaxWidth().heightIn(min=52.dp),enabled=name.isNotBlank()&&cpf.length==11&&email.isNotBlank()&&password.length>=8&&accepted){Text("Cadastrar e confirmar e-mail",fontWeight=FontWeight.Bold)}}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun NativeCheckoutScreen(vm:DeliveryViewModel){val order=vm.selectedOrder?:return;val methods=vm.paymentMethods;val customer=vm.customer;val clipboard=LocalClipboardManager.current;val snack=remember{SnackbarHostState()};var showCard by remember{mutableStateOf(false)};var showCash by remember{mutableStateOf(false)};var changeText by remember{mutableStateOf("")};LaunchedEffect(vm.message){vm.message?.let{snack.showSnackbar(it);vm.clearMessage()}};LaunchedEffect(showCard,customer?.cpfConfigured){if(showCard&&customer?.cpfConfigured==true&&vm.payerCpf.isBlank())vm.prepareCardIdentification()};Scaffold(topBar={TopAppBar(title={Text("Pagamento",fontWeight=FontWeight.Bold)},navigationIcon={IconButton({vm.openOrder(order.orderNumber)}){Icon(Icons.Default.ArrowBack,null)}})},snackbarHost={SnackbarHost(snack)}){pad->LazyColumn(Modifier.fillMaxSize().padding(pad),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Card{Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(order.storeName,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("Pedido #${order.orderNumber}");Text(money(order.totalCents),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black,color=V2Dark)}}};if(customer?.cpfConfigured!=true)item{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.errorContainer)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Complete seu CPF para liberar PIX e cartão.",fontWeight=FontWeight.Bold);Text("Você informa uma única vez e depois o EventMenu reutiliza o cadastro com segurança.");Button({vm.openProfile()}){Text("Completar cadastro")}}}};if(methods==null)item{Card{Column(Modifier.padding(16.dp)){Text("Carregando formas de pagamento…");LinearProgressIndicator(Modifier.fillMaxWidth());TextButton({vm.reloadPaymentMethods()}){Text("Atualizar")}}}}else{
if(methods.pixProviders.isNotEmpty())item{Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(8.dp)){Icon(Icons.Default.QrCode2,null,tint=V2Primary);Text("PIX",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium)};Text("O QR Code e o Copia e Cola ficam dentro do EventMenu.",style=MaterialTheme.typography.bodySmall);methods.pixProviders.forEach{provider->Button({vm.payPix(provider,"")},Modifier.fillMaxWidth(),enabled=customer?.cpfConfigured==true&&!vm.paymentWaiting){Text("Gerar PIX · ${v2Provider(provider)}")}}}}}
vm.pixPayment?.let{pix->item{Card{Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(10.dp)){Text("PIX ${v2Provider(pix.provider)}",fontWeight=FontWeight.Bold);rememberQr(pix.copyPaste)?.let{Image(it,"QR Code PIX",Modifier.size(230.dp))};OutlinedTextField(pix.copyPaste,{},readOnly=true,label={Text("PIX Copia e Cola")},modifier=Modifier.fillMaxWidth(),minLines=3);Button({clipboard.setText(AnnotatedString(pix.copyPaste))},Modifier.fillMaxWidth()){Icon(Icons.Default.ContentCopy,null);Spacer(Modifier.width(8.dp));Text("Copiar código")};if(vm.paymentWaiting){LinearProgressIndicator(Modifier.fillMaxWidth());Text("Aguardando confirmação automática…")}}}}}
methods.cards.firstOrNull()?.let{card->item{Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth().clickable(enabled=customer?.cpfConfigured==true){showCard=!showCard},verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.CreditCard,null,tint=V2Primary);Spacer(Modifier.width(10.dp));Text("Cartão de crédito ou débito",Modifier.weight(1f),fontWeight=FontWeight.Bold);Icon(if(showCard)Icons.Default.ExpandLess else Icons.Default.ExpandMore,null)};if(showCard){if(vm.payerCpf.length==11)SavedCpfCardPaymentForm(card.publicKey,card.maxInstallments,customer?.name.orEmpty(),vm.payerCpf,card.paymentTypes){token,methodId,type,installments->vm.payCardToken(token,methodId,type,installments,"")}else{LinearProgressIndicator(Modifier.fillMaxWidth());Text("Preparando identificação segura…",style=MaterialTheme.typography.bodySmall)}}}}}
if(methods.cash)item{Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth().clickable{showCash=!showCash},verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Payments,null,tint=V2Primary);Spacer(Modifier.width(10.dp));Text("Dinheiro na entrega",Modifier.weight(1f),fontWeight=FontWeight.Bold);Icon(if(showCash)Icons.Default.ExpandLess else Icons.Default.ExpandMore,null)};if(showCash){OutlinedTextField(changeText,{changeText=it.filter{c->c.isDigit()||c==','||c=='.'}},label={Text("Troco para (opcional)")},modifier=Modifier.fillMaxWidth());Button({val cents=changeText.replace(',','.').toDoubleOrNull()?.let{(it*100).toInt()};vm.payCash(cents)},Modifier.fillMaxWidth()){Text("Pagar em dinheiro")}}}}}
}}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun CpfProfileScreen(vm:DeliveryViewModel){val c=vm.customer;var name by remember(c){mutableStateOf(c?.name.orEmpty())};var phone by remember(c){mutableStateOf(c?.phone.orEmpty())};var cpf by remember{mutableStateOf("")};val snack=remember{SnackbarHostState()};LaunchedEffect(vm.message){vm.message?.let{snack.showSnackbar(it);vm.clearMessage()}};Scaffold(topBar={TopAppBar(title={Text("Minha conta",fontWeight=FontWeight.Bold)},navigationIcon={IconButton({if(vm.selectedOrder!=null)vm.navigate(Screen.Checkout)else vm.navigate(Screen.Home)}){Icon(Icons.Default.ArrowBack,null)}})},snackbarHost={SnackbarHost(snack)}){pad->LazyColumn(Modifier.fillMaxSize().padding(pad),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(name,{name=it},label={Text("Nome")},modifier=Modifier.fillMaxWidth());OutlinedTextField(phone,{phone=it},label={Text("Celular")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Phone),modifier=Modifier.fillMaxWidth());Text(c?.email.orEmpty(),style=MaterialTheme.typography.bodySmall);if(c?.cpfConfigured==true){OutlinedTextField(c.cpfMasked,{},readOnly=true,label={Text("CPF")},modifier=Modifier.fillMaxWidth());Text("CPF protegido e já configurado.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}else{OutlinedTextField(cpf,{cpf=it.filter(Char::isDigit).take(11)},label={Text("CPF")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number),modifier=Modifier.fillMaxWidth());Text("Informe uma única vez para completar seu cadastro.",style=MaterialTheme.typography.bodySmall)};Button({vm.saveProfile(name,phone,if(c?.cpfConfigured==true)"" else cpf)},Modifier.fillMaxWidth(),enabled=name.isNotBlank()&&(c?.cpfConfigured==true||cpf.length==11)){Text("Salvar perfil")};if(vm.selectedOrder!=null)OutlinedButton({vm.navigate(Screen.Checkout)},Modifier.fillMaxWidth()){Text("Voltar ao pagamento")}}}};item{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("Meus endereços",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);FilledTonalIconButton({vm.editAddress()}){Icon(Icons.Default.Add,null)}}};if(c?.addresses.isNullOrEmpty())item{Card{Text("Cadastre seu endereço de entrega.",Modifier.padding(16.dp))}}else items(c!!.addresses,key={it.id}){a->Card{Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(a.label,fontWeight=FontWeight.Bold);Text("${a.street}, ${a.number} · ${a.city}/${a.state}");if(a.isDefault)Text("Endereço principal",style=MaterialTheme.typography.bodySmall,color=V2Primary)};IconButton({vm.editAddress(a)}){Icon(Icons.Default.Edit,null)};IconButton({vm.deleteAddress(a.id)}){Icon(Icons.Default.Delete,null)}}}};item{OutlinedButton({vm.logout()},Modifier.fillMaxWidth()){Text("Sair da conta")}}}}}

private fun v2Provider(provider:String)=when(provider.lowercase()){ "mercadopago"->"Mercado Pago";"pagbank"->"PagBank";"efi"->"Efí";"inter"->"Banco Inter";else->provider }
@Composable private fun rememberQr(text:String):androidx.compose.ui.graphics.ImageBitmap?=remember(text){runCatching{val matrix=QRCodeWriter().encode(text,BarcodeFormat.QR_CODE,600,600);val bitmap=Bitmap.createBitmap(600,600,Bitmap.Config.ARGB_8888);for(y in 0 until 600)for(x in 0 until 600)bitmap.setPixel(x,y,if(matrix[x,y])android.graphics.Color.BLACK else android.graphics.Color.WHITE);bitmap.asImageBitmap()}.getOrNull()}
