<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\BackupService;

if(Auth::role()!=='super_admin'){http_response_code(403);exit('Backup completo é restrito ao Super Administrador.');}$service=new BackupService();
if($_SERVER['REQUEST_METHOD']==='POST'){em_post_csrf();$action=(string)($_POST['action']??'');try{if($action==='create'){$result=$service->create((string)($_POST['password']??''));header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="'.$result['filename'].'"');header('X-Content-Type-Options: nosniff');echo$result['blob'];exit;}if($action==='restore'){if((string)($_POST['confirm']??'')!=='RESTAURAR')throw new RuntimeException('Digite RESTAURAR para confirmar.');if(empty($_FILES['backup']['tmp_name'])||!is_uploaded_file($_FILES['backup']['tmp_name']))throw new RuntimeException('Selecione o arquivo .embak.');$blob=(string)file_get_contents($_FILES['backup']['tmp_name']);$service->restore($blob,(string)($_POST['password']??''));em_flash('ok','Backup restaurado. Gateways foram desativados e dispositivos NFC revogados para revisão.');}}catch(Throwable $e){em_flash('error',$e->getMessage());}em_go('backup');}
$s=$pdo->query('SELECT bh.*,u.name user_name FROM backup_history bh LEFT JOIN users u ON u.id=bh.created_by ORDER BY bh.id DESC LIMIT 30');$history=$s->fetchAll();em_header('Backup e restauração','backup');?>
<div class="grid" style="grid-template-columns:1fr 1fr"><section class="card"><h2>Criar backup criptografado</h2><p class="muted">Gera um snapshot completo do banco no formato .embak usando AES-256-GCM e PBKDF2. Guarde a senha fora do servidor.</p><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="create"><label>Senha do backup<input type="password" name="password" minlength="12" required autocomplete="new-password"></label><button class="primary" style="margin-top:12px">Gerar e baixar .embak</button></form></section><section class="card"><h2>Restaurar backup</h2><div class="alert warning"><strong>Atenção:</strong> a restauração substitui o banco atual. Gateways ficam desativados e NFC é revogado automaticamente.</div><form method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="restore"><label>Arquivo .embak<input type="file" name="backup" accept=".embak" required></label><label>Senha<input type="password" name="password" minlength="12" required></label><label>Confirmação<input name="confirm" placeholder="Digite RESTAURAR" required></label><button class="danger" style="margin-top:12px">Restaurar banco</button></form></section></div><section class="card" style="margin-top:16px"><h2>Histórico</h2><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Operação</th><th>Arquivo</th><th>Status</th><th>Usuário</th></tr></thead><tbody><?php foreach($history as$h):?><tr><td><?= Security::e($h['created_at']) ?></td><td><?= Security::e($h['operation']) ?></td><td><?= Security::e($h['filename']??'—') ?></td><td><?= Security::e($h['status']) ?></td><td><?= Security::e($h['user_name']??'—') ?></td></tr><?php endforeach;?></tbody></table></div></section><?php em_footer();
