<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use EventMenu\Core\Security;
use EventMenu\Services\MarketplaceFinanceService;
use EventMenu\Services\MarketplaceReconciliationService;
use EventMenu\Services\PlatformBillingService;

Auth::requirePermission('settings.manage');
$tenantId=(int)(Auth::tenantId()??0);if($tenantId<1){http_response_code(403);exit('Empresa não selecionada.');}
(new MarketplaceReconciliationService())->reconcileTenant($pdo,$tenantId,500);
$pdo->prepare('UPDATE platform_invoices SET status="overdue",updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND status="open" AND due_at IS NOT NULL AND due_at<CURRENT_TIMESTAMP')->execute([$tenantId]);
$finance=new MarketplaceFinanceService();$billing=new PlatformBillingService();$invoices=$finance->invoices($pdo,$tenantId,100);$invoiceId=max(0,(int)($_GET['invoice']??0));$invoice=null;if($invoiceId){$candidate=$billing->detail($pdo,$invoiceId);if((int)$candidate['tenant_id']!==$tenantId){http_response_code(404);exit('Fatura não encontrada.');}$invoice=$candidate;}
$s=$pdo->prepare('SELECT ms.participates,ms.status marketplace_status,ts.status subscription_status,ts.billing_cycle,COALESCE(ts.custom_price_cents,CASE WHEN ts.billing_cycle="yearly" THEN p.yearly_cents ELSE p.monthly_cents END) contract_cents,p.name plan_name FROM tenants t LEFT JOIN marketplace_tenant_settings ms ON ms.tenant_id=t.id LEFT JOIN tenant_subscriptions ts ON ts.tenant_id=t.id LEFT JOIN saas_plans p ON p.id=ts.plan_id WHERE t.id=? LIMIT 1');$s->execute([$tenantId]);$summary=$s->fetch()?:[];
$status=['draft'=>'Em preparação','open'=>'Aberta','overdue'=>'Vencida','paid'=>'Paga','cancelled'=>'Cancelada'];$percent=static fn(int$bps):string=>number_format($bps/100,2,',','.').'%';
em_header('Faturas e cobrança','billing');
?>
<section class="page-hero"><div><span class="eyebrow">MINHA EMPRESA</span><h2>Faturas e cobrança</h2><p>Veja a mensalidade, serviços e as comissões dos pedidos do EventMenu Delivery com a composição completa.</p></div></section>
<section class="metric-grid"><div class="metric-card"><span>Plano EventMenu</span><strong><?=Security::e($summary['plan_name']??'—')?></strong><small><?=Security::e(($summary['subscription_status']??'')==='active'?'Ativo':(string)($summary['subscription_status']??'—'))?></small></div><div class="metric-card"><span>EventMenu Delivery</span><strong><?=((int)($summary['participates']??0)===1)?'Participando':'Não participa'?></strong><small><?=Security::e(($summary['marketplace_status']??'')==='suspended'?'Participação suspensa':'')?></small></div><div class="metric-card"><span>Valor do contrato</span><strong><?=isset($summary['contract_cents'])?em_money((int)$summary['contract_cents']):'—'?></strong><small><?=Security::e((string)($summary['billing_cycle']??''))?></small></div></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">HISTÓRICO</span><h2>Suas faturas</h2></div></div><?php if(!$invoices):?><div class="empty-state"><strong>Nenhuma fatura disponível</strong><p>Quando uma fatura for emitida, ela aparecerá aqui com todos os lançamentos detalhados.</p></div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Período</th><th>Situação</th><th>Vencimento</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($invoices as$i):?><tr><td><?=Security::e($i['period_start'].' a '.$i['period_end'])?></td><td><span class="status-pill <?=Security::e($i['status'])?>"><?=Security::e($status[$i['status']]??$i['status'])?></span></td><td><?=Security::e((string)($i['due_at']??'—'))?></td><td><strong><?=em_money((int)$i['total_cents'])?></strong></td><td><a class="button secondary compact" href="<?=Security::e(app_url('?route=billing&invoice='.(int)$i['id']))?>">Abrir fatura</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if($invoice):?><section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">FATURA #<?=(int)$invoice['id']?></span><h2><?=Security::e($status[$invoice['status']]??$invoice['status'])?></h2><p><?=Security::e($invoice['period_start'].' a '.$invoice['period_end'])?><?php if($invoice['due_at']):?> · vence em <?=Security::e((string)$invoice['due_at'])?><?php endif;?></p></div><strong style="font-size:1.6rem"><?=em_money((int)$invoice['total_cents'])?></strong></div><div class="table-wrap"><table class="table"><thead><tr><th>Descrição</th><th>Pedido</th><th>Base</th><th>Taxa</th><th>Valor</th></tr></thead><tbody><?php foreach($invoice['items'] as$item):?><tr><td><?=Security::e($item['description'])?></td><td><?=!empty($item['order_id'])?'#'.(int)$item['order_id']:'—'?></td><td><?=isset($item['calculation_base_cents'])&&$item['calculation_base_cents']!==null?em_money((int)$item['calculation_base_cents']):'—'?></td><td><?=isset($item['commission_bps'])&&$item['commission_bps']!==null?$percent((int)$item['commission_bps']):'—'?></td><td><?=em_money((int)$item['amount_cents'])?></td></tr><?php endforeach;?></tbody></table></div><div class="metric-grid"><div class="metric-card"><span>Cobranças</span><strong><?=em_money((int)$invoice['subtotal_cents'])?></strong></div><div class="metric-card"><span>Créditos</span><strong>-<?=em_money((int)$invoice['credits_cents'])?></strong></div><div class="metric-card"><span>Total</span><strong><?=em_money((int)$invoice['total_cents'])?></strong></div></div><p class="muted">Cada pedido do EventMenu Delivery mantém a taxa que estava vigente no momento da compra. Alterações futuras de taxa não mudam esta fatura retroativamente.</p></section><?php endif;?>
<?php em_footer(); ?>
