<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

Auth::requirePermission('coupons.manage');$tenantId=em_require_tenant();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    if($action==='save'){
        $id=(int)($_POST['id']??0);$code=strtoupper(trim((string)($_POST['code']??'')));$type=(string)($_POST['type']??'percent');$raw=(float)str_replace(',','.',(string)($_POST['value']??'0'));if($code===''||!in_array($type,['percent','fixed'],true)||$raw<=0)exit('Cupom inválido.');$value=$type==='percent'?(int)round($raw):(int)round($raw*100);if($type==='percent'&&$value>100)exit('Percentual máximo é 100%.');$min=(int)round((float)str_replace(',','.',(string)($_POST['min_order']??'0'))*100);$max=(int)($_POST['max_uses']??0);$start=(string)($_POST['starts_at']??'');$end=(string)($_POST['ends_at']??'');$start=$start?str_replace('T',' ',$start):null;$end=$end?str_replace('T',' ',$end):null;
        if($id){$s=$pdo->prepare('UPDATE coupons SET code=?,type=?,value=?,min_order_cents=?,max_uses=?,starts_at=?,ends_at=?,active=? WHERE id=? AND tenant_id=?');$s->execute([$code,$type,$value,$min,$max?:null,$start,$end,isset($_POST['active'])?1:0,$id,$tenantId]);}
        else{$s=$pdo->prepare('INSERT INTO coupons (tenant_id,code,type,value,min_order_cents,max_uses,starts_at,ends_at,active) VALUES (?,?,?,?,?,?,?,?,1)');$s->execute([$tenantId,$code,$type,$value,$min,$max?:null,$start,$end]);$id=(int)$pdo->lastInsertId();}
        Auth::audit('coupon.saved','coupon',(string)$id);em_flash('ok','Cupom salvo.');em_go('coupons');
    }
}
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=$pdo->prepare('SELECT * FROM coupons WHERE id=? AND tenant_id=?');$s->execute([$editId,$tenantId]);$edit=$s->fetch()?:null;}
$s=$pdo->prepare('SELECT * FROM coupons WHERE tenant_id=? ORDER BY id DESC');$s->execute([$tenantId]);$coupons=$s->fetchAll();
em_header('Cupons','coupons');
?><div class="grid" style="grid-template-columns:minmax(280px,1fr) minmax(0,2fr)"><section class="card"><h2><?= $edit?'Editar cupom':'Novo cupom' ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Código<input name="code" required value="<?= Security::e($edit['code']??'') ?>"></label><label>Tipo<select name="type"><option value="percent"<?= em_selected($edit['type']??'percent','percent') ?>>Percentual</option><option value="fixed"<?= em_selected($edit['type']??'','fixed') ?>>Valor fixo</option></select></label><label>Valor<input name="value" inputmode="decimal" required value="<?= $edit?Security::e($edit['type']==='fixed'?number_format(((int)$edit['value'])/100,2,',',''):(string)$edit['value']):'' ?>"></label><label>Pedido mínimo<input name="min_order" inputmode="decimal" value="<?= $edit?Security::e(number_format(((int)$edit['min_order_cents'])/100,2,',','')):'0' ?>"></label><label>Máx. usos<input type="number" name="max_uses" min="0" value="<?= Security::e((string)($edit['max_uses']??'')) ?>"></label><label>Início<input type="datetime-local" name="starts_at" value="<?= $edit&&$edit['starts_at']?Security::e(date('Y-m-d\TH:i',strtotime($edit['starts_at']))):'' ?>"></label><label>Fim<input type="datetime-local" name="ends_at" value="<?= $edit&&$edit['ends_at']?Security::e(date('Y-m-d\TH:i',strtotime($edit['ends_at']))):'' ?>"></label><label class="checkbox"><input type="checkbox" name="active"<?= em_checked($edit?($edit['active']??0):1) ?>> Ativo</label><button class="primary span-2">Salvar cupom</button></form></section><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Desconto</th><th>Usos</th><th>Validade</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($coupons as $c):?><tr><td><strong><?= Security::e($c['code']) ?></strong></td><td><?= $c['type']==='percent'?(int)$c['value'].'%':em_money($c['value']) ?></td><td><?= (int)$c['uses_count'] ?><?= $c['max_uses']!==null?' / '.(int)$c['max_uses']:'' ?></td><td><?= Security::e($c['ends_at']??'Sem limite') ?></td><td><span class="badge"><?= $c['active']?'Ativo':'Inativo' ?></span></td><td><a class="button secondary" href="/?route=coupons&edit=<?= (int)$c['id'] ?>">Editar</a></td></tr><?php endforeach;?></tbody></table></div></section></div><?php em_footer();
