<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

Auth::requirePermission('customers.manage');$tenantId=em_require_tenant();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    if($action==='customer-save'){
        $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$phone=trim((string)($_POST['phone']??''));if($name==='')exit('Cliente inválido.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))exit('E-mail inválido.');
        if($id){$s=$pdo->prepare('UPDATE customers SET name=?,phone=?,email=?,document=? WHERE id=? AND tenant_id=?');$s->execute([$name,$phone?:null,$email?:null,trim((string)($_POST['document']??''))?:null,$id,$tenantId]);}
        else{$s=$pdo->prepare('INSERT INTO customers (tenant_id,name,phone,email,document) VALUES (?,?,?,?,?)');$s->execute([$tenantId,$name,$phone?:null,$email?:null,trim((string)($_POST['document']??''))?:null]);$id=(int)$pdo->lastInsertId();}
        Auth::audit('customer.saved','customer',(string)$id);em_flash('ok','Cliente salvo.');em_go('customers');
    }
    if($action==='points-adjust'){
        $id=(int)($_POST['id']??0);$points=(int)($_POST['points']??0);if($points===0)exit('Informe pontos diferentes de zero.');$key='adjust:'.Auth::id().':'.$id.':'.bin2hex(random_bytes(8));
        $pdo->beginTransaction();try{$s=$pdo->prepare('SELECT points FROM customers WHERE id=? AND tenant_id=? FOR UPDATE');$s->execute([$id,$tenantId]);$current=$s->fetchColumn();if($current===false)throw new RuntimeException('Cliente não encontrado.');if((int)$current+$points<0)throw new RuntimeException('Saldo não pode ficar negativo.');$pdo->prepare('INSERT INTO customer_points_movements (tenant_id,customer_id,points,type,idempotency_key) VALUES (?,?,?,"adjustment",?)')->execute([$tenantId,$id,$points,$key]);$pdo->prepare('UPDATE customers SET points=points+? WHERE id=?')->execute([$points,$id]);$pdo->commit();Auth::audit('customer.points_adjusted','customer',(string)$id,['points'=>$points]);em_flash('ok','Pontos ajustados.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();em_flash('error',$e->getMessage());}em_go('customers');
    }
}
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=$pdo->prepare('SELECT * FROM customers WHERE id=? AND tenant_id=?');$s->execute([$editId,$tenantId]);$edit=$s->fetch()?:null;}
$q=trim((string)($_GET['q']??''));$sql='SELECT c.*,(SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id AND o.payment_status="paid") paid_orders,(SELECT COALESCE(SUM(o.total_cents),0) FROM orders o WHERE o.customer_id=c.id AND o.payment_status="paid") lifetime_value FROM customers c WHERE c.tenant_id=?';$args=[$tenantId];if($q!==''){$sql.=' AND (c.name LIKE ? OR c.phone LIKE ? OR c.email LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$sql.=' ORDER BY c.id DESC LIMIT 200';$s=$pdo->prepare($sql);$s->execute($args);$customers=$s->fetchAll();
em_header('Clientes e pontos','customers');
?><div class="grid" style="grid-template-columns:minmax(280px,1fr) minmax(0,2fr)"><section class="card"><h2><?= $edit?'Editar cliente':'Novo cliente' ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="customer-save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label class="span-2">Nome<input name="name" required value="<?= Security::e($edit['name']??'') ?>"></label><label>Telefone<input name="phone" value="<?= Security::e($edit['phone']??'') ?>"></label><label>E-mail<input type="email" name="email" value="<?= Security::e($edit['email']??'') ?>"></label><label class="span-2">Documento<input name="document" value="<?= Security::e($edit['document']??'') ?>"></label><button class="primary span-2">Salvar</button></form></section><section class="card"><form method="get" class="actions"><input type="hidden" name="route" value="customers"><input name="q" value="<?= Security::e($q) ?>" placeholder="Buscar nome, telefone ou e-mail"><button class="secondary">Buscar</button></form><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Pedidos pagos</th><th>Valor histórico</th><th>Pontos</th><th>Ações</th></tr></thead><tbody><?php foreach($customers as $c):?><tr><td><strong><?= Security::e($c['name']) ?></strong><br><span class="muted"><?= Security::e($c['phone']??'') ?> <?= Security::e($c['email']??'') ?></span></td><td><?= (int)$c['paid_orders'] ?></td><td><?= em_money($c['lifetime_value']) ?></td><td><strong><?= (int)$c['points'] ?></strong><form method="post" class="actions" style="margin-top:6px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="points-adjust"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><input type="number" name="points" style="width:90px" placeholder="+/-"><button class="secondary">Ajustar</button></form></td><td><a class="button secondary" href="/?route=customers&edit=<?= (int)$c['id'] ?>">Editar</a></td></tr><?php endforeach;?></tbody></table></div></section></div><?php em_footer();
