<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\OrderService;

Auth::requirePermission('orders.delivery');$tenantId=em_require_tenant();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');$target=$action==='pickup'?'out_for_delivery':($action==='delivered'?'completed':'');if($target==='')exit('Ação inválida.');try{(new OrderService())->changeStatus($id,$target,'delivery');em_flash('ok','Pedido #'.$id.' atualizado.');}catch(Throwable $e){em_flash('error',$e->getMessage());}em_go('delivery');
}
$sql='SELECT o.*,c.name customer_name,c.phone customer_phone,u.name delivery_name FROM orders o LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN users u ON u.id=o.assigned_delivery_user_id WHERE o.tenant_id=? AND o.channel="delivery" AND o.status IN ("ready","out_for_delivery","completed")';$args=[$tenantId];if(Auth::role()==='delivery'){$sql.=' AND o.assigned_delivery_user_id=?';$args[]=Auth::id();}$sql.=' ORDER BY CASE WHEN o.status="out_for_delivery" THEN 0 WHEN o.status="ready" THEN 1 ELSE 2 END,o.id DESC LIMIT 100';$s=$pdo->prepare($sql);$s->execute($args);$orders=$s->fetchAll();
em_header('Entregas','delivery');
?><div class="section-head"><p class="muted"><?= Auth::role()==='delivery'?'Somente pedidos atribuídos a você. Pagamento não pode ser confirmado por esta tela.':'Visão operacional das entregas.' ?></p><span class="badge"><?= count($orders) ?> pedidos</span></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr))"><?php foreach($orders as $o):?><article class="card"><div class="section-head"><div><h2>#<?= (int)$o['id'] ?></h2><strong><?= Security::e($o['customer_name']??'Cliente') ?></strong></div><span class="badge"><?= Security::e($o['status']) ?></span></div><p><?= Security::e($o['customer_phone']??'') ?><br><strong>Endereço:</strong> <?= nl2br(Security::e($o['delivery_address']??'')) ?></p><p><strong>Total:</strong> <?= em_money($o['total_cents']) ?><br><strong>Pagamento:</strong> <span class="badge"><?= Security::e($o['payment_status']) ?></span><?php if(Auth::role()!=='delivery'):?><br><strong>Entregador:</strong> <?= Security::e($o['delivery_name']??'Não atribuído') ?><?php endif;?></p><?php if($o['notes']):?><div class="alert">Obs.: <?= Security::e($o['notes']) ?></div><?php endif;?><?php if($o['status']==='ready'):?><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="id" value="<?= (int)$o['id'] ?>"><input type="hidden" name="action" value="pickup"><button class="primary" style="width:100%">Saiu para entrega</button></form><?php elseif($o['status']==='out_for_delivery'):?><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="id" value="<?= (int)$o['id'] ?>"><input type="hidden" name="action" value="delivered"><button class="primary" style="width:100%"<?= $o['payment_status']!=='paid'?' disabled title="Pagamento precisa estar confirmado pelo servidor"':'' ?>>Concluir entrega</button></form><?php else:?><div class="alert ok">Entrega concluída.</div><?php endif;?></article><?php endforeach;?></div><?php if(!$orders):?><section class="card"><h2>Nenhuma entrega na fila</h2><p class="muted">Pedidos atribuídos aparecerão aqui quando estiverem prontos.</p></section><?php endif;?><?php em_footer();
