<?php

declare(strict_types=1);
use EventMenu\Core\Auth;use EventMenu\Core\Security;use EventMenu\Services\OperatingUnitService;use EventMenu\Services\OrderService;use EventMenu\Services\WorkShiftService;use EventMenu\Services\DeliveryTrackingService;
Auth::requirePermission('orders.delivery');$tenantId=em_require_tenant();try{$unit=(new OperatingUnitService())->requireCurrent();}catch(Throwable$e){em_header('Entregas','delivery');?><div class="alert error"><?=Security::e($e->getMessage())?></div><?php em_footer();return;}$unitId=(int)$unit['id'];$shift=null;try{$shift=(new WorkShiftService())->current();}catch(Throwable){}
if(Auth::role()==='delivery'&&$shift&&$shift['unit_id']!==null&&(int)$shift['unit_id']!==$unitId){em_header('Entregas','delivery');?><div class="alert error">Seu turno de entrega está aberto em outra unidade.</div><?php em_footer();return;}
if($_SERVER['REQUEST_METHOD']==='POST'){em_post_csrf();$id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');try{if($action==='tracking'){$token=(new DeliveryTrackingService())->publicToken($tenantId,$id);em_flash('ok','Link do cliente: '.rtrim((string)env('APP_URL',''),'/').'/rastreio.php?t='.$token);}else{$target=$action==='pickup'?'out_for_delivery':($action==='delivered'?'completed':'');if($target==='')throw new RuntimeException('Ação inválida.');(new OrderService())->changeStatus($id,$target,'delivery');em_flash('ok','Pedido #'.$id.' atualizado.');}}catch(Throwable$e){em_flash('error',$e->getMessage());}em_go('delivery');}
$sql='SELECT o.*,c.name customer_name,c.phone customer_phone,u.name delivery_name,l.latitude live_lat,l.longitude live_lng,l.accuracy_m live_accuracy,l.updated_at live_updated FROM orders o LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN users u ON u.id=o.assigned_delivery_user_id LEFT JOIN delivery_live_locations l ON l.tenant_id=o.tenant_id AND l.order_id=o.id WHERE o.tenant_id=? AND o.unit_id=? AND o.channel="delivery" AND o.status IN ("ready","out_for_delivery","completed")';$args=[$tenantId,$unitId];if(Auth::role()==='delivery'){$sql.=' AND o.assigned_delivery_user_id=?';$args[]=Auth::id();}$sql.=' ORDER BY CASE WHEN o.status="out_for_delivery" THEN 0 WHEN o.status="ready" THEN 1 ELSE 2 END,o.id DESC LIMIT 100';$s=$pdo->prepare($sql);$s->execute($args);$orders=$s->fetchAll();$ready=count(array_filter($orders,fn($o)=>$o['status']==='ready'));$onRoute=count(array_filter($orders,fn($o)=>$o['status']==='out_for_delivery'));$done=count(array_filter($orders,fn($o)=>$o['status']==='completed'));
em_header('Entregas','delivery');?>
<section class="page-hero"><div><span class="eyebrow">DELIVERY · <?=Security::e($unit['name'])?></span><h2>Entregas e GPS ao vivo</h2><p><?=Auth::role()==='delivery'?'Somente seus pedidos. O GPS é compartilhado apenas enquanto a rota estiver ativa.':'Acompanhe saída, posição do entregador e conclusão das entregas.'?></p></div><div class="hero-actions"><a class="button secondary" href="<?=Security::e(app_url('?route=orders&channel=delivery'))?>">Pedidos</a></div></section>
<section class="grid dashboard-metrics"><div class="card metric"><span class="muted">Prontos</span><strong><?=$ready?></strong></div><div class="card metric"><span class="muted">Em rota</span><strong><?=$onRoute?></strong></div><div class="card metric"><span class="muted">Concluídos</span><strong><?=$done?></strong></div><div class="card metric"><span class="muted">Unidade</span><strong style="font-size:20px"><?=Security::e($unit['name'])?></strong></div></section>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));margin-top:18px"><?php foreach($orders as$o):?><article class="card"><div class="section-head"><div><span class="eyebrow"><?=Security::e(date('H:i',strtotime((string)$o['created_at'])))?></span><h2>#<?=(int)$o['id']?></h2><strong><?=Security::e($o['customer_name']??'Cliente')?></strong></div><span class="status-pill <?=$o['status']==='completed'?'active':''?>"><?=Security::e($o['status'])?></span></div><p><?=Security::e($o['customer_phone']??'')?><br><strong>Endereço:</strong> <?=nl2br(Security::e($o['delivery_address']??''))?></p><p><strong>Total:</strong> <?=em_money($o['total_cents'])?><br><strong>Pagamento:</strong> <span class="badge"><?=Security::e($o['payment_status'])?></span><?php if(Auth::role()!=='delivery'):?><br><strong>Entregador:</strong> <?=Security::e($o['delivery_name']??'Não atribuído')?><?php endif;?></p>
<?php if($o['status']==='out_for_delivery'):?><div class="alert <?=$o['live_lat']!==null?'ok':''?>"><strong>GPS:</strong> <?=$o['live_lat']!==null?'Localização recebida · '.Security::e((string)$o['live_updated']):'Aguardando sinal do celular do entregador'?><?php if($o['live_lat']!==null):?><br><a target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat=<?=rawurlencode((string)$o['live_lat'])?>&mlon=<?=rawurlencode((string)$o['live_lng'])?>#map=17/<?=rawurlencode((string)$o['live_lat'])?>/<?=rawurlencode((string)$o['live_lng'])?>">Abrir posição no mapa</a><?php endif;?></div><form method="post"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="id" value="<?=(int)$o['id']?>"><input type="hidden" name="action" value="tracking"><button class="secondary" style="width:100%">Gerar link de acompanhamento do cliente</button></form><?php endif;?>
<?php if($o['notes']):?><div class="alert">Obs.: <?=Security::e($o['notes'])?></div><?php endif;?><?php if($o['status']==='ready'):?><form method="post"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="id" value="<?=(int)$o['id']?>"><input type="hidden" name="action" value="pickup"><button class="primary" style="width:100%">Saiu para entrega</button></form><?php elseif($o['status']==='out_for_delivery'):?><form method="post"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="id" value="<?=(int)$o['id']?>"><input type="hidden" name="action" value="delivered"><button class="primary" style="width:100%"<?=$o['payment_status']!=='paid'?' disabled':''?>>Concluir entrega</button></form><?php else:?><div class="alert ok">Entrega concluída.</div><?php endif;?></article><?php endforeach;?></div><?php if(!$orders):?><section class="card" style="margin-top:18px"><h2>Nenhuma entrega na fila</h2></section><?php endif;?>
<?php if($onRoute>0):?><script>setTimeout(()=>location.reload(),15000);</script><?php endif;?><?php em_footer();