<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use EventMenu\Core\Security;
use EventMenu\Services\EventProfessionalService;

Auth::requirePermission('events.manage');$tenantId=em_require_tenant();$eventId=(int)($_GET['id']??$_POST['event_id']??0);if($eventId<1)em_go('events');$service=new EventProfessionalService();
$section=(string)($_GET['section']??$_POST['section']??'overview');if(!in_array($section,['overview','tickets','page','marketing','operation','audit'],true))$section='overview';

if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='public-settings'){$service->savePublicSettings($eventId,$_POST);em_flash('ok','Página pública e capacidade atualizadas.');$section='page';}
        elseif($action==='type-save'){$service->saveTicketType($eventId,$_POST);em_flash('ok','Tipo de ingresso salvo.');$section='tickets';}
        elseif($action==='batch-save'){
            $name=mb_substr(trim((string)($_POST['name']??'')),0,160);$price=(int)round((float)str_replace(',','.',(string)($_POST['price']??'0'))*100);$qty=max(1,(int)($_POST['quantity_total']??1));$typeId=(int)($_POST['ticket_type_id']??0);$start=trim((string)($_POST['sales_start']??''));$end=trim((string)($_POST['sales_end']??''));$start=$start?str_replace('T',' ',$start):null;$end=$end?str_replace('T',' ',$end):null;
            if($name===''||$price<0)throw new RuntimeException('Informe nome e preço válidos do lote.');if($start&&strtotime($start)===false||$end&&strtotime($end)===false||($start&&$end&&strtotime($end)<=strtotime($start)))throw new RuntimeException('Período de venda inválido.');
            Database::transaction(function(PDO$tx)use($eventId,$tenantId,$name,$price,$qty,$typeId,$start,$end):void{$e=$tx->prepare('SELECT status FROM events WHERE id=? AND tenant_id=?');$e->execute([$eventId,$tenantId]);$status=$e->fetchColumn();if(!$status)throw new RuntimeException('Evento inválido.');if($status==='cancelled')throw new RuntimeException('Evento cancelado não aceita novos lotes.');if($typeId){$t=$tx->prepare('SELECT id FROM ticket_types WHERE id=? AND event_id=? AND tenant_id=? AND active=1');$t->execute([$typeId,$eventId,$tenantId]);if(!$t->fetchColumn())throw new RuntimeException('Tipo de ingresso inválido.');}$s=$tx->prepare('INSERT INTO ticket_batches (event_id,ticket_type_id,name,price_cents,quantity_total,sales_start,sales_end,active) VALUES (?,?,?,?,?,?,?,1)');$s->execute([$eventId,$typeId?:null,$name,$price,$qty,$start,$end]);});
            Auth::audit('ticket_batch.saved','event',(string)$eventId,['name'=>$name,'quantity_total'=>$qty,'price_cents'=>$price]);em_flash('ok','Lote criado.');$section='tickets';
        }
        elseif($action==='batch-type'){$service->setBatchType($eventId,(int)($_POST['batch_id']??0),(int)($_POST['ticket_type_id']??0)?:null);em_flash('ok','Tipo vinculado ao lote.');$section='tickets';}
        elseif($action==='promoter-link'){$raw=trim((string)($_POST['commission_percent']??''));$commission=$raw===''?null:(float)str_replace(',','.',$raw);$service->linkPromoter($eventId,(int)($_POST['promoter_id']??0),$commission,true);em_flash('ok','Promotor vinculado ao evento.');$section='marketing';}
        elseif($action==='coupon-link'){$service->linkCoupon($eventId,(int)($_POST['coupon_id']??0),true);em_flash('ok','Cupom vinculado ao evento.');$section='marketing';}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable$e){em_flash('error',$e->getMessage());}
    em_go('event-admin',['id'=>$eventId,'section'=>$section]);
}

try{$d=$service->dashboard($eventId);}catch(Throwable$e){em_flash('error',$e->getMessage());em_go('events');}$event=$d['event'];$types=$d['types'];$batches=$d['batches'];$ticketStats=$d['ticket_stats'];$sales=$d['sales_stats'];
$p=$pdo->prepare('SELECT id,name,code,commission_percent FROM promoters WHERE tenant_id=? AND active=1 ORDER BY name');$p->execute([$tenantId]);$allPromoters=$p->fetchAll();$c=$pdo->prepare('SELECT id,code,type,value FROM coupons WHERE tenant_id=? AND active=1 ORDER BY code');$c->execute([$tenantId]);$allCoupons=$c->fetchAll();
$used=(int)($ticketStats['sold']??0)+(int)($ticketStats['reserved']??0);$capacity=$event['capacity_total']!==null?(int)$event['capacity_total']:null;$remaining=$capacity!==null?max(0,$capacity-$used):null;$sold=(int)($ticketStats['sold']??0);$checkins=(int)($ticketStats['checkins']??0);$checkinPct=$sold>0?(int)round($checkins*100/$sold):0;$publicUrl=app_url('evento.php?evento='.urlencode((string)$event['slug']));
$statusLabels=['draft'=>'Rascunho','published'=>'Publicado','closed'=>'Encerrado','cancelled'=>'Cancelado'];
$tabs=['overview'=>'Visão geral','tickets'=>'Ingressos e lotes','page'=>'Página pública','marketing'=>'Promoção e cupons','operation'=>'Operação e check-in','audit'=>'Auditoria'];

em_header('Evento · '.$event['name'],'events');
?>
<section class="page-hero"><div><span class="eyebrow">GESTÃO DO EVENTO</span><h2><?= Security::e($event['name']) ?></h2><p><?= Security::e(date('d/m/Y · H:i',strtotime((string)$event['starts_at']))) ?><?= $event['venue']?' · '.Security::e($event['venue']):'' ?> · <strong><?= Security::e($statusLabels[$event['status']]??$event['status']) ?></strong></p></div><div class="hero-actions"><a class="button primary" target="_blank" rel="noopener" href="<?= Security::e($publicUrl) ?>">Ver página pública</a><a class="button secondary" href="<?= Security::e(app_url('?route=events&edit='.$eventId)) ?>">Editar dados básicos</a><a class="button secondary" href="<?= Security::e(app_url('?route=events')) ?>">Todos os eventos</a></div></section>
<nav class="subtabs" style="margin-bottom:18px"><?php foreach($tabs as$key=>$label):?><a class="<?= $section===$key?'active':'' ?>" href="<?= Security::e(app_url('?route=event-admin&id='.$eventId.'&section='.$key)) ?>"><?= Security::e($label) ?></a><?php endforeach;?></nav>

<?php if($section==='overview'):?>
<section class="metric-grid"><div class="metric-card"><span>Receita confirmada</span><strong><?= em_money((int)($sales['revenue']??0)) ?></strong><small><?= (int)($sales['orders_count']??0) ?> pedidos pagos</small></div><div class="metric-card"><span>Ingressos vendidos</span><strong><?= $sold ?></strong><small><?= (int)($ticketStats['reserved']??0) ?> reservados</small></div><div class="metric-card"><span>Check-ins</span><strong><?= $checkins ?></strong><small><?= $checkinPct ?>% dos pagos</small></div><div class="metric-card"><span>Capacidade restante</span><strong><?= $remaining===null?'∞':$remaining ?></strong><small><?= $capacity===null?'sem limite definido':'de '.$capacity ?></small></div></section>
<div class="grid" style="grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:16px;margin-top:18px"><section class="card"><div class="section-head"><div><span class="eyebrow">PRÓXIMOS PASSOS</span><h2>Preparação do evento</h2></div></div><?php $checks=[['Página publicada',$event['status']==='published','page'],['Tipos de ingresso cadastrados',count($types)>0,'tickets'],['Lotes de venda cadastrados',count($batches)>0,'tickets'],['Capacidade definida',$capacity!==null,'page'],['Promotores configurados',count($d['promoters'])>0,'marketing'],['Cupons do evento configurados',count($d['coupons'])>0,'marketing']];foreach($checks as[$label,$ok,$target]):?><div class="list-row"><div><strong><?= $ok?'✓':'○' ?> <?= Security::e($label) ?></strong></div><a class="button secondary compact" href="<?= Security::e(app_url('?route=event-admin&id='.$eventId.'&section='.$target)) ?>"><?= $ok?'Revisar':'Configurar' ?></a></div><?php endforeach;?></section><aside class="card"><span class="eyebrow">ATALHOS</span><h2>Operação</h2><div class="actions" style="display:grid;margin-top:14px"><a class="button primary" href="<?= Security::e(app_url('?route=tickets')) ?>">Abrir check-in</a><a class="button secondary" href="<?= Security::e(app_url('?route=guests')) ?>">Lista de convidados</a><a class="button secondary" href="<?= Security::e(app_url('?route=reports')) ?>">Relatórios</a><a class="button secondary" href="<?= Security::e(app_url('?route=payments')) ?>">Pagamentos</a></div></aside></div>
<?php endif;?>

<?php if($section==='tickets'):?>
<div class="grid" style="grid-template-columns:minmax(300px,.8fr) minmax(0,1.2fr);gap:16px"><section class="card"><span class="eyebrow">TIPOS DE INGRESSO</span><h2>Pista, VIP, camarote...</h2><p class="muted">O tipo define área e capacidade. O lote define preço e período de venda.</p><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="type-save"><input type="hidden" name="event_id" value="<?= $eventId ?>"><input type="hidden" name="section" value="tickets"><label class="span-2">Nome<input name="name" required placeholder="Ex.: Pista Premium"></label><label>Área de acesso<input name="access_area" placeholder="Setor/portão"></label><label>Capacidade<input type="number" name="capacity_total" min="1" placeholder="Opcional"></label><label>Ordem<input type="number" name="sort_order" value="0"></label><label class="checkbox"><input type="checkbox" name="active" checked> Ativo</label><label class="span-2">Descrição<textarea name="description"></textarea></label><button class="primary span-2">Criar tipo</button></form><?php if($types):?><div style="margin-top:18px"><?php foreach($types as$t):?><div class="list-row"><div><strong><?= Security::e($t['name']) ?></strong><small><?= Security::e($t['access_area']??'Sem área') ?> · <?= (int)$t['used_count'] ?> usado(s)<?= $t['capacity_total']!==null?' de '.(int)$t['capacity_total']:'' ?></small></div><span class="status-pill <?= $t['active']?'active':'cancelled' ?>"><?= $t['active']?'Ativo':'Inativo' ?></span></div><?php endforeach;?></div><?php endif;?></section>
<section class="card"><span class="eyebrow">LOTES DE VENDA</span><h2>Preço, quantidade e período</h2><form method="post" class="form-grid" style="margin-bottom:18px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="batch-save"><input type="hidden" name="event_id" value="<?= $eventId ?>"><input type="hidden" name="section" value="tickets"><label>Tipo<select name="ticket_type_id"><option value="0">Sem tipo específico</option><?php foreach($types as$t):?><option value="<?= (int)$t['id'] ?>"><?= Security::e($t['name']) ?></option><?php endforeach;?></select></label><label>Nome do lote<input name="name" required placeholder="1º lote"></label><label>Preço (R$)<input name="price" inputmode="decimal" required placeholder="50,00"></label><label>Quantidade<input type="number" name="quantity_total" min="1" required></label><label>Início da venda<input type="datetime-local" name="sales_start"></label><label>Fim da venda<input type="datetime-local" name="sales_end"></label><button class="primary span-2">Criar lote</button></form><?php if(!$batches):?><div class="alert">Nenhum lote criado. A venda só começa quando existir um lote ativo.</div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Lote</th><th>Tipo</th><th>Preço</th><th>Vendido</th><th>Reservado</th><th>Disponível</th></tr></thead><tbody><?php foreach($batches as$b):$available=max(0,(int)$b['quantity_total']-(int)$b['quantity_sold']-(int)$b['quantity_reserved']);?><tr><td><strong><?= Security::e($b['name']) ?></strong></td><td><?= Security::e($b['ticket_type_name']??'—') ?></td><td><?= em_money((int)$b['price_cents']) ?></td><td><?= (int)$b['quantity_sold'] ?></td><td><?= (int)$b['quantity_reserved'] ?></td><td><strong><?= $available ?></strong></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div>
<?php endif;?>

<?php if($section==='page'):?>
<div class="grid" style="grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:16px"><section class="card"><span class="eyebrow">PÁGINA PÚBLICA</span><h2>Identidade, capacidade e venda</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="public-settings"><input type="hidden" name="event_id" value="<?= $eventId ?>"><input type="hidden" name="section" value="page"><label class="span-2">Subtítulo público<input name="public_subtitle" value="<?= Security::e($event['public_subtitle']??'') ?>" placeholder="Uma noite inesquecível..."></label><label>Tipo do evento<input name="event_type" value="<?= Security::e($event['event_type']??'general') ?>" placeholder="show, festa, congresso..."></label><label>Capacidade total<input type="number" name="capacity_total" min="1" value="<?= Security::e((string)($event['capacity_total']??'')) ?>" placeholder="Sem limite"></label><label>Cor principal<input type="color" name="primary_color" value="<?= Security::e($event['primary_color']??'#6236df') ?>"></label><label>Cor secundária<input type="color" name="secondary_color" value="<?= Security::e($event['secondary_color']??'#20134f') ?>"></label><label>Cor do texto<input type="color" name="text_color" value="<?= Security::e($event['text_color']??'#252137') ?>"></label><label class="span-2">Link do mapa<input type="url" name="map_url" value="<?= Security::e($event['map_url']??'') ?>" placeholder="https://maps.google.com/..."></label><label>Latitude<input name="latitude" value="<?= Security::e((string)($event['latitude']??'')) ?>"></label><label>Longitude<input name="longitude" value="<?= Security::e((string)($event['longitude']??'')) ?>"></label><label class="checkbox"><input type="checkbox" name="sales_enabled"<?= em_checked($event['sales_enabled']??1) ?>> Venda online habilitada</label><label class="checkbox"><input type="checkbox" name="bar_enabled"<?= em_checked($event['bar_enabled']??1) ?>> Venda de produtos/bar habilitada</label><button class="primary span-2">Salvar página pública</button></form></section><aside class="card"><span class="eyebrow">PUBLICAÇÃO</span><h2>Link do evento</h2><p class="muted">Esse endereço pode ser divulgado diretamente ao público.</p><div class="public-link-box"><strong><?= Security::e($publicUrl) ?></strong></div><div class="actions" style="margin-top:12px"><a class="button primary" target="_blank" rel="noopener" href="<?= Security::e($publicUrl) ?>">Abrir página</a><button type="button" class="secondary" onclick="navigator.clipboard?.writeText(<?= Security::e(json_encode($publicUrl)) ?>);this.textContent='Copiado ✓'">Copiar link</button></div></aside></div>
<?php endif;?>

<?php if($section==='marketing'):?>
<div class="grid" style="grid-template-columns:1fr 1fr;gap:16px"><section class="card"><span class="eyebrow">PROMOTORES / AFILIADOS</span><h2>Comissão por evento</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="promoter-link"><input type="hidden" name="event_id" value="<?= $eventId ?>"><input type="hidden" name="section" value="marketing"><label class="span-2">Promotor<select name="promoter_id" required><option value="">Selecione</option><?php foreach($allPromoters as$p):?><option value="<?= (int)$p['id'] ?>"><?= Security::e($p['name'].' · '.$p['code']) ?></option><?php endforeach;?></select></label><label class="span-2">Comissão específica %<input name="commission_percent" inputmode="decimal" placeholder="Vazio = comissão padrão"></label><button class="primary span-2">Vincular promotor</button></form><?php foreach($d['promoters'] as$p):?><div class="list-row"><div><strong><?= Security::e($p['name']) ?></strong><small>Código <?= Security::e($p['code']) ?></small></div><strong><?= Security::e((string)($p['commission_percent']??$p['default_commission'])) ?>%</strong></div><?php endforeach;?></section><section class="card"><span class="eyebrow">CUPONS</span><h2>Descontos do evento</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="coupon-link"><input type="hidden" name="event_id" value="<?= $eventId ?>"><input type="hidden" name="section" value="marketing"><label class="span-2">Cupom<select name="coupon_id" required><option value="">Selecione</option><?php foreach($allCoupons as$c):?><option value="<?= (int)$c['id'] ?>"><?= Security::e($c['code']) ?></option><?php endforeach;?></select></label><button class="primary span-2">Vincular cupom</button></form><?php foreach($d['coupons'] as$c):?><div class="list-row"><div><strong><?= Security::e($c['code']) ?></strong><small><?= Security::e($c['type'].' · '.$c['value']) ?></small></div><span><?= (int)$c['uses_count'] ?> usos</span></div><?php endforeach;?></section></div>
<?php endif;?>

<?php if($section==='operation'):?>
<section class="metric-grid"><div class="metric-card"><span>Ingressos pagos</span><strong><?= $sold ?></strong></div><div class="metric-card"><span>Entradas validadas</span><strong><?= $checkins ?></strong></div><div class="metric-card"><span>Taxa de entrada</span><strong><?= $checkinPct ?>%</strong></div><div class="metric-card"><span>Aguardando entrada</span><strong><?= max(0,$sold-$checkins) ?></strong></div></section><div class="grid" style="grid-template-columns:repeat(3,1fr);gap:16px;margin-top:18px"><section class="card"><span class="eyebrow">PORTARIA</span><h2>Check-in</h2><p class="muted">Valide QR individual e bloqueie reutilização.</p><a class="button primary" href="<?= Security::e(app_url('?route=tickets')) ?>">Abrir check-in</a></section><section class="card"><span class="eyebrow">CONVIDADOS</span><h2>Lista de convidados</h2><p class="muted">Controle nomes, acessos e presença.</p><a class="button secondary" href="<?= Security::e(app_url('?route=guests')) ?>">Gerenciar convidados</a></section><section class="card"><span class="eyebrow">BAR / PRODUTOS</span><h2>Venda no evento</h2><p class="muted"><?= (int)($event['bar_enabled']??1)?'Habilitada para a operação do evento.':'Desabilitada na configuração pública.' ?></p><a class="button secondary" href="<?= Security::e(app_url('?route=pos')) ?>">Abrir PDV</a></section></div>
<?php endif;?>

<?php if($section==='audit'):?><section class="card"><div class="section-head"><div><span class="eyebrow">AUDITORIA</span><h2>Histórico do evento</h2></div><span class="muted"><?= count($d['audit']) ?> registros</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Ação</th><th>Usuário</th><th>Entidade</th><th>Dados</th></tr></thead><tbody><?php foreach($d['audit'] as$a):?><tr><td><?= Security::e($a['created_at']) ?></td><td><strong><?= Security::e($a['action']) ?></strong></td><td><?= Security::e($a['user_name']??'Sistema/cliente') ?></td><td><?= Security::e(($a['entity_type']??'').' '.($a['entity_id']??'')) ?></td><td><small><?= Security::e(mb_substr((string)($a['metadata']??''),0,180)) ?></small></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php em_footer();