<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\EventProfessionalService;

Auth::requirePermission('events.manage');$tenantId=em_require_tenant();$eventId=(int)($_GET['id']??$_POST['event_id']??0);if($eventId<1)em_go('events');$service=new EventProfessionalService();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='public-settings'){$service->savePublicSettings($eventId,$_POST);em_flash('ok','Página pública e capacidade atualizadas.');}
        elseif($action==='type-save'){$service->saveTicketType($eventId,$_POST);em_flash('ok','Tipo de ingresso salvo.');}
        elseif($action==='batch-type'){$service->setBatchType($eventId,(int)($_POST['batch_id']??0),(int)($_POST['ticket_type_id']??0)?:null);em_flash('ok','Tipo vinculado ao lote.');}
        elseif($action==='promoter-link'){$raw=trim((string)($_POST['commission_percent']??''));$commission=$raw===''?null:(float)str_replace(',','.',$raw);$service->linkPromoter($eventId,(int)($_POST['promoter_id']??0),$commission,true);em_flash('ok','Promotor vinculado ao evento.');}
        elseif($action==='coupon-link'){$service->linkCoupon($eventId,(int)($_POST['coupon_id']??0),true);em_flash('ok','Cupom vinculado ao evento.');}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable $e){em_flash('error',$e->getMessage());}
    em_go('event-admin',['id'=>$eventId]);
}
try{$d=$service->dashboard($eventId);}catch(Throwable $e){em_flash('error',$e->getMessage());em_go('events');}$event=$d['event'];$types=$d['types'];$batches=$d['batches'];$ticketStats=$d['ticket_stats'];$sales=$d['sales_stats'];
$p=$pdo->prepare('SELECT id,name,code,commission_percent FROM promoters WHERE tenant_id=? AND active=1 ORDER BY name');$p->execute([$tenantId]);$allPromoters=$p->fetchAll();$c=$pdo->prepare('SELECT id,code,type,value FROM coupons WHERE tenant_id=? AND active=1 ORDER BY code');$c->execute([$tenantId]);$allCoupons=$c->fetchAll();
$used=(int)($ticketStats['sold']??0)+(int)($ticketStats['reserved']??0);$capacity=$event['capacity_total']!==null?(int)$event['capacity_total']:null;$remaining=$capacity!==null?max(0,$capacity-$used):null;
em_header('Evento · '.$event['name'],'events');
?>
<section class="page-hero"><div><span class="eyebrow">ÁREA ADMINISTRATIVA DO EVENTO</span><h2><?= Security::e($event['name']) ?></h2><p><?= Security::e(date('d/m/Y H:i',strtotime($event['starts_at']))) ?> · <?= Security::e($event['venue']??'Local não informado') ?></p></div><div class="actions"><a class="button primary" target="_blank" rel="noopener" href="<?= Security::e(app_url('evento.php?evento='.urlencode($event['slug']))) ?>">Página pública</a><a class="button secondary" href="<?= Security::e(app_url('?route=events&edit='.$eventId)) ?>">Dados básicos / lotes</a></div></section>
<section class="grid" style="grid-template-columns:repeat(auto-fit,minmax(190px,1fr));margin-bottom:18px"><div class="card metric"><span class="muted">Receita confirmada</span><strong><?= em_money((int)($sales['revenue']??0)) ?></strong></div><div class="card metric"><span class="muted">Ingressos pagos</span><strong><?= (int)($ticketStats['sold']??0) ?></strong></div><div class="card metric"><span class="muted">Check-ins</span><strong><?= (int)($ticketStats['checkins']??0) ?></strong></div><div class="card metric"><span class="muted">Reservados</span><strong><?= (int)($ticketStats['reserved']??0) ?></strong></div><div class="card metric"><span class="muted">Capacidade restante</span><strong><?= $remaining===null?'Sem limite':$remaining ?></strong></div></section>
<div class="grid" style="grid-template-columns:minmax(320px,1fr) minmax(0,2fr)">
<section class="card"><span class="eyebrow">IDENTIDADE E OPERAÇÃO</span><h2>Página pública</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="public-settings"><input type="hidden" name="event_id" value="<?= $eventId ?>"><label class="span-2">Subtítulo público<input name="public_subtitle" value="<?= Security::e($event['public_subtitle']??'') ?>" placeholder="Uma noite inesquecível..."></label><label>Tipo do evento<input name="event_type" value="<?= Security::e($event['event_type']??'general') ?>" placeholder="show, festa, congresso..."></label><label>Capacidade total<input type="number" name="capacity_total" min="1" value="<?= Security::e((string)($event['capacity_total']??'')) ?>" placeholder="Sem limite"></label><label>Cor principal<input type="color" name="primary_color" value="<?= Security::e($event['primary_color']??'#f4b942') ?>"></label><label>Cor secundária<input type="color" name="secondary_color" value="<?= Security::e($event['secondary_color']??'#121925') ?>"></label><label>Cor do texto<input type="color" name="text_color" value="<?= Security::e($event['text_color']??'#f5f7fb') ?>"></label><label class="span-2">Link do mapa<input type="url" name="map_url" value="<?= Security::e($event['map_url']??'') ?>" placeholder="https://maps.google.com/..."></label><label>Latitude<input name="latitude" inputmode="decimal" value="<?= Security::e((string)($event['latitude']??'')) ?>"></label><label>Longitude<input name="longitude" inputmode="decimal" value="<?= Security::e((string)($event['longitude']??'')) ?>"></label><label class="checkbox"><input type="checkbox" name="sales_enabled"<?= em_checked($event['sales_enabled']??1) ?>> Venda online habilitada</label><label class="checkbox"><input type="checkbox" name="bar_enabled"<?= em_checked($event['bar_enabled']??1) ?>> Bar/produtos habilitados</label><button class="primary span-2">Salvar identidade e operação</button></form></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">TIPOS DE INGRESSO</span><h2>Áreas e capacidades</h2></div><span class="muted">separados dos lotes</span></div><form method="post" class="form-grid" style="margin-bottom:18px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="type-save"><input type="hidden" name="event_id" value="<?= $eventId ?>"><label>Nome<input name="name" required placeholder="Pista, VIP, Camarote..."></label><label>Área de acesso<input name="access_area" placeholder="Portão / setor"></label><label>Capacidade<input type="number" name="capacity_total" min="1" placeholder="Opcional"></label><label>Ordem<input type="number" name="sort_order" value="0"></label><label class="checkbox"><input type="checkbox" name="active" checked> Ativo</label><label class="span-2">Descrição<textarea name="description" maxlength="500"></textarea></label><button class="secondary span-2">Criar tipo de ingresso</button></form><?php if(!$types):?><div class="alert">Crie tipos como Pista, VIP ou Camarote. Os lotes continuam definindo preço e período de venda.</div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Tipo</th><th>Área</th><th>Uso</th><th>Capacidade</th><th>Status</th></tr></thead><tbody><?php foreach($types as$t):?><tr><td><strong><?= Security::e($t['name']) ?></strong></td><td><?= Security::e($t['access_area']??'—') ?></td><td><?= (int)$t['used_count'] ?></td><td><?= $t['capacity_total']!==null?(int)$t['capacity_total']:'Sem limite' ?></td><td><span class="status-pill <?= $t['active']?'active':'cancelled' ?>"><?= $t['active']?'Ativo':'Inativo' ?></span></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
</div>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">LOTES</span><h2>Vincular lote ao tipo de ingresso</h2></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Lote</th><th>Preço</th><th>Tipo atual</th><th>Vincular</th></tr></thead><tbody><?php foreach($batches as$b):?><tr><td><strong><?= Security::e($b['name']) ?></strong></td><td><?= em_money((int)$b['price_cents']) ?></td><td><?= Security::e($b['ticket_type_name']??'Sem tipo') ?></td><td><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="batch-type"><input type="hidden" name="event_id" value="<?= $eventId ?>"><input type="hidden" name="batch_id" value="<?= (int)$b['id'] ?>"><select name="ticket_type_id"><option value="0">Sem tipo</option><?php foreach($types as$t):?><option value="<?= (int)$t['id'] ?>"<?= em_selected($b['ticket_type_id']??0,$t['id']) ?>><?= Security::e($t['name']) ?></option><?php endforeach;?></select><button class="secondary">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="grid" style="grid-template-columns:1fr 1fr;margin-top:18px">
<section class="card"><div class="section-head"><div><span class="eyebrow">PROMOTORES / AFILIADOS</span><h2>Vinculados ao evento</h2></div></div><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="promoter-link"><input type="hidden" name="event_id" value="<?= $eventId ?>"><label class="span-2">Promotor<select name="promoter_id" required><option value="">Selecione</option><?php foreach($allPromoters as$p):?><option value="<?= (int)$p['id'] ?>"><?= Security::e($p['name'].' · '.$p['code'].' · padrão '.$p['commission_percent'].'%') ?></option><?php endforeach;?></select></label><label class="span-2">Comissão específica %<input name="commission_percent" inputmode="decimal" placeholder="Vazio = comissão padrão"></label><button class="secondary span-2">Vincular promotor</button></form><?php if($d['promoters']):?><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>Código</th><th>Comissão</th></tr></thead><tbody><?php foreach($d['promoters'] as$p):?><tr><td><?= Security::e($p['name']) ?></td><td><?= Security::e($p['code']) ?></td><td><?= Security::e((string)($p['commission_percent']??$p['default_commission'])) ?>%</td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">CUPONS DO EVENTO</span><h2>Restringir cupons</h2></div></div><p class="muted">Ao vincular pelo menos um cupom, somente os cupons vinculados serão aceitos neste evento.</p><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="coupon-link"><input type="hidden" name="event_id" value="<?= $eventId ?>"><label class="span-2">Cupom<select name="coupon_id" required><option value="">Selecione</option><?php foreach($allCoupons as$c):?><option value="<?= (int)$c['id'] ?>"><?= Security::e($c['code']) ?></option><?php endforeach;?></select></label><button class="secondary span-2">Vincular cupom</button></form><?php if($d['coupons']):?><div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Regra</th><th>Usos</th></tr></thead><tbody><?php foreach($d['coupons'] as$c):?><tr><td><strong><?= Security::e($c['code']) ?></strong></td><td><?= Security::e($c['type'].' · '.$c['value']) ?></td><td><?= (int)$c['uses_count'] ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
</div>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">AUDITORIA DO EVENTO</span><h2>Últimas ações</h2></div><span class="muted"><?= count($d['audit']) ?> registros</span></div><?php if(!$d['audit']):?><p class="muted">Nenhuma ação avançada registrada ainda.</p><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Usuário</th><th>Dados</th></tr></thead><tbody><?php foreach($d['audit'] as$a):?><tr><td><?= Security::e($a['created_at']) ?></td><td><?= Security::e($a['action']) ?></td><td><?= Security::e(($a['entity_type']??'').' '.($a['entity_id']??'')) ?></td><td><?= Security::e($a['user_name']??'Sistema/cliente') ?></td><td><small class="muted"><?= Security::e(mb_substr((string)($a['metadata']??''),0,180)) ?></small></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php em_footer();
