<?php

declare(strict_types=1);

use EventMenu\Core\Auth;

if(!Auth::can('exports.view')&&!Auth::can('reports.view')){http_response_code(403);exit('Acesso negado.');}$tenantId=em_require_tenant();$kind=(string)($_GET['kind']??'orders');$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['from']??''))?(string)$_GET['from']:date('Y-m-01');$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['to']??''))?(string)$_GET['to']:date('Y-m-d');$filename='eventmenu-'.$kind.'-'.$from.'-'.$to.'.csv';header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');$write=fn(array$r)=>fputcsv($out,$r,';');
if($kind==='orders'){$write(['Pedido','Canal','Status','Pagamento','Cliente','Subtotal','Desconto','Frete','Total','Data']);$s=$pdo->prepare('SELECT o.*,c.name customer_name FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.tenant_id=? AND DATE(o.created_at) BETWEEN ? AND ? ORDER BY o.id');$s->execute([$tenantId,$from,$to]);foreach($s->fetchAll()as$r)$write([$r['id'],$r['channel'],$r['status'],$r['payment_status'],$r['customer_name'],number_format($r['subtotal_cents']/100,2,',','.'),number_format($r['discount_cents']/100,2,',','.'),number_format($r['delivery_fee_cents']/100,2,',','.'),number_format($r['total_cents']/100,2,',','.'),$r['created_at']]);}
elseif($kind==='customers'){$write(['ID','Nome','E-mail','Telefone','Status','Pontos','Criado em']);$s=$pdo->prepare('SELECT * FROM customers WHERE tenant_id=? ORDER BY id');$s->execute([$tenantId]);foreach($s->fetchAll()as$r)$write([$r['id'],$r['name'],$r['email'],$r['phone'],$r['status']??'active',$r['points'],$r['created_at']]);}
elseif($kind==='tickets'){$write(['ID','Evento','Lote','Código','Status','Check-in','Criado em']);$s=$pdo->prepare('SELECT tk.*,e.name event_name,b.name batch_name FROM tickets tk JOIN events e ON e.id=tk.event_id JOIN ticket_batches b ON b.id=tk.batch_id WHERE tk.tenant_id=? ORDER BY tk.id');$s->execute([$tenantId]);foreach($s->fetchAll()as$r)$write([$r['id'],$r['event_name'],$r['batch_name'],$r['code'],$r['status'],$r['checked_in_at'],$r['created_at']]);}
elseif($kind==='stock'){$write(['ID','Produto','SKU','Estoque','Mínimo','Controlado','Status']);$s=$pdo->prepare('SELECT id,name,sku,stock_qty,min_stock_qty,track_stock,active FROM products WHERE tenant_id=? ORDER BY name');$s->execute([$tenantId]);foreach($s->fetchAll()as$r)$write([$r['id'],$r['name'],$r['sku'],$r['stock_qty'],$r['min_stock_qty'],$r['track_stock']?'Sim':'Não',$r['active']?'Ativo':'Inativo']);}
else{http_response_code(400);$write(['Tipo de exportação inválido']);}fclose($out);exit;
