<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\DiscountPolicyService;
use EventMenu\Services\FinanceService;
use EventMenu\Services\OperatingUnitService;

Auth::requirePermission('finance.view');$tenantId=em_require_tenant();$service=new FinanceService();$unitService=new OperatingUnitService();$canManage=Auth::can('finance.manage');
$moneyInput=static function(string$value):int{$v=str_replace(['R$',' ','.'],['','',''],trim($value));$v=str_replace(',','.',$v);return(int)round(((float)$v)*100);};
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();if(!$canManage){http_response_code(403);exit('Acesso negado.');}$action=(string)($_POST['action']??'');
    try{
        if($action==='entry-create'){$service->createEntry(['direction'=>(string)($_POST['direction']??'out'),'amount_cents'=>$moneyInput((string)($_POST['amount']??'0')),'description'=>(string)($_POST['description']??''),'competence_date'=>(string)($_POST['competence_date']??date('Y-m-d')),'due_date'=>(string)($_POST['due_date']??''),'status'=>(string)($_POST['status']??'open'),'unit_id'=>(int)($_POST['unit_id']??0),'event_id'=>(int)($_POST['event_id']??0),'category_id'=>(int)($_POST['category_id']??0),'account_id'=>(int)($_POST['account_id']??0),'notes'=>(string)($_POST['notes']??'')]);em_flash('ok','Lançamento financeiro criado.');}
        elseif($action==='entry-settle'){$service->settle((int)($_POST['id']??0),(int)($_POST['account_id']??0)?:null);em_flash('ok','Lançamento liquidado.');}
        elseif($action==='fee-rule'){$service->saveFeeRule((string)($_POST['provider']??''),(string)($_POST['payment_method']??'*'),(int)round(((float)str_replace(',','.',(string)($_POST['percent']??'0')))*100),(int)$moneyInput((string)($_POST['fixed']??'0')),(int)($_POST['settlement_days']??0),isset($_POST['active']));em_flash('ok','Regra de taxa atualizada.');}
        elseif($action==='discount-policy'){(new DiscountPolicyService())->save((int)round(((float)str_replace(',','.',(string)($_POST['cashier_percent']??'5')))*100),(int)round(((float)str_replace(',','.',(string)($_POST['manager_percent']??'20')))*100),(int)round(((float)str_replace(',','.',(string)($_POST['admin_percent']??'100')))*100),isset($_POST['require_reason']),isset($_POST['allow_percentage']));em_flash('ok','Política de descontos atualizada.');}
    }catch(Throwable$e){em_flash('error',$e->getMessage());}
    em_go('finance');
}
$from=(string)($_GET['from']??date('Y-m-01'));$to=(string)($_GET['to']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from))$from=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to))$to=date('Y-m-d');
$units=$unitService->availableForCurrentUser();$current=$unitService->current();$scope=(string)($_GET['scope']??'current');$unitIds=[];$scopeLabel='Todas as unidades';if($scope!=='all'||!in_array((string)Auth::role(),['admin','manager','super_admin'],true)){$selectedId=(int)($_GET['unit_id']??($current['id']??0));foreach($units as$u)if((int)$u['id']===$selectedId){$unitIds=[(int)$u['id']];$scopeLabel=(string)$u['name'];break;}if(!$unitIds&&$units){$unitIds=[(int)$units[0]['id']];$scopeLabel=(string)$units[0]['name'];}$scope='current';}
$data=$service->dashboard($from,$to,$unitIds);$ref=$service->referenceData();$summary=$data['summary'];$dre=$data['dre'];$policy=(new DiscountPolicyService())->get($tenantId);
em_header('Financeiro','finance');
?>
<section class="page-hero"><div><span class="eyebrow">GESTÃO FINANCEIRA · <?= Security::e($scopeLabel) ?></span><h2>Resultado, contas e fluxo financeiro</h2><p>Vendas, taxas, estornos, compras, comissões, despesas e recebíveis em um único livro financeiro.</p></div><div class="hero-actions"><a class="button secondary" href="<?= Security::e(app_url('?route=payments')) ?>">Transações</a><a class="button secondary" href="<?= Security::e(app_url('?route=reports')) ?>">Relatórios</a></div></section>
<section class="card"><form method="get" class="form-grid"><input type="hidden" name="route" value="finance"><label>De<input type="date" name="from" value="<?= Security::e($from) ?>"></label><label>Até<input type="date" name="to" value="<?= Security::e($to) ?>"></label><label class="span-2">Escopo<select name="scope"><?php foreach($units as$u):?><option value="current" data-unit="<?= (int)$u['id'] ?>"<?= count($unitIds)===1&&(int)$unitIds[0]===(int)$u['id']?' selected':'' ?>>Unidade · <?= Security::e($u['name']) ?></option><?php endforeach;?><?php if(count($units)>1&&in_array((string)Auth::role(),['admin','manager','super_admin'],true)):?><option value="all"<?= $scope==='all'?' selected':'' ?>>Consolidado · todas</option><?php endif;?></select><input type="hidden" name="unit_id" value="<?= count($unitIds)===1?(int)$unitIds[0]:0 ?>"></label><button class="primary span-2">Atualizar financeiro</button></form></section>
<script>(()=>{const s=document.querySelector('select[name="scope"]'),u=document.querySelector('input[name="unit_id"]');s?.addEventListener('change',()=>{const o=s.options[s.selectedIndex];u.value=o.dataset.unit||'0';});})();</script>
<section class="grid" style="margin-top:18px;grid-template-columns:repeat(auto-fit,minmax(180px,1fr))"><div class="card metric"><span class="muted">Entradas</span><strong><?= em_money($summary['income_cents']) ?></strong></div><div class="card metric"><span class="muted">Saídas</span><strong><?= em_money($summary['expense_cents']) ?></strong></div><div class="card metric"><span class="muted">Resultado</span><strong><?= em_money($summary['result_cents']) ?></strong></div><div class="card metric"><span class="muted">A receber vencido</span><strong><?= em_money($summary['overdue_receivable_cents']) ?></strong></div><div class="card metric"><span class="muted">A pagar vencido</span><strong><?= em_money($summary['overdue_payable_cents']) ?></strong></div></section>
<section class="grid" style="margin-top:18px;grid-template-columns:minmax(0,1.15fr) minmax(320px,.85fr)">
<div class="card"><div class="section-head"><div><span class="eyebrow">DRE GERENCIAL</span><h2>Resultado do período</h2></div></div><div class="table-wrap"><table><tbody><tr><th>Receita bruta</th><td><?= em_money($dre['gross_revenue_cents']) ?></td></tr><tr><th>(−) Descontos</th><td><?= em_money($dre['discounts_cents']) ?></td></tr><tr><th>(−) Estornos</th><td><?= em_money($dre['refunds_cents']) ?></td></tr><tr><th>Receita líquida</th><td><strong><?= em_money($dre['net_revenue_cents']) ?></strong></td></tr><tr><th>(−) Compras / CMV</th><td><?= em_money($dre['cogs_cents']) ?></td></tr><tr><th>Lucro bruto</th><td><strong><?= em_money($dre['gross_profit_cents']) ?></strong></td></tr><tr><th>(−) Taxas de pagamento</th><td><?= em_money($dre['payment_fees_cents']) ?></td></tr><tr><th>(−) Comissões</th><td><?= em_money($dre['commissions_cents']) ?></td></tr><tr><th>(−) Despesas operacionais</th><td><?= em_money($dre['operating_expense_cents']) ?></td></tr><tr><th>(−) Impostos</th><td><?= em_money($dre['taxes_cents']) ?></td></tr><tr><th>Resultado operacional</th><td><strong><?= em_money($dre['operating_result_cents']) ?></strong></td></tr></tbody></table></div></div>
<div class="card"><span class="eyebrow">PRÓXIMOS COMPROMISSOS</span><h2>Contas abertas</h2><?php if(!$data['open']):?><div class="empty-state">Nenhuma conta aberta.</div><?php endif;?><?php foreach(array_slice($data['open'],0,12)as$row):?><article class="gateway-device-card"><div><strong><?= Security::e($row['description']) ?></strong><span><?= $row['direction']==='in'?'A receber':'A pagar' ?> · <?= Security::e($row['due_date']??'Sem vencimento') ?></span><small><?= Security::e($row['category_name']??'Sem categoria') ?><?= !empty($row['unit_name'])?' · '.Security::e($row['unit_name']):'' ?></small></div><div><strong><?= em_money($row['net_cents']) ?></strong><?php if($canManage):?><form method="post" style="margin-top:6px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="entry-settle"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="secondary compact">Liquidar</button></form><?php endif;?></div></article><?php endforeach;?></div>
</section>
<?php if($canManage):?><details class="card" style="margin-top:18px" open><summary><strong>Novo lançamento financeiro</strong></summary><form method="post" class="form-grid" style="margin-top:16px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="entry-create"><label>Tipo<select name="direction"><option value="out">Despesa / conta a pagar</option><option value="in">Receita / conta a receber</option></select></label><label>Valor (R$)<input name="amount" inputmode="decimal" required></label><label class="span-2">Descrição<input name="description" required maxlength="255"></label><label>Competência<input type="date" name="competence_date" value="<?= date('Y-m-d') ?>" required></label><label>Vencimento<input type="date" name="due_date"></label><label>Unidade<select name="unit_id"><option value="0">Empresa / geral</option><?php foreach($units as$u):?><option value="<?= (int)$u['id'] ?>"<?= $current&&(int)$current['id']===(int)$u['id']?' selected':'' ?>><?= Security::e($u['name']) ?></option><?php endforeach;?></select></label><label>Evento<select name="event_id"><option value="0">Sem evento</option><?php foreach($ref['events'] as$e):?><option value="<?= (int)$e['id'] ?>"><?= Security::e($e['name']) ?></option><?php endforeach;?></select></label><label class="span-2">Categoria<select name="category_id"><option value="0">Sem categoria</option><?php foreach($ref['categories'] as$c):?><option value="<?= (int)$c['id'] ?>"><?= $c['direction']==='in'?'Entrada':'Saída' ?> · <?= Security::e($c['name']) ?></option><?php endforeach;?></select></label><label class="span-2">Observação<textarea name="notes"></textarea></label><button class="primary span-2">Salvar lançamento</button></form></details>
<details class="card" style="margin-top:18px"><summary><strong>Política de descontos</strong></summary><form method="post" class="form-grid" style="margin-top:16px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="discount-policy"><label>Caixa · automático até %<input name="cashier_percent" type="number" min="0" max="100" step="0.01" value="<?= Security::e(number_format(((int)$policy['cashier_auto_bps'])/100,2,'.','')) ?>"></label><label>Gerente · automático até %<input name="manager_percent" type="number" min="0" max="100" step="0.01" value="<?= Security::e(number_format(((int)$policy['manager_auto_bps'])/100,2,'.','')) ?>"></label><label>Administrador · automático até %<input name="admin_percent" type="number" min="0" max="100" step="0.01" value="<?= Security::e(number_format(((int)$policy['admin_auto_bps'])/100,2,'.','')) ?>"></label><label class="checkbox"><input type="checkbox" name="allow_percentage"<?= em_checked($policy['allow_percentage']) ?>> Permitir desconto em %</label><label class="checkbox span-2"><input type="checkbox" name="require_reason"<?= em_checked($policy['require_reason']) ?>> Exigir motivo para desconto</label><p class="muted span-2">Dentro do limite do cargo o desconto é aplicado imediatamente. Acima do limite, vira solicitação para gerente/administrador.</p><button class="secondary span-2">Salvar política</button></form></details>
<details class="card" style="margin-top:18px"><summary><strong>Taxas e prazo dos meios de pagamento</strong></summary><form method="post" class="form-grid" style="margin-top:16px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="fee-rule"><label>Provedor<select name="provider"><option value="pagbank">PagBank</option><option value="mercadopago">Mercado Pago</option><option value="stripe">Stripe</option><option value="manual">Dinheiro/manual</option></select></label><label>Método<select name="payment_method"><option value="*">Todos</option><option value="pix">PIX</option><option value="debit">Débito</option><option value="credit">Crédito</option><option value="card">Cartão</option><option value="cash">Dinheiro</option></select></label><label>Taxa %<input name="percent" type="number" min="0" max="100" step="0.01" value="0"></label><label>Taxa fixa (R$)<input name="fixed" inputmode="decimal" value="0,00"></label><label>Dias para recebimento<input name="settlement_days" type="number" min="0" max="365" value="0"></label><label class="checkbox"><input type="checkbox" name="active" checked> Regra ativa</label><button class="secondary span-2">Salvar regra</button></form><?php if($ref['fee_rules']):?><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>Provedor</th><th>Método</th><th>Taxa</th><th>Fixa</th><th>Prazo</th></tr></thead><tbody><?php foreach($ref['fee_rules'] as$r):?><tr><td><?= Security::e($r['provider']) ?></td><td><?= Security::e($r['payment_method']) ?></td><td><?= number_format(((int)$r['percent_bps'])/100,2,',','.') ?>%</td><td><?= em_money($r['fixed_cents']) ?></td><td><?= (int)$r['settlement_days'] ?> dia(s)</td></tr><?php endforeach;?></tbody></table></div><?php endif;?></details><?php endif;?>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">LIVRO FINANCEIRO</span><h2>Lançamentos do período</h2></div><span class="muted"><?= count($data['entries']) ?> registro(s)</span></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Unidade / evento</th><th>Status</th><th>Entrada</th><th>Saída</th></tr></thead><tbody><?php foreach($data['entries'] as$row):?><tr><td><?= Security::e($row['competence_date']) ?></td><td><strong><?= Security::e($row['description']) ?></strong><?php if((int)$row['fee_cents']>0):?><small class="muted">Taxa estimada: <?= em_money($row['fee_cents']) ?></small><?php endif;?></td><td><?= Security::e($row['category_name']??$row['entry_type']) ?></td><td><?= Security::e(trim(($row['unit_name']??'').' '.($row['event_name']??''))?:'Empresa') ?></td><td><?= Security::e($row['status']) ?><?= $row['due_date']?' · '.Security::e($row['due_date']):'' ?></td><td><?= $row['direction']==='in'?em_money($row['net_cents']):'—' ?></td><td><?= $row['direction']==='out'?em_money($row['net_cents']):'—' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php em_footer();
