<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

if(!Auth::can('payments.manage')&&!Auth::can('reports.view')){http_response_code(403);exit('Acesso negado.');}
em_require_tenant();
$links=[
 ['payments','Pagamentos','Consulte recebimentos, pendências, falhas e conciliação.','payments.manage','💳','primary'],
 ['cash','Caixa','Abertura, fechamento, sangrias, reforços e recebimentos presenciais.','payments.manage','💵','primary'],
 ['reports','Relatórios financeiros','Faturamento, canais, produtos, eventos e desempenho.','reports.view','📈','primary'],
 ['gateways','Gateways e NFC','Configuração técnica de credenciais, webhooks e dispositivos.','gateways.manage','⚙️','secondary'],
];
$tz=new DateTimeZone('UTC');$todayStart=(new DateTimeImmutable('today',$tz))->format('Y-m-d H:i:s');$monthStart=(new DateTimeImmutable('first day of this month 00:00:00',$tz))->format('Y-m-d H:i:s');
$s=$pdo->prepare('SELECT COALESCE(SUM(total_cents),0),COUNT(*) FROM orders WHERE tenant_id=? AND payment_status="paid" AND created_at>=?');$s->execute([Auth::tenantId(),$todayStart]);[$todayRevenue,$todayPaid]=$s->fetch(PDO::FETCH_NUM)?:[0,0];
$m=$pdo->prepare('SELECT COALESCE(SUM(total_cents),0),COUNT(*) FROM orders WHERE tenant_id=? AND payment_status="paid" AND created_at>=?');$m->execute([Auth::tenantId(),$monthStart]);[$monthRevenue,$monthPaid]=$m->fetch(PDO::FETCH_NUM)?:[0,0];
$p=$pdo->prepare('SELECT COUNT(*) FROM payments WHERE tenant_id=? AND status IN ("created","pending","authorized")');$p->execute([Auth::tenantId()]);$pending=(int)$p->fetchColumn();
$recent=$pdo->prepare('SELECT p.id,p.order_id,p.provider,p.status,p.amount_cents,p.created_at,o.channel,c.name customer_name FROM payments p LEFT JOIN orders o ON o.id=p.order_id LEFT JOIN customers c ON c.id=o.customer_id WHERE p.tenant_id=? ORDER BY p.id DESC LIMIT 12');$recent->execute([Auth::tenantId()]);$recent=$recent->fetchAll();
$cashOpen=0;try{$c=$pdo->prepare('SELECT COUNT(*) FROM cash_sessions WHERE tenant_id=? AND status="open"');$c->execute([Auth::tenantId()]);$cashOpen=(int)$c->fetchColumn();}catch(Throwable){}
em_header('Financeiro','finance-hub');
?>
<style>.finance-title{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:13px}.finance-title h2{margin:0;font-size:23px}.finance-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-bottom:15px}.finance-metric{border-radius:14px;border-top:3px solid #6d4aff}.finance-metric span{color:var(--muted);font-size:10px;font-weight:850;text-transform:uppercase}.finance-metric strong{display:block;font-size:23px;margin-top:7px}.finance-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-bottom:16px}.finance-card{text-decoration:none;color:inherit;border-radius:14px;position:relative;overflow:hidden}.finance-card i{font-style:normal;font-size:22px;display:block;margin-bottom:10px}.finance-card h3{margin:0 0 6px}.finance-card p{margin:0;min-height:48px}.finance-card.secondary{background:#faf9fd}.finance-card.secondary:before{content:'Configuração';position:absolute;right:10px;top:10px;font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#8c8797;font-weight:900}.finance-table th{background:#faf9fd}.finance-table td{vertical-align:middle}.provider{font-size:10px;text-transform:uppercase;font-weight:850;color:#665f72}.cash-state{font-size:10px;font-weight:850}.cash-state.open{color:#15803d}.cash-state.closed{color:#9a3412}@media(max-width:1050px){.finance-metrics{grid-template-columns:repeat(2,1fr)}.finance-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.finance-title{align-items:flex-start;flex-direction:column}.finance-metrics{grid-template-columns:1fr 1fr}.finance-grid{grid-template-columns:1fr}.finance-metric strong{font-size:19px}}</style>
<section class="finance-title"><div><h2>Financeiro</h2><p class="muted">Visão dos recebimentos e do caixa da operação.</p></div><span class="cash-state <?= $cashOpen?'open':'closed' ?>"><?= $cashOpen?'● Caixa aberto':'○ Nenhum caixa aberto' ?></span></section>
<section class="finance-metrics"><article class="card finance-metric"><span>Recebido hoje</span><strong><?= em_money($todayRevenue) ?></strong></article><article class="card finance-metric"><span>Recebido no mês</span><strong><?= em_money($monthRevenue) ?></strong></article><article class="card finance-metric"><span>Vendas pagas no mês</span><strong><?= (int)$monthPaid ?></strong></article><article class="card finance-metric"><span>Pagamentos pendentes</span><strong><?= $pending ?></strong></article></section>
<section class="finance-grid"><?php foreach($links as[$route,$title,$desc,$permission,$icon,$kind]):if(!Auth::can($permission))continue;?><a class="card finance-card <?= Security::e($kind) ?>" href="<?= Security::e(em_url('/?route='.$route)) ?>"><i><?= $icon ?></i><h3><?= Security::e($title) ?></h3><p class="muted"><?= Security::e($desc) ?></p></a><?php endforeach;?></section>
<section class="card"><div class="section-head"><div><h2>Últimos recebimentos</h2><p class="muted">Movimentações mais recentes registradas pelos gateways ou pelo caixa.</p></div><?php if(Auth::can('payments.manage')):?><a class="button secondary" href="<?= Security::e(em_url('/?route=payments')) ?>">Ver todos</a><?php endif;?></div><div class="table-wrap"><table class="table finance-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Origem</th><th>Forma</th><th>Status</th><th>Valor</th><th>Data UTC</th></tr></thead><tbody><?php foreach($recent as$r):?><tr><td><?= $r['order_id']?'#'.(int)$r['order_id']:'—' ?></td><td><?= Security::e($r['customer_name']??'Consumidor') ?></td><td><?= Security::e($r['channel']??'—') ?></td><td><span class="provider"><?= Security::e($r['provider']) ?></span></td><td><span class="badge"><?= Security::e(em_status_label($r['status'])) ?></span></td><td><strong><?= em_money((int)$r['amount_cents']) ?></strong></td><td><?= Security::e($r['created_at']) ?></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="7" class="muted">Nenhum recebimento registrado ainda.</td></tr><?php endif;?></tbody></table></div></section>
<?php em_footer();
