<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\FinanceService;
use EventMenu\Services\OperatingUnitService;
use EventMenu\Services\RecurringFinanceService;

Auth::requirePermission('finance.view');$tenantId=em_require_tenant();$finance=new FinanceService();$recurring=new RecurringFinanceService();$unitService=new OperatingUnitService();$canManage=Auth::can('finance.manage');
$moneyInput=static function(string$value):int{$raw=trim($value);if($raw==='')return 0;$raw=str_replace(['R$',' '],'',$raw);if(str_contains($raw,',')&&str_contains($raw,'.'))$raw=str_replace('.','',$raw);$raw=str_replace(',','.',$raw);return(int)round(((float)$raw)*100);};
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();if(!$canManage){http_response_code(403);exit('Acesso negado.');}$action=(string)($_POST['action']??'');
    try{
        if($action==='recurring-save'){$recurring->save((int)($_POST['id']??0)?:null,(string)($_POST['direction']??'out'),(string)($_POST['description']??''),$moneyInput((string)($_POST['amount']??'0')),(string)($_POST['frequency']??'monthly'),(int)($_POST['interval_count']??1),(string)($_POST['next_due_date']??''),(string)($_POST['end_date']??'')?:null,(int)($_POST['unit_id']??0)?:null,(int)($_POST['event_id']??0)?:null,(int)($_POST['account_id']??0)?:null,(int)($_POST['category_id']??0)?:null,isset($_POST['active']));em_flash('ok','Recorrência financeira salva.');}
        elseif($action==='recurring-toggle'){$recurring->setActive((int)($_POST['id']??0),(int)($_POST['active']??0)===1);em_flash('ok','Status da recorrência atualizado.');}
        elseif($action==='reconcile'){$finance->reconcileReceivable((int)($_POST['id']??0),$moneyInput((string)($_POST['actual_net']??'0')),(int)($_POST['account_id']??0)?:null,(string)($_POST['settled_date']??date('Y-m-d')),(string)($_POST['note']??''));em_flash('ok','Recebível conciliado com o valor efetivamente creditado.');}
        elseif($action==='account-save'){$finance->saveAccount((int)($_POST['id']??0)?:null,(string)($_POST['name']??''),(string)($_POST['account_type']??'bank'),(string)($_POST['provider']??''),(int)($_POST['unit_id']??0)?:null,$moneyInput((string)($_POST['opening_balance']??'0')),isset($_POST['active']));em_flash('ok','Conta financeira atualizada.');}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable$e){em_flash('error',$e->getMessage());}
    em_go('finance-advanced');
}
$units=$unitService->availableForCurrentUser();$current=$unitService->current();$unitIds=$current?[(int)$current['id']]:[];$from=date('Y-m-01');$to=date('Y-m-d');$data=$finance->dashboard($from,$to,$unitIds);$ref=$finance->referenceData();$templates=$recurring->templates();$accountTypes=['cash'=>'Caixa físico','bank'=>'Conta bancária','gateway'=>'Gateway / adquirente','wallet'=>'Carteira digital','other'=>'Outra'];$frequencies=['daily'=>'Diária','weekly'=>'Semanal','monthly'=>'Mensal','yearly'=>'Anual'];
em_header('Financeiro avançado','finance-advanced');
?>
<section class="page-hero"><div><span class="eyebrow">CONTROLE FINANCEIRO</span><h2>Recorrências, conciliação e eventos</h2><p>Automatize vencimentos, confira o valor líquido dos gateways e acompanhe o resultado financeiro de cada evento.</p></div><div class="hero-actions"><a class="button primary" href="<?= Security::e(app_url('?route=finance')) ?>">Voltar ao Financeiro</a></div></section>

<section class="grid" style="grid-template-columns:minmax(320px,.9fr) minmax(0,1.5fr);margin-top:18px">
<?php if($canManage):?><div class="card"><span class="eyebrow">RECORRÊNCIA</span><h2>Novo compromisso recorrente</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="recurring-save"><label>Tipo<select name="direction"><option value="out">Despesa</option><option value="in">Receita</option></select></label><label>Valor (R$)<input name="amount" inputmode="decimal" required></label><label class="span-2">Descrição<input name="description" required maxlength="255" placeholder="Ex.: Aluguel da unidade"></label><label>Frequência<select name="frequency"><?php foreach($frequencies as$key=>$label):?><option value="<?= Security::e($key) ?>"<?= $key==='monthly'?' selected':'' ?>><?= Security::e($label) ?></option><?php endforeach;?></select></label><label>Intervalo<input type="number" name="interval_count" min="1" max="60" value="1"><small class="muted">Ex.: 1 = todo mês; 2 = a cada 2 meses</small></label><label>Próximo vencimento<input type="date" name="next_due_date" value="<?= date('Y-m-d') ?>" required></label><label>Encerrar em<input type="date" name="end_date"><small class="muted">Opcional</small></label><label>Categoria<select name="category_id"><option value="0">Sem categoria</option><?php foreach($ref['categories'] as$c):?><option value="<?= (int)$c['id'] ?>"><?= $c['direction']==='out'?'Saída':'Entrada' ?> · <?= Security::e($c['name']) ?></option><?php endforeach;?></select></label><label>Conta preferencial<select name="account_id"><option value="0">Definir na liquidação</option><?php foreach($ref['accounts'] as$a):if(!(int)$a['active'])continue;?><option value="<?= (int)$a['id'] ?>"><?= Security::e($a['name']) ?></option><?php endforeach;?></select></label><label>Unidade<select name="unit_id"><option value="0">Empresa / geral</option><?php foreach($units as$u):?><option value="<?= (int)$u['id'] ?>"<?= $current&&(int)$current['id']===(int)$u['id']?' selected':'' ?>><?= Security::e($u['name']) ?></option><?php endforeach;?></select></label><label>Evento<select name="event_id"><option value="0">Sem evento</option><?php foreach($ref['events'] as$e):?><option value="<?= (int)$e['id'] ?>"><?= Security::e($e['name']) ?></option><?php endforeach;?></select></label><label class="checkbox span-2"><input type="checkbox" name="active" checked> Recorrência ativa</label><button class="primary span-2">Salvar recorrência</button></form></div><?php endif;?>
<div class="card"><div class="section-head"><div><span class="eyebrow">AUTOMAÇÕES FINANCEIRAS</span><h2>Recorrências cadastradas</h2></div><span class="muted"><?= count($templates) ?> regra(s)</span></div><?php if(!$templates):?><div class="empty-state">Nenhuma recorrência cadastrada.</div><?php endif;?><div class="table-wrap"><table><thead><tr><th>Descrição</th><th>Valor</th><th>Frequência</th><th>Próximo</th><th>Escopo</th><th>Status</th></tr></thead><tbody><?php foreach($templates as$r):?><tr><td><strong><?= Security::e($r['description']) ?></strong><br><small><?= Security::e($r['category_name']??'Sem categoria') ?></small></td><td><?= $r['direction']==='in'?'+':'−' ?> <?= em_money($r['amount_cents']) ?></td><td><?= Security::e($frequencies[$r['frequency']]??$r['frequency']) ?><?= (int)$r['interval_count']>1?' · a cada '.(int)$r['interval_count']:'' ?></td><td><?= Security::e($r['next_due_date']) ?><?= $r['end_date']?' até '.Security::e($r['end_date']):'' ?></td><td><?= Security::e($r['unit_name']??'Empresa') ?><?= $r['event_name']?' · '.Security::e($r['event_name']):'' ?></td><td><?php if($canManage):?><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="recurring-toggle"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="active" value="<?= (int)$r['active']?0:1 ?>"><button class="secondary compact"><?= (int)$r['active']?'Pausar':'Ativar' ?></button></form><?php else:?><?= (int)$r['active']?'Ativa':'Pausada' ?><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
</section>

<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">CONCILIAÇÃO</span><h2>Recebíveis de cartão / gateway</h2><p class="muted">Compare o líquido previsto com o valor realmente creditado. A diferença atualiza a taxa financeira, sem criar outra venda.</p></div><span class="muted"><?= count($data['reconciliation']) ?> pendente(s)</span></div><?php if(!$data['reconciliation']):?><div class="empty-state">Nenhum recebível aguardando conciliação.</div><?php endif;?><?php foreach($data['reconciliation'] as$row):?><article class="gateway-device-card"><div><strong><?= Security::e(ucfirst((string)$row['provider'])) ?> · Pedido #<?= (int)$row['order_id'] ?></strong><span>Bruto <?= em_money($row['payment_gross_cents']) ?> · líquido previsto <?= em_money($row['net_cents']) ?></span><small>Previsto para <?= Security::e($row['due_date']??'—') ?><?= $row['unit_name']?' · '.Security::e($row['unit_name']):'' ?><?= $row['provider_payment_id']?' · '.$row['provider_payment_id']:'' ?></small></div><?php if($canManage):?><form method="post" class="form-grid" style="min-width:min(100%,420px)"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="reconcile"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><label>Líquido recebido<input name="actual_net" value="<?= Security::e(number_format(((int)$row['net_cents'])/100,2,',','.')) ?>" inputmode="decimal" required></label><label>Data do crédito<input type="date" name="settled_date" value="<?= date('Y-m-d') ?>" required></label><label>Conta<select name="account_id"><option value="0">Conta já vinculada</option><?php foreach($ref['accounts'] as$a):if(!(int)$a['active'])continue;?><option value="<?= (int)$a['id'] ?>"<?= (int)($row['account_id']??0)===(int)$a['id']?' selected':'' ?>><?= Security::e($a['name']) ?></option><?php endforeach;?></select></label><label>Observação<input name="note" maxlength="500" placeholder="Opcional"></label><button class="primary span-2">Conciliar crédito</button></form><?php endif;?></article><?php endforeach;?></section>

<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">EVENTOS</span><h2>Resultado financeiro por evento</h2><p class="muted">Competência de <?= Security::e($from) ?> a <?= Security::e($to) ?><?= $current?' · '.Security::e($current['name']):'' ?>.</p></div></div><?php if(!$data['events']):?><div class="empty-state">Nenhum movimento financeiro de evento neste período.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Evento</th><th>Receita bruta</th><th>Receita líquida</th><th>CMV</th><th>Taxas</th><th>Comissões</th><th>Outras despesas</th><th>Resultado</th></tr></thead><tbody><?php foreach($data['events'] as$e):?><tr><td><strong><?= Security::e($e['name']) ?></strong><br><small><?= Security::e(substr((string)$e['starts_at'],0,16)) ?></small></td><td><?= em_money($e['gross_revenue_cents']) ?></td><td><?= em_money($e['net_revenue_cents']) ?></td><td><?= em_money($e['cogs_cents']) ?></td><td><?= em_money($e['fees_cents']) ?></td><td><?= em_money($e['commissions_cents']) ?></td><td><?= em_money($e['other_expenses_cents']) ?></td><td><strong><?= em_money($e['result_cents']) ?></strong></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>

<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">CONTAS FINANCEIRAS</span><h2>Editar contas, bancos e carteiras</h2></div></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr))"><?php foreach($ref['accounts'] as$a):?><details class="card" style="box-shadow:none"><summary><strong><?= Security::e($a['name']) ?></strong> · <?= (int)$a['active']?'Ativa':'Inativa' ?></summary><?php if($canManage):?><form method="post" class="form-grid" style="margin-top:14px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="account-save"><input type="hidden" name="id" value="<?= (int)$a['id'] ?>"><label class="span-2">Nome<input name="name" value="<?= Security::e($a['name']) ?>" required></label><label>Tipo<select name="account_type"><?php foreach($accountTypes as$key=>$label):?><option value="<?= Security::e($key) ?>"<?= em_selected($a['account_type'],$key) ?>><?= Security::e($label) ?></option><?php endforeach;?></select></label><label>Banco/provedor<input name="provider" value="<?= Security::e($a['provider']??'') ?>"></label><label>Saldo inicial<input name="opening_balance" value="<?= Security::e(number_format(((int)$a['opening_balance_cents'])/100,2,',','.')) ?>" inputmode="decimal"></label><label>Unidade<select name="unit_id"><option value="0">Empresa / compartilhada</option><?php foreach($units as$u):?><option value="<?= (int)$u['id'] ?>"<?= em_selected($a['unit_id']??0,$u['id']) ?>><?= Security::e($u['name']) ?></option><?php endforeach;?></select></label><label class="checkbox span-2"><input type="checkbox" name="active"<?= em_checked($a['active']) ?>> Conta ativa</label><button class="secondary span-2">Salvar conta</button></form><?php endif;?></details><?php endforeach;?><?php if(!$ref['accounts']):?><div class="empty-state">Cadastre uma conta na tela Financeiro.</div><?php endif;?></div></section>
<?php em_footer();
