<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

Auth::requirePermission('guests.manage');$tenantId=em_require_tenant();$ownPromoterId=null;if(Auth::role()==='promoter'){$x=$pdo->prepare('SELECT id FROM promoters WHERE tenant_id=? AND user_id=? AND active=1');$x->execute([$tenantId,Auth::id()]);$ownPromoterId=$x->fetchColumn();if(!$ownPromoterId){http_response_code(403);exit('Promotor sem cadastro vinculado.');}}
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    if($action==='save'){
        $eventId=(int)($_POST['event_id']??0);$e=$pdo->prepare('SELECT id FROM events WHERE id=? AND tenant_id=?');$e->execute([$eventId,$tenantId]);if(!$e->fetchColumn())exit('Evento inválido.');$name=trim((string)($_POST['name']??''));if($name==='')exit('Nome inválido.');$promoterId=$ownPromoterId?:((int)($_POST['promoter_id']??0)?:null);if($promoterId){$p=$pdo->prepare('SELECT id FROM promoters WHERE id=? AND tenant_id=? AND active=1');$p->execute([$promoterId,$tenantId]);if(!$p->fetchColumn())exit('Promotor inválido.');}
        $s=$pdo->prepare('INSERT INTO event_guests (tenant_id,event_id,promoter_id,name,document,phone,plus_ones,status,checkin_code) VALUES (?,?,?,?,?,?,?,"invited",?)');$s->execute([$tenantId,$eventId,$promoterId,$name,trim((string)($_POST['document']??''))?:null,trim((string)($_POST['phone']??''))?:null,max(0,(int)($_POST['plus_ones']??0)),sprintf('%s-%s',str_pad((string)$eventId,4,'0',STR_PAD_LEFT),strtoupper(bin2hex(random_bytes(6))))]);$id=(int)$pdo->lastInsertId();Auth::audit('guest.created','guest',(string)$id);em_flash('ok','Convidado adicionado.');em_go('guests');
    }
    if($action==='checkin'){
        $code=trim((string)($_POST['code']??''));$pdo->beginTransaction();try{$sql='SELECT * FROM event_guests WHERE tenant_id=? AND checkin_code=?';$args=[$tenantId,$code];if($ownPromoterId){$sql.=' AND promoter_id=?';$args[]=$ownPromoterId;}$sql.=' LIMIT 1 FOR UPDATE';$s=$pdo->prepare($sql);$s->execute($args);$g=$s->fetch();if(!$g)throw new RuntimeException('Convidado não encontrado.');if($g['status']==='checked_in')throw new RuntimeException('Convidado já realizou check-in.');if($g['status']!=='invited')throw new RuntimeException('Convite não está válido.');$pdo->prepare('UPDATE event_guests SET status="checked_in",checked_in_at=NOW(),checked_in_by=? WHERE id=?')->execute([Auth::id(),$g['id']]);$pdo->commit();Auth::audit('guest.checkin','guest',(string)$g['id']);em_flash('ok','Entrada liberada para '.$g['name'].'.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();em_flash('error',$e->getMessage());}em_go('guests');
    }
}
$events=$pdo->prepare('SELECT id,name,starts_at FROM events WHERE tenant_id=? AND status IN ("draft","published") ORDER BY starts_at DESC');$events->execute([$tenantId]);$events=$events->fetchAll();$promoters=$pdo->prepare('SELECT id,name,code FROM promoters WHERE tenant_id=? AND active=1 ORDER BY name');$promoters->execute([$tenantId]);$promoters=$promoters->fetchAll();
$sql='SELECT g.*,e.name event_name,p.name promoter_name FROM event_guests g JOIN events e ON e.id=g.event_id LEFT JOIN promoters p ON p.id=g.promoter_id WHERE g.tenant_id=?';$args=[$tenantId];if($ownPromoterId){$sql.=' AND g.promoter_id=?';$args[]=$ownPromoterId;}$sql.=' ORDER BY g.id DESC LIMIT 300';$s=$pdo->prepare($sql);$s->execute($args);$guests=$s->fetchAll();
em_header('Lista de convidados','guests');
?><div class="grid" style="grid-template-columns:minmax(280px,1fr) minmax(0,2fr)"><section class="card"><h2>Adicionar convidado</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="save"><label class="span-2">Evento<select name="event_id" required><?php foreach($events as $e):?><option value="<?= (int)$e['id'] ?>"><?= Security::e($e['name']) ?></option><?php endforeach;?></select></label><label class="span-2">Nome<input name="name" required></label><label>Telefone<input name="phone"></label><label>Documento<input name="document"></label><label>Acompanhantes<input type="number" min="0" name="plus_ones" value="0"></label><?php if(!$ownPromoterId):?><label>Promotor<select name="promoter_id"><option value="0">Sem promotor</option><?php foreach($promoters as $p):?><option value="<?= (int)$p['id'] ?>"><?= Security::e($p['name'].' · '.$p['code']) ?></option><?php endforeach;?></select></label><?php endif;?><button class="primary span-2">Adicionar</button></form><hr style="border-color:var(--line);margin:24px 0"><h2>Check-in convidado</h2><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="checkin"><label>Código<input name="code" required autocomplete="off"></label><button class="secondary" style="margin-top:8px">Validar entrada</button></form></section><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Convidado</th><th>Evento</th><th>Promotor</th><th>Acomp.</th><th>Status</th><th>Código</th></tr></thead><tbody><?php foreach($guests as $g):?><tr><td><strong><?= Security::e($g['name']) ?></strong><br><span class="muted"><?= Security::e($g['phone']??'') ?></span></td><td><?= Security::e($g['event_name']) ?></td><td><?= Security::e($g['promoter_name']??'—') ?></td><td><?= (int)$g['plus_ones'] ?></td><td><span class="badge"><?= Security::e($g['status']) ?></span></td><td><code><?= Security::e($g['checkin_code']) ?></code></td></tr><?php endforeach;?></tbody></table></div></section></div><?php em_footer();
