<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\ProductConfigurationService;
use EventMenu\Services\ProductCostService;
use EventMenu\Services\ProductMediaService;

Auth::requirePermission('catalog.manage');$tenantId=em_require_tenant();$productId=(int)($_GET['id']??$_POST['product_id']??0);if($productId<1)em_go('products');$config=new ProductConfigurationService();$costs=new ProductCostService();$media=new ProductMediaService();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='profile-save'){$config->saveProductProfile($productId,$_POST);em_flash('ok','Roteamento de produção salvo.');}
        elseif($action==='recipe-save'){$costs->saveRecipeItem($productId,(int)($_POST['ingredient_product_id']??0),(float)str_replace(',','.',(string)($_POST['quantity']??'0')),(float)str_replace(',','.',(string)($_POST['waste_percent']??'0')));em_flash('ok','Ficha técnica atualizada.');}
        elseif($action==='recipe-remove'){$costs->removeRecipeItem($productId,(int)($_POST['recipe_id']??0));em_flash('ok','Ingrediente removido da ficha técnica.');}
        elseif($action==='group-save'){$config->saveModifierGroup($productId,$_POST);em_flash('ok','Grupo de adicionais salvo.');}
        elseif($action==='option-save'){$config->saveModifierOption((int)($_POST['group_id']??0),$_POST);em_flash('ok','Opção/adicional salvo.');}
        elseif($action==='photo-upload'){$media->replace($tenantId,$productId,$_FILES['product_photo']??[]);Auth::audit('product.photo_updated','product',(string)$productId);em_flash('ok','Foto do produto atualizada.');}
        elseif($action==='photo-remove'){$media->remove($tenantId,$productId);Auth::audit('product.photo_removed','product',(string)$productId);em_flash('ok','Foto do produto removida.');}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable $e){em_flash('error',$e->getMessage());}
    em_go('product-config',['id'=>$productId]);
}
try{$setup=$config->productSetup($productId);$economics=$costs->economics($productId,$tenantId);}catch(Throwable $e){em_flash('error',$e->getMessage());em_go('products');}
$product=$setup['product'];$profile=$setup['profile'];$stations=$setup['stations'];$groups=$setup['groups'];$options=$setup['options'];
$all=$pdo->prepare('SELECT id,name,sku,track_stock,stock_qty,average_cost_cents FROM products WHERE tenant_id=? AND id<>? ORDER BY name');$all->execute([$tenantId,$productId]);$ingredients=$all->fetchAll();
em_header('Configuração avançada · '.$product['name'],'products');
?>
<section class="page-hero"><div><span class="eyebrow">PRODUTO PROFISSIONAL</span><h2><?= Security::e($product['name']) ?></h2><p>Adicionais, regras obrigatórias, ficha técnica, custo, margem e roteamento por estação ficam vinculados ao mesmo produto.</p></div><div class="actions"><a class="button secondary" href="<?= Security::e(app_url('?route=products&edit='.$productId)) ?>">Cadastro básico</a><a class="button secondary" href="<?= Security::e(app_url('?route=production')) ?>">Estações</a></div></section>
<section class="card" style="margin-bottom:18px"><div class="section-head"><div><span class="eyebrow">FOTO DO PRODUTO</span><h2>Imagem do cardápio</h2></div><span class="muted">JPG, PNG ou WebP · até 5 MB</span></div><div class="grid" style="grid-template-columns:minmax(180px,260px) minmax(280px,1fr);gap:18px;align-items:start"><div><?php if(!empty($product['image_url'])):?><img src="<?= Security::e($product['image_url']) ?>" alt="<?= Security::e($product['name']) ?>" style="width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:16px;border:1px solid var(--line);background:var(--surface)"><?php else:?><div class="muted" style="width:100%;aspect-ratio:1/1;display:grid;place-items:center;border-radius:16px;border:1px dashed var(--line);background:var(--surface)">Sem foto</div><?php endif;?></div><div><p class="muted">Envie a foto diretamente pelo EventMenu. Ela será salva por estabelecimento e usada no cardápio público, EventMenu GO e demais canais que consomem o catálogo.</p><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="photo-upload"><input type="hidden" name="product_id" value="<?= $productId ?>"><label class="span-2">Nova foto<input type="file" name="product_photo" accept="image/jpeg,image/png,image/webp" required></label><button class="primary span-2">Enviar foto</button></form><?php if(!empty($product['image_url'])):?><form method="post" style="margin-top:10px" onsubmit="return confirm('Remover a foto deste produto?')"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="photo-remove"><input type="hidden" name="product_id" value="<?= $productId ?>"><button class="secondary">Remover foto</button></form><?php endif;?></div></div></section>
<section class="grid" style="grid-template-columns:repeat(auto-fit,minmax(210px,1fr));margin-bottom:18px"><div class="card metric"><span class="muted">Preço de venda</span><strong><?= em_money($economics['price_cents']) ?></strong></div><div class="card metric"><span class="muted">Custo calculado</span><strong><?= em_money($economics['cost_cents']) ?></strong></div><div class="card metric"><span class="muted">Lucro unitário</span><strong><?= em_money($economics['profit_cents']) ?></strong></div><div class="card metric"><span class="muted">Margem</span><strong><?= Security::e(number_format((float)$economics['margin_percent'],2,',','.')) ?>%</strong></div></section>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:18px">
<section class="card"><span class="eyebrow">ROTEAMENTO</span><h2>Produção do produto</h2><p class="muted">Defina se o item vai para cozinha/bar/chapa/fritadeira ou se não precisa aparecer na produção.</p><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="profile-save"><input type="hidden" name="product_id" value="<?= $productId ?>"><label class="checkbox span-2"><input type="checkbox" name="production_enabled"<?= em_checked($profile['production_enabled']??0) ?>> Enviar este produto para produção</label><label class="span-2">Estação<select name="station_id"><option value="0">Não definida</option><?php foreach($stations as$s):?><option value="<?= (int)$s['id'] ?>"<?= em_selected($profile['station_id']??0,$s['id']) ?>><?= Security::e($s['name'].' · '.$s['station_type'].(!$s['active']?' · inativa':'')) ?></option><?php endforeach;?></select></label><label>Tempo próprio<input type="number" name="prep_minutes" min="1" max="240" value="<?= Security::e((string)($profile['prep_minutes']??'')) ?>" placeholder="usar SLA"></label><label>Impressão<select name="print_mode"><?php foreach(['inherit'=>'Herdar estação','auto'=>'Automática','manual'=>'Manual','none'=>'Não imprimir'] as$v=>$l):?><option value="<?= $v ?>"<?= em_selected($profile['print_mode']??'inherit',$v) ?>><?= $l ?></option><?php endforeach;?></select></label><label class="span-2">Instrução para produção<textarea name="production_notes" maxlength="500" placeholder="Ex.: montar em embalagem térmica"><?= Security::e($profile['production_notes']??'') ?></textarea></label><button class="primary span-2">Salvar roteamento</button></form></section>
<section class="card"><span class="eyebrow">FICHA TÉCNICA</span><h2>Ingredientes e consumo</h2><p class="muted">Quando houver ficha técnica, o estoque é reservado e baixado nos ingredientes em vez de baixar o produto acabado.</p><?php if($economics['recipe']):?><div class="table-wrap"><table class="table"><thead><tr><th>Ingrediente</th><th>Qtd.</th><th>Perda</th><th>Custo</th><th></th></tr></thead><tbody><?php foreach($economics['recipe'] as$r):?><tr><td><strong><?= Security::e($r['ingredient_name']) ?></strong><br><span class="muted"><?= Security::e($r['ingredient_sku']??'') ?></span></td><td><?= Security::e((string)$r['quantity']) ?></td><td><?= Security::e((string)$r['waste_percent']) ?>%</td><td><?= em_money((int)$r['line_cost_cents']) ?></td><td><form method="post" onsubmit="return confirm('Remover este ingrediente da ficha técnica?')"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="recipe-remove"><input type="hidden" name="product_id" value="<?= $productId ?>"><input type="hidden" name="recipe_id" value="<?= (int)$r['id'] ?>"><button class="secondary compact">Remover</button></form></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="alert">Sem ficha técnica. O custo usado é o custo médio do próprio produto.</div><?php endif;?><hr style="border-color:var(--line);margin:20px 0"><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="recipe-save"><input type="hidden" name="product_id" value="<?= $productId ?>"><label class="span-2">Ingrediente<select name="ingredient_product_id" required><option value="">Selecione</option><?php foreach($ingredients as$i):?><option value="<?= (int)$i['id'] ?>"><?= Security::e($i['name'].' · custo médio '.em_money((int)$i['average_cost_cents']).($i['track_stock']?' · estoque '.$i['stock_qty']:' · sem controle')) ?></option><?php endforeach;?></select></label><label>Quantidade por unidade<input name="quantity" inputmode="decimal" required placeholder="Ex.: 0,180"></label><label>Perda técnica %<input name="waste_percent" inputmode="decimal" value="0"></label><button class="secondary span-2">Adicionar / atualizar ingrediente</button></form></section>
</div>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">ADICIONAIS E MODIFICADORES</span><h2>Grupos de escolha</h2></div><span class="muted">mínimo, máximo e obrigatoriedade</span></div><form method="post" class="form-grid" style="margin-bottom:20px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="group-save"><input type="hidden" name="product_id" value="<?= $productId ?>"><label>Nome do grupo<input name="name" required placeholder="Ex.: Ponto da carne"></label><label>Mínimo<input type="number" name="min_select" min="0" value="0"></label><label>Máximo<input type="number" name="max_select" min="1" value="1"></label><label>Ordem<input type="number" name="sort_order" value="0"></label><label class="checkbox"><input type="checkbox" name="required"> Obrigatório</label><label class="checkbox"><input type="checkbox" name="active" checked> Ativo</label><button class="primary span-2">Criar grupo</button></form>
<?php if(!$groups):?><div class="alert">Nenhum grupo cadastrado. Crie “Tamanho”, “Ponto da carne”, “Adicionais”, “Molhos” ou qualquer regra que o produto precisar.</div><?php endif;?>
<?php foreach($groups as$g):?><article class="card" style="margin:14px 0;background:color-mix(in srgb,var(--surface) 92%,transparent)"><div class="section-head"><div><h3><?= Security::e($g['name']) ?></h3><span class="muted"><?= $g['required']?'Obrigatório':'Opcional' ?> · mínimo <?= (int)$g['min_select'] ?> · máximo <?= (int)$g['max_select'] ?> · <?= $g['active']?'ativo':'inativo' ?></span></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Opção</th><th>Extra</th><th>Custo</th><th>Estoque</th><th>Produção</th></tr></thead><tbody><?php foreach($options[(int)$g['id']]??[] as$o):?><tr><td><strong><?= Security::e($o['name']) ?></strong><?= !$o['active']?' <span class="muted">(inativa)</span>':'' ?></td><td><?= ((int)$o['price_delta_cents']>=0?'+ ':'- ').em_money(abs((int)$o['price_delta_cents'])) ?></td><td><?= em_money((int)$o['cost_cents']) ?></td><td><?= $o['inventory_product_id']?Security::e(($o['inventory_product_name']??'Produto').' × '.$o['inventory_quantity']):'Sem impacto' ?></td><td><?= $o['production_enabled']?Security::e($o['station_name']??'Estação'):'Não envia' ?></td></tr><?php endforeach;?></tbody></table></div><details style="margin-top:14px"><summary class="button secondary">Adicionar opção</summary><form method="post" class="form-grid" style="margin-top:14px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="option-save"><input type="hidden" name="product_id" value="<?= $productId ?>"><input type="hidden" name="group_id" value="<?= (int)$g['id'] ?>"><label>Nome<input name="name" required placeholder="Ex.: Bacon extra"></label><label>Valor extra<input name="price_delta" inputmode="decimal" value="0"></label><label>Custo próprio<input name="cost" inputmode="decimal" value="0"></label><label>Produto de estoque<select name="inventory_product_id"><option value="0">Sem impacto</option><?php foreach($ingredients as$i):?><option value="<?= (int)$i['id'] ?>"><?= Security::e($i['name']) ?></option><?php endforeach;?></select></label><label>Qtd. de estoque<input name="inventory_quantity" inputmode="decimal" value="0"></label><label>Estação<select name="station_id"><option value="0">Não enviar</option><?php foreach($stations as$s):?><option value="<?= (int)$s['id'] ?>"><?= Security::e($s['name']) ?></option><?php endforeach;?></select></label><label class="checkbox"><input type="checkbox" name="production_enabled"> Enviar adicional à produção</label><label>Ordem<input type="number" name="sort_order" value="0"></label><label class="checkbox"><input type="checkbox" name="active" checked> Ativa</label><button class="primary span-2">Salvar opção</button></form></details></article><?php endforeach;?>
</section>
<?php em_footer();