<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\ProductConfigurationService;

Auth::requirePermission('production.manage');$tenantId=em_require_tenant();$config=new ProductConfigurationService();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='station-save'){$id=$config->saveStation($_POST);em_flash('ok','Estação #'.$id.' salva.');}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable $e){em_flash('error',$e->getMessage());}
    em_go('production');
}
$stations=$config->stations($tenantId,false);
$productsStmt=$pdo->prepare('SELECT p.id,p.name,p.sku,pp.production_enabled,pp.prep_minutes,ps.name station_name,ps.station_type FROM products p LEFT JOIN product_production_profiles pp ON pp.product_id=p.id AND pp.tenant_id=p.tenant_id LEFT JOIN production_stations ps ON ps.id=pp.station_id WHERE p.tenant_id=? ORDER BY p.active DESC,p.name');$productsStmt->execute([$tenantId]);$products=$productsStmt->fetchAll();
$printStmt=$pdo->prepare('SELECT pr.*,ps.name station_name,u.name user_name FROM production_prints pr JOIN production_stations ps ON ps.id=pr.station_id LEFT JOIN users u ON u.id=pr.printed_by WHERE pr.tenant_id=? ORDER BY pr.id DESC LIMIT 80');$printStmt->execute([$tenantId]);$prints=$printStmt->fetchAll();
$activeStations=count(array_filter($stations,fn($s)=>(int)$s['active']===1));$routed=count(array_filter($products,fn($p)=>(int)($p['production_enabled']??0)===1));
em_header('Produção / Estações','production');
?>
<section class="page-hero"><div><span class="eyebrow">OPERAÇÃO PROFISSIONAL</span><h2>Estações de produção</h2><p>Configure cozinha, bar, chapa, fritadeira, sobremesas ou montagem. Cada produto e adicional pode ter sua própria rota, SLA e política de impressão.</p></div><div class="actions"><a class="button primary" href="<?= Security::e(app_url('?route=kitchen')) ?>">Abrir KDS</a></div></section>
<section class="grid" style="grid-template-columns:repeat(auto-fit,minmax(220px,1fr));margin-bottom:18px"><div class="card metric"><span class="muted">Estações ativas</span><strong><?= $activeStations ?></strong></div><div class="card metric"><span class="muted">Produtos roteados</span><strong><?= $routed ?></strong></div><div class="card metric"><span class="muted">Produtos sem rota</span><strong><?= max(0,count($products)-$routed) ?></strong></div></section>
<div class="grid" style="grid-template-columns:minmax(320px,1fr) minmax(0,2fr)">
<section class="card"><span class="eyebrow">NOVA ESTAÇÃO</span><h2>Configurar setor</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="station-save"><label>Nome<input name="name" required placeholder="Ex.: Chapa"></label><label>Código<input name="code" required placeholder="CHAPA"></label><label>Tipo<select name="station_type"><option value="kitchen">Cozinha</option><option value="bar">Bar</option><option value="grill">Chapa / grelha</option><option value="fryer">Fritadeira</option><option value="dessert">Sobremesa</option><option value="assembly">Montagem / expedição</option><option value="other">Outro</option></select></label><label>SLA em minutos<input type="number" name="sla_minutes" min="1" max="240" value="15"></label><label>Impressão<select name="printer_mode"><option value="manual">Manual</option><option value="auto">Automática</option><option value="none">Não imprimir</option></select></label><label>Destino da impressora<input name="printer_target" placeholder="Opcional: nome/fila"></label><label>Ordem<input type="number" name="sort_order" value="0"></label><label class="checkbox"><input type="checkbox" name="active" checked> Estação ativa</label><button class="primary span-2">Salvar estação</button></form></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">SETORES</span><h2>Estações cadastradas</h2></div><span class="muted"><?= count($stations) ?> total</span></div><?php if(!$stations):?><div class="alert">Cadastre pelo menos uma estação antes de rotear produtos para a produção.</div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Estação</th><th>Tipo</th><th>SLA</th><th>Impressão</th><th>Status</th><th>Editar</th></tr></thead><tbody><?php foreach($stations as$s):?><tr><td><strong><?= Security::e($s['name']) ?></strong><br><span class="muted"><?= Security::e($s['code']) ?></span></td><td><?= Security::e($s['station_type']) ?></td><td><?= (int)$s['sla_minutes'] ?> min</td><td><?= Security::e($s['printer_mode']) ?><?= $s['printer_target']?'<br><span class="muted">'.Security::e($s['printer_target']).'</span>':'' ?></td><td><span class="status-pill <?= $s['active']?'active':'cancelled' ?>"><?= $s['active']?'Ativa':'Inativa' ?></span></td><td><details><summary class="button secondary compact">Editar</summary><form method="post" class="form-grid" style="margin-top:12px;min-width:280px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="station-save"><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><label class="span-2">Nome<input name="name" value="<?= Security::e($s['name']) ?>" required></label><label>Código<input name="code" value="<?= Security::e($s['code']) ?>" required></label><label>Tipo<select name="station_type"><?php foreach(['kitchen'=>'Cozinha','bar'=>'Bar','grill'=>'Chapa','fryer'=>'Fritadeira','dessert'=>'Sobremesa','assembly'=>'Montagem','other'=>'Outro'] as$v=>$l):?><option value="<?= $v ?>"<?= em_selected($s['station_type'],$v) ?>><?= $l ?></option><?php endforeach;?></select></label><label>SLA<input type="number" name="sla_minutes" value="<?= (int)$s['sla_minutes'] ?>"></label><label>Impressão<select name="printer_mode"><?php foreach(['manual'=>'Manual','auto'=>'Automática','none'=>'Não imprimir'] as$v=>$l):?><option value="<?= $v ?>"<?= em_selected($s['printer_mode'],$v) ?>><?= $l ?></option><?php endforeach;?></select></label><label>Destino<input name="printer_target" value="<?= Security::e($s['printer_target']??'') ?>"></label><label>Ordem<input type="number" name="sort_order" value="<?= (int)$s['sort_order'] ?>"></label><label class="checkbox"><input type="checkbox" name="active"<?= em_checked($s['active']) ?>> Ativa</label><button class="primary span-2">Salvar</button></form></details></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
</div>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">ROTEAMENTO</span><h2>Produtos e estação</h2></div><span class="muted">Abra a configuração avançada para adicionais e ficha técnica</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Produto</th><th>Produção</th><th>Estação</th><th>Tempo</th><th></th></tr></thead><tbody><?php foreach($products as$p):?><tr><td><strong><?= Security::e($p['name']) ?></strong><?php if($p['sku']):?><br><span class="muted"><?= Security::e($p['sku']) ?></span><?php endif;?></td><td><span class="status-pill <?= !empty($p['production_enabled'])?'active':'cancelled' ?>"><?= !empty($p['production_enabled'])?'Vai para produção':'Não roteado' ?></span></td><td><?= Security::e($p['station_name']??'—') ?></td><td><?= $p['prep_minutes']?((int)$p['prep_minutes'].' min'):'SLA da estação' ?></td><td><a class="button secondary" href="<?= Security::e(app_url('?route=product-config&id='.(int)$p['id'])) ?>">Configurar</a></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">AUDITORIA DE IMPRESSÃO</span><h2>Impressões e reimpressões</h2></div><span class="muted">reimpressão exige motivo</span></div><?php if(!$prints):?><p class="muted">Nenhuma impressão registrada ainda.</p><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Pedido</th><th>Estação</th><th>Tipo</th><th>Usuário</th><th>Motivo</th></tr></thead><tbody><?php foreach($prints as$pr):?><tr><td><?= Security::e($pr['created_at']) ?></td><td>#<?= (int)$pr['order_id'] ?></td><td><?= Security::e($pr['station_name']) ?></td><td><?= Security::e($pr['print_type']) ?></td><td><?= Security::e($pr['user_name']??'Sistema') ?></td><td><?= Security::e($pr['reason']??'—') ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php em_footer();
