<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

Auth::requirePermission('catalog.manage');
$tenantId=em_require_tenant();
$tenantStmt=$pdo->prepare('SELECT id,name,slug,settings FROM tenants WHERE id=?');$tenantStmt->execute([$tenantId]);$tenant=$tenantStmt->fetch();if(!$tenant)exit('Empresa não encontrada.');
$publicMenuUrl=app_url('menu.php?empresa='.rawurlencode((string)$tenant['slug']));

if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    if($action==='category-save'){
        $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));if($name==='')exit('Categoria inválida.');
        if($id){$s=$pdo->prepare('UPDATE categories SET name=?,sort_order=?,active=? WHERE id=? AND tenant_id=?');$s->execute([$name,(int)($_POST['sort_order']??0),isset($_POST['active'])?1:0,$id,$tenantId]);}
        else{$s=$pdo->prepare('INSERT INTO categories (tenant_id,name,sort_order,active) VALUES (?,?,?,1)');$s->execute([$tenantId,$name,(int)($_POST['sort_order']??0)]);$id=(int)$pdo->lastInsertId();}
        Auth::audit('category.saved','category',(string)$id);em_flash('ok','Categoria salva.');em_go('products');
    }
    if($action==='product-save'){
        $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$sku=trim((string)($_POST['sku']??''));$price=(int)round((float)str_replace(',','.',(string)($_POST['price']??'0'))*100);$cat=(int)($_POST['category_id']??0);$track=isset($_POST['track_stock'])?1:0;$description=mb_substr(trim((string)($_POST['description']??'')),0,1200);$imageRaw=trim((string)($_POST['image_url']??''));$image=null;
        if($imageRaw!==''){$valid=filter_var($imageRaw,FILTER_VALIDATE_URL);$scheme=strtolower((string)parse_url($imageRaw,PHP_URL_SCHEME));if(!$valid||!in_array($scheme,['http','https'],true))exit('A foto precisa usar uma URL http ou https válida.');$image=mb_substr($imageRaw,0,700);}
        $active=isset($_POST['active'])?1:0;if($name===''||$price<0)exit('Produto inválido.');
        if($cat){$c=$pdo->prepare('SELECT id FROM categories WHERE id=? AND tenant_id=?');$c->execute([$cat,$tenantId]);if(!$c->fetchColumn())exit('Categoria inválida.');}
        if($id){
            $exists=$pdo->prepare('SELECT id,stock_qty,track_stock FROM products WHERE id=? AND tenant_id=?');$exists->execute([$id,$tenantId]);$current=$exists->fetch();if(!$current)exit('Produto não encontrado.');
            if((int)$current['track_stock']===1&&$track===0){$r=$pdo->prepare('SELECT COALESCE(SUM(quantity),0) FROM stock_reservations WHERE tenant_id=? AND product_id=? AND status="reserved"');$r->execute([$tenantId,$id]);if((float)$r->fetchColumn()>0)exit('Não é possível desativar o controle de estoque enquanto houver unidades reservadas em pedidos.');}
            $s=$pdo->prepare('UPDATE products SET category_id=?,name=?,description=?,sku=?,price_cents=?,track_stock=?,image_url=?,active=? WHERE id=? AND tenant_id=?');$s->execute([$cat?:null,$name,$description,$sku?:null,$price,$track,$image,$active,$id,$tenantId]);
        }else{
            $stock=(float)str_replace(',','.',(string)($_POST['stock_qty']??'0'));if(!is_finite($stock)||$stock<0)exit('Estoque inicial inválido.');
            $s=$pdo->prepare('INSERT INTO products (tenant_id,category_id,name,description,sku,price_cents,stock_qty,track_stock,image_url,active) VALUES (?,?,?,?,?,?,?,?,?,?)');$s->execute([$tenantId,$cat?:null,$name,$description,$sku?:null,$price,$stock,$track,$image,$active]);$id=(int)$pdo->lastInsertId();
            if($track&&$stock>0){$key='initial-stock:'.$tenantId.':'.$id;$pdo->prepare('INSERT INTO stock_movements (tenant_id,product_id,order_id,type,quantity,idempotency_key) VALUES (?,?,NULL,"in",?,?)')->execute([$tenantId,$id,$stock,$key]);}
        }
        Auth::audit('product.saved','product',(string)$id);em_flash('ok','Produto salvo e o cardápio público foi atualizado.');em_go('products');
    }
}

$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=$pdo->prepare('SELECT p.*,COALESCE((SELECT SUM(sr.quantity) FROM stock_reservations sr WHERE sr.tenant_id=p.tenant_id AND sr.product_id=p.id AND sr.status="reserved"),0) reserved_qty FROM products p WHERE p.id=? AND p.tenant_id=?');$s->execute([$editId,$tenantId]);$edit=$s->fetch()?:null;}
$cats=$pdo->prepare('SELECT * FROM categories WHERE tenant_id=? ORDER BY sort_order,name');$cats->execute([$tenantId]);$categories=$cats->fetchAll();
$s=$pdo->prepare('SELECT p.*,c.name category_name,COALESCE((SELECT SUM(sr.quantity) FROM stock_reservations sr WHERE sr.tenant_id=p.tenant_id AND sr.product_id=p.id AND sr.status="reserved"),0) reserved_qty FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.tenant_id=? ORDER BY p.active DESC,p.id DESC');$s->execute([$tenantId]);$products=$s->fetchAll();
$activeProducts=count(array_filter($products,static fn(array$p):bool=>(int)$p['active']===1));$activeCategories=count(array_filter($categories,static fn(array$c):bool=>(int)$c['active']===1));$lowStock=count(array_filter($products,static fn(array$p):bool=>(int)$p['track_stock']===1&&(float)$p['stock_qty']<=5));$averagePrice=$activeProducts?intdiv(array_sum(array_map(static fn(array$p):int=>(int)$p['price_cents'],array_filter($products,static fn(array$p):bool=>(int)$p['active']===1))),$activeProducts):0;
$showEditor=$edit!==null||isset($_GET['new']);

em_header('Produtos e Estoque','products');
?>
<section class="page-hero"><div><span class="eyebrow">CATÁLOGO</span><h2>Produtos e estoque</h2><p>Gerencie produtos, categorias, preços, disponibilidade, ficha técnica e produção em um só lugar.</p></div><div class="hero-actions"><a class="button primary" href="<?= Security::e(app_url('?route=products&new=1')) ?>">+ Novo produto</a><a class="button secondary" href="<?= Security::e(app_url('?route=inventory')) ?>">Estoque</a><a class="button secondary" target="_blank" rel="noopener" href="<?= Security::e($publicMenuUrl) ?>">Ver cardápio</a></div></section>
<section class="grid dashboard-metrics"><div class="card metric"><span class="muted">Produtos publicados</span><strong><?= $activeProducts ?></strong></div><div class="card metric"><span class="muted">Categorias ativas</span><strong><?= $activeCategories ?></strong></div><div class="card metric"><span class="muted">Estoque baixo</span><strong><?= $lowStock ?></strong></div><div class="card metric"><span class="muted">Preço médio</span><strong><?= em_money($averagePrice) ?></strong></div></section>
<section class="card" style="margin-top:14px"><div class="section-head"><div><span class="eyebrow">CARDÁPIO</span><h2>Catálogo de produtos</h2></div><div class="actions"><button type="button" class="secondary compact" onclick="navigator.clipboard?.writeText(<?= Security::e(json_encode($publicMenuUrl,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)) ?>);this.textContent='Link copiado ✓'">Copiar link público</button><a class="button secondary compact" href="<?= Security::e(app_url('?route=settings#cardapio')) ?>">Personalizar</a></div></div>
<div class="actions" style="margin-bottom:12px"><input id="product-search" type="search" placeholder="Buscar produto..." style="max-width:320px"><select id="category-filter" style="max-width:230px"><option value="">Todas as categorias</option><?php foreach($categories as$c):?><option value="<?= Security::e(mb_strtolower((string)$c['name'])) ?>"><?= Security::e($c['name']) ?></option><?php endforeach;?></select><select id="status-filter" style="max-width:180px"><option value="">Todos os status</option><option value="published">Publicado</option><option value="hidden">Oculto</option></select></div>
<?php if(!$products):?><div class="alert">Você ainda não cadastrou produtos.</div><?php else:?><div class="table-wrap"><table class="table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody id="product-table-body"><?php foreach($products as$p):$search=mb_strtolower(trim((string)$p['name'].' '.(string)($p['sku']??'')));$cat=mb_strtolower((string)($p['category_name']??'Outros'));$status=$p['active']?'published':'hidden';?><tr data-product-row data-search="<?= Security::e($search) ?>" data-category="<?= Security::e($cat) ?>" data-status="<?= $status ?>"><td><div class="product-admin-item"><?php if(!empty($p['image_url'])):?><img class="product-thumb" src="<?= Security::e($p['image_url']) ?>" alt="" loading="lazy"><?php else:?><span class="product-thumb"></span><?php endif;?><div><strong><?= Security::e($p['name']) ?></strong><?php if(!empty($p['sku'])):?><br><span class="muted"><?= Security::e($p['sku']) ?></span><?php endif;?></div></div></td><td><?= Security::e($p['category_name']??'Outros') ?></td><td><strong><?= em_money($p['price_cents']) ?></strong></td><td><?php if($p['track_stock']):?><strong><?= Security::e((string)$p['stock_qty']) ?></strong><?php if((float)$p['reserved_qty']>0):?><br><span class="muted"><?= Security::e((string)$p['reserved_qty']) ?> reservado</span><?php endif;?><?php else:?><span class="muted">Sem controle</span><?php endif;?></td><td><span class="status-pill <?= $p['active']?'active':'cancelled' ?>"><?= $p['active']?'Ativo':'Oculto' ?></span></td><td><div class="actions"><a class="button secondary compact" href="<?= Security::e(app_url('?route=products&edit='.(int)$p['id'])) ?>">Editar</a><a class="button secondary compact" href="<?= Security::e(app_url('?route=product-config&product_id='.(int)$p['id'])) ?>">Ficha técnica / adicionais</a><?php if($p['track_stock']&&Auth::can('inventory.manage')):?><a class="button secondary compact" href="<?= Security::e(app_url('?route=inventory&product_id='.(int)$p['id'])) ?>">Estoque</a><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>

<details class="technical-details"<?= $showEditor?' open':'' ?> style="margin-top:14px"><summary><?= $edit?'Editar produto selecionado':'Cadastrar novo produto' ?></summary><section class="card"><div class="section-head"><div><span class="eyebrow"><?= $edit?'EDIÇÃO':'NOVO PRODUTO' ?></span><h2><?= $edit?'Editar '.$edit['name']:'Adicionar produto' ?></h2></div><?php if($edit):?><a class="button secondary compact" href="<?= Security::e(app_url('?route=products')) ?>">Cancelar</a><?php endif;?></div><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="product-save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label class="span-2">Nome do produto<input name="name" required value="<?= Security::e($edit['name']??'') ?>" placeholder="Ex.: X-Bacon Especial"></label><label>Preço de venda<input name="price" required inputmode="decimal" value="<?= $edit?Security::e(number_format(((int)$edit['price_cents'])/100,2,',','')):'' ?>" placeholder="24,90"></label><label>SKU<input name="sku" value="<?= Security::e($edit['sku']??'') ?>" placeholder="Opcional"></label><label class="span-2">Categoria<select name="category_id"><option value="0">Outros / sem categoria</option><?php foreach($categories as$c):?><option value="<?= (int)$c['id'] ?>"<?= em_selected($edit['category_id']??0,$c['id']) ?>><?= Security::e($c['name']) ?><?= !$c['active']?' (inativa)':'' ?></option><?php endforeach;?></select></label><?php if($edit):?><label>Saldo disponível<input value="<?= Security::e((string)($edit['stock_qty']??'0')) ?>" readonly></label><label>Reservado<input value="<?= Security::e((string)($edit['reserved_qty']??'0')) ?>" readonly></label><?php else:?><label>Estoque inicial<input name="stock_qty" inputmode="decimal" value="0"></label><div class="muted">Depois do cadastro, movimentos ficam no módulo Estoque.</div><?php endif;?><label class="checkbox span-2"><input type="checkbox" name="track_stock"<?= em_checked($edit['track_stock']??0) ?>> Controlar disponibilidade pelo estoque</label><label class="span-2">Foto do produto (URL)<input type="url" name="image_url" value="<?= Security::e($edit['image_url']??'') ?>" placeholder="https://..."></label><label class="span-2">Descrição<textarea name="description"><?= Security::e($edit['description']??'') ?></textarea></label><label class="checkbox span-2"><input type="checkbox" name="active"<?= em_checked($edit?($edit['active']??0):1) ?>> Publicado no cardápio</label><button class="primary span-2"><?= $edit?'Salvar alterações':'Publicar produto' ?></button></form></section></details>

<details class="technical-details" style="margin-top:12px"><summary>Gerenciar categorias</summary><section class="card"><div class="section-head"><div><span class="eyebrow">ORGANIZAÇÃO</span><h2>Categorias</h2></div></div><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="category-save"><label>Nome<input name="name" required placeholder="Ex.: Hambúrgueres"></label><label>Ordem de exibição<input type="number" name="sort_order" value="0"></label><button class="secondary span-2">Criar categoria</button></form><div class="table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>Categoria</th><th>Ordem</th><th>Status</th></tr></thead><tbody><?php foreach($categories as$c):?><tr><td><?= Security::e($c['name']) ?></td><td><?= (int)$c['sort_order'] ?></td><td><span class="status-pill <?= $c['active']?'active':'cancelled' ?>"><?= $c['active']?'Ativa':'Inativa' ?></span></td></tr><?php endforeach;?></tbody></table></div></section></details>
<script>const ps=document.getElementById('product-search'),cf=document.getElementById('category-filter'),sf=document.getElementById('status-filter');function filterProducts(){const q=(ps?.value||'').trim().toLocaleLowerCase('pt-BR'),cat=cf?.value||'',st=sf?.value||'';document.querySelectorAll('[data-product-row]').forEach(row=>{row.hidden=(q&&!row.dataset.search.includes(q))||(cat&&row.dataset.category!==cat)||(st&&row.dataset.status!==st)})}ps?.addEventListener('input',filterProducts);cf?.addEventListener('change',filterProducts);sf?.addEventListener('change',filterProducts);</script>
<?php em_footer();
