<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\OperatingUnitService;
use EventMenu\Services\PurchaseService;

Auth::requirePermission('inventory.manage');$tenantId=em_require_tenant();$service=new PurchaseService();$unitService=new OperatingUnitService();
try{$unit=$unitService->requireCurrent();}catch(Throwable$e){em_header('Compras e Fornecedores','purchases');?><div class="alert error"><?= Security::e($e->getMessage()) ?></div><?php em_footer();return;}

$moneyToCents=static function(mixed$value):int{$raw=trim((string)$value);if($raw==='')return 0;$raw=str_replace(['R$',' '],'',$raw);if(str_contains($raw,',')&&str_contains($raw,'.'))$raw=str_replace('.','',$raw);$raw=str_replace(',','.',$raw);return max(0,(int)round((float)$raw*100));};
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='supplier-save'){$id=(int)($_POST['id']??0);$service->saveSupplier($id?:null,(string)($_POST['name']??''),(string)($_POST['document']??''),(string)($_POST['phone']??''),(string)($_POST['email']??''),(string)($_POST['notes']??''),!empty($_POST['active']));em_flash('ok','Fornecedor salvo.');em_go('purchases',['tab'=>'suppliers']);}
        if($action==='purchase-create'){$id=$service->createOrder((int)($_POST['supplier_id']??0)?:null,(string)($_POST['notes']??''));em_flash('ok','Compra #'.$id.' criada em rascunho.');em_go('purchases',['view'=>$id]);}
        if($action==='item-add'){$orderId=(int)($_POST['purchase_order_id']??0);$service->addItem($orderId,(int)($_POST['product_id']??0),(float)str_replace(',','.',(string)($_POST['quantity']??'0')),$moneyToCents($_POST['unit_cost']??0));em_flash('ok','Item salvo na compra.');em_go('purchases',['view'=>$orderId]);}
        if($action==='item-remove'){$orderId=(int)($_POST['purchase_order_id']??0);$service->removeItem($orderId,(int)($_POST['item_id']??0));em_flash('ok','Item removido.');em_go('purchases',['view'=>$orderId]);}
        if($action==='mark-ordered'){$orderId=(int)($_POST['purchase_order_id']??0);$service->markOrdered($orderId);em_flash('ok','Compra marcada como enviada ao fornecedor.');em_go('purchases',['view'=>$orderId]);}
        if($action==='receive'){$orderId=(int)($_POST['purchase_order_id']??0);$service->receive($orderId);em_flash('ok','Compra recebida. O estoque e o custo médio da unidade foram atualizados.');em_go('purchases',['view'=>$orderId]);}
        if($action==='cancel'){$orderId=(int)($_POST['purchase_order_id']??0);$service->cancel($orderId,(string)($_POST['reason']??''));em_flash('ok','Compra cancelada.');em_go('purchases',['view'=>$orderId]);}
        throw new RuntimeException('Ação inválida.');
    }catch(Throwable$e){em_flash('error',$e->getMessage());$view=(int)($_POST['purchase_order_id']??0);em_go('purchases',$view?['view'=>$view]:[]);}
}

$suppliers=$service->suppliers(false);$activeSuppliers=array_values(array_filter($suppliers,static fn(array$s):bool=>(int)$s['active']===1));$orders=$service->orders(150);$productsStmt=$pdo->prepare('SELECT p.id,p.name,p.sku,p.purchase_unit,p.stock_unit,p.purchase_factor,COALESCE(ui.stock_qty,0) unit_stock,COALESCE(ui.average_cost_cents,p.average_cost_cents,0) unit_cost FROM products p LEFT JOIN unit_inventory ui ON ui.tenant_id=p.tenant_id AND ui.unit_id=? AND ui.product_id=p.id WHERE p.tenant_id=? AND p.track_stock=1 AND p.active=1 ORDER BY p.name');$productsStmt->execute([(int)$unit['id'],$tenantId]);$products=$productsStmt->fetchAll();
$viewId=(int)($_GET['view']??0);$detail=null;if($viewId){try{$detail=$service->details($viewId);}catch(Throwable$e){em_flash('error',$e->getMessage());}}
$tab=(string)($_GET['tab']??'orders');if(!in_array($tab,['orders','suppliers'],true))$tab='orders';$statusLabels=['draft'=>'Rascunho','ordered'=>'Enviada','received'=>'Recebida','cancelled'=>'Cancelada'];
$pendingCount=count(array_filter($orders,static fn(array$o):bool=>in_array($o['status'],['draft','ordered'],true)));$receivedTotal=array_sum(array_map(static fn(array$o):int=>$o['status']==='received'?(int)$o['total_cents']:0,$orders));
em_header('Compras e Fornecedores','purchases');
?>
<section class="page-hero"><div><span class="eyebrow">SUPRIMENTOS · <?= Security::e($unit['name']) ?></span><h2>Compras e fornecedores</h2><p>Monte o pedido na unidade de compra do produto. No recebimento, o EventMenu converte para a unidade de estoque e recalcula o custo médio automaticamente.</p></div><div class="hero-actions"><a class="button secondary" href="<?= Security::e(app_url('?route=inventory')) ?>">Voltar ao estoque</a></div></section>
<section class="grid dashboard-metrics"><div class="card metric"><span class="muted">Compras abertas</span><strong><?= $pendingCount ?></strong></div><div class="card metric"><span class="muted">Fornecedores ativos</span><strong><?= count($activeSuppliers) ?></strong></div><div class="card metric"><span class="muted">Recebido no histórico</span><strong><?= em_money($receivedTotal) ?></strong></div><div class="card metric"><span class="muted">Unidade</span><strong style="font-size:20px"><?= Security::e($unit['name']) ?></strong></div></section>
<nav class="actions" style="margin:18px 0"><a class="button <?= $tab==='orders'?'primary':'secondary' ?>" href="<?= Security::e(app_url('?route=purchases&tab=orders')) ?>">Compras</a><a class="button <?= $tab==='suppliers'?'primary':'secondary' ?>" href="<?= Security::e(app_url('?route=purchases&tab=suppliers')) ?>">Fornecedores</a></nav>
<?php if($tab==='suppliers'):?>
<div class="grid" style="grid-template-columns:minmax(300px,.9fr) minmax(0,1.6fr)"><section class="card"><span class="eyebrow">CADASTRO</span><h2>Novo fornecedor</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="supplier-save"><label class="span-2">Nome<input name="name" required placeholder="Razão social ou nome"></label><label>CPF/CNPJ<input name="document"></label><label>Telefone<input name="phone"></label><label class="span-2">E-mail<input type="email" name="email"></label><label class="span-2">Observações<textarea name="notes" maxlength="1000"></textarea></label><label class="checkbox span-2"><input type="checkbox" name="active" checked> Fornecedor ativo</label><button class="primary span-2">Salvar fornecedor</button></form></section><section class="card"><div class="section-head"><h2>Fornecedores</h2><span class="muted"><?= count($suppliers) ?> cadastrados</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Fornecedor</th><th>Documento</th><th>Contato</th><th>Status</th><th>Editar</th></tr></thead><tbody><?php foreach($suppliers as$s):?><tr><td><strong><?= Security::e($s['name']) ?></strong><?php if($s['notes']):?><br><span class="muted"><?= Security::e($s['notes']) ?></span><?php endif;?></td><td><?= Security::e($s['document']??'—') ?></td><td><?= Security::e($s['phone']??'—') ?><?php if($s['email']):?><br><span class="muted"><?= Security::e($s['email']) ?></span><?php endif;?></td><td><span class="status-pill <?= $s['active']?'active':'cancelled' ?>"><?= $s['active']?'Ativo':'Inativo' ?></span></td><td><details><summary class="button secondary compact">Editar</summary><form method="post" class="form-grid" style="margin-top:10px;min-width:290px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="supplier-save"><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><label class="span-2">Nome<input name="name" required value="<?= Security::e($s['name']) ?>"></label><label>Documento<input name="document" value="<?= Security::e($s['document']??'') ?>"></label><label>Telefone<input name="phone" value="<?= Security::e($s['phone']??'') ?>"></label><label class="span-2">E-mail<input type="email" name="email" value="<?= Security::e($s['email']??'') ?>"></label><label class="span-2">Observações<textarea name="notes"><?= Security::e($s['notes']??'') ?></textarea></label><label class="checkbox span-2"><input type="checkbox" name="active"<?= em_checked($s['active']) ?>> Ativo</label><button class="primary span-2">Salvar</button></form></details></td></tr><?php endforeach;?></tbody></table></div></section></div>
<?php else:?>
<div class="grid" style="grid-template-columns:minmax(300px,.8fr) minmax(0,1.7fr)"><section class="card"><span class="eyebrow">NOVA COMPRA</span><h2>Criar pedido</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="purchase-create"><label class="span-2">Fornecedor<select name="supplier_id"><option value="0">Sem fornecedor definido</option><?php foreach($activeSuppliers as$s):?><option value="<?= (int)$s['id'] ?>"><?= Security::e($s['name']) ?></option><?php endforeach;?></select></label><label class="span-2">Observações<textarea name="notes" placeholder="Prazo, contato, condição negociada..."></textarea></label><button class="primary span-2">Criar rascunho</button></form><p class="muted">A compra será criada para <strong><?= Security::e($unit['name']) ?></strong>. Troque a unidade no topo antes de criar se o recebimento for em outra loja.</p></section><section class="card"><div class="section-head"><h2>Histórico da unidade</h2><span class="muted"><?= count($orders) ?> compras</span></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Fornecedor</th><th>Itens</th><th>Total</th><th>Status</th><th>Data</th><th></th></tr></thead><tbody><?php foreach($orders as$o):?><tr><td><strong>#<?= (int)$o['id'] ?></strong></td><td><?= Security::e($o['supplier_name']??'Não definido') ?></td><td><?= (int)$o['items_count'] ?></td><td><strong><?= em_money($o['total_cents']) ?></strong></td><td><span class="status-pill <?= $o['status']==='received'?'active':($o['status']==='cancelled'?'cancelled':'') ?>"><?= Security::e($statusLabels[$o['status']]??$o['status']) ?></span></td><td><?= Security::e($o['created_at']) ?></td><td><a class="button secondary compact" href="<?= Security::e(app_url('?route=purchases&view='.(int)$o['id'])) ?>">Abrir</a></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td colspan="7">Nenhuma compra registrada nesta unidade.</td></tr><?php endif;?></tbody></table></div></section></div>
<?php if($detail):$po=$detail['order'];$editable=$po['status']==='draft';?><section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">COMPRA #<?= (int)$po['id'] ?></span><h2><?= Security::e($po['supplier_name']??'Fornecedor não definido') ?></h2><p class="muted"><?= Security::e($po['unit_name']) ?> · <?= Security::e($statusLabels[$po['status']]??$po['status']) ?></p></div><strong style="font-size:26px"><?= em_money($po['total_cents']) ?></strong></div>
<?php if($editable):?><form method="post" class="form-grid" style="margin-bottom:18px"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="item-add"><input type="hidden" name="purchase_order_id" value="<?= (int)$po['id'] ?>"><label class="span-2">Produto<select name="product_id" required id="purchase-product"><option value="">Selecione</option><?php foreach($products as$p):?><option value="<?= (int)$p['id'] ?>" data-factor="<?= Security::e((string)$p['purchase_factor']) ?>" data-purchase="<?= Security::e($p['purchase_unit']) ?>" data-stock="<?= Security::e($p['stock_unit']) ?>"><?= Security::e($p['name'].($p['sku']?' · '.$p['sku']:'')) ?></option><?php endforeach;?></select></label><label>Quantidade de compra<input name="quantity" id="purchase-qty" inputmode="decimal" required placeholder="Ex.: 2"></label><label>Custo por unidade de compra<input name="unit_cost" inputmode="decimal" required placeholder="Ex.: 89,90"></label><div class="span-2 alert" id="purchase-conversion">Selecione um produto para ver a conversão.</div><button class="primary span-2">Adicionar / atualizar item</button></form><?php endif;?>
<div class="table-wrap"><table class="table"><thead><tr><th>Produto</th><th>Compra</th><th>Conversão registrada</th><th>Entrada no estoque</th><th>Custo compra</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($detail['items'] as$i):?><tr><td><strong><?= Security::e($i['product_name']) ?></strong><br><span class="muted"><?= Security::e($i['sku']??'') ?></span></td><td><?= Security::e((string)$i['quantity'].' '.($i['purchase_unit_snapshot']??'un')) ?></td><td>1 <?= Security::e($i['purchase_unit_snapshot']??'un') ?> = <?= Security::e((string)$i['purchase_factor_snapshot'].' '.($i['stock_unit_snapshot']??'un')) ?></td><td><strong><?= Security::e((string)$i['stock_quantity'].' '.($i['stock_unit_snapshot']??'un')) ?></strong></td><td><?= em_money($i['unit_cost_cents']) ?></td><td><strong><?= em_money($i['total_cents']) ?></strong></td><td><?php if($editable):?><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="item-remove"><input type="hidden" name="purchase_order_id" value="<?= (int)$po['id'] ?>"><input type="hidden" name="item_id" value="<?= (int)$i['id'] ?>"><button class="secondary compact">Remover</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$detail['items']):?><tr><td colspan="7">Adicione os itens da compra.</td></tr><?php endif;?></tbody></table></div>
<div class="actions" style="margin-top:18px"><?php if($po['status']==='draft'&&$detail['items']):?><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="mark-ordered"><input type="hidden" name="purchase_order_id" value="<?= (int)$po['id'] ?>"><button class="secondary">Marcar como enviada</button></form><?php endif;?><?php if(in_array($po['status'],['draft','ordered'],true)&&$detail['items']):?><form method="post" onsubmit="return confirm('Confirmar recebimento? Isto dará entrada no estoque desta unidade e atualizará o custo médio.')"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="receive"><input type="hidden" name="purchase_order_id" value="<?= (int)$po['id'] ?>"><button class="primary">Receber compra e dar entrada</button></form><form method="post" onsubmit="return confirm('Cancelar esta compra?')"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="purchase_order_id" value="<?= (int)$po['id'] ?>"><input type="hidden" name="reason" value="Cancelada pelo operador"><button class="secondary">Cancelar</button></form><?php endif;?></div>
</section><?php endif;?>
<script>(()=>{const p=document.getElementById('purchase-product'),q=document.getElementById('purchase-qty'),out=document.getElementById('purchase-conversion');function show(){if(!p||!q||!out)return;const o=p.options[p.selectedIndex];if(!o||!o.value){out.textContent='Selecione um produto para ver a conversão.';return;}const f=parseFloat(o.dataset.factor||'1')||1,qty=parseFloat((q.value||'0').replace(',','.'))||0;out.textContent=`1 ${o.dataset.purchase||'un'} = ${f} ${o.dataset.stock||'un'} · ${qty||0} ${o.dataset.purchase||'un'} entrarão como ${(qty*f).toLocaleString('pt-BR')} ${o.dataset.stock||'un'} no estoque.`}p?.addEventListener('change',show);q?.addEventListener('input',show);show()})();</script>
<?php endif;em_footer();
