<?php

declare(strict_types=1);
use EventMenu\Core\Auth;use EventMenu\Core\Security;
if(!Auth::isSuperAdmin()){http_response_code(403);exit('Acesso exclusivo do ADM Geral.');}
$clean=static fn(mixed$v,int$max=300):string=>mb_substr(trim((string)$v),0,$max);
if($_SERVER['REQUEST_METHOD']==='POST'){
 em_post_csrf();$tenantId=(int)($_POST['tenant_id']??0);$s=$pdo->prepare('SELECT id,settings FROM tenants WHERE id=? LIMIT 1');$s->execute([$tenantId]);$tenant=$s->fetch();if(!$tenant){em_flash('error','Empresa não encontrada.');em_go('receipt-ads');}
 $settings=json_decode((string)($tenant['settings']??'{}'),true);if(!is_array($settings))$settings=[];$image=$clean($_POST['image_url']??'',600);$target=$clean($_POST['target_url']??'',600);foreach(['image'=>&$image,'target'=>&$target]as&$url)if($url!==''&&(!filter_var($url,FILTER_VALIDATE_URL)||!in_array(strtolower((string)parse_url($url,PHP_URL_SCHEME)),['http','https'],true)))$url='';unset($url);
 $settings['platform_receipt_ad_enabled']=isset($_POST['enabled']);$settings['platform_receipt_ad_campaign']=$clean($_POST['campaign']??'',80);$settings['platform_receipt_ad_headline']=$clean($_POST['headline']??'',120);$settings['platform_receipt_ad_body']=$clean($_POST['body']??'',300);$settings['platform_receipt_ad_image_url']=$image;$settings['platform_receipt_ad_target_url']=$target;
 $u=$pdo->prepare('UPDATE tenants SET settings=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$u->execute([json_encode($settings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$tenantId]);Auth::audit('platform.receipt_ad_updated','tenant',(string)$tenantId,['enabled'=>$settings['platform_receipt_ad_enabled'],'campaign'=>$settings['platform_receipt_ad_campaign']]);em_flash('ok','Publicidade do comprovante atualizada.');em_go('receipt-ads');
}
$tenants=$pdo->query('SELECT id,name,status,settings FROM tenants ORDER BY name')->fetchAll();em_header('Publicidade nos comprovantes','super');?>
<section class="page-hero"><div><span class="eyebrow">ADM GERAL</span><h2>Publicidade no cupom</h2><p>Escolha individualmente quais empresas recebem propaganda no comprovante. A empresa não pode habilitar nem alterar este conteúdo.</p></div><div class="hero-actions"><a class="button secondary" href="<?=Security::e(app_url('?route=super'))?>">Voltar</a></div></section>
<?php foreach($tenants as$t):$st=json_decode((string)($t['settings']??'{}'),true);if(!is_array($st))$st=[];?><form method="post" class="card" style="margin-bottom:14px"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="tenant_id" value="<?=(int)$t['id']?>"><div class="section-head"><div><span class="eyebrow">EMPRESA #<?=(int)$t['id']?></span><h2><?=Security::e($t['name'])?></h2></div><label class="checkbox"><input type="checkbox" name="enabled"<?=em_checked($st['platform_receipt_ad_enabled']??false)?>> Exibir anúncio</label></div><div class="form-grid"><label>Campanha<input name="campaign" value="<?=Security::e($st['platform_receipt_ad_campaign']??'')?>"></label><label>Título<input name="headline" value="<?=Security::e($st['platform_receipt_ad_headline']??'')?>"></label><label class="span-2">Texto<textarea name="body" maxlength="300"><?=Security::e($st['platform_receipt_ad_body']??'')?></textarea></label><label>Imagem (URL)<input type="url" name="image_url" value="<?=Security::e($st['platform_receipt_ad_image_url']??'')?>"></label><label>Destino/QR do anúncio (URL)<input type="url" name="target_url" value="<?=Security::e($st['platform_receipt_ad_target_url']??'')?>"></label></div><button class="primary" style="margin-top:12px">Salvar publicidade desta empresa</button></form><?php endforeach;?><?php em_footer();
