<?php

declare(strict_types=1);
use EventMenu\Core\Auth;use EventMenu\Core\Security;
Auth::requirePermission('settings.manage');$tenantId=em_require_tenant();$s=$pdo->prepare('SELECT * FROM tenants WHERE id=? LIMIT 1');$s->execute([$tenantId]);$tenant=$s->fetch();if(!$tenant)exit('Empresa não encontrada.');$settings=json_decode((string)($tenant['settings']??'{}'),true);if(!is_array($settings))$settings=[];$clean=static fn(mixed$v,int$max=300):string=>mb_substr(trim((string)$v),0,$max);
if($_SERVER['REQUEST_METHOD']==='POST'){
 em_post_csrf();$paper=(string)($_POST['receipt_paper_width']??'80');if(!in_array($paper,['58','80'],true))$paper='80';$logo=$clean($_POST['receipt_logo_url']??'',600);if($logo!==''&&(!filter_var($logo,FILTER_VALIDATE_URL)||!in_array(strtolower((string)parse_url($logo,PHP_URL_SCHEME)),['http','https'],true)))$logo='';
 $settings=array_merge($settings,[
 'receipt_trade_name'=>$clean($_POST['receipt_trade_name']??'',120),'receipt_legal_name'=>$clean($_POST['receipt_legal_name']??'',160),'receipt_document'=>$clean($_POST['receipt_document']??'',30),'receipt_state_registration'=>$clean($_POST['receipt_state_registration']??'',40),'receipt_municipal_registration'=>$clean($_POST['receipt_municipal_registration']??'',40),'receipt_address'=>$clean($_POST['receipt_address']??'',260),'receipt_phone'=>$clean($_POST['receipt_phone']??'',40),'receipt_email'=>$clean($_POST['receipt_email']??'',120),'receipt_website'=>$clean($_POST['receipt_website']??'',160),'receipt_logo_url'=>$logo,'receipt_paper_width'=>$paper,
 'receipt_title'=>$clean($_POST['receipt_title']??'',80),'receipt_subtitle'=>$clean($_POST['receipt_subtitle']??'',120),'receipt_footer'=>$clean($_POST['receipt_footer']??'',300),'receipt_qr_label'=>$clean($_POST['receipt_qr_label']??'',120),'receipt_qr_help'=>$clean($_POST['receipt_qr_help']??'',180),
 'receipt_show_order_qr'=>isset($_POST['receipt_show_order_qr']),'receipt_show_ticket_qr'=>isset($_POST['receipt_show_ticket_qr']),'receipt_section_business'=>isset($_POST['receipt_section_business']),'receipt_section_customer'=>isset($_POST['receipt_section_customer']),'receipt_section_items'=>isset($_POST['receipt_section_items']),'receipt_section_payments'=>isset($_POST['receipt_section_payments']),'receipt_section_event'=>isset($_POST['receipt_section_event']),'receipt_show_operator'=>isset($_POST['receipt_show_operator']),'receipt_show_customer_phone'=>isset($_POST['receipt_show_customer_phone'])]);
 $u=$pdo->prepare('UPDATE tenants SET settings=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$u->execute([json_encode($settings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$tenantId]);Auth::audit('receipt.settings','tenant',(string)$tenantId,['paper_width'=>$paper,'schema'=>2]);em_flash('ok','Padrão do comprovante salvo. GO, Windows e Web passam a receber esta configuração do servidor.');em_go('receipt-settings');
}
$last=$pdo->prepare('SELECT id FROM orders WHERE tenant_id=? ORDER BY id DESC LIMIT 1');$last->execute([$tenantId]);$lastId=(int)($last->fetchColumn()?:0);$v=static fn(string$k,string$d=''):string=>Security::e((string)($settings[$k]??$d));em_header('Comprovante do pedido','settings');?>
<section class="page-hero"><div><span class="eyebrow">PADRÃO ÚNICO</span><h2>Comprovante controlado pelo servidor</h2><p>O mesmo contrato visual é enviado ao EventMenu GO e ao Windows. O QR do pedido também é gerado pelo servidor.</p></div><div class="hero-actions"><?php if($lastId):?><a class="button primary" target="_blank" href="<?=Security::e(app_url('?route=receipt&id='.$lastId))?>">Visualizar último</a><?php endif;?></div></section>
<form method="post" class="card"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><h2>Identificação</h2><div class="form-grid"><label>Nome fantasia<input name="receipt_trade_name" value="<?=$v('receipt_trade_name',(string)$tenant['name'])?>"></label><label>Razão social<input name="receipt_legal_name" value="<?=$v('receipt_legal_name')?>"></label><label>CPF/CNPJ<input name="receipt_document" value="<?=$v('receipt_document')?>"></label><label>IE<input name="receipt_state_registration" value="<?=$v('receipt_state_registration')?>"></label><label>IM<input name="receipt_municipal_registration" value="<?=$v('receipt_municipal_registration')?>"></label><label>Telefone<input name="receipt_phone" value="<?=$v('receipt_phone')?>"></label><label class="span-2">Endereço<input name="receipt_address" value="<?=$v('receipt_address')?>"></label><label>E-mail<input name="receipt_email" value="<?=$v('receipt_email')?>"></label><label>Site<input name="receipt_website" value="<?=$v('receipt_website')?>"></label><label class="span-2">Logo URL<input type="url" name="receipt_logo_url" value="<?=$v('receipt_logo_url')?>"></label></div>
<h2 style="margin-top:20px">Layout e textos</h2><div class="form-grid"><label>Largura<select name="receipt_paper_width"><option value="80"<?=em_selected($settings['receipt_paper_width']??'80','80')?>>80 mm</option><option value="58"<?=em_selected($settings['receipt_paper_width']??'80','58')?>>58 mm</option></select></label><label>Título<input name="receipt_title" value="<?=$v('receipt_title','COMPROVANTE NÃO FISCAL')?>"></label><label class="span-2">Subtítulo<input name="receipt_subtitle" value="<?=$v('receipt_subtitle','Documento operacional EventMenu')?>"></label><label>Texto acima do QR<input name="receipt_qr_label" value="<?=$v('receipt_qr_label','QR DO PEDIDO')?>"></label><label>Orientação do QR<input name="receipt_qr_help" value="<?=$v('receipt_qr_help')?>"></label><label class="span-2">Rodapé<textarea name="receipt_footer" maxlength="300"><?=$v('receipt_footer','Obrigado pela preferência!')?></textarea></label></div>
<h2 style="margin-top:20px">O que aparece</h2><div class="form-grid"><?php $checks=['receipt_section_business'=>'Dados da empresa','receipt_section_customer'=>'Cliente','receipt_show_customer_phone'=>'Telefone do cliente','receipt_section_items'=>'Itens','receipt_section_payments'=>'Pagamentos','receipt_show_operator'=>'Operador','receipt_section_event'=>'Dados do evento','receipt_show_order_qr'=>'QR do pedido','receipt_show_ticket_qr'=>'QR dos ingressos'];foreach($checks as$k=>$label):?><label class="checkbox"><input type="checkbox" name="<?=$k?>"<?=em_checked($settings[$k]??true)?>> <?=$label?></label><?php endforeach;?></div><button class="primary" style="margin-top:18px">Salvar padrão do comprovante</button></form>
<section class="card" style="margin-top:14px"><span class="eyebrow">PUBLICIDADE</span><h2>Espaço reservado para anúncio</h2><p>A empresa não controla a propaganda deste espaço. Campanhas no cupom são habilitadas exclusivamente pelo ADM Geral do EventMenu e podem ser direcionadas por empresa.</p></section><?php em_footer();
