<?php

declare(strict_types=1);

use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\RoundBlockSizeMode;
use Endroid\QrCode\Writer\SvgWriter;
use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\OrderFulfillmentService;
use EventMenu\Services\ReceiptService;

Auth::requirePermission('orders.view');
$orderId=(int)($_GET['id']??0);if($orderId<1)exit('Pedido inválido.');
try{$r=(new ReceiptService())->order($orderId);}catch(Throwable$e){http_response_code(400);exit(Security::e($e->getMessage()));}
$identity=$r['identity'];$order=$r['order'];$paper=(string)$identity['paper_width'];$width=$paper==='58'?54:76;
function receipt_money(int$c):string{return 'R$ '.number_format($c/100,2,',','.');}
function receipt_qty(float|int|string$v):string{$q=(float)$v;return abs($q-round($q))<0.0005?(string)(int)round($q):rtrim(rtrim(number_format($q,3,',','.'),'0'),',');}
function receipt_channel(string$c):string{return match($c){'counter'=>'Balcão / PDV','pickup'=>'Retirada','delivery'=>'Delivery','table'=>'Mesa / comanda','event'=>'Evento / Ingresso','event_bar'=>'Evento / Bar',default=>$c};}
function receipt_payment(string$m):string{return match(strtolower($m)){'cash','manual'=>'Dinheiro','pix'=>'Pix','credit','credit_card'=>'Cartão crédito','debit','debit_card'=>'Cartão débito','pagbank'=>'PagBank','mercadopago'=>'Mercado Pago','stripe'=>'Stripe',default=>ucfirst($m)};}
function receipt_qr(string$data,int$size=220):string{$qr=new QrCode(data:$data,encoding:new Encoding('ISO-8859-1'),errorCorrectionLevel:ErrorCorrectionLevel::Medium,size:$size,margin:8,roundBlockSizeMode:RoundBlockSizeMode::Margin);return(new SvgWriter())->write($qr)->getDataUri();}
$orderQr=null;if($identity['show_order_qr']&&!empty($order['public_token'])){$f=new OrderFulfillmentService();if($f->supportsChannel((string)$order['channel']))try{$orderQr=$f->qrDataUri((string)$order['public_token'],240);}catch(Throwable){$orderQr=null;}}
$auto=($_GET['autoprint']??'')==='1';
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Cupom pedido #<?= $orderId ?></title><style>
*{box-sizing:border-box}html,body{margin:0;padding:0;background:#ececf2;color:#000;font-family:Arial,Helvetica,sans-serif}.toolbar{position:sticky;top:0;display:flex;justify-content:center;gap:8px;padding:10px;background:#241552;z-index:3}.toolbar button,.toolbar a{border:0;border-radius:8px;padding:10px 14px;font-weight:700;text-decoration:none}.toolbar button{background:#6c35e2;color:#fff}.toolbar a{background:#fff;color:#241552}.receipt{width:<?= $width ?>mm;min-height:40mm;margin:16px auto;background:#fff;padding:3mm 2.5mm;box-shadow:0 8px 30px #0002;font-size:11px;line-height:1.25}.center{text-align:center}.logo{max-width:42mm;max-height:18mm;object-fit:contain;margin:0 auto 2mm;display:block}.title{font-size:15px;font-weight:800;margin:1mm 0}.small{font-size:9px}.muted{color:#333}.sep{border-top:1px dashed #000;margin:2mm 0}.row{display:flex;justify-content:space-between;gap:3mm}.row>span:last-child{text-align:right;white-space:nowrap}.item{margin:1.5mm 0}.item-head{display:flex;justify-content:space-between;gap:2mm;font-weight:700}.modifier{font-size:9px;padding-left:3mm}.total{font-size:14px;font-weight:900}.qr{display:block;width:34mm;height:34mm;margin:2mm auto}.ticket{page-break-inside:avoid;margin-top:2mm;padding-top:2mm;border-top:1px dashed #000}.ticket .qr{width:31mm;height:31mm}.badge{display:inline-block;border:1px solid #000;border-radius:10px;padding:1mm 2mm;font-size:8px;font-weight:700}.footer{margin-top:3mm;text-align:center;font-size:9px}.legal{font-size:8px;text-align:center;margin-top:2mm}.event-box{border:1px solid #000;padding:2mm;margin:2mm 0}@media print{html,body{background:#fff}.toolbar{display:none}.receipt{box-shadow:none;margin:0;width:<?= $width ?>mm;padding:1.5mm 1mm}@page{margin:1mm}}
</style></head><body><div class="toolbar"><button onclick="window.print()">Imprimir cupom</button><a href="<?= Security::e(app_url('?route=orders&view='.$orderId)) ?>">Voltar ao pedido</a></div><main class="receipt">
<?php if($identity['logo_url']):?><img class="logo" src="<?= Security::e($identity['logo_url']) ?>" alt="Logo"><?php endif;?>
<div class="center"><div class="title"><?= Security::e($identity['trade_name']) ?></div><?php if($identity['legal_name']&&$identity['legal_name']!==$identity['trade_name']):?><div><?= Security::e($identity['legal_name']) ?></div><?php endif;?><?php if($identity['document']):?><div>CPF/CNPJ: <?= Security::e($identity['document']) ?></div><?php endif;?><?php if($identity['state_registration']):?><div>IE: <?= Security::e($identity['state_registration']) ?></div><?php endif;?><?php if($identity['municipal_registration']):?><div>IM: <?= Security::e($identity['municipal_registration']) ?></div><?php endif;?><?php if($identity['address']):?><div><?= Security::e($identity['address']) ?></div><?php endif;?><?php if($identity['phone']):?><div>Tel/WhatsApp: <?= Security::e($identity['phone']) ?></div><?php endif;?><?php if($identity['email']):?><div><?= Security::e($identity['email']) ?></div><?php endif;?><?php if($identity['website']):?><div><?= Security::e($identity['website']) ?></div><?php endif;?></div>
<div class="sep"></div><div class="center"><strong>COMPROVANTE NÃO FISCAL</strong><br><span class="small">Documento operacional EventMenu · <?= Security::e($r['receipt_number']) ?></span></div><div class="sep"></div>
<div class="row"><span>Pedido</span><strong>#<?= $orderId ?></strong></div><div class="row"><span>Data/hora</span><span><?= Security::e(date('d/m/Y H:i',strtotime((string)$r['created_at']))) ?></span></div><div class="row"><span>Canal</span><span><?= Security::e(receipt_channel((string)$r['channel'])) ?></span></div><?php if($r['customer_name']):?><div class="row"><span>Cliente</span><span><?= Security::e($r['customer_name']) ?></span></div><?php endif;?><?php if($r['customer_phone']):?><div class="row"><span>Telefone</span><span><?= Security::e($r['customer_phone']) ?></span></div><?php endif;?><?php if($r['table_name']):?><div class="row"><span>Mesa</span><span><?= Security::e($r['table_name']) ?></span></div><?php endif;?><?php if($r['tab_label']):?><div class="row"><span>Comanda</span><span><?= Security::e($r['tab_label']) ?></span></div><?php endif;?><?php if($r['created_by_name']):?><div class="row"><span>Operador</span><span><?= Security::e($r['created_by_name']) ?></span></div><?php endif;?>
<?php if($r['event']):$e=$r['event'];?><div class="event-box"><strong>EVENTO</strong><div class="title" style="font-size:13px"><?= Security::e($e['name']) ?></div><div><?= Security::e(date('d/m/Y H:i',strtotime((string)$e['starts_at']))) ?></div><?php if($e['venue']):?><div><?= Security::e($e['venue']) ?></div><?php endif;?><?php if($e['address']):?><div><?= Security::e($e['address']) ?></div><?php endif;?></div><?php endif;?>
<div class="sep"></div><strong>ITENS</strong><?php foreach($r['items']as$i):?><div class="item"><div class="item-head"><span><?= receipt_qty($i['quantity']) ?>x <?= Security::e($i['name_snapshot']) ?></span><span><?= receipt_money((int)$i['total_cents']) ?></span></div><div class="small row"><span><?= receipt_money((int)$i['unit_price_cents']) ?> un.</span><span></span></div><?php foreach($r['modifiers'][(int)$i['id']]??[]as$m):?><div class="modifier">+ <?= receipt_qty($m['quantity']) ?> <?= Security::e($m['option_name_snapshot']) ?><?= (int)$m['total_delta_cents']!==0?' · '.receipt_money((int)$m['total_delta_cents']):'' ?></div><?php endforeach;?><?php if(!empty($i['notes'])):?><div class="small">Obs.: <?= Security::e($i['notes']) ?></div><?php endif;?></div><?php endforeach;?>
<div class="sep"></div><div class="row"><span>Subtotal</span><span><?= receipt_money((int)$r['subtotal_cents']) ?></span></div><?php if((int)$r['discount_cents']>0):?><div class="row"><span>Desconto</span><span>- <?= receipt_money((int)$r['discount_cents']) ?></span></div><?php endif;?><?php if((int)$r['delivery_fee_cents']>0):?><div class="row"><span>Entrega</span><span><?= receipt_money((int)$r['delivery_fee_cents']) ?></span></div><?php endif;?><div class="row total"><span>TOTAL</span><span><?= receipt_money((int)$r['total_cents']) ?></span></div>
<div class="sep"></div><strong>PAGAMENTO</strong><?php if(!$r['payments']):?><div>Pagamento: <?= Security::e((string)$r['payment_status']) ?></div><?php else:?><?php foreach($r['payments']as$p):?><div class="row"><span><?= Security::e(receipt_payment((string)($p['method']??$p['provider']))) ?> · <?= Security::e((string)$p['status']) ?></span><span><?= receipt_money((int)$p['amount_cents']) ?></span></div><?php if(!empty($p['provider_payment_id'])):?><div class="small">Transação: <?= Security::e((string)$p['provider_payment_id']) ?></div><?php endif;?><?php endforeach;?><?php endif;?>
<?php if($orderQr):?><div class="sep"></div><div class="center"><strong>QR DO PEDIDO</strong><img class="qr" src="<?= Security::e($orderQr) ?>" alt="QR do pedido"><span class="small"><?= in_array((string)$r['channel'],['counter','pickup'],true)?'Apresente este QR para retirada e conferência.':'QR para conferência do pedido.' ?></span></div><?php endif;?>
<?php if($r['tickets']):?><div class="sep"></div><div class="center"><strong>INGRESSOS</strong></div><?php foreach($r['tickets']as$t):?><div class="ticket"><div><strong><?= Security::e(($t['ticket_type_name']??'')?:'Ingresso') ?></strong> · <?= Security::e($t['batch_name']) ?></div><div>Código: <strong><?= Security::e($t['code']) ?></strong></div><div>Status: <?= Security::e($t['status']) ?></div><?php if($identity['show_ticket_qr']&&!empty($t['qr_token'])):$ticketUrl=app_absolute_url('ingresso.php?t='.rawurlencode((string)$t['qr_token']));?><img class="qr" src="<?= Security::e(receipt_qr($ticketUrl,220)) ?>" alt="QR ingresso"><div class="center small">QR individual de entrada</div><?php endif;?></div><?php endforeach;?><?php endif;?>
<div class="footer"><?= nl2br(Security::e($identity['footer'])) ?></div><div class="legal">Este comprovante não substitui NFC-e, NF-e ou documento fiscal legal quando exigido.</div><div class="center small" style="margin-top:2mm">Impresso em <?= Security::e(date('d/m/Y H:i:s')) ?> · EventMenu</div></main><?php if($auto):?><script>addEventListener('load',()=>setTimeout(()=>window.print(),250))</script><?php endif;?></body></html>
