<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

if(!Auth::can('reports.view')&&!Auth::can('reports.own')){http_response_code(403);exit('Acesso negado.');}$tenantId=em_require_tenant();$from=(string)($_GET['from']??date('Y-m-d',strtotime('-29 days')));$to=(string)($_GET['to']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||strtotime($from)===false||strtotime($to)===false||strtotime($from)>strtotime($to))exit('Período inválido.');if((strtotime($to)-strtotime($from))>366*86400)exit('O período máximo do relatório é de 366 dias.');$start=$from.' 00:00:00';$end=$to.' 23:59:59';
$ownPromoter=null;if(Auth::role()==='promoter'){$p=$pdo->prepare('SELECT id,name FROM promoters WHERE tenant_id=? AND user_id=? AND active=1');$p->execute([$tenantId,Auth::id()]);$ownPromoter=$p->fetch();if(!$ownPromoter){http_response_code(403);exit('Promotor sem vínculo.');}}
$totals=['sales'=>0,'orders'=>0,'commissions'=>0,'gross_payments'=>0,'refunds'=>0,'net'=>0,'avg_ticket'=>0,'cash_difference'=>0];$daily=[];$channels=[];$products=[];$events=[];$providers=[];$cashiers=[];$refundRows=[];
if($ownPromoter){
    $s=$pdo->prepare('SELECT DATE(o.created_at) day,COUNT(DISTINCT o.id) orders,COALESCE(SUM(o.total_cents),0) sales,COALESCE(SUM(pc.amount_cents),0) commissions FROM orders o LEFT JOIN promoter_commissions pc ON pc.order_id=o.id AND pc.promoter_id=? WHERE o.tenant_id=? AND o.promoter_id=? AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY DATE(o.created_at) ORDER BY day');$s->execute([$ownPromoter['id'],$tenantId,$ownPromoter['id'],$start,$end]);$daily=$s->fetchAll();foreach($daily as $r){$totals['sales']+=(int)$r['sales'];$totals['orders']+=(int)$r['orders'];$totals['commissions']+=(int)$r['commissions'];}$totals['net']=$totals['sales'];$totals['avg_ticket']=$totals['orders']?intdiv($totals['sales'],$totals['orders']):0;
}else{
    $s=$pdo->prepare('SELECT DATE(o.created_at) day,COUNT(*) orders,COALESCE(SUM(o.total_cents),0) sales FROM orders o WHERE o.tenant_id=? AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY DATE(o.created_at) ORDER BY day');$s->execute([$tenantId,$start,$end]);$daily=$s->fetchAll();foreach($daily as $r){$totals['sales']+=(int)$r['sales'];$totals['orders']+=(int)$r['orders'];}
    $q=$pdo->prepare('SELECT COALESCE(SUM(amount_cents),0) FROM payments WHERE tenant_id=? AND status IN ("paid","refunded","partially_refunded") AND verified_at BETWEEN ? AND ?');$q->execute([$tenantId,$start,$end]);$totals['gross_payments']=(int)$q->fetchColumn();
    $q=$pdo->prepare('SELECT COALESCE(SUM(amount_cents),0) FROM refunds WHERE tenant_id=? AND status="completed" AND completed_at BETWEEN ? AND ?');$q->execute([$tenantId,$start,$end]);$totals['refunds']=(int)$q->fetchColumn();$totals['net']=$totals['gross_payments']-$totals['refunds'];$totals['avg_ticket']=$totals['orders']?intdiv($totals['sales'],$totals['orders']):0;
    $q=$pdo->prepare('SELECT COALESCE(SUM(difference_cents),0) FROM cash_sessions WHERE tenant_id=? AND status="closed" AND closed_at BETWEEN ? AND ?');$q->execute([$tenantId,$start,$end]);$totals['cash_difference']=(int)$q->fetchColumn();
    $s=$pdo->prepare('SELECT channel,COUNT(*) orders,COALESCE(SUM(total_cents),0) sales FROM orders WHERE tenant_id=? AND payment_status="paid" AND created_at BETWEEN ? AND ? GROUP BY channel ORDER BY sales DESC');$s->execute([$tenantId,$start,$end]);$channels=$s->fetchAll();
    $s=$pdo->prepare('SELECT oi.name_snapshot product,SUM(oi.quantity) qty,SUM(oi.total_cents) gross FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.tenant_id=? AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY oi.name_snapshot ORDER BY gross DESC LIMIT 30');$s->execute([$tenantId,$start,$end]);$products=$s->fetchAll();
    $s=$pdo->prepare('SELECT e.name,COUNT(t.id) tickets,SUM(CASE WHEN t.status="checked_in" THEN 1 ELSE 0 END) checkins,SUM(CASE WHEN t.status="refunded" THEN 1 ELSE 0 END) refunded_tickets FROM events e LEFT JOIN tickets t ON t.event_id=e.id AND t.status IN ("paid","checked_in","refunded") WHERE e.tenant_id=? GROUP BY e.id,e.name ORDER BY e.starts_at DESC LIMIT 20');$s->execute([$tenantId]);$events=$s->fetchAll();
    $s=$pdo->prepare('SELECT provider,COUNT(*) qty,COALESCE(SUM(amount_cents),0) gross FROM payments WHERE tenant_id=? AND status IN ("paid","refunded","partially_refunded") AND verified_at BETWEEN ? AND ? GROUP BY provider ORDER BY gross DESC');$s->execute([$tenantId,$start,$end]);$providers=$s->fetchAll();
    $s=$pdo->prepare('SELECT cs.id,cs.opened_at,cs.closed_at,cs.opening_cash_cents,cs.expected_cash_cents,cs.closing_cash_cents,cs.difference_cents,u.name user_name FROM cash_sessions cs JOIN users u ON u.id=cs.user_id WHERE cs.tenant_id=? AND cs.opened_at BETWEEN ? AND ? ORDER BY cs.id DESC LIMIT 100');$s->execute([$tenantId,$start,$end]);$cashiers=$s->fetchAll();
    $s=$pdo->prepare('SELECT r.*,p.provider,p.provider_payment_id,o.id order_number,u.name requested_by_name FROM refunds r JOIN payments p ON p.id=r.payment_id JOIN orders o ON o.id=r.order_id LEFT JOIN users u ON u.id=r.requested_by WHERE r.tenant_id=? AND r.created_at BETWEEN ? AND ? ORDER BY r.id DESC LIMIT 100');$s->execute([$tenantId,$start,$end]);$refundRows=$s->fetchAll();
}
if(($_GET['format']??'')==='csv'&&!$ownPromoter){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="eventmenu-relatorio-'.$from.'-'.$to.'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['Data','Pedidos pagos','Vendas pagas (R$)'],';');foreach($daily as $r)fputcsv($out,[$r['day'],(int)$r['orders'],number_format(((int)$r['sales'])/100,2,',','')],';');fputcsv($out,[], ';');fputcsv($out,['Pagamentos brutos',number_format($totals['gross_payments']/100,2,',','')],';');fputcsv($out,['Estornos',number_format($totals['refunds']/100,2,',','')],';');fputcsv($out,['Líquido após estornos',number_format($totals['net']/100,2,',','')],';');fclose($out);exit;}
em_header('Relatórios','reports');
?><section class="card"><form method="get" class="actions"><input type="hidden" name="route" value="reports"><label>De<input type="date" name="from" value="<?= Security::e($from) ?>"></label><label>Até<input type="date" name="to" value="<?= Security::e($to) ?>"></label><button class="secondary">Aplicar</button><?php if(!$ownPromoter):?><a class="button secondary" href="<?= Security::e(app_url('?route=reports&from='.urlencode($from).'&to='.urlencode($to).'&format=csv')) ?>">Exportar CSV</a><?php endif;?></form></section>
<section class="grid" style="margin-top:18px;grid-template-columns:repeat(auto-fit,minmax(190px,1fr))"><div class="card metric"><span class="muted">Vendas pagas atuais</span><strong><?= em_money($totals['sales']) ?></strong></div><div class="card metric"><span class="muted">Pedidos pagos</span><strong><?= (int)$totals['orders'] ?></strong></div><div class="card metric"><span class="muted">Ticket médio</span><strong><?= em_money($totals['avg_ticket']) ?></strong></div><?php if($ownPromoter):?><div class="card metric"><span class="muted">Suas comissões</span><strong><?= em_money($totals['commissions']) ?></strong></div><?php else:?><div class="card metric"><span class="muted">Pagamentos brutos</span><strong><?= em_money($totals['gross_payments']) ?></strong></div><div class="card metric"><span class="muted">Estornos concluídos</span><strong><?= em_money($totals['refunds']) ?></strong></div><div class="card metric"><span class="muted">Líquido após estornos</span><strong><?= em_money($totals['net']) ?></strong></div><div class="card metric"><span class="muted">Diferença de caixas</span><strong><?= em_money($totals['cash_difference']) ?></strong></div><?php endif;?></section>
<section class="card" style="margin-top:18px"><h2>Por dia</h2><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Pedidos</th><th>Vendas</th><?php if($ownPromoter):?><th>Comissões</th><?php endif;?></tr></thead><tbody><?php foreach($daily as $r):?><tr><td><?= Security::e(date('d/m/Y',strtotime($r['day']))) ?></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td><?php if($ownPromoter):?><td><?= em_money($r['commissions']) ?></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section>
<?php if(!$ownPromoter):?><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(320px,1fr));margin-top:18px"><section class="card"><h2>Por canal</h2><div class="table-wrap"><table class="table"><thead><tr><th>Canal</th><th>Pedidos</th><th>Vendas</th></tr></thead><tbody><?php foreach($channels as $r):?><tr><td><?= Security::e($r['channel']) ?></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td></tr><?php endforeach;?></tbody></table></div></section><section class="card"><h2>Por provedor de pagamento</h2><div class="table-wrap"><table class="table"><thead><tr><th>Provedor</th><th>Transações</th><th>Bruto</th></tr></thead><tbody><?php foreach($providers as $r):?><tr><td><?= Security::e($r['provider']) ?></td><td><?= (int)$r['qty'] ?></td><td><?= em_money($r['gross']) ?></td></tr><?php endforeach;?></tbody></table></div></section><section class="card"><h2>Eventos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Evento</th><th>Ingressos</th><th>Check-ins</th><th>Estornados</th></tr></thead><tbody><?php foreach($events as $e):?><tr><td><?= Security::e($e['name']) ?></td><td><?= (int)$e['tickets'] ?></td><td><?= (int)$e['checkins'] ?></td><td><?= (int)$e['refunded_tickets'] ?></td></tr><?php endforeach;?></tbody></table></div></section></div>
<section class="card" style="margin-top:18px"><h2>Itens mais vendidos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Qtd.</th><th>Bruto</th></tr></thead><tbody><?php foreach($products as $r):?><tr><td><?= Security::e($r['product']) ?></td><td><?= Security::e((string)$r['qty']) ?></td><td><?= em_money($r['gross']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:18px"><div class="section-head"><h2>Turnos de caixa</h2><span class="muted">diferenças de fechamento</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Operador</th><th>Abertura</th><th>Fechamento</th><th>Esperado</th><th>Contado</th><th>Diferença</th></tr></thead><tbody><?php foreach($cashiers as $c):?><tr><td><?= Security::e($c['user_name']) ?></td><td><?= Security::e($c['opened_at']) ?></td><td><?= Security::e($c['closed_at']??'Aberto') ?></td><td><?= $c['expected_cash_cents']!==null?em_money($c['expected_cash_cents']):'—' ?></td><td><?= $c['closing_cash_cents']!==null?em_money($c['closing_cash_cents']):'—' ?></td><td><?= $c['difference_cents']!==null?em_money($c['difference_cents']):'—' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:18px"><div class="section-head"><h2>Estornos</h2><span class="muted"><?= count($refundRows) ?> registros no período</span></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Pedido</th><th>Provedor</th><th>Valor</th><th>Status</th><th>Solicitado por</th><th>Motivo</th></tr></thead><tbody><?php foreach($refundRows as $r):?><tr><td>#<?= (int)$r['id'] ?></td><td>#<?= (int)$r['order_number'] ?></td><td><?= Security::e($r['provider']) ?></td><td><?= em_money($r['amount_cents']) ?></td><td><span class="badge"><?= Security::e($r['status']) ?></span></td><td><?= Security::e($r['requested_by_name']??'Sistema') ?></td><td><?= Security::e($r['reason']) ?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?><?php em_footer();
