<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

if(!Auth::can('reports.view')&&!Auth::can('reports.own')){http_response_code(403);exit('Acesso negado.');}$tenantId=em_require_tenant();$from=(string)($_GET['from']??date('Y-m-d',strtotime('-29 days')));$to=(string)($_GET['to']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to))exit('Período inválido.');$start=$from.' 00:00:00';$end=$to.' 23:59:59';
$ownPromoter=null;if(Auth::role()==='promoter'){$p=$pdo->prepare('SELECT id,name FROM promoters WHERE tenant_id=? AND user_id=? AND active=1');$p->execute([$tenantId,Auth::id()]);$ownPromoter=$p->fetch();if(!$ownPromoter){http_response_code(403);exit('Promotor sem vínculo.');}}
if($ownPromoter){$s=$pdo->prepare('SELECT DATE(o.created_at) day,COUNT(*) orders,COALESCE(SUM(o.total_cents),0) sales,COALESCE(SUM(pc.amount_cents),0) commissions FROM orders o LEFT JOIN promoter_commissions pc ON pc.order_id=o.id AND pc.promoter_id=? WHERE o.tenant_id=? AND o.promoter_id=? AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY DATE(o.created_at) ORDER BY day');$s->execute([$ownPromoter['id'],$tenantId,$ownPromoter['id'],$start,$end]);$daily=$s->fetchAll();$totals=['sales'=>0,'orders'=>0,'commissions'=>0];foreach($daily as $r){$totals['sales']+=(int)$r['sales'];$totals['orders']+=(int)$r['orders'];$totals['commissions']+=(int)$r['commissions'];}$products=[];$channels=[];$events=[];}
else{$s=$pdo->prepare('SELECT DATE(created_at) day,COUNT(*) orders,COALESCE(SUM(total_cents),0) sales FROM orders WHERE tenant_id=? AND payment_status="paid" AND created_at BETWEEN ? AND ? GROUP BY DATE(created_at) ORDER BY day');$s->execute([$tenantId,$start,$end]);$daily=$s->fetchAll();$totals=['sales'=>0,'orders'=>0,'commissions'=>0];foreach($daily as $r){$totals['sales']+=(int)$r['sales'];$totals['orders']+=(int)$r['orders'];}$s=$pdo->prepare('SELECT channel,COUNT(*) orders,COALESCE(SUM(total_cents),0) sales FROM orders WHERE tenant_id=? AND payment_status="paid" AND created_at BETWEEN ? AND ? GROUP BY channel ORDER BY sales DESC');$s->execute([$tenantId,$start,$end]);$channels=$s->fetchAll();$s=$pdo->prepare('SELECT oi.name_snapshot product,SUM(oi.quantity) qty,SUM(oi.total_cents) gross FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.tenant_id=? AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY oi.name_snapshot ORDER BY gross DESC LIMIT 30');$s->execute([$tenantId,$start,$end]);$products=$s->fetchAll();$s=$pdo->prepare('SELECT e.name,COUNT(t.id) tickets,SUM(CASE WHEN t.status="checked_in" THEN 1 ELSE 0 END) checkins FROM events e LEFT JOIN tickets t ON t.event_id=e.id AND t.status IN ("paid","checked_in") WHERE e.tenant_id=? GROUP BY e.id,e.name ORDER BY e.starts_at DESC LIMIT 20');$s->execute([$tenantId]);$events=$s->fetchAll();}
em_header('Relatórios','reports');
?><section class="card"><form method="get" class="actions"><input type="hidden" name="route" value="reports"><label>De<input type="date" name="from" value="<?= Security::e($from) ?>"></label><label>Até<input type="date" name="to" value="<?= Security::e($to) ?>"></label><button class="secondary">Aplicar</button></form></section><section class="grid" style="margin-top:18px"><div class="card metric"><span class="muted">Vendas pagas</span><strong><?= em_money($totals['sales']) ?></strong></div><div class="card metric"><span class="muted">Pedidos pagos</span><strong><?= (int)$totals['orders'] ?></strong></div><?php if($ownPromoter):?><div class="card metric"><span class="muted">Suas comissões</span><strong><?= em_money($totals['commissions']) ?></strong></div><?php endif;?></section><section class="card" style="margin-top:18px"><h2>Por dia</h2><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Pedidos</th><th>Vendas</th><?php if($ownPromoter):?><th>Comissões</th><?php endif;?></tr></thead><tbody><?php foreach($daily as $r):?><tr><td><?= Security::e(date('d/m/Y',strtotime($r['day']))) ?></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td><?php if($ownPromoter):?><td><?= em_money($r['commissions']) ?></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></section><?php if(!$ownPromoter):?><div class="grid" style="grid-template-columns:1fr 1fr;margin-top:18px"><section class="card"><h2>Por canal</h2><div class="table-wrap"><table class="table"><tbody><?php foreach($channels as $r):?><tr><td><?= Security::e($r['channel']) ?></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td></tr><?php endforeach;?></tbody></table></div></section><section class="card"><h2>Eventos</h2><div class="table-wrap"><table class="table"><tbody><?php foreach($events as $e):?><tr><td><?= Security::e($e['name']) ?></td><td><?= (int)$e['tickets'] ?> ingressos</td><td><?= (int)$e['checkins'] ?> check-ins</td></tr><?php endforeach;?></tbody></table></div></section></div><section class="card" style="margin-top:18px"><h2>Itens mais vendidos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Qtd.</th><th>Bruto</th></tr></thead><tbody><?php foreach($products as $r):?><tr><td><?= Security::e($r['product']) ?></td><td><?= Security::e((string)$r['qty']) ?></td><td><?= em_money($r['gross']) ?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?><?php em_footer();
