<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\OperatingUnitService;

if(!Auth::can('reports.view')&&!Auth::can('reports.own')){http_response_code(403);exit('Acesso negado.');}
$tenantId=em_require_tenant();$from=(string)($_GET['from']??date('Y-m-d',strtotime('-29 days')));$to=(string)($_GET['to']??date('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)||strtotime($from)===false||strtotime($to)===false||strtotime($from)>strtotime($to))exit('Período inválido.');if((strtotime($to)-strtotime($from))>366*86400)exit('O período máximo do relatório é de 366 dias.');$start=$from.' 00:00:00';$end=$to.' 23:59:59';
$ownPromoter=null;if(Auth::role()==='promoter'){$p=$pdo->prepare('SELECT id,name FROM promoters WHERE tenant_id=? AND user_id=? AND active=1');$p->execute([$tenantId,Auth::id()]);$ownPromoter=$p->fetch();if(!$ownPromoter){http_response_code(403);exit('Promotor sem vínculo.');}}
$unitService=new OperatingUnitService();$availableUnits=$ownPromoter?[]:$unitService->availableForCurrentUser();$canConsolidate=in_array((string)Auth::role(),['admin','manager','super_admin'],true)&&Auth::can('reports.view');$scopeRaw=(string)($_GET['scope']??'current');$selectedUnit=null;$scopeIds=[];$scopeLabel='';
if(!$ownPromoter){
    if(!$availableUnits){em_header('Relatórios','reports');?><div class="alert error">Nenhuma unidade operacional disponível para este usuário.</div><?php em_footer();return;}
    $requestedUnit=(int)($_GET['unit_id']??0);if($requestedUnit>0){foreach($availableUnits as$u)if((int)$u['id']===$requestedUnit)$selectedUnit=$u;}
    if($scopeRaw==='all'&&$canConsolidate){$scopeIds=array_map('intval',array_column($availableUnits,'id'));$scopeLabel=count($scopeIds)>1?'Consolidado · unidades permitidas':(string)$availableUnits[0]['name'];}
    else{if(!$selectedUnit)$selectedUnit=$unitService->current();if(!$selectedUnit)$selectedUnit=$availableUnits[0];$scopeIds=[(int)$selectedUnit['id']];$scopeLabel=(string)$selectedUnit['name'];$scopeRaw='unit';}
}
$unitClause=static function(string$alias,array$ids):array{if(!$ids)return['',[]];$marks=implode(',',array_fill(0,count($ids),'?'));return[' AND '.$alias.'.unit_id IN ('.$marks.')',$ids];};
$totals=['sales'=>0,'orders'=>0,'commissions'=>0,'gross_payments'=>0,'refunds'=>0,'net'=>0,'avg_ticket'=>0,'cash_difference'=>0,'waste_cost'=>0,'purchases'=>0];$daily=[];$channels=[];$products=[];$events=[];$providers=[];$cashiers=[];$refundRows=[];$unitBreakdown=[];$wasteRows=[];$purchaseRows=[];
if($ownPromoter){
    $s=$pdo->prepare('SELECT DATE(o.created_at) day,COUNT(DISTINCT o.id) orders,COALESCE(SUM(o.total_cents),0) sales,COALESCE(SUM(pc.amount_cents),0) commissions FROM orders o LEFT JOIN promoter_commissions pc ON pc.order_id=o.id AND pc.promoter_id=? WHERE o.tenant_id=? AND o.promoter_id=? AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY DATE(o.created_at) ORDER BY day');$s->execute([$ownPromoter['id'],$tenantId,$ownPromoter['id'],$start,$end]);$daily=$s->fetchAll();foreach($daily as$r){$totals['sales']+=(int)$r['sales'];$totals['orders']+=(int)$r['orders'];$totals['commissions']+=(int)$r['commissions'];}$totals['net']=$totals['sales'];$totals['avg_ticket']=$totals['orders']?intdiv($totals['sales'],$totals['orders']):0;
}else{
    [$oUnit,$oArgs]=$unitClause('o',$scopeIds);
    $s=$pdo->prepare('SELECT DATE(o.created_at) day,COUNT(*) orders,COALESCE(SUM(o.total_cents),0) sales FROM orders o WHERE o.tenant_id=?'.$oUnit.' AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY DATE(o.created_at) ORDER BY day');$s->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$daily=$s->fetchAll();foreach($daily as$r){$totals['sales']+=(int)$r['sales'];$totals['orders']+=(int)$r['orders'];}$totals['avg_ticket']=$totals['orders']?intdiv($totals['sales'],$totals['orders']):0;
    $q=$pdo->prepare('SELECT COALESCE(SUM(p.amount_cents),0) FROM payments p JOIN orders o ON o.id=p.order_id AND o.tenant_id=p.tenant_id WHERE p.tenant_id=?'.$oUnit.' AND p.status IN ("paid","refunded","partially_refunded") AND p.verified_at BETWEEN ? AND ?');$q->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$totals['gross_payments']=(int)$q->fetchColumn();
    $q=$pdo->prepare('SELECT COALESCE(SUM(r.amount_cents),0) FROM refunds r JOIN orders o ON o.id=r.order_id AND o.tenant_id=r.tenant_id WHERE r.tenant_id=?'.$oUnit.' AND r.status="completed" AND r.completed_at BETWEEN ? AND ?');$q->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$totals['refunds']=(int)$q->fetchColumn();$totals['net']=$totals['gross_payments']-$totals['refunds'];
    [$csUnit,$csArgs]=$unitClause('cs',$scopeIds);$q=$pdo->prepare('SELECT COALESCE(SUM(cs.difference_cents),0) FROM cash_sessions cs WHERE cs.tenant_id=?'.$csUnit.' AND cs.status="closed" AND cs.closed_at BETWEEN ? AND ?');$q->execute(array_merge([$tenantId],$csArgs,[$start,$end]));$totals['cash_difference']=(int)$q->fetchColumn();
    $s=$pdo->prepare('SELECT o.channel,COUNT(*) orders,COALESCE(SUM(o.total_cents),0) sales FROM orders o WHERE o.tenant_id=?'.$oUnit.' AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY o.channel ORDER BY sales DESC');$s->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$channels=$s->fetchAll();
    $s=$pdo->prepare('SELECT oi.name_snapshot product,SUM(oi.quantity) qty,SUM(oi.total_cents) gross FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.tenant_id=?'.$oUnit.' AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? GROUP BY oi.name_snapshot ORDER BY gross DESC LIMIT 30');$s->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$products=$s->fetchAll();
    $s=$pdo->prepare('SELECT p.provider,COUNT(*) qty,COALESCE(SUM(p.amount_cents),0) gross FROM payments p JOIN orders o ON o.id=p.order_id AND o.tenant_id=p.tenant_id WHERE p.tenant_id=?'.$oUnit.' AND p.status IN ("paid","refunded","partially_refunded") AND p.verified_at BETWEEN ? AND ? GROUP BY p.provider ORDER BY gross DESC');$s->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$providers=$s->fetchAll();
    $s=$pdo->prepare('SELECT cs.id,cs.opened_at,cs.closed_at,cs.expected_cash_cents,cs.closing_cash_cents,cs.difference_cents,u.name user_name,ou.name unit_name FROM cash_sessions cs JOIN users u ON u.id=cs.user_id LEFT JOIN operating_units ou ON ou.id=cs.unit_id WHERE cs.tenant_id=?'.$csUnit.' AND cs.opened_at BETWEEN ? AND ? ORDER BY cs.id DESC LIMIT 150');$s->execute(array_merge([$tenantId],$csArgs,[$start,$end]));$cashiers=$s->fetchAll();
    $s=$pdo->prepare('SELECT r.*,p.provider,o.id order_number,u.name requested_by_name,ou.name unit_name FROM refunds r JOIN payments p ON p.id=r.payment_id JOIN orders o ON o.id=r.order_id LEFT JOIN users u ON u.id=r.requested_by LEFT JOIN operating_units ou ON ou.id=o.unit_id WHERE r.tenant_id=?'.$oUnit.' AND r.created_at BETWEEN ? AND ? ORDER BY r.id DESC LIMIT 100');$s->execute(array_merge([$tenantId],$oArgs,[$start,$end]));$refundRows=$s->fetchAll();
    [$iwUnit,$iwArgs]=$unitClause('iw',$scopeIds);$s=$pdo->prepare('SELECT iw.*,p.name product_name,ou.name unit_name FROM inventory_waste iw JOIN products p ON p.id=iw.product_id JOIN operating_units ou ON ou.id=iw.unit_id WHERE iw.tenant_id=?'.$iwUnit.' AND iw.created_at BETWEEN ? AND ? ORDER BY iw.id DESC LIMIT 100');$s->execute(array_merge([$tenantId],$iwArgs,[$start,$end]));$wasteRows=$s->fetchAll();$totals['waste_cost']=array_sum(array_map(static fn(array$r):int=>(int)$r['cost_cents'],$wasteRows));
    [$poUnit,$poArgs]=$unitClause('po',$scopeIds);$s=$pdo->prepare('SELECT po.id,po.total_cents,po.status,po.created_at,po.received_at,s.name supplier_name,ou.name unit_name FROM purchase_orders po LEFT JOIN suppliers s ON s.id=po.supplier_id JOIN operating_units ou ON ou.id=po.unit_id WHERE po.tenant_id=?'.$poUnit.' AND po.status="received" AND po.received_at BETWEEN ? AND ? ORDER BY po.id DESC LIMIT 100');$s->execute(array_merge([$tenantId],$poArgs,[$start,$end]));$purchaseRows=$s->fetchAll();$totals['purchases']=array_sum(array_map(static fn(array$r):int=>(int)$r['total_cents'],$purchaseRows));
    if(count($scopeIds)>1){$marks=implode(',',array_fill(0,count($scopeIds),'?'));$s=$pdo->prepare('SELECT ou.id,ou.name,COUNT(o.id) orders,COALESCE(SUM(o.total_cents),0) sales FROM operating_units ou LEFT JOIN orders o ON o.unit_id=ou.id AND o.tenant_id=ou.tenant_id AND o.payment_status="paid" AND o.created_at BETWEEN ? AND ? WHERE ou.tenant_id=? AND ou.id IN ('.$marks.') GROUP BY ou.id,ou.name ORDER BY sales DESC,ou.name');$s->execute(array_merge([$start,$end,$tenantId],$scopeIds));$unitBreakdown=$s->fetchAll();}
    $s=$pdo->prepare('SELECT e.name,COUNT(t.id) tickets,SUM(CASE WHEN t.status="checked_in" THEN 1 ELSE 0 END) checkins,SUM(CASE WHEN t.status="refunded" THEN 1 ELSE 0 END) refunded_tickets FROM events e LEFT JOIN tickets t ON t.event_id=e.id AND t.status IN ("paid","checked_in","refunded") WHERE e.tenant_id=? GROUP BY e.id,e.name ORDER BY e.starts_at DESC LIMIT 20');$s->execute([$tenantId]);$events=$s->fetchAll();
}
$scopeQuery=$ownPromoter?'':('&scope='.urlencode($scopeRaw).($selectedUnit?'&unit_id='.(int)$selectedUnit['id']:''));
if(($_GET['format']??'')==='csv'&&!$ownPromoter){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="eventmenu-relatorio-'.$from.'-'.$to.'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['Escopo',$scopeLabel],';');fputcsv($out,['Data','Pedidos pagos','Vendas pagas (R$)'],';');foreach($daily as$r)fputcsv($out,[$r['day'],(int)$r['orders'],number_format(((int)$r['sales'])/100,2,',','')],';');fputcsv($out,[],';');fputcsv($out,['Pagamentos brutos',number_format($totals['gross_payments']/100,2,',','')],';');fputcsv($out,['Estornos',number_format($totals['refunds']/100,2,',','')],';');fputcsv($out,['Líquido após estornos',number_format($totals['net']/100,2,',','')],';');fputcsv($out,['Compras recebidas',number_format($totals['purchases']/100,2,',','')],';');fputcsv($out,['Custo de perdas',number_format($totals['waste_cost']/100,2,',','')],';');fclose($out);exit;}
em_header('Relatórios','reports');
?>
<section class="page-hero"><div><span class="eyebrow"><?= $ownPromoter?'PROMOTOR':'GESTÃO · '.Security::e($scopeLabel) ?></span><h2><?= $ownPromoter?'Seu desempenho':'Relatórios gerenciais' ?></h2><p><?= $ownPromoter?'Vendas e comissões vinculadas ao seu código.':'Compare vendas, pagamentos, caixa, compras e perdas sem misturar unidades.' ?></p></div></section>
<section class="card"><form method="get" class="form-grid"><input type="hidden" name="route" value="reports"><label>De<input type="date" name="from" value="<?= Security::e($from) ?>"></label><label>Até<input type="date" name="to" value="<?= Security::e($to) ?>"></label><?php if(!$ownPromoter):?><label class="span-2">Escopo<select name="scope" id="report-scope"><?php foreach($availableUnits as$u):?><option value="unit:<?= (int)$u['id'] ?>"<?= count($scopeIds)===1&&(int)$scopeIds[0]===(int)$u['id']?' selected':'' ?>>Unidade · <?= Security::e($u['name']) ?></option><?php endforeach;?><?php if($canConsolidate&&count($availableUnits)>1):?><option value="all"<?= $scopeRaw==='all'?' selected':'' ?>>Consolidado · todas as unidades permitidas</option><?php endif;?></select><input type="hidden" name="unit_id" id="report-unit-id" value="<?= $selectedUnit?(int)$selectedUnit['id']:0 ?>"><input type="hidden" name="scope_mode" id="report-scope-mode" value="<?= Security::e($scopeRaw) ?>"></label><?php endif;?><div class="actions span-2"><button class="primary">Aplicar</button><?php if(!$ownPromoter):?><a class="button secondary" href="<?= Security::e(app_url('?route=reports&from='.urlencode($from).'&to='.urlencode($to).$scopeQuery.'&format=csv')) ?>">Exportar CSV</a><?php endif;?></div></form></section>
<?php if(!$ownPromoter):?><script>(()=>{const s=document.getElementById('report-scope'),u=document.getElementById('report-unit-id'),m=document.getElementById('report-scope-mode');s?.addEventListener('change',()=>{if(s.value==='all'){m.value='all';u.value='0'}else{m.value='unit';u.value=s.value.split(':')[1]||'0'}});const form=s?.form;form?.addEventListener('submit',()=>{const mode=m.value;if(mode==='all'){const hidden=document.createElement('input');hidden.type='hidden';hidden.name='scope';hidden.value='all';form.append(hidden)}else{const hidden=document.createElement('input');hidden.type='hidden';hidden.name='scope';hidden.value='unit';form.append(hidden)}})})();</script><?php endif;?>
<section class="grid" style="margin-top:18px;grid-template-columns:repeat(auto-fit,minmax(180px,1fr))"><div class="card metric"><span class="muted">Vendas pagas</span><strong><?= em_money($totals['sales']) ?></strong></div><div class="card metric"><span class="muted">Pedidos pagos</span><strong><?= (int)$totals['orders'] ?></strong></div><div class="card metric"><span class="muted">Ticket médio</span><strong><?= em_money($totals['avg_ticket']) ?></strong></div><?php if($ownPromoter):?><div class="card metric"><span class="muted">Suas comissões</span><strong><?= em_money($totals['commissions']) ?></strong></div><?php else:?><div class="card metric"><span class="muted">Líquido após estornos</span><strong><?= em_money($totals['net']) ?></strong></div><div class="card metric"><span class="muted">Compras recebidas</span><strong><?= em_money($totals['purchases']) ?></strong></div><div class="card metric"><span class="muted">Perdas de estoque</span><strong><?= em_money($totals['waste_cost']) ?></strong></div><div class="card metric"><span class="muted">Diferença de caixas</span><strong><?= em_money($totals['cash_difference']) ?></strong></div><?php endif;?></section>
<section class="card" style="margin-top:18px"><div class="section-head"><h2>Vendas por dia</h2><span class="muted"><?= Security::e($ownPromoter?'Seu código':$scopeLabel) ?></span></div><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Pedidos</th><th>Vendas</th><?php if($ownPromoter):?><th>Comissões</th><?php endif;?></tr></thead><tbody><?php foreach($daily as$r):?><tr><td><?= Security::e(date('d/m/Y',strtotime($r['day']))) ?></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td><?php if($ownPromoter):?><td><?= em_money($r['commissions']) ?></td><?php endif;?></tr><?php endforeach;?><?php if(!$daily):?><tr><td colspan="4">Sem vendas pagas no período.</td></tr><?php endif;?></tbody></table></div></section>
<?php if(!$ownPromoter):?>
<?php if($unitBreakdown):?><section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">COMPARATIVO</span><h2>Desempenho por unidade</h2></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Unidade</th><th>Pedidos pagos</th><th>Vendas</th><th>Ticket médio</th><th>Participação</th></tr></thead><tbody><?php foreach($unitBreakdown as$r):$pct=$totals['sales']>0?round((int)$r['sales']*100/$totals['sales'],1):0;?><tr><td><strong><?= Security::e($r['name']) ?></strong></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td><td><?= (int)$r['orders']?em_money((int)round((int)$r['sales']/(int)$r['orders'])):'—' ?></td><td><?= Security::e(number_format($pct,1,',','.')) ?>%</td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(320px,1fr));margin-top:18px"><section class="card"><h2>Por canal</h2><div class="table-wrap"><table class="table"><thead><tr><th>Canal</th><th>Pedidos</th><th>Vendas</th></tr></thead><tbody><?php foreach($channels as$r):?><tr><td><?= Security::e($r['channel']) ?></td><td><?= (int)$r['orders'] ?></td><td><?= em_money($r['sales']) ?></td></tr><?php endforeach;?></tbody></table></div></section><section class="card"><h2>Por provedor</h2><div class="table-wrap"><table class="table"><thead><tr><th>Provedor</th><th>Transações</th><th>Bruto</th></tr></thead><tbody><?php foreach($providers as$r):?><tr><td><?= Security::e($r['provider']) ?></td><td><?= (int)$r['qty'] ?></td><td><?= em_money($r['gross']) ?></td></tr><?php endforeach;?></tbody></table></div></section></div>
<section class="card" style="margin-top:18px"><h2>Itens mais vendidos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Qtd.</th><th>Bruto</th></tr></thead><tbody><?php foreach($products as$r):?><tr><td><?= Security::e($r['product']) ?></td><td><?= Security::e((string)$r['qty']) ?></td><td><?= em_money($r['gross']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(360px,1fr));margin-top:18px"><section class="card"><div class="section-head"><h2>Compras recebidas</h2><strong><?= em_money($totals['purchases']) ?></strong></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Unidade</th><th>Fornecedor</th><th>Total</th><th>Recebimento</th></tr></thead><tbody><?php foreach($purchaseRows as$r):?><tr><td>#<?= (int)$r['id'] ?></td><td><?= Security::e($r['unit_name']) ?></td><td><?= Security::e($r['supplier_name']??'—') ?></td><td><?= em_money($r['total_cents']) ?></td><td><?= Security::e($r['received_at']) ?></td></tr><?php endforeach;?><?php if(!$purchaseRows):?><tr><td colspan="5">Nenhuma compra recebida.</td></tr><?php endif;?></tbody></table></div></section><section class="card"><div class="section-head"><h2>Perdas de estoque</h2><strong><?= em_money($totals['waste_cost']) ?></strong></div><div class="table-wrap"><table class="table"><thead><tr><th>Unidade</th><th>Produto</th><th>Qtd.</th><th>Custo</th><th>Motivo</th></tr></thead><tbody><?php foreach($wasteRows as$r):?><tr><td><?= Security::e($r['unit_name']) ?></td><td><?= Security::e($r['product_name']) ?></td><td><?= Security::e((string)$r['quantity']) ?></td><td><?= em_money($r['cost_cents']) ?></td><td><?= Security::e($r['reason']??$r['reason_type']) ?></td></tr><?php endforeach;?><?php if(!$wasteRows):?><tr><td colspan="5">Nenhuma perda registrada.</td></tr><?php endif;?></tbody></table></div></section></div>
<section class="card" style="margin-top:18px"><div class="section-head"><h2>Turnos de caixa</h2><span class="muted">fechamentos no escopo selecionado</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Unidade</th><th>Operador</th><th>Abertura</th><th>Fechamento</th><th>Esperado</th><th>Contado</th><th>Diferença</th></tr></thead><tbody><?php foreach($cashiers as$c):?><tr><td><?= Security::e($c['unit_name']??'—') ?></td><td><?= Security::e($c['user_name']) ?></td><td><?= Security::e($c['opened_at']) ?></td><td><?= Security::e($c['closed_at']??'Aberto') ?></td><td><?= $c['expected_cash_cents']!==null?em_money($c['expected_cash_cents']):'—' ?></td><td><?= $c['closing_cash_cents']!==null?em_money($c['closing_cash_cents']):'—' ?></td><td><?= $c['difference_cents']!==null?em_money($c['difference_cents']):'—' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:18px"><div class="section-head"><h2>Estornos</h2><span class="muted"><?= count($refundRows) ?> registros</span></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Unidade</th><th>Pedido</th><th>Provedor</th><th>Valor</th><th>Status</th><th>Solicitado por</th><th>Motivo</th></tr></thead><tbody><?php foreach($refundRows as$r):?><tr><td>#<?= (int)$r['id'] ?></td><td><?= Security::e($r['unit_name']??'—') ?></td><td>#<?= (int)$r['order_number'] ?></td><td><?= Security::e($r['provider']) ?></td><td><?= em_money($r['amount_cents']) ?></td><td><?= Security::e($r['status']) ?></td><td><?= Security::e($r['requested_by_name']??'Sistema') ?></td><td><?= Security::e($r['reason']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:18px"><div class="section-head"><div><span class="eyebrow">EVENTOS · EMPRESA</span><h2>Ingressos e check-ins</h2></div><span class="muted">Eventos ainda são consolidados por empresa, não por unidade operacional.</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Evento</th><th>Ingressos</th><th>Check-ins</th><th>Estornados</th></tr></thead><tbody><?php foreach($events as$e):?><tr><td><?= Security::e($e['name']) ?></td><td><?= (int)$e['tickets'] ?></td><td><?= (int)$e['checkins'] ?></td><td><?= (int)$e['refunded_tickets'] ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;em_footer();
