<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use EventMenu\Core\Security;

Auth::requirePermission('tables.manage');$tenantId=em_require_tenant();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    if($action==='table-save'){
        $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$seats=max(1,(int)($_POST['seats']??4));if($name==='')exit('Nome da mesa inválido.');
        if($id){$s=$pdo->prepare('UPDATE restaurant_tables SET name=?,seats=?,status=? WHERE id=? AND tenant_id=?');$s->execute([$name,$seats,(string)($_POST['status']??'available'),$id,$tenantId]);}
        else{$s=$pdo->prepare('INSERT INTO restaurant_tables (tenant_id,name,seats,status,qr_token) VALUES (?,?,?,"available",?)');$s->execute([$tenantId,$name,$seats,bin2hex(random_bytes(20))]);$id=(int)$pdo->lastInsertId();}
        Auth::audit('table.saved','table',(string)$id);em_flash('ok','Mesa salva.');em_go('restaurant');
    }
    if($action==='tab-open'){
        $tableId=(int)($_POST['table_id']??0);$label=trim((string)($_POST['label']??''));
        try{$id=Database::transaction(function(PDO $tx)use($tableId,$tenantId,$label):int{$t=$tx->prepare(Database::portableSql($tx,'SELECT id,status FROM restaurant_tables WHERE id=? AND tenant_id=? FOR UPDATE'));$t->execute([$tableId,$tenantId]);$table=$t->fetch();if(!$table||$table['status']==='inactive')throw new RuntimeException('Mesa indisponível.');$open=$tx->prepare('SELECT id FROM tabs WHERE tenant_id=? AND table_id=? AND status="open"');$open->execute([$tenantId,$tableId]);if($open->fetchColumn())throw new RuntimeException('A mesa já possui comanda aberta.');$s=$tx->prepare('INSERT INTO tabs (tenant_id,table_id,opened_by,label,status) VALUES (?,?,?, ?,"open")');$s->execute([$tenantId,$tableId,Auth::id(),$label?:null]);$id=(int)$tx->lastInsertId();$tx->prepare('UPDATE restaurant_tables SET status="occupied" WHERE id=?')->execute([$tableId]);return $id;});Auth::audit('tab.opened','tab',(string)$id);em_flash('ok','Comanda aberta.');}catch(Throwable $e){em_flash('error',$e->getMessage());}em_go('restaurant');
    }
    if($action==='tab-close'){
        $id=(int)($_POST['id']??0);
        try{$tab=Database::transaction(function(PDO $tx)use($id,$tenantId):array{$s=$tx->prepare(Database::portableSql($tx,'SELECT * FROM tabs WHERE id=? AND tenant_id=? AND status="open" FOR UPDATE'));$s->execute([$id,$tenantId]);$tab=$s->fetch();if(!$tab)throw new RuntimeException('Comanda não encontrada.');$u=$tx->prepare('SELECT COUNT(*) FROM orders WHERE tenant_id=? AND tab_id=? AND status<>"cancelled" AND payment_status<>"paid"');$u->execute([$tenantId,$id]);if((int)$u->fetchColumn()>0)throw new RuntimeException('Existem pedidos não pagos nesta comanda.');$tx->prepare('UPDATE tabs SET status="closed",closed_by=?,closed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([Auth::id(),$id]);if($tab['table_id'])$tx->prepare('UPDATE restaurant_tables SET status="available" WHERE id=?')->execute([$tab['table_id']]);return $tab;});Auth::audit('tab.closed','tab',(string)$id);em_flash('ok','Comanda encerrada.');}catch(Throwable $e){em_flash('error',$e->getMessage());}em_go('restaurant');
    }
}
$s=$pdo->prepare('SELECT rt.*,tb.id open_tab_id,tb.label,(SELECT COALESCE(SUM(o.total_cents),0) FROM orders o WHERE o.tab_id=tb.id AND o.status<>"cancelled") tab_total,(SELECT COALESCE(SUM(CASE WHEN o.payment_status<>"paid" THEN o.total_cents ELSE 0 END),0) FROM orders o WHERE o.tab_id=tb.id AND o.status<>"cancelled") unpaid_total FROM restaurant_tables rt LEFT JOIN tabs tb ON tb.table_id=rt.id AND tb.status="open" WHERE rt.tenant_id=? ORDER BY rt.name');$s->execute([$tenantId]);$tables=$s->fetchAll();
em_header('Mesas e comandas','restaurant');
?><div class="grid" style="grid-template-columns:minmax(280px,1fr) minmax(0,2fr)"><section class="card"><h2>Nova mesa</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="table-save"><label>Nome<input name="name" placeholder="Mesa 01" required></label><label>Lugares<input type="number" name="seats" min="1" value="4"></label><button class="primary span-2">Criar mesa</button></form></section><section class="card"><div class="section-head"><h2>Salão</h2><span class="muted"><?= count($tables) ?> mesas</span></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(240px,1fr))"><?php foreach($tables as $t):?><article class="card"><div class="section-head"><h3><?= Security::e($t['name']) ?></h3><span class="badge"><?= Security::e($t['status']) ?></span></div><p class="muted"><?= (int)$t['seats'] ?> lugares</p><?php if($t['open_tab_id']):?><p><strong>Comanda #<?= (int)$t['open_tab_id'] ?></strong> <?= Security::e($t['label']??'') ?><br>Total: <?= em_money($t['tab_total']) ?><br><span class="muted">Em aberto: <?= em_money($t['unpaid_total']) ?></span></p><form method="post" onsubmit="return confirm('Encerrar esta comanda?')"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="tab-close"><input type="hidden" name="id" value="<?= (int)$t['open_tab_id'] ?>"><button class="secondary">Encerrar comanda</button></form><?php else:?><form method="post"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="tab-open"><input type="hidden" name="table_id" value="<?= (int)$t['id'] ?>"><label>Identificação<input name="label" placeholder="Ex.: João / aniversário"></label><button class="primary" style="margin-top:8px">Abrir comanda</button></form><?php endif;?><p style="margin-top:12px"><a href="<?= Security::e(app_url('mesa.php?t='.urlencode($t['qr_token']))) ?>" target="_blank">Link/QR da mesa</a></p></article><?php endforeach;?></div></section></div><?php em_footer();
