<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

if(!Auth::can('dashboard')&&!Auth::can('orders.view')&&!Auth::can('counter.orders')){http_response_code(403);exit('Acesso negado.');}$tenantId=em_require_tenant();$q=trim((string)($_GET['q']??''));$like='%'.$q.'%';$results=[];
if($q!==''){
    if(Auth::can('catalog.manage')){$s=$pdo->prepare('SELECT id,name,sku FROM products WHERE tenant_id=? AND (name LIKE ? OR sku LIKE ?) ORDER BY active DESC,name LIMIT 10');$s->execute([$tenantId,$like,$like]);foreach($s->fetchAll()as$r)$results[]=['type'=>'Produto','title'=>$r['name'],'sub'=>$r['sku']??'','url'=>em_url('/?route=products&edit='.(int)$r['id'])];}
    if(Auth::can('orders.view')||Auth::can('counter.orders')){$sql='SELECT o.id,o.channel,o.status,c.name customer_name FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.tenant_id=? AND (CAST(o.id AS CHAR)=? OR c.name LIKE ?)';$args=[$tenantId,ltrim($q,'#'),$like];if(Auth::role()==='counter'){$sql.=' AND o.channel="counter" AND o.created_by=?';$args[]=Auth::id();}$sql.=' ORDER BY o.id DESC LIMIT 15';$s=$pdo->prepare($sql);$s->execute($args);foreach($s->fetchAll()as$r)$results[]=['type'=>'Pedido','title'=>'#'.$r['id'].' · '.($r['customer_name']?:'Cliente'),'sub'=>$r['channel'].' · '.$r['status'],'url'=>em_url('/?route='.(Auth::role()==='counter'?'counter-orders':'orders').'&id='.(int)$r['id'])];}
    if(Auth::can('events.manage')){$s=$pdo->prepare('SELECT id,name,venue FROM events WHERE tenant_id=? AND (name LIKE ? OR venue LIKE ?) ORDER BY starts_at DESC LIMIT 10');$s->execute([$tenantId,$like,$like]);foreach($s->fetchAll()as$r)$results[]=['type'=>'Evento','title'=>$r['name'],'sub'=>$r['venue']??'','url'=>em_url('/?route=events&edit='.(int)$r['id'])];}
    if(Auth::can('customers.manage')){$s=$pdo->prepare('SELECT id,name,email,phone FROM customers WHERE tenant_id=? AND (name LIKE ? OR email LIKE ? OR phone LIKE ?) ORDER BY updated_at DESC LIMIT 10');$s->execute([$tenantId,$like,$like,$like]);foreach($s->fetchAll()as$r)$results[]=['type'=>'Cliente','title'=>$r['name'],'sub'=>trim(($r['phone']??'').' '.($r['email']??'')),'url'=>em_url('/?route=customers&edit='.(int)$r['id'])];}
    if(Auth::can('tickets.manage')){$s=$pdo->prepare('SELECT tk.id,tk.code,e.name event_name FROM tickets tk JOIN events e ON e.id=tk.event_id WHERE tk.tenant_id=? AND (tk.code LIKE ? OR tk.qr_token LIKE ? OR e.name LIKE ?) ORDER BY tk.id DESC LIMIT 10');$s->execute([$tenantId,$like,$like,$like]);foreach($s->fetchAll()as$r)$results[]=['type'=>'Ingresso','title'=>$r['event_name'],'sub'=>$r['code'],'url'=>em_url('/?route=tickets&q='.urlencode($r['code']))];}
}
em_header('Busca global','search');?>
<section class="card"><form method="get" class="actions"><input type="hidden" name="route" value="search"><input name="q" value="<?= Security::e($q) ?>" placeholder="Pedido, produto, evento, cliente ou ingresso" autofocus style="min-width:min(520px,70vw)"><button class="primary">Buscar</button></form></section><?php if($q!==''):?><section class="card" style="margin-top:16px"><div class="section-head"><h2>Resultados</h2><span class="muted"><?= count($results) ?> encontrados</span></div><?php foreach($results as$r):?><a href="<?= Security::e($r['url']) ?>" style="display:block;padding:14px 0;border-bottom:1px solid var(--line);text-decoration:none;color:inherit"><span class="badge"><?= Security::e($r['type']) ?></span> <strong><?= Security::e($r['title']) ?></strong><br><small class="muted"><?= Security::e($r['sub']) ?></small></a><?php endforeach;?><?php if(!$results):?><p class="muted">Nada encontrado.</p><?php endif;?></section><?php endif;?><?php em_footer();
