<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;

Auth::requirePermission('settings.manage');$tenantId=em_require_tenant();
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$name=trim((string)($_POST['name']??''));if($name==='')exit('Nome inválido.');$settings=['delivery_fee_cents'=>(int)round((float)str_replace(',','.',(string)($_POST['delivery_fee']??'0'))*100),'min_delivery_order_cents'=>(int)round((float)str_replace(',','.',(string)($_POST['min_delivery_order']??'0'))*100),'points_enabled'=>isset($_POST['points_enabled']),'menu_message'=>mb_substr(trim((string)($_POST['menu_message']??'')),0,300),'whatsapp'=>mb_substr(trim((string)($_POST['whatsapp']??'')),0,30)];$s=$pdo->prepare('UPDATE tenants SET name=?,settings=? WHERE id=?');$s->execute([$name,json_encode($settings,JSON_UNESCAPED_UNICODE),$tenantId]);Auth::audit('tenant.settings','tenant',(string)$tenantId);em_flash('ok','Configurações salvas.');em_go('settings');
}
$s=$pdo->prepare('SELECT * FROM tenants WHERE id=?');$s->execute([$tenantId]);$tenant=$s->fetch();$settings=json_decode((string)($tenant['settings']??'{}'),true)?:[];
em_header('Configurações','settings');
?><section class="card" style="max-width:780px"><h2>Empresa e operação</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><label class="span-2">Nome da empresa<input name="name" required value="<?= Security::e($tenant['name']) ?>"></label><label>Taxa padrão de entrega<input name="delivery_fee" inputmode="decimal" value="<?= Security::e(number_format(((int)($settings['delivery_fee_cents']??0))/100,2,',','')) ?>"></label><label>Pedido mínimo delivery<input name="min_delivery_order" inputmode="decimal" value="<?= Security::e(number_format(((int)($settings['min_delivery_order_cents']??0))/100,2,',','')) ?>"></label><label class="span-2">WhatsApp<input name="whatsapp" value="<?= Security::e($settings['whatsapp']??'') ?>"></label><label class="span-2">Mensagem no cardápio<textarea name="menu_message"><?= Security::e($settings['menu_message']??'') ?></textarea></label><label class="checkbox span-2"><input type="checkbox" name="points_enabled"<?= em_checked($settings['points_enabled']??true) ?>> Programa de pontos ativo</label><button class="primary span-2">Salvar configurações</button></form><hr style="border-color:var(--line);margin:24px 0"><h3>Identificação técnica</h3><p>Slug: <code><?= Security::e($tenant['slug']) ?></code><br>Plano: <span class="badge"><?= Security::e($tenant['plan']) ?></span><br>Status: <span class="badge"><?= Security::e($tenant['status']) ?></span></p><p class="muted">O APP_KEY deve permanecer secreto. Alterá-lo depois de cadastrar gateways impedirá descriptografar credenciais existentes.</p></section><?php em_footer();
