<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\BusinessUnitService;

Auth::requirePermission('units.manage');$tenantId=em_require_tenant();$service=new BusinessUnitService();
if($_SERVER['REQUEST_METHOD']==='POST'){em_post_csrf();$action=(string)($_POST['action']??'');try{
    if($action==='save'){$id=(int)($_POST['id']??0);$service->save($tenantId,$_POST,$id?:null);em_flash('ok','Unidade salva.');}
    elseif($action==='select'){Auth::selectUnit(($id=(int)($_POST['unit_id']??0))>0?$id:null);em_flash('ok',$id?'Unidade ativa alterada.':'Visualização de todas as unidades ativada.');}
}catch(Throwable $e){em_flash('error',$e->getMessage());}em_go('units');}
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=$pdo->prepare('SELECT * FROM business_units WHERE id=? AND tenant_id=?');$s->execute([$editId,$tenantId]);$edit=$s->fetch()?:null;}$s=$pdo->prepare('SELECT bu.*,(SELECT COUNT(*) FROM user_units uu WHERE uu.unit_id=bu.id) users_count FROM business_units bu WHERE bu.tenant_id=? ORDER BY bu.status="active" DESC,bu.name');$s->execute([$tenantId]);$units=$s->fetchAll();
em_header('Unidades','units');?>
<div class="grid" style="grid-template-columns:minmax(280px,1fr) minmax(0,2fr)"><section class="card"><h2><?= $edit?'Editar unidade':'Nova unidade' ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label class="span-2">Nome<input name="name" required value="<?= Security::e($edit['name']??'') ?>"></label><label>Slug<input name="slug" value="<?= Security::e($edit['slug']??'') ?>" placeholder="gerado automaticamente"></label><label>Status<select name="status"><option value="active"<?= em_selected($edit['status']??'active','active') ?>>Ativa</option><option value="inactive"<?= em_selected($edit['status']??'','inactive') ?>>Inativa</option><option value="archived"<?= em_selected($edit['status']??'','archived') ?>>Arquivada</option></select></label><label class="span-2">Endereço<input name="address" value="<?= Security::e($edit['address']??'') ?>"></label><label>Cidade<input name="city" value="<?= Security::e($edit['city']??'') ?>"></label><label>Telefone<input name="phone" value="<?= Security::e($edit['phone']??'') ?>"></label><button class="primary span-2">Salvar unidade</button></form></section><section class="card"><div class="section-head"><h2>Filiais / unidades</h2><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="select"><select name="unit_id"><option value="0">Todas as unidades</option><?php foreach($units as$u):if($u['status']!=='active')continue;?><option value="<?= (int)$u['id'] ?>"<?= em_selected(Auth::unitId(),$u['id']) ?>><?= Security::e($u['name']) ?></option><?php endforeach;?></select><button class="secondary">Usar</button></form></div><div class="table-wrap"><table class="table"><thead><tr><th>Unidade</th><th>Contato</th><th>Equipe</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($units as$u):?><tr><td><strong><?= Security::e($u['name']) ?></strong><br><span class="muted"><?= Security::e($u['slug']) ?> · <?= Security::e($u['city']??'') ?></span></td><td><?= Security::e($u['phone']??'—') ?></td><td><?= (int)$u['users_count'] ?></td><td><span class="badge"><?= Security::e($u['status']) ?></span></td><td><a class="button secondary" href="<?= Security::e(em_url('/?route=units&edit='.(int)$u['id'])) ?>">Editar</a></td></tr><?php endforeach;?></tbody></table></div></section></div><?php em_footer();
