<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Database;
use EventMenu\Core\Security;

Auth::requirePermission('users.manage');$tenantId=em_require_tenant();$roles=['admin','manager','cashier','waiter','kitchen','delivery','promoter'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    if($action==='save'){
        $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$phone=trim((string)($_POST['phone']??''));$role=(string)($_POST['role']??'waiter');$status=(string)($_POST['status']??'active');$password=(string)($_POST['password']??'');if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($role,$roles,true)||!in_array($status,['active','blocked'],true))exit('Usuário inválido.');if($id===Auth::id()&&($status==='blocked'||$role!=='admin')&&Auth::role()==='admin')exit('Você não pode bloquear ou remover sua própria função administrativa.');
        try{Database::transaction(function(PDO $tx)use(&$id,$tenantId,$name,$email,$phone,$role,$status,$password):void{
            if($id){$u=$tx->prepare(Database::portableSql($tx,'SELECT id FROM users WHERE id=? AND tenant_id=? FOR UPDATE'));$u->execute([$id,$tenantId]);if(!$u->fetchColumn())throw new RuntimeException('Usuário não encontrado.');if($password!==''&&strlen($password)<10)throw new RuntimeException('A senha precisa ter pelo menos 10 caracteres.');if($password!==''){$s=$tx->prepare('UPDATE users SET name=?,email=?,phone=?,role=?,status=?,password_hash=? WHERE id=? AND tenant_id=?');$s->execute([$name,$email,$phone?:null,$role,$status,password_hash($password,PASSWORD_DEFAULT),$id,$tenantId]);}else{$s=$tx->prepare('UPDATE users SET name=?,email=?,phone=?,role=?,status=? WHERE id=? AND tenant_id=?');$s->execute([$name,$email,$phone?:null,$role,$status,$id,$tenantId]);}}
            else{if(strlen($password)<10)throw new RuntimeException('A senha precisa ter pelo menos 10 caracteres.');$s=$tx->prepare('INSERT INTO users (tenant_id,name,email,phone,password_hash,role,status) VALUES (?,?,?,?,?,?,?)');$s->execute([$tenantId,$name,$email,$phone?:null,password_hash($password,PASSWORD_DEFAULT),$role,$status]);$id=(int)$tx->lastInsertId();}
            if($status==='blocked'){
                $tx->prepare('UPDATE api_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND user_id=? AND revoked_at IS NULL')->execute([$tenantId,$id]);
                $tx->prepare('UPDATE nfc_devices SET status="revoked",revoked_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND user_id=? AND status<>"revoked"')->execute([$tenantId,$id]);
                $tx->prepare('UPDATE nfc_payment_intents SET status="failed" WHERE tenant_id=? AND user_id=? AND status="created"')->execute([$tenantId,$id]);
            }
        });Auth::audit('user.saved','user',(string)$id,['role'=>$role,'status'=>$status]);em_flash('ok',$status==='blocked'?'Usuário bloqueado; acessos do app e NFC foram revogados.':'Usuário salvo.');}catch(Throwable $e){em_flash('error',$e->getMessage());}em_go('users');
    }
}
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=$pdo->prepare('SELECT * FROM users WHERE id=? AND tenant_id=?');$s->execute([$editId,$tenantId]);$edit=$s->fetch()?:null;}
$s=$pdo->prepare('SELECT u.*,(SELECT COUNT(*) FROM nfc_devices d WHERE d.user_id=u.id AND d.status="active") active_devices,(SELECT COUNT(*) FROM api_tokens at WHERE at.user_id=u.id AND at.revoked_at IS NULL AND at.expires_at>CURRENT_TIMESTAMP) active_app_tokens FROM users u WHERE tenant_id=? ORDER BY status,name');$s->execute([$tenantId]);$users=$s->fetchAll();
em_header('Equipe e permissões','users');
?><div class="grid" style="grid-template-columns:minmax(300px,1fr) minmax(0,2fr)"><section class="card"><h2><?= $edit?'Editar usuário':'Novo usuário' ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= em_csrf() ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label class="span-2">Nome<input name="name" required value="<?= Security::e($edit['name']??'') ?>"></label><label class="span-2">E-mail<input type="email" name="email" required value="<?= Security::e($edit['email']??'') ?>"></label><label class="span-2">Telefone<input name="phone" value="<?= Security::e($edit['phone']??'') ?>"></label><label>Função<select name="role"><?php foreach($roles as $r):?><option value="<?= $r ?>"<?= em_selected($edit['role']??'waiter',$r) ?>><?= Security::e($r) ?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="active"<?= em_selected($edit['status']??'active','active') ?>>Ativo</option><option value="blocked"<?= em_selected($edit['status']??'','blocked') ?>>Bloqueado</option></select></label><label class="span-2"><?= $edit?'Nova senha (deixe vazio para manter)':'Senha' ?><input type="password" name="password" minlength="10"<?= $edit?'':' required' ?>></label><button class="primary span-2">Salvar usuário</button><?php if($edit):?><a class="button secondary span-2" href="<?= Security::e(app_url('?route=users')) ?>">Cancelar</a><?php endif;?></form><p class="muted">Garçom e entregador não podem confirmar pagamentos manualmente. Ao bloquear alguém, tokens do app, aparelhos NFC vinculados e intenções NFC pendentes são revogados.</p></section><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Usuário</th><th>Função</th><th>Status</th><th>Último login</th><th>App</th><th>NFC</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><strong><?= Security::e($u['name']) ?></strong><br><span class="muted"><?= Security::e($u['email']) ?></span></td><td><span class="badge"><?= Security::e($u['role']) ?></span></td><td><?= Security::e($u['status']) ?></td><td><?= Security::e($u['last_login_at']??'—') ?></td><td><?= (int)$u['active_app_tokens'] ?></td><td><?= (int)$u['active_devices'] ?></td><td><a class="button secondary" href="<?= Security::e(app_url('?route=users&edit='.(int)$u['id'])) ?>">Editar</a></td></tr><?php endforeach;?></tbody></table></div></section></div><?php em_footer();
