<?php

declare(strict_types=1);

use EventMenu\Core\Auth;
use EventMenu\Core\Security;
use EventMenu\Services\WhatsAppIntegrationService;

Auth::requirePermission('settings.manage');
$tenantId=(int)(Auth::tenantId()??0);if($tenantId<1){http_response_code(403);exit('Selecione uma empresa para configurar o WhatsApp.');}
$service=new WhatsAppIntegrationService();
$eventLabels=['order_received'=>'Pedido recebido','order_confirmed'=>'Pedido confirmado','payment_confirmed'=>'Pagamento confirmado','preparing'=>'Pedido em preparo','ready'=>'Pedido pronto','out_for_delivery'=>'Saiu para entrega','delivered'=>'Pedido entregue','cancelled'=>'Pedido cancelado'];

if(($_GET['ajax']??'')==='status'){
    header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
    try{echo json_encode(['ok'=>true,'data'=>$service->status($pdo,$tenantId,true)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}catch(Throwable){http_response_code(503);echo json_encode(['ok'=>false,'error'=>'Não foi possível consultar o WhatsApp agora.'],JSON_UNESCAPED_UNICODE);}exit;
}
if($_SERVER['REQUEST_METHOD']==='POST'){
    em_post_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='save'){$templates=[];foreach($eventLabels as$event=>$label)$templates[$event]=['enabled'=>isset($_POST['event_enabled'][$event]),'message'=>(string)($_POST['event_message'][$event]??'')];$service->saveConfiguration($pdo,$tenantId,isset($_POST['automation_enabled']),$templates);Auth::audit('whatsapp.settings_saved','whatsapp_connection',(string)$tenantId,['automation_enabled'=>isset($_POST['automation_enabled'])]);em_flash('ok','Configuração do WhatsApp salva.');}
        elseif($action==='save_commerce'){$service->ensureConnection($pdo,$tenantId);$enabled=isset($_POST['commerce_enabled']);$pdo->prepare('UPDATE whatsapp_connections SET commerce_enabled=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=?')->execute([$enabled?1:0,$tenantId]);Auth::audit('whatsapp.commerce_toggled','whatsapp_connection',(string)$tenantId,['commerce_enabled'=>$enabled]);em_flash('ok',$enabled?'WhatsApp Commerce ativado para receber e processar conversas.':'WhatsApp Commerce pausado. As mensagens recebidas continuam sendo registradas sem respostas automáticas.');}
        elseif($action==='connect'||$action==='reconnect'){$service->connect($pdo,$tenantId,false);Auth::audit('whatsapp.connect_requested','whatsapp_connection',(string)$tenantId,['action'=>$action]);em_flash('ok','Conexão iniciada. Se necessário, escaneie o QR Code abaixo.');}
        elseif($action==='replace'){$service->connect($pdo,$tenantId,true);Auth::audit('whatsapp.number_replace_requested','whatsapp_connection',(string)$tenantId,[]);em_flash('ok','Sessão anterior encerrada. Escaneie o novo QR Code para conectar outro número.');}
        elseif($action==='disconnect'){$service->disconnect($pdo,$tenantId);Auth::audit('whatsapp.disconnected','whatsapp_connection',(string)$tenantId,[]);em_flash('ok','WhatsApp desconectado desta empresa.');}
    }catch(Throwable$e){em_flash('error',$e->getMessage());}
    header('Location: '.app_url('whatsapp.php'));exit;
}
$connection=$service->status($pdo,$tenantId,true);$templates=$service->templates($pdo,$tenantId);$templatesByEvent=[];foreach($templates as$row)$templatesByEvent[(string)$row['event_type']]=$row;$defaults=$service->defaultTemplates();$bridgeEnabled=!empty($connection['bridge_enabled']);$status=(string)($connection['status']??'disconnected');
$commerceStmt=$pdo->prepare('SELECT commerce_enabled FROM whatsapp_connections WHERE tenant_id=? LIMIT 1');$commerceStmt->execute([$tenantId]);$commerceEnabled=(int)($commerceStmt->fetchColumn()?:0)===1;
$statusLabel=match($status){'connected'=>'Conectado','starting'=>'Iniciando','qr'=>'Aguardando leitura do QR','reconnecting'=>'Reconectando','error'=>'Precisa de atenção',default=>'Desconectado'};$statusTone=match($status){'connected'=>'success','starting','qr','reconnecting'=>'warning','error'=>'danger',default=>'muted'};$pollUrl=json_encode(app_url('whatsapp.php?ajax=status'),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
em_header('WhatsApp','whatsapp');
?>
<section class="page-hero"><div><span class="eyebrow">EVENTMENU CONNECT</span><h2>WhatsApp da empresa</h2><p>Configure os avisos automáticos dos pedidos. O envio é feito pelo EventMenu Connect com o WhatsApp conectado no aparelho responsável.</p></div><div class="hero-actions"><a class="button secondary" href="<?=Security::e(app_url('?route=settings'))?>">Voltar às configurações</a></div></section>
<?php if(!$bridgeEnabled):?><section class="card"><div class="section-head"><div><span class="eyebrow">SERVIDOR</span><h2>EventMenu Connect</h2></div><span class="badge status-warning">Conexão no aparelho</span></div><p class="muted">O EventMenu Connect precisa estar conectado para consumir a fila e enviar as mensagens. O servidor apenas mantém as filas e as conversas; a sessão do WhatsApp permanece no dispositivo Connect.</p></section><?php endif;?>
<div class="settings-layout"><div class="settings-main">
<section class="card" data-wa-panel><div class="section-head"><div><span class="eyebrow">CONEXÃO</span><h2>Status do número</h2></div><span class="badge status-<?=$statusTone?>" data-wa-status><?=Security::e($statusLabel)?></span></div>
<div class="detail-grid"><div><span class="muted">Número conectado</span><strong data-wa-phone><?=Security::e((string)($connection['phone_number']?:'—'))?></strong></div><div><span class="muted">Última conexão</span><strong data-wa-last><?=Security::e((string)($connection['last_connected_at']?:'—'))?></strong></div></div><p class="muted" data-wa-error><?=Security::e((string)($connection['bridge_error']??$connection['last_error']??''))?></p>
<div data-wa-qr-wrap style="<?=empty($connection['qr'])?'display:none;':''?>text-align:center;margin:18px 0"><p><strong>No celular:</strong> use o EventMenu Connect para manter a sessão do WhatsApp vinculada.</p><img data-wa-qr src="<?=Security::e((string)($connection['qr']??''))?>" alt="QR Code para conectar o WhatsApp" style="display:block;max-width:320px;width:100%;height:auto;margin:12px auto;border-radius:18px;border:1px solid #ddd"><p class="muted">A sessão e o mecanismo Baileys permanecem dentro do EventMenu Connect.</p></div>
<div class="actions" style="display:flex;gap:8px;flex-wrap:wrap"><form method="post"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="action" value="connect"><button class="primary" type="submit"<?=$bridgeEnabled?'':' disabled'?>>Conectar / gerar QR</button></form><form method="post"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="action" value="reconnect"><button class="secondary" type="submit"<?=$bridgeEnabled?'':' disabled'?>>Reconectar</button></form><form method="post" onsubmit="return confirm('Encerrar a sessão atual e conectar outro número?')"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="action" value="replace"><button class="secondary" type="submit"<?=$bridgeEnabled?'':' disabled'?>>Conectar outro número</button></form><form method="post" onsubmit="return confirm('Desconectar o WhatsApp desta empresa?')"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="action" value="disconnect"><button class="secondary" type="submit">Desconectar</button></form></div></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">WHATSAPP COMMERCE · ETAPA 0</span><h2>Receber conversas no EventMenu</h2></div><span class="badge status-<?=$commerceEnabled?'success':'muted'?>"><?=$commerceEnabled?'Ativo':'Pausado'?></span></div><p class="muted">Quando ativo, mensagens recebidas pelo Baileys entram no EventMenu com deduplicação e podem gerar respostas automáticas básicas. Quando pausado, as mensagens continuam sendo registradas no histórico, mas nenhuma automação comercial altera o estado da conversa ou responde ao cliente.</p><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="action" value="save_commerce"><label class="checkbox span-2"><input type="checkbox" name="commerce_enabled"<?=em_checked($commerceEnabled)?>> Ativar infraestrutura do WhatsApp Commerce nesta empresa</label><div class="span-2 alert"><strong>Etapa atual:</strong> entrada bidirecional, histórico, idempotência, comandos globais e transferência básica para atendimento humano. Cardápio e carrinho serão habilitados somente na próxima etapa.</div><div class="span-2 actions"><button class="primary" type="submit">Salvar WhatsApp Commerce</button></div></form></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">AUTOMAÇÕES</span><h2>Mensagens por etapa do pedido</h2></div></div><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?=em_csrf()?>"><input type="hidden" name="action" value="save"><label class="checkbox span-2"><input type="checkbox" name="automation_enabled"<?=em_checked($connection['automation_enabled']??false)?>> Ativar mensagens automáticas desta empresa</label><div class="span-2"><p class="muted">Variáveis: <code>{nome}</code>, <code>{pedido}</code>, <code>{valor}</code>, <code>{status}</code>, <code>{previsao}</code>, <code>{link}</code>. Compatíveis também: <code>{cliente}</code>, <code>{total}</code>, <code>{restaurante}</code>.</p></div>
<?php foreach($eventLabels as$event=>$label):$row=$templatesByEvent[$event]??[];$message=(string)($row['message_template']??$defaults[$event]??'');?><section class="span-2" style="padding:14px;border:1px solid #ddd;border-radius:16px"><label class="checkbox"><input type="checkbox" name="event_enabled[<?=Security::e($event)?>]"<?=em_checked($row['enabled']??false)?>> <strong><?=Security::e($label)?></strong></label><label style="display:block;margin-top:10px">Mensagem<textarea name="event_message[<?=Security::e($event)?>]" rows="3" maxlength="1500" required><?=Security::e($message)?></textarea></label></section><?php endforeach;?><div class="span-2 actions"><button class="primary" type="submit">Salvar automações</button></div></form></section>
</div><aside class="settings-side"><section class="card"><span class="eyebrow">ISOLAMENTO</span><h3>Uma sessão por empresa</h3><p class="muted">Cada empresa usa sua própria sessão autenticada do EventMenu Connect. A sessão do WhatsApp não fica no navegador nem na hospedagem.</p></section><section class="card"><span class="eyebrow">RISCO</span><h3>Integração não oficial</h3><p class="muted">Mudanças no WhatsApp Web podem interromper a sessão sem aviso. Também existe risco de restrição da conta quando há automação excessiva. Evite disparos em massa e use primeiro em ambiente controlado.</p></section><section class="card"><span class="eyebrow">FILA SEGURA</span><h3>Sem mensagens duplicadas</h3><p class="muted">Mensagens recebidas e enviadas usam identificadores únicos, fila persistente e idempotência para resistir a reconexões.</p></section></aside></div>
<script>(()=>{const endpoint=<?=$pollUrl?>,root=document.querySelector('[data-wa-panel]');if(!root)return;const label={connected:'Conectado',starting:'Iniciando',qr:'Aguardando leitura do QR',reconnecting:'Reconectando',error:'Precisa de atenção',disconnected:'Desconectado'},tone={connected:'success',starting:'warning',qr:'warning',reconnecting:'warning',error:'danger',disconnected:'muted'};async function refresh(){try{const r=await fetch(endpoint,{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}}),p=await r.json();if(!r.ok||!p.ok)return;const d=p.data||{},s=d.status||'disconnected',b=root.querySelector('[data-wa-status]');b.textContent=label[s]||'Desconectado';b.className='badge status-'+(tone[s]||'muted');root.querySelector('[data-wa-phone]').textContent=d.phone_number||'—';root.querySelector('[data-wa-last]').textContent=d.last_connected_at||'—';root.querySelector('[data-wa-error]').textContent=d.bridge_error||d.last_error||'';const w=root.querySelector('[data-wa-qr-wrap]'),i=root.querySelector('[data-wa-qr]');if(d.qr){i.src=d.qr;w.style.display='block'}else{i.removeAttribute('src');w.style.display='none'}}catch(_){}}refresh();setInterval(refresh,4000)})();</script>
<?php em_footer(); ?>