<?php

declare(strict_types=1);

require dirname(__DIR__).'/app/bootstrap.php';

use EventMenu\Core\Database;
use EventMenu\Services\ProductionDesktopService;
use EventMenu\Services\ProductionPrintPolicyService;

function pp5_fail(string$m):never{fwrite(STDERR,"PRODUCTION PRINT STAGE5 CI FAIL: {$m}\n");exit(1);}function pp5_assert(bool$ok,string$m):void{if(!$ok)pp5_fail($m);}
$pdo=Database::connection();if(Database::driver($pdo)!=='sqlite')pp5_fail('Este smoke exige SQLite.');$uid='pp5'.bin2hex(random_bytes(4));
$pdo->prepare('INSERT INTO tenants (name,slug,plan,status,settings) VALUES (?,?,"premium","active","{}")')->execute(['Print Stage5 CI',$uid]);$tenantId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO users (tenant_id,name,email,password_hash,role,status) VALUES (?,?,?,?,"admin","active")')->execute([$tenantId,'Print Admin',$uid.'@example.test',password_hash('CiPassword123!',PASSWORD_DEFAULT)]);$userId=(int)$pdo->lastInsertId();$_SESSION['user_id']=$userId;$_SESSION['tenant_id']=$tenantId;$_SESSION['role']='admin';$_SESSION['name']='Print Admin';unset($_SESSION['acting_tenant_id']);
$pdo->prepare('INSERT INTO operating_units (tenant_id,code,name,active) VALUES (?,?,?,1)')->execute([$tenantId,'principal','Principal']);$unitId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO categories (tenant_id,name,sort_order,active) VALUES (?,?,0,1)')->execute([$tenantId,'Cardápio']);$categoryId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO products (tenant_id,category_id,name,price_cents,track_stock,stock_qty,active) VALUES (?,?,?,?,0,0,1)')->execute([$tenantId,$categoryId,'X-Bacon CI',2500]);$foodId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO products (tenant_id,category_id,name,price_cents,track_stock,stock_qty,active) VALUES (?,?,?,?,0,0,1)')->execute([$tenantId,$categoryId,'Coca CI',800]);$drinkId=(int)$pdo->lastInsertId();
$station=$pdo->prepare('INSERT INTO production_stations (tenant_id,unit_id,code,name,station_type,sla_minutes,sort_order,printer_mode,printer_target,active) VALUES (?,?,?,?,?,10,0,"auto",?,1)');
$station->execute([$tenantId,$unitId,'cozinha','Cozinha','kitchen','Printer Kitchen']);$kitchenId=(int)$pdo->lastInsertId();$station->execute([$tenantId,$unitId,'bar','Bar','bar','Printer Bar']);$barId=(int)$pdo->lastInsertId();$station->execute([$tenantId,$unitId,'caixa','Caixa','other','Printer Cashier']);$cashierId=(int)$pdo->lastInsertId();
$profile=$pdo->prepare('INSERT INTO product_unit_production_profiles (tenant_id,unit_id,product_id,station_id,production_enabled,prep_minutes,print_mode) VALUES (?,?,?,?,1,10,"inherit")');$profile->execute([$tenantId,$unitId,$foodId,$kitchenId]);$profile->execute([$tenantId,$unitId,$drinkId,$barId]);
$pdo->prepare('INSERT INTO customers (tenant_id,name,phone,phone_normalized) VALUES (?,?,?,?)')->execute([$tenantId,'Cliente Print','(11) 99999-5505','11999995505']);$customerId=(int)$pdo->lastInsertId();
$token=bin2hex(random_bytes(20));$pdo->prepare("INSERT INTO orders (public_token,tenant_id,unit_id,customer_id,channel,order_source,status,payment_status,subtotal_cents,discount_cents,delivery_fee_cents,total_cents,delivery_address,notes) VALUES (?,?,?,?, 'delivery','WHATSAPP','pending','pending',4100,0,500,4600,'Rua CI, 123','Sem cebola')")->execute([$token,$tenantId,$unitId,$customerId]);$orderId=(int)$pdo->lastInsertId();
$item=$pdo->prepare('INSERT INTO order_items (order_id,product_id,name_snapshot,unit_price_cents,quantity,total_cents,notes) VALUES (?,?,?,?,?,?,?)');$item->execute([$orderId,$foodId,'X-Bacon CI',2500,1,2500,'Sem cebola']);$item->execute([$orderId,$drinkId,'Coca CI',800,2,1600,null]);
$pdo->prepare('INSERT OR REPLACE INTO production_print_settings (tenant_id,unit_id,enabled,trigger_event,cashier_enabled,cashier_station_id,enabled_at) VALUES (?,?,1,"payment_confirmed",1,?,"2000-01-01 00:00:00")')->execute([$tenantId,$unitId,$cashierId]);
$policy=new ProductionPrintPolicyService();$r=$policy->syncCurrentUnit($pdo,$tenantId,$unitId);$q=$pdo->prepare('SELECT COUNT(*) FROM production_print_queue WHERE tenant_id=? AND order_id=? AND queue_type="auto"');$q->execute([$tenantId,$orderId]);pp5_assert((int)$q->fetchColumn()===0,'Pedido não pago imprimiu com gatilho payment_confirmed.');
$pdo->prepare('INSERT INTO payments (tenant_id,order_id,provider,provider_payment_id,idempotency_key,amount_cents,currency,status,verified_at) VALUES (?, ?, "manual", ?, ?, 4600,"BRL","paid",CURRENT_TIMESTAMP)')->execute([$tenantId,$orderId,'PP5-'.strtoupper(bin2hex(random_bytes(5))),'pp5-'.$uid]);$pdo->prepare('UPDATE orders SET payment_status="paid",status="confirmed" WHERE id=?')->execute([$orderId]);
$policy->syncCurrentUnit($pdo,$tenantId,$unitId);$policy->syncCurrentUnit($pdo,$tenantId,$unitId);
$q=$pdo->prepare('SELECT id,station_id,print_scope,payload_json,status FROM production_print_queue WHERE tenant_id=? AND order_id=? AND queue_type="auto" ORDER BY id');$q->execute([$tenantId,$orderId]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);pp5_assert(count($rows)===3,'Gatilho pago não gerou exatamente cozinha, bar e caixa.');
$byScope=[];foreach($rows as$row){$payload=json_decode((string)$row['payload_json'],true);pp5_assert(is_array($payload)&&!empty($payload['items']),'Fila automática não possui snapshot persistente.');$byScope[$row['print_scope'].':'.$row['station_id']]=[$row,$payload];}
pp5_assert(isset($byScope['station:'.$kitchenId]),'Via da cozinha ausente.');pp5_assert(isset($byScope['station:'.$barId]),'Via do bar ausente.');pp5_assert(isset($byScope['cashier:'.$cashierId]),'Via completa do caixa ausente.');
$kitchenPayload=$byScope['station:'.$kitchenId][1];$barPayload=$byScope['station:'.$barId][1];$cashPayload=$byScope['cashier:'.$cashierId][1];pp5_assert(count($kitchenPayload['items'])===1&&$kitchenPayload['items'][0]['description']==='X-Bacon CI','Cozinha recebeu item de outro setor.');pp5_assert(count($barPayload['items'])===1&&$barPayload['items'][0]['description']==='Coca CI','Bar recebeu item de outro setor.');pp5_assert(count($cashPayload['items'])===2&&(int)$cashPayload['order']['total_cents']===4600,'Caixa não recebeu pedido completo com total.');

// Idempotência: múltiplas reconciliações não duplicam as vias automáticas.
$policy->syncCurrentUnit($pdo,$tenantId,$unitId);$q->execute([$tenantId,$orderId]);pp5_assert(count($q->fetchAll(PDO::FETCH_ASSOC))===3,'Reconciliação repetida duplicou impressão automática.');

// O Print Agent mantém falha na fila e agenda retry; nova tentativa manual preserva o mesmo job.
$pdo->prepare('INSERT INTO work_shifts (tenant_id,user_id,unit_id,mode,status,opening_notes) VALUES (?,?,?,"operation","open","CI impressão")')->execute([$tenantId,$userId,$unitId]);$desktop=new ProductionDesktopService();$claimed=$desktop->claimPrint('ci-device-print');pp5_assert(is_array($claimed)&&!empty($claimed['queue']['id']),'Desktop não conseguiu reservar impressão.');$queueId=(int)$claimed['queue']['id'];$failed=$desktop->completePrint($queueId,'ci-device-print',false,'Impressora offline CI');pp5_assert(($failed['status']??'')==='error'&&!empty($failed['next_attempt_at']),'Falha transitória desapareceu ou não agendou retry.');$retried=$desktop->retryPrint($queueId,'Impressora voltou online');pp5_assert(($retried['status']??'')==='pending'&&(int)($retried['attempts']??-1)===0,'Retry manual não preservou/reabriu o job.');$claimedAgain=$desktop->claimPrint('ci-device-print');pp5_assert((int)($claimedAgain['queue']['id']??0)===$queueId,'Retry criou/substituiu o job em vez de processar o mesmo.');$printed=$desktop->completePrint($queueId,'ci-device-print',true);pp5_assert(($printed['status']??'')==='printed','ACK de impressão não marcou job como printed.');

// Reimpressão é sempre um novo job e pode ocorrer mais de uma vez.
$first=$policy->reprintOrder($orderId,'kitchen','Via danificada na cozinha');$second=$policy->reprintOrder($orderId,'kitchen','Segunda via solicitada cozinha');pp5_assert(count($first)>=1&&count($second)>=1&&$first[0]!==$second[0],'Reimpressões consecutivas reutilizaram o mesmo job.');$q=$pdo->prepare('SELECT COUNT(*) FROM production_print_queue WHERE tenant_id=? AND order_id=? AND queue_type="reprint"');$q->execute([$tenantId,$orderId]);pp5_assert((int)$q->fetchColumn()>=2,'Reimpressões não ficaram registradas como jobs próprios.');$q=$pdo->prepare('SELECT status FROM production_print_queue WHERE id=?');$q->execute([$queueId]);pp5_assert($q->fetchColumn()==='printed','Reimpressão alterou o job original.');

// Trocar para order_created permite pedido operacional ainda não pago.
$pdo->prepare('UPDATE production_print_settings SET trigger_event="order_created",cashier_enabled=0,enabled_at="2000-01-01 00:00:00" WHERE tenant_id=? AND unit_id=?')->execute([$tenantId,$unitId]);$token2=bin2hex(random_bytes(20));$pdo->prepare("INSERT INTO orders (public_token,tenant_id,unit_id,customer_id,channel,order_source,status,payment_status,subtotal_cents,total_cents) VALUES (?,?,?,?, 'pickup','WHATSAPP','pending','unpaid',2500,2500)")->execute([$token2,$tenantId,$unitId,$customerId]);$order2=(int)$pdo->lastInsertId();$item->execute([$order2,$foodId,'X-Bacon CI',2500,1,2500,null]);$policy->syncCurrentUnit($pdo,$tenantId,$unitId);$q=$pdo->prepare('SELECT COUNT(*) FROM production_print_queue WHERE tenant_id=? AND order_id=? AND queue_type="auto" AND status="pending"');$q->execute([$tenantId,$order2]);pp5_assert((int)$q->fetchColumn()===1,'Gatilho order_created não gerou a via antes do pagamento.');

echo "CI Production Print Stage5 smoke OK\n";
