<?php

declare(strict_types=1);

require dirname(__DIR__).'/app/bootstrap.php';

use EventMenu\Core\Database;
use EventMenu\Services\WhatsAppCommerceService;
use EventMenu\Services\WhatsAppIntegrationService;

function wa1_fail(string $m):never{fwrite(STDERR,"WHATSAPP COMMERCE STAGE1 CI FAIL: {$m}\n");exit(1);}
function wa1_assert(bool $ok,string $m):void{if(!$ok)wa1_fail($m);}

$pdo=Database::connection();if(Database::driver($pdo)!=='sqlite')wa1_fail('Este smoke exige SQLite.');
$slug='wa-stage1-'.bin2hex(random_bytes(4));$pdo->prepare('INSERT INTO tenants (name,slug,plan,status) VALUES (?,?,"premium","active")')->execute(['WhatsApp Stage1 CI',$slug]);$tenantId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO users (tenant_id,name,email,password_hash,role,status) VALUES (?,?,?,?,"admin","active")')->execute([$tenantId,'WA CI',$slug.'@example.test',password_hash('CiPassword123!',PASSWORD_DEFAULT)]);$userId=(int)$pdo->lastInsertId();$_SESSION['user_id']=$userId;$_SESSION['tenant_id']=$tenantId;$_SESSION['role']='admin';$_SESSION['name']='WA CI';
$pdo->prepare('INSERT INTO operating_units (tenant_id,code,name,active) VALUES (?,?,?,1)')->execute([$tenantId,'principal','Principal']);$unitId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO categories (tenant_id,name,sort_order,active) VALUES (?,?,0,1)')->execute([$tenantId,'Lanches']);$categoryId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO products (tenant_id,category_id,name,price_cents,track_stock,active) VALUES (?,?,?,?,0,1)')->execute([$tenantId,$categoryId,'X-Bacon',2000]);$burgerId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO products (tenant_id,category_id,name,price_cents,track_stock,active) VALUES (?,?,?,?,0,1)')->execute([$tenantId,$categoryId,'Refrigerante',500]);$drinkId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modifier_groups (tenant_id,product_id,name,required,min_select,max_select,sort_order,active) VALUES (?,?,?,1,1,1,0,1)')->execute([$tenantId,$burgerId,'Tamanho']);$sizeGroup=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modifier_options (tenant_id,group_id,name,price_delta_cents,cost_cents,inventory_quantity,production_enabled,sort_order,active) VALUES (?,?,?,0,0,0,0,0,1)')->execute([$tenantId,$sizeGroup,'Médio']);$sizeM=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modifier_options (tenant_id,group_id,name,price_delta_cents,cost_cents,inventory_quantity,production_enabled,sort_order,active) VALUES (?,?,?,500,0,0,0,1,1)')->execute([$tenantId,$sizeGroup,'Grande']);$sizeL=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modifier_groups (tenant_id,product_id,name,required,min_select,max_select,sort_order,active) VALUES (?,?,?,0,0,2,1,1)')->execute([$tenantId,$burgerId,'Adicionais']);$extraGroup=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modifier_options (tenant_id,group_id,name,price_delta_cents,cost_cents,inventory_quantity,production_enabled,sort_order,active) VALUES (?,?,?,400,0,0,0,0,1)')->execute([$tenantId,$extraGroup,'Bacon extra']);$bacon=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO modifier_options (tenant_id,group_id,name,price_delta_cents,cost_cents,inventory_quantity,production_enabled,sort_order,active) VALUES (?,?,?,300,0,0,0,1,1)')->execute([$tenantId,$extraGroup,'Queijo extra']);$cheese=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO customers (tenant_id,name,phone,phone_normalized,document) VALUES (?,?,?,?,?)')->execute([$tenantId,'Cliente Conhecido','(11) 99999-8877','11999998877','52998224725']);$customerId=(int)$pdo->lastInsertId();

$deviceId='ci-stage1-'.bin2hex(random_bytes(8));$deviceHash=hash('sha256',$deviceId);$pdo->prepare('INSERT INTO whatsapp_desktop_agents (tenant_id,device_hash,device_label,status,engine) VALUES (?,?,?,"connected","baileys")')->execute([$tenantId,$deviceHash,'CI Connect']);(new WhatsAppIntegrationService())->ensureConnection($pdo,$tenantId);$pdo->prepare('UPDATE whatsapp_connections SET commerce_enabled=1 WHERE tenant_id=?')->execute([$tenantId]);
$commerce=new WhatsAppCommerceService();$seq=0;
$send=function(string$text,string$phone='5511999998877',?string$id=null,string$name='Cliente Conhecido')use($commerce,$deviceId,&$seq):array{$seq++;return$commerce->receiveInbound($deviceId,['provider_message_id'=>$id??('CI.ST1.'.$seq.'.'.bin2hex(random_bytes(3))),'phone'=>$phone,'name'=>$name,'message_type'=>'text','text'=>$text,'timestamp'=>time(),'payload'=>[]]);};

$send('menu');$startId='CI.ST1.START.'.bin2hex(random_bytes(4));$start=$send('1','5511999998877',$startId);wa1_assert(($start['state']??'')==='SELECTING_CATEGORY','1 não abriu categorias.');
$q=$pdo->prepare('SELECT c.customer_id,c.draft_order_id,o.status,o.order_source,o.channel,o.unit_id FROM whatsapp_conversations c JOIN orders o ON o.id=c.draft_order_id WHERE c.tenant_id=? AND c.phone=?');$q->execute([$tenantId,'5511999998877']);$draft=$q->fetch(PDO::FETCH_ASSOC);wa1_assert(is_array($draft),'Draft normal não foi criado.');wa1_assert((int)$draft['customer_id']===$customerId,'Cliente conhecido não foi identificado pelo telefone.');wa1_assert($draft['status']==='draft'&&$draft['order_source']==='WHATSAPP'&&$draft['channel']==='pending','Origem/canal/status do draft estão incorretos.');wa1_assert((int)$draft['unit_id']===$unitId,'Draft não foi vinculado à unidade ativa.');$draftId=(int)$draft['draft_order_id'];
$dup=$send('1','5511999998877',$startId);wa1_assert(!empty($dup['duplicate']),'Mensagem duplicada não foi ignorada.');$q=$pdo->prepare('SELECT COUNT(*) FROM orders WHERE tenant_id=? AND order_source="WHATSAPP"');$q->execute([$tenantId]);wa1_assert((int)$q->fetchColumn()===1,'Mensagem duplicada criou pedido adicional.');

wa1_assert(($send('1')['state']??'')==='SELECTING_PRODUCT','Categoria não abriu produtos.');wa1_assert(($send('2')['state']??'')==='SELECTING_VARIANT','Produto configurado não abriu variação obrigatória.');wa1_assert(($send('2')['state']??'')==='SELECTING_ADDONS','Tamanho não avançou para adicionais.');$send('1');$send('2');wa1_assert(($send('ok')['state']??'')==='SELECTING_QUANTITY','Adicionais não avançaram para quantidade.');wa1_assert(($send('2')['state']??'')==='ENTERING_NOTE','Quantidade não avançou para observação.');wa1_assert(($send('sem cebola')['state']??'')==='CART','Item não entrou no carrinho.');
$q=$pdo->prepare('SELECT unit_price_cents,quantity,total_cents,notes FROM order_items WHERE order_id=? ORDER BY id LIMIT 1');$q->execute([$draftId]);$item=$q->fetch(PDO::FETCH_ASSOC);wa1_assert((int)$item['unit_price_cents']===3200&&(int)$item['quantity']===2&&(int)$item['total_cents']===6400,'Preço/quantidade do item configurado divergiu.');wa1_assert($item['notes']==='sem cebola','Observação não foi persistida.');$q=$pdo->prepare('SELECT COUNT(*) FROM order_item_modifiers WHERE tenant_id=? AND order_id=?');$q->execute([$tenantId,$draftId]);wa1_assert((int)$q->fetchColumn()===3,'Variação e adicionais não foram persistidos na estrutura normal.');

$send('menu');$resume=$send('meu pedido');wa1_assert(($resume['state']??'')==='CART','Carrinho abandonado não foi retomado pela conversa persistente.');$q=$pdo->prepare('SELECT COUNT(*) FROM order_items WHERE order_id=?');$q->execute([$draftId]);wa1_assert((int)$q->fetchColumn()===1,'Reentrada apagou ou duplicou itens do draft.');
$pdo->prepare('UPDATE products SET price_cents=2200 WHERE id=? AND tenant_id=?')->execute([$burgerId,$tenantId]);$send('meu pedido');$q=$pdo->prepare('SELECT unit_price_cents,total_cents FROM order_items WHERE order_id=? ORDER BY id LIMIT 1');$q->execute([$draftId]);$repriced=$q->fetch(PDO::FETCH_ASSOC);wa1_assert((int)$repriced['unit_price_cents']===3400&&(int)$repriced['total_cents']===6800,'Carrinho não recalculou preço atual do servidor.');
$pdo->prepare('UPDATE modifier_options SET active=0 WHERE id=? AND tenant_id=?')->execute([$cheese,$tenantId]);$send('meu pedido');$q=$pdo->prepare('SELECT total_cents FROM order_items WHERE order_id=? ORDER BY id LIMIT 1');$q->execute([$draftId]);wa1_assert((int)$q->fetchColumn()===0,'Adicional indisponível permaneceu válido no carrinho.');$pdo->prepare('UPDATE modifier_options SET active=1 WHERE id=? AND tenant_id=?')->execute([$cheese,$tenantId]);$send('meu pedido');$q=$pdo->prepare('SELECT unit_price_cents,total_cents FROM order_items WHERE order_id=? ORDER BY id LIMIT 1');$q->execute([$draftId]);$restored=$q->fetch(PDO::FETCH_ASSOC);wa1_assert((int)$restored['unit_price_cents']===3400&&(int)$restored['total_cents']===6800,'Carrinho não voltou a validar após restauração do adicional.');
$send('2');$send('1');$send('3');$q=$pdo->prepare('SELECT quantity,total_cents FROM order_items WHERE order_id=? ORDER BY id LIMIT 1');$q->execute([$draftId]);$resized=$q->fetch(PDO::FETCH_ASSOC);wa1_assert((int)$resized['quantity']===3&&(int)$resized['total_cents']===10200,'Alteração de quantidade não foi recalculada.');
$send('1');$send('1');wa1_assert(($send('1')['state']??'')==='SELECTING_QUANTITY','Produto simples deveria ir direto para quantidade.');$send('1');$send('0');$q=$pdo->prepare('SELECT COUNT(*) FROM order_items WHERE order_id=?');$q->execute([$draftId]);wa1_assert((int)$q->fetchColumn()===2,'Segundo item não foi adicionado.');
$pdo->prepare('UPDATE products SET active=0 WHERE id=? AND tenant_id=?')->execute([$drinkId,$tenantId]);$send('meu pedido');$q=$pdo->prepare('SELECT total_cents FROM order_items WHERE order_id=? AND product_id=?');$q->execute([$draftId,$drinkId]);wa1_assert((int)$q->fetchColumn()===0,'Produto desativado permaneceu valorizado no draft.');$send('3');$send('2');$q=$pdo->prepare('SELECT COUNT(*) FROM order_items WHERE order_id=? AND product_id=?');$q->execute([$draftId,$drinkId]);wa1_assert((int)$q->fetchColumn()===0,'Remoção de item não funcionou.');

$final=$send('4');wa1_assert(($final['state']??'')==='CHOOSING_FULFILLMENT','Finalizar carrinho não parou na fronteira da ETAPA 2.');$q=$pdo->prepare('SELECT status,channel,order_source,total_cents FROM orders WHERE id=?');$q->execute([$draftId]);$order=$q->fetch(PDO::FETCH_ASSOC);wa1_assert($order['status']==='draft'&&$order['channel']==='pending'&&$order['order_source']==='WHATSAPP','ETAPA 1 transformou indevidamente o draft em pedido operacional.');wa1_assert((int)$order['total_cents']===10200,'Total final do draft divergiu.');
$q=$pdo->prepare('SELECT COUNT(*) FROM payments WHERE tenant_id=? AND order_id=?');$q->execute([$tenantId,$draftId]);wa1_assert((int)$q->fetchColumn()===0,'ETAPA 1 criou pagamento.');$q=$pdo->prepare('SELECT COUNT(*) FROM stock_reservations WHERE tenant_id=? AND order_id=?');$q->execute([$tenantId,$draftId]);wa1_assert((int)$q->fetchColumn()===0,'ETAPA 1 reservou estoque antes da finalização operacional.');$q=$pdo->prepare('SELECT COUNT(*) FROM production_jobs WHERE tenant_id=? AND order_id=?');$q->execute([$tenantId,$draftId]);wa1_assert((int)$q->fetchColumn()===0,'ETAPA 1 criou produção/impressão.');

$requiredAudit=['whatsapp.customer_identified','whatsapp.draft_created','whatsapp.item_added','whatsapp.item_quantity_changed','whatsapp.item_removed','whatsapp.cart_finalized'];$q=$pdo->prepare('SELECT action,metadata FROM audit_logs WHERE tenant_id=? AND action LIKE "whatsapp.%"');$q->execute([$tenantId]);$auditRows=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$actions=array_values(array_unique(array_map(fn(array$r)=>(string)$r['action'],$auditRows)));foreach($requiredAudit as$action)wa1_assert(in_array($action,$actions,true),'Auditoria obrigatória ausente: '.$action);foreach($auditRows as$row)wa1_assert(!str_contains(mb_strtolower((string)($row['metadata']??'')),'sem cebola'),'Texto de observação do cliente vazou para audit_logs.');

// Primeiro contato: telefone já vem do WhatsApp. Nome e CPF são obrigatórios antes do pedido;
// endereço só será pedido posteriormente se a pessoa escolher entrega.
$unknownPhone='5521998887766';
$registration=$send('menu',$unknownPhone,null,'Pessoa Nova');wa1_assert(($registration['state']??'')==='REGISTER_NAME','Primeiro contato não iniciou cadastro pelo nome.');
$registration=$send('Pessoa Nova',$unknownPhone,null,'Pessoa Nova');wa1_assert(($registration['state']??'')==='REGISTER_CPF','Nome não avançou para CPF.');
$invalidCpf=$send('11111111111',$unknownPhone,null,'Pessoa Nova');wa1_assert(($invalidCpf['state']??'')==='REGISTER_CPF','CPF inválido avançou o cadastro.');
$registration=$send('11144477735',$unknownPhone,null,'Pessoa Nova');wa1_assert(($registration['state']??'')==='REGISTER_CONFIRM','CPF válido não abriu confirmação cadastral.');
$q=$pdo->prepare("SELECT message_text FROM whatsapp_messages m JOIN whatsapp_conversations c ON c.id=m.conversation_id AND c.tenant_id=m.tenant_id WHERE m.tenant_id=? AND c.phone=? AND m.direction='outbound' ORDER BY m.id DESC LIMIT 1");$q->execute([$tenantId,$unknownPhone]);$registrationReply=(string)$q->fetchColumn();wa1_assert(str_contains($registrationReply,'CPF:')&&str_contains($registrationReply,'***')&&!str_contains($registrationReply,'11144477735'),'Confirmação não mascarou o CPF corretamente.');wa1_assert(str_contains($registrationReply,'somente se você escolher entrega'),'Cadastro inicial exigiu endereço antes da escolha de entrega.');
$registration=$send('1',$unknownPhone,null,'Pessoa Nova');wa1_assert(($registration['state']??'')==='WELCOME'&&!empty($registration['registration_complete']),'Confirmação não concluiu o cadastro.');
$unknown=$send('1',$unknownPhone,null,'Pessoa Nova');wa1_assert(($unknown['state']??'')==='SELECTING_CATEGORY','Cliente recém-cadastrado não conseguiu iniciar pedido.');
$q=$pdo->prepare('SELECT c.customer_id,c.draft_order_id,cu.name,cu.document,cu.default_address FROM whatsapp_conversations c JOIN customers cu ON cu.id=c.customer_id AND cu.tenant_id=c.tenant_id WHERE c.tenant_id=? AND c.phone=?');$q->execute([$tenantId,$unknownPhone]);$unknownConversation=$q->fetch(PDO::FETCH_ASSOC);wa1_assert(is_array($unknownConversation)&&(int)$unknownConversation['customer_id']>0,'Cadastro confirmado não vinculou cliente à conversa.');wa1_assert((int)$unknownConversation['draft_order_id']>0,'Cliente cadastrado não recebeu draft normal.');wa1_assert($unknownConversation['name']==='Pessoa Nova'&&$unknownConversation['document']==='11144477735','Nome/CPF do cadastro inicial não foram persistidos.');wa1_assert(trim((string)($unknownConversation['default_address']??''))==='','Endereço foi inventado ou exigido antes da entrega.');

echo "WhatsApp Commerce Stage 1 order smoke: OK\n";