CREATE TABLE IF NOT EXISTS terminal_payment_intents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id INTEGER NOT NULL,
  unit_id INTEGER NOT NULL,
  order_id INTEGER NOT NULL,
  terminal_config_id INTEGER NOT NULL,
  device_hash TEXT NOT NULL,
  provider TEXT NOT NULL,
  intent_token TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('debit','credit','pix','voucher')),
  installments INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'created' CHECK (status IN ('created','processing','approved_local','verified','failed','cancelled','expired')),
  provider_transaction_id TEXT NULL,
  authorization_code TEXT NULL,
  local_result_encrypted TEXT NULL,
  verification_result_encrypted TEXT NULL,
  expires_at TEXT NOT NULL,
  verified_at TEXT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (unit_id) REFERENCES operating_units(id) ON DELETE RESTRICT,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  FOREIGN KEY (terminal_config_id) REFERENCES payment_terminal_configs(id) ON DELETE RESTRICT,
  UNIQUE (intent_token),
  UNIQUE (tenant_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_terminal_intent_order ON terminal_payment_intents(tenant_id, order_id, status);
CREATE INDEX IF NOT EXISTS idx_terminal_intent_expiry ON terminal_payment_intents(status, expires_at);
