using System.Windows;using EventMenu.Desktop.Models;using EventMenu.Desktop.Services;
namespace EventMenu.Desktop;
public partial class ReceiptWindow:Window{
 private readonly OperationalActionsApiClient _api;private readonly ReceiptPresentationApiClient _presentationApi;private readonly int _orderId;private OrderReceipt? _receipt;private ReceiptPresentation? _presentation;private bool _busy;
 public ReceiptWindow(SecureSessionStore store,int orderId){_api=new OperationalActionsApiClient(store);_presentationApi=new ReceiptPresentationApiClient(store);_orderId=orderId;InitializeComponent();Loaded+=async(_,_)=>await LoadAsync();Closed+=(_,_)=>{_api.Dispose();_presentationApi.Dispose();};}
 private async Task LoadAsync(){if(_busy)return;_busy=true;PrintButton.IsEnabled=false;StatusText.Text="Carregando cupom...";try{var response=await _api.OrderReceiptAsync(_orderId);_receipt=response.Receipt??throw new InvalidOperationException("Comprovante não encontrado.");_presentation=await _presentationApi.GetAsync(_orderId);Render(_receipt,_presentation);PrintButton.IsEnabled=true;StatusText.Text=$"{_receipt.ReceiptNumber} • {_receipt.CreatedDisplay}";}catch(Exception ex){_receipt=null;_presentation=null;StatusText.Text=Friendly(ex.Message);}finally{_busy=false;}}
 private void Render(OrderReceipt r,ReceiptPresentation p){TitleText.Text=$"Cupom do pedido #{r.OrderId}";SubtitleText.Text=$"{r.CreatedDisplay} • padrão definido no servidor";var trade=string.IsNullOrWhiteSpace(r.Identity.TradeName)?r.TenantName:r.Identity.TradeName;BusinessNameText.Text=string.IsNullOrWhiteSpace(trade)?"EventMenu":trade;BusinessDetailText.Text=JoinNonEmpty("\n",r.Identity.LegalName,DocumentLine(r.Identity.Document),r.Identity.Address);IdentityExtraText.Text=JoinNonEmpty(" • ",PhoneLine(r.Identity.Phone),r.Identity.Email);IdentityExtraText.Visibility=p.Sections.Business&&Has(IdentityExtraText.Text)?Visibility.Visible:Visibility.Collapsed;BusinessNameText.Visibility=p.Sections.Business?Visibility.Visible:Visibility.Collapsed;BusinessDetailText.Visibility=p.Sections.Business?Visibility.Visible:Visibility.Collapsed;ReceiptPaper.Width=p.PaperWidth=="58"?326:430;ReceiptNumberText.Text=$"{p.Subtitle} · {r.ReceiptNumber}";OrderText.Text=$"#{r.OrderId}";ReceiptDateText.Text=r.CreatedDisplay;ReceiptChannelText.Text=ChannelLabel(r.Channel);ReceiptCustomerText.Text=r.CustomerName;ReceiptPhoneText.Text=r.CustomerPhone;ReceiptLocationText.Text=JoinNonEmpty(" • ",r.TableName,r.TabLabel);ReceiptOperatorText.Text=r.CreatedByName;CustomerRow.Visibility=p.Sections.Customer&&Has(r.CustomerName)?Visibility.Visible:Visibility.Collapsed;PhoneRow.Visibility=p.Sections.Customer&&p.Sections.CustomerPhone&&Has(r.CustomerPhone)?Visibility.Visible:Visibility.Collapsed;LocationRow.Visibility=Has(ReceiptLocationText.Text)?Visibility.Visible:Visibility.Collapsed;OperatorRow.Visibility=p.Sections.Operator&&Has(r.CreatedByName)?Visibility.Visible:Visibility.Collapsed;ReceiptItemsList.ItemsSource=p.Sections.Items?r.Items:Array.Empty<ReceiptItem>();ReceiptPaymentsList.ItemsSource=p.Sections.Payments?r.Payments:Array.Empty<ReceiptPayment>();SubtotalText.Text=r.SubtotalDisplay;DiscountText.Text=$"- {r.DiscountDisplay}";DeliveryFeeText.Text=r.DeliveryFeeDisplay;DiscountRow.Visibility=p.Sections.Items&&r.DiscountCents>0?Visibility.Visible:Visibility.Collapsed;DeliveryFeeRow.Visibility=p.Sections.Items&&r.DeliveryFeeCents>0?Visibility.Visible:Visibility.Collapsed;TotalText.Text=r.TotalDisplay;PaidText.Text=r.PaidDisplay;RemainingText.Text=r.RemainingDisplay;RemainingRow.Visibility=r.RemainingCents>0?Visibility.Visible:Visibility.Collapsed;FooterMessageText.Text=Has(p.Footer)?p.Footer:"Obrigado pela preferência!";PrintedAtText.Text=$"EventMenu · visualização em {DateTime.Now:dd/MM/yyyy HH:mm:ss}";}
 private void PrintButton_Click(object sender,RoutedEventArgs e){if(_busy||_receipt is null||_presentation is null)return;try{StatusText.Text=SiteReceiptPrinter.Print(_receipt,_presentation)?"Cupom enviado para impressão.":"Impressão cancelada.";}catch(Exception ex){StatusText.Text=Friendly(ex.Message);}}
 private static Visibility Has(string? v)=>string.IsNullOrWhiteSpace(v)?Visibility.Collapsed:Visibility.Visible;private static string DocumentLine(string v)=>string.IsNullOrWhiteSpace(v)?"":$"CPF/CNPJ: {v}";private static string PhoneLine(string v)=>string.IsNullOrWhiteSpace(v)?"":$"Tel/WhatsApp: {v}";private static string ChannelLabel(string c)=>c switch{"counter"=>"Balcão / PDV","pickup"=>"Retirada","delivery"=>"Delivery","table"=>"Mesa / comanda","event"=>"Evento / Ingresso","bar" or "event_bar"=>"Evento / Bar",_=>c};private static string JoinNonEmpty(string s,params string[]v)=>string.Join(s,v.Where(x=>!string.IsNullOrWhiteSpace(x)));private async void RefreshButton_Click(object sender,RoutedEventArgs e)=>await LoadAsync();private void CloseButton_Click(object sender,RoutedEventArgs e)=>Close();private static string Friendly(string m){var l=m.ToLowerInvariant();return l.Contains("sqlstate")||l.Contains("exception")||l.Contains("stack trace")?"Não foi possível carregar ou imprimir o comprovante.":m;}
}
